/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DuelsRouteImport } from './routes/duels'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeeklyIndexRouteImport } from './routes/weekly.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as DuelsIndexRouteImport } from './routes/duels.index'
import { Route as WeeklyIdRouteImport } from './routes/weekly.$id'
import { Route as PlayDailyRouteImport } from './routes/play.daily'
import { Route as PlayChainRouteImport } from './routes/play.chain'
import { Route as DuelsIdRouteImport } from './routes/duels.$id'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelsRoute = DuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyIndexRoute = WeeklyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeeklyRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const DuelsIndexRoute = DuelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DuelsRoute,
} as any)
const WeeklyIdRoute = WeeklyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WeeklyRoute,
} as any)
const PlayDailyRoute = PlayDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => PlayRoute,
} as any)
const PlayChainRoute = PlayChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => PlayRoute,
} as any)
const DuelsIdRoute = DuelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DuelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duels': typeof DuelsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRouteWithChildren
  '/profile': typeof ProfileRoute
  '/weekly': typeof WeeklyRouteWithChildren
  '/duels/$id': typeof DuelsIdRoute
  '/play/chain': typeof PlayChainRoute
  '/play/daily': typeof PlayDailyRoute
  '/weekly/$id': typeof WeeklyIdRoute
  '/duels/': typeof DuelsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/weekly/': typeof WeeklyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/duels/$id': typeof DuelsIdRoute
  '/play/chain': typeof PlayChainRoute
  '/play/daily': typeof PlayDailyRoute
  '/weekly/$id': typeof WeeklyIdRoute
  '/duels': typeof DuelsIndexRoute
  '/play': typeof PlayIndexRoute
  '/weekly': typeof WeeklyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duels': typeof DuelsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRouteWithChildren
  '/profile': typeof ProfileRoute
  '/weekly': typeof WeeklyRouteWithChildren
  '/duels/$id': typeof DuelsIdRoute
  '/play/chain': typeof PlayChainRoute
  '/play/daily': typeof PlayDailyRoute
  '/weekly/$id': typeof WeeklyIdRoute
  '/duels/': typeof DuelsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/weekly/': typeof WeeklyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/duels'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/weekly'
    | '/duels/$id'
    | '/play/chain'
    | '/play/daily'
    | '/weekly/$id'
    | '/duels/'
    | '/play/'
    | '/weekly/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/duels/$id'
    | '/play/chain'
    | '/play/daily'
    | '/weekly/$id'
    | '/duels'
    | '/play'
    | '/weekly'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/duels'
    | '/leaderboard'
    | '/play'
    | '/profile'
    | '/weekly'
    | '/duels/$id'
    | '/play/chain'
    | '/play/daily'
    | '/weekly/$id'
    | '/duels/'
    | '/play/'
    | '/weekly/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DuelsRoute: typeof DuelsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  WeeklyRoute: typeof WeeklyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duels': {
      id: '/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof DuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly/': {
      id: '/weekly/'
      path: '/'
      fullPath: '/weekly/'
      preLoaderRoute: typeof WeeklyIndexRouteImport
      parentRoute: typeof WeeklyRoute
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/duels/': {
      id: '/duels/'
      path: '/'
      fullPath: '/duels/'
      preLoaderRoute: typeof DuelsIndexRouteImport
      parentRoute: typeof DuelsRoute
    }
    '/weekly/$id': {
      id: '/weekly/$id'
      path: '/$id'
      fullPath: '/weekly/$id'
      preLoaderRoute: typeof WeeklyIdRouteImport
      parentRoute: typeof WeeklyRoute
    }
    '/play/daily': {
      id: '/play/daily'
      path: '/daily'
      fullPath: '/play/daily'
      preLoaderRoute: typeof PlayDailyRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/chain': {
      id: '/play/chain'
      path: '/chain'
      fullPath: '/play/chain'
      preLoaderRoute: typeof PlayChainRouteImport
      parentRoute: typeof PlayRoute
    }
    '/duels/$id': {
      id: '/duels/$id'
      path: '/$id'
      fullPath: '/duels/$id'
      preLoaderRoute: typeof DuelsIdRouteImport
      parentRoute: typeof DuelsRoute
    }
  }
}

interface DuelsRouteChildren {
  DuelsIdRoute: typeof DuelsIdRoute
  DuelsIndexRoute: typeof DuelsIndexRoute
}

const DuelsRouteChildren: DuelsRouteChildren = {
  DuelsIdRoute: DuelsIdRoute,
  DuelsIndexRoute: DuelsIndexRoute,
}

const DuelsRouteWithChildren = DuelsRoute._addFileChildren(DuelsRouteChildren)

interface PlayRouteChildren {
  PlayChainRoute: typeof PlayChainRoute
  PlayDailyRoute: typeof PlayDailyRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayChainRoute: PlayChainRoute,
  PlayDailyRoute: PlayDailyRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface WeeklyRouteChildren {
  WeeklyIdRoute: typeof WeeklyIdRoute
  WeeklyIndexRoute: typeof WeeklyIndexRoute
}

const WeeklyRouteChildren: WeeklyRouteChildren = {
  WeeklyIdRoute: WeeklyIdRoute,
  WeeklyIndexRoute: WeeklyIndexRoute,
}

const WeeklyRouteWithChildren =
  WeeklyRoute._addFileChildren(WeeklyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DuelsRoute: DuelsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRouteWithChildren,
  ProfileRoute: ProfileRoute,
  WeeklyRoute: WeeklyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
