-- Migration: Add 200 science questions (100 French + 100 English)
-- Categories: physics, chemistry, biology, astronomy, famous scientists
-- 20 questions per difficulty level (1-5) for each language

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES

-- =============================================
-- FRENCH QUESTIONS - DIFFICULTY 1 (Basic)
-- =============================================
('sciences', 1, 'Quelle planète est surnommée la "planète rouge" ?', 'Mars', ARRAY['Vénus', 'Jupiter', 'Saturne'], 'fr', true),
('sciences', 1, 'Combien de pattes a une araignée ?', '8', ARRAY['6', '10', '4'], 'fr', true),
('sciences', 1, 'Quel est le plus grand organe du corps humain ?', 'La peau', ARRAY['Le foie', 'Le cerveau', 'Les poumons'], 'fr', true),
('sciences', 1, 'Quelle est la planète la plus proche du Soleil ?', 'Mercure', ARRAY['Vénus', 'Mars', 'Terre'], 'fr', true),
('sciences', 1, 'De quelle couleur sont les feuilles des plantes grâce à la chlorophylle ?', 'Vert', ARRAY['Rouge', 'Bleu', 'Jaune'], 'fr', true),
('sciences', 1, 'Quel gaz respirons-nous principalement ?', 'Oxygène', ARRAY['Azote', 'Dioxyde de carbone', 'Hélium'], 'fr', true),
('sciences', 1, 'Combien d''os y a-t-il approximativement dans le corps humain adulte ?', '206', ARRAY['106', '306', '156'], 'fr', true),
('sciences', 1, 'Quel animal est le plus grand mammifère marin ?', 'La baleine bleue', ARRAY['Le requin blanc', 'L''orque', 'Le dauphin'], 'fr', true),
('sciences', 1, 'Quelle est l''étoile la plus proche de la Terre ?', 'Le Soleil', ARRAY['Alpha Centauri', 'Sirius', 'Polaris'], 'fr', true),
('sciences', 1, 'De quoi est principalement composée l''eau ?', 'Hydrogène et oxygène', ARRAY['Carbone et oxygène', 'Azote et hydrogène', 'Hélium et oxygène'], 'fr', true),
('sciences', 1, 'Quel organe pompe le sang dans le corps ?', 'Le cœur', ARRAY['Les poumons', 'Le foie', 'Les reins'], 'fr', true),
('sciences', 1, 'Combien de planètes y a-t-il dans notre système solaire ?', '8', ARRAY['9', '7', '10'], 'fr', true),
('sciences', 1, 'Quel est le symbole chimique de l''eau ?', 'H2O', ARRAY['CO2', 'O2', 'NaCl'], 'fr', true),
('sciences', 1, 'Quel sens est associé aux oreilles ?', 'L''ouïe', ARRAY['La vue', 'L''odorat', 'Le goût'], 'fr', true),
('sciences', 1, 'Quelle planète est connue pour ses anneaux spectaculaires ?', 'Saturne', ARRAY['Jupiter', 'Uranus', 'Neptune'], 'fr', true),
('sciences', 1, 'Comment s''appelle le bébé de la grenouille ?', 'Le têtard', ARRAY['L''alevin', 'La larve', 'Le poussin'], 'fr', true),
('sciences', 1, 'Quel est l''état de l''eau quand elle gèle ?', 'Solide', ARRAY['Liquide', 'Gazeux', 'Plasma'], 'fr', true),
('sciences', 1, 'Quel scientifique a découvert la gravité grâce à une pomme ?', 'Isaac Newton', ARRAY['Albert Einstein', 'Galilée', 'Archimède'], 'fr', true),
('sciences', 1, 'Quel est le plus gros animal terrestre ?', 'L''éléphant', ARRAY['Le rhinocéros', 'L''hippopotame', 'La girafe'], 'fr', true),
('sciences', 1, 'De quoi les plantes ont-elles besoin pour faire la photosynthèse ?', 'Lumière', ARRAY['Obscurité', 'Vent', 'Froid'], 'fr', true),

-- =============================================
-- FRENCH QUESTIONS - DIFFICULTY 2 (Easy-Medium)
-- =============================================
('sciences', 2, 'Quel est le symbole chimique de l''or ?', 'Au', ARRAY['Or', 'Ag', 'Fe'], 'fr', true),
('sciences', 2, 'Comment s''appelle la couche de gaz qui entoure la Terre ?', 'L''atmosphère', ARRAY['La stratosphère', 'L''ionosphère', 'La lithosphère'], 'fr', true),
('sciences', 2, 'Quel type de cellules transporte l''oxygène dans le sang ?', 'Les globules rouges', ARRAY['Les globules blancs', 'Les plaquettes', 'Les neurones'], 'fr', true),
('sciences', 2, 'Quelle force nous maintient sur Terre ?', 'La gravité', ARRAY['Le magnétisme', 'L''électricité', 'La friction'], 'fr', true),
('sciences', 2, 'Quel est le gaz le plus abondant dans l''atmosphère terrestre ?', 'L''azote', ARRAY['L''oxygène', 'Le dioxyde de carbone', 'L''argon'], 'fr', true),
('sciences', 2, 'Combien de chromosomes possède une cellule humaine normale ?', '46', ARRAY['23', '48', '36'], 'fr', true),
('sciences', 2, 'Quel phénomène naturel est mesuré sur l''échelle de Richter ?', 'Les tremblements de terre', ARRAY['Les tornades', 'Les ouragans', 'Les tsunamis'], 'fr', true),
('sciences', 2, 'Quel est le plus petit os du corps humain ?', 'L''étrier', ARRAY['Le marteau', 'L''enclume', 'La rotule'], 'fr', true),
('sciences', 2, 'Quelle vitamine est produite par la peau exposée au soleil ?', 'Vitamine D', ARRAY['Vitamine C', 'Vitamine A', 'Vitamine B12'], 'fr', true),
('sciences', 2, 'Quel scientifique a développé la théorie de la relativité ?', 'Albert Einstein', ARRAY['Isaac Newton', 'Stephen Hawking', 'Niels Bohr'], 'fr', true),
('sciences', 2, 'Comment s''appelle le processus par lequel l''eau s''évapore des feuilles ?', 'La transpiration', ARRAY['La respiration', 'La condensation', 'La photosynthèse'], 'fr', true),
('sciences', 2, 'Quel est le métal liquide à température ambiante ?', 'Le mercure', ARRAY['Le plomb', 'L''aluminium', 'Le zinc'], 'fr', true),
('sciences', 2, 'Quelle partie de la cellule contient l''ADN ?', 'Le noyau', ARRAY['Le cytoplasme', 'La membrane', 'Les mitochondries'], 'fr', true),
('sciences', 2, 'Quel est le nom de notre galaxie ?', 'La Voie lactée', ARRAY['Andromède', 'La galaxie du Sombrero', 'La galaxie du Triangle'], 'fr', true),
('sciences', 2, 'Quel est le symbole chimique du fer ?', 'Fe', ARRAY['Fr', 'Fi', 'Ir'], 'fr', true),
('sciences', 2, 'Combien de dents possède un adulte en moyenne ?', '32', ARRAY['28', '36', '30'], 'fr', true),
('sciences', 2, 'Quel organe filtre le sang et produit l''urine ?', 'Les reins', ARRAY['Le foie', 'La rate', 'Le pancréas'], 'fr', true),
('sciences', 2, 'Quelle planète est la plus grande du système solaire ?', 'Jupiter', ARRAY['Saturne', 'Neptune', 'Uranus'], 'fr', true),
('sciences', 2, 'Quel type d''énergie est stockée dans les aliments ?', 'Énergie chimique', ARRAY['Énergie cinétique', 'Énergie nucléaire', 'Énergie mécanique'], 'fr', true),
('sciences', 2, 'Comment s''appelle l''étude des fossiles ?', 'La paléontologie', ARRAY['L''archéologie', 'La géologie', 'L''anthropologie'], 'fr', true),

-- =============================================
-- FRENCH QUESTIONS - DIFFICULTY 3 (Medium)
-- =============================================
('sciences', 3, 'Quelle est l''unité de mesure de la force ?', 'Le Newton', ARRAY['Le Joule', 'Le Watt', 'Le Pascal'], 'fr', true),
('sciences', 3, 'Quel élément chimique a le numéro atomique 6 ?', 'Le carbone', ARRAY['L''oxygène', 'L''azote', 'L''hydrogène'], 'fr', true),
('sciences', 3, 'Comment s''appelle le phénomène de division cellulaire ?', 'La mitose', ARRAY['La méiose', 'La fusion', 'La fission'], 'fr', true),
('sciences', 3, 'Quelle est la vitesse de la lumière approximativement ?', '300 000 km/s', ARRAY['150 000 km/s', '500 000 km/s', '1 000 000 km/s'], 'fr', true),
('sciences', 3, 'Quel acide est contenu dans l''estomac ?', 'Acide chlorhydrique', ARRAY['Acide sulfurique', 'Acide citrique', 'Acide acétique'], 'fr', true),
('sciences', 3, 'Qui a découvert la pénicilline ?', 'Alexander Fleming', ARRAY['Louis Pasteur', 'Marie Curie', 'Robert Koch'], 'fr', true),
('sciences', 3, 'Quel est le nom de la théorie de Darwin sur l''évolution ?', 'La sélection naturelle', ARRAY['La mutation génétique', 'L''adaptation forcée', 'La dérive génétique'], 'fr', true),
('sciences', 3, 'Quelle particule subatomique a une charge négative ?', 'L''électron', ARRAY['Le proton', 'Le neutron', 'Le quark'], 'fr', true),
('sciences', 3, 'Quel est le pH d''une solution neutre ?', '7', ARRAY['0', '14', '1'], 'fr', true),
('sciences', 3, 'Comment s''appellent les organismes qui produisent leur propre nourriture ?', 'Autotrophes', ARRAY['Hétérotrophes', 'Carnivores', 'Décomposeurs'], 'fr', true),
('sciences', 3, 'Quelle glande régule le métabolisme ?', 'La thyroïde', ARRAY['L''hypophyse', 'Le pancréas', 'Les surrénales'], 'fr', true),
('sciences', 3, 'Quel est le symbole chimique du sodium ?', 'Na', ARRAY['So', 'Sd', 'S'], 'fr', true),
('sciences', 3, 'Combien de temps met la lumière du Soleil pour atteindre la Terre ?', 'Environ 8 minutes', ARRAY['Environ 1 minute', 'Environ 1 heure', 'Environ 1 seconde'], 'fr', true),
('sciences', 3, 'Quel physicien a formulé les trois lois du mouvement ?', 'Isaac Newton', ARRAY['Galilée', 'Albert Einstein', 'Johannes Kepler'], 'fr', true),
('sciences', 3, 'Comment s''appelle le processus de transformation d''un gaz en liquide ?', 'La condensation', ARRAY['L''évaporation', 'La sublimation', 'La fusion'], 'fr', true),
('sciences', 3, 'Quel type de liaison chimique implique le partage d''électrons ?', 'Liaison covalente', ARRAY['Liaison ionique', 'Liaison métallique', 'Liaison hydrogène'], 'fr', true),
('sciences', 3, 'Quelle est la fonction principale des mitochondries ?', 'Produire de l''énergie', ARRAY['Stocker l''ADN', 'Synthétiser les protéines', 'Digérer les déchets'], 'fr', true),
('sciences', 3, 'Quel scientifique a découvert la radioactivité ?', 'Henri Becquerel', ARRAY['Marie Curie', 'Pierre Curie', 'Ernest Rutherford'], 'fr', true),
('sciences', 3, 'Quelle est l''unité de mesure de l''énergie électrique ?', 'Le kilowattheure', ARRAY['L''ampère', 'Le volt', 'L''ohm'], 'fr', true),
('sciences', 3, 'Comment s''appelle la couche de la Terre sur laquelle nous vivons ?', 'La croûte terrestre', ARRAY['Le manteau', 'Le noyau', 'L''asthénosphère'], 'fr', true),

-- =============================================
-- FRENCH QUESTIONS - DIFFICULTY 4 (Hard)
-- =============================================
('sciences', 4, 'Quelle est la formule de l''acide sulfurique ?', 'H2SO4', ARRAY['H2SO3', 'HSO4', 'H3SO4'], 'fr', true),
('sciences', 4, 'Quel est le nom du processus de réplication de l''ADN ?', 'La réplication semi-conservative', ARRAY['La réplication conservative', 'La réplication dispersive', 'La transcription'], 'fr', true),
('sciences', 4, 'Quelle constante physique vaut approximativement 6,626 × 10⁻³⁴ J·s ?', 'La constante de Planck', ARRAY['La constante de Boltzmann', 'La constante d''Avogadro', 'La constante gravitationnelle'], 'fr', true),
('sciences', 4, 'Quel est le principe d''incertitude formulé par Heisenberg ?', 'On ne peut pas connaître simultanément la position et la vitesse d''une particule', ARRAY['L''énergie est toujours conservée', 'Rien ne se déplace plus vite que la lumière', 'Toute action a une réaction égale'], 'fr', true),
('sciences', 4, 'Quelle molécule transporte l''information génétique du noyau vers les ribosomes ?', 'L''ARN messager', ARRAY['L''ARN de transfert', 'L''ARN ribosomal', 'L''ADN polymérase'], 'fr', true),
('sciences', 4, 'Quel est le nom du cycle qui décrit les réactions de la respiration cellulaire ?', 'Le cycle de Krebs', ARRAY['Le cycle de Calvin', 'Le cycle de l''azote', 'Le cycle de Cori'], 'fr', true),
('sciences', 4, 'Quelle particule a été théorisée par Peter Higgs ?', 'Le boson de Higgs', ARRAY['Le photon', 'Le gluon', 'Le graviton'], 'fr', true),
('sciences', 4, 'Quel est le numéro atomique de l''uranium ?', '92', ARRAY['82', '88', '94'], 'fr', true),
('sciences', 4, 'Comment s''appelle le phénomène où la lumière change de direction en passant d''un milieu à un autre ?', 'La réfraction', ARRAY['La réflexion', 'La diffraction', 'La dispersion'], 'fr', true),
('sciences', 4, 'Quelle équation décrit la relation entre masse et énergie ?', 'E=mc²', ARRAY['F=ma', 'PV=nRT', 'E=hf'], 'fr', true),
('sciences', 4, 'Quel est le nom de l''enzyme qui déroule l''ADN pendant la réplication ?', 'L''hélicase', ARRAY['La ligase', 'La polymérase', 'La topoisomérase'], 'fr', true),
('sciences', 4, 'Quelle théorie décrit le comportement des particules à l''échelle quantique ?', 'La mécanique quantique', ARRAY['La relativité générale', 'La théorie des cordes', 'La thermodynamique'], 'fr', true),
('sciences', 4, 'Quel est le produit de la glycolyse ?', 'Le pyruvate', ARRAY['Le glucose', 'L''acétyl-CoA', 'Le lactate'], 'fr', true),
('sciences', 4, 'Quelle est la charge d''un proton en coulombs ?', '1,6 × 10⁻¹⁹ C', ARRAY['9,1 × 10⁻³¹ C', '1,6 × 10⁻¹⁹ kg', '6,02 × 10²³ C'], 'fr', true),
('sciences', 4, 'Qui a découvert la structure en double hélice de l''ADN ?', 'Watson et Crick', ARRAY['Franklin et Wilkins', 'Darwin et Mendel', 'Pasteur et Koch'], 'fr', true),
('sciences', 4, 'Quelle est l''unité SI de la pression ?', 'Le Pascal', ARRAY['Le Bar', 'L''atmosphère', 'Le Torr'], 'fr', true),
('sciences', 4, 'Comment s''appelle le processus par lequel les cellules se spécialisent ?', 'La différenciation cellulaire', ARRAY['La mitose', 'La méiose', 'L''apoptose'], 'fr', true),
('sciences', 4, 'Quel type de rayonnement a le plus petit longueur d''onde ?', 'Les rayons gamma', ARRAY['Les rayons X', 'Les ultraviolets', 'Les micro-ondes'], 'fr', true),
('sciences', 4, 'Quelle loi de la thermodynamique stipule que l''entropie d''un système isolé ne peut qu''augmenter ?', 'La deuxième loi', ARRAY['La première loi', 'La troisième loi', 'La loi zéro'], 'fr', true),
('sciences', 4, 'Quel est le nom de la force qui maintient les quarks ensemble ?', 'La force nucléaire forte', ARRAY['La force nucléaire faible', 'La force électromagnétique', 'La force gravitationnelle'], 'fr', true),

-- =============================================
-- FRENCH QUESTIONS - DIFFICULTY 5 (Expert)
-- =============================================
('sciences', 5, 'Quelle est la constante de Boltzmann approximativement ?', '1,38 × 10⁻²³ J/K', ARRAY['6,02 × 10²³ J/K', '8,31 J/mol·K', '9,81 × 10⁻¹¹ J/K'], 'fr', true),
('sciences', 5, 'Comment s''appelle le principe qui stipule que deux fermions ne peuvent pas occuper le même état quantique ?', 'Le principe d''exclusion de Pauli', ARRAY['Le principe d''incertitude de Heisenberg', 'Le principe de superposition', 'Le principe de correspondance'], 'fr', true),
('sciences', 5, 'Quelle est la formule de l''équation de Schrödinger indépendante du temps ?', 'ĤΨ = EΨ', ARRAY['E = mc²', 'F = ma', 'PV = nRT'], 'fr', true),
('sciences', 5, 'Quel est le nombre quantique qui détermine la forme de l''orbitale ?', 'Le nombre quantique azimutal (l)', ARRAY['Le nombre quantique principal (n)', 'Le nombre quantique magnétique (ml)', 'Le nombre quantique de spin (ms)'], 'fr', true),
('sciences', 5, 'Comment s''appelle le mécanisme de régulation génétique découvert par Jacob et Monod ?', 'L''opéron', ARRAY['Le réplicon', 'Le codon', 'L''intron'], 'fr', true),
('sciences', 5, 'Quelle est la valeur de la constante gravitationnelle G ?', '6,67 × 10⁻¹¹ N·m²/kg²', ARRAY['9,81 m/s²', '3 × 10⁸ m/s', '1,6 × 10⁻¹⁹ C'], 'fr', true),
('sciences', 5, 'Quel est le nom du phénomène où une particule traverse une barrière de potentiel classiquement interdite ?', 'L''effet tunnel quantique', ARRAY['L''effet photoélectrique', 'L''effet Compton', 'L''effet Doppler'], 'fr', true),
('sciences', 5, 'Quelle enzyme catalyse la synthèse de l''ATP dans les mitochondries ?', 'L''ATP synthase', ARRAY['L''ATPase', 'La cytochrome oxydase', 'La NADH déshydrogénase'], 'fr', true),
('sciences', 5, 'Comment s''appelle la température théorique minimale où tout mouvement moléculaire cesse ?', 'Le zéro absolu', ARRAY['Le point triple', 'Le point critique', 'Le point d''ébullition'], 'fr', true),
('sciences', 5, 'Quelle est la durée de demi-vie du carbone-14 ?', 'Environ 5730 ans', ARRAY['Environ 1600 ans', 'Environ 12000 ans', 'Environ 8000 ans'], 'fr', true),
('sciences', 5, 'Quel est le nom de la particule hypothétique médiatrice de la gravité ?', 'Le graviton', ARRAY['Le boson de Higgs', 'Le photon', 'Le gluon'], 'fr', true),
('sciences', 5, 'Comment s''appelle le processus de production d''énergie dans les étoiles ?', 'La fusion nucléaire', ARRAY['La fission nucléaire', 'La combustion', 'L''annihilation'], 'fr', true),
('sciences', 5, 'Quelle est l''équation d''état des gaz parfaits ?', 'PV = nRT', ARRAY['E = mc²', 'F = ma', 'ΔG = ΔH - TΔS'], 'fr', true),
('sciences', 5, 'Quel scientifique a proposé le modèle planétaire de l''atome ?', 'Niels Bohr', ARRAY['Ernest Rutherford', 'J.J. Thomson', 'John Dalton'], 'fr', true),
('sciences', 5, 'Comment s''appelle la technique de séquençage de l''ADN la plus utilisée ?', 'La méthode de Sanger', ARRAY['La PCR', 'L''électrophorèse', 'Le Southern blot'], 'fr', true),
('sciences', 5, 'Quelle est la relation entre l''énergie libre de Gibbs, l''enthalpie et l''entropie ?', 'ΔG = ΔH - TΔS', ARRAY['ΔG = ΔH + TΔS', 'ΔG = ΔH × TΔS', 'ΔG = ΔH / TΔS'], 'fr', true),
('sciences', 5, 'Quel est le nom du principe qui stipule que les lois de la physique sont les mêmes dans tous les référentiels inertiels ?', 'Le principe de relativité', ARRAY['Le principe d''équivalence', 'Le principe de moindre action', 'Le principe de Mach'], 'fr', true),
('sciences', 5, 'Quelle est la configuration électronique du fer (Fe) ?', '[Ar] 3d⁶ 4s²', ARRAY['[Ar] 3d⁸', '[Ar] 3d⁵ 4s²', '[Ar] 3d⁷ 4s¹'], 'fr', true),
('sciences', 5, 'Comment s''appelle le phénomène de dégénérescence du code génétique ?', 'La redondance', ARRAY['La mutation', 'La transcription', 'La traduction'], 'fr', true),
('sciences', 5, 'Quelle est la constante d''Avogadro ?', '6,022 × 10²³ mol⁻¹', ARRAY['1,38 × 10⁻²³ mol⁻¹', '8,314 mol⁻¹', '9,109 × 10³¹ mol⁻¹'], 'fr', true),

-- =============================================
-- ENGLISH QUESTIONS - DIFFICULTY 1 (Basic)
-- =============================================
('sciences', 1, 'Which planet is known as the "Red Planet"?', 'Mars', ARRAY['Venus', 'Jupiter', 'Saturn'], 'en', true),
('sciences', 1, 'How many legs does a spider have?', '8', ARRAY['6', '10', '4'], 'en', true),
('sciences', 1, 'What is the largest organ of the human body?', 'Skin', ARRAY['Liver', 'Brain', 'Lungs'], 'en', true),
('sciences', 1, 'Which planet is closest to the Sun?', 'Mercury', ARRAY['Venus', 'Mars', 'Earth'], 'en', true),
('sciences', 1, 'What color do plants appear because of chlorophyll?', 'Green', ARRAY['Red', 'Blue', 'Yellow'], 'en', true),
('sciences', 1, 'What gas do we primarily breathe?', 'Oxygen', ARRAY['Nitrogen', 'Carbon dioxide', 'Helium'], 'en', true),
('sciences', 1, 'Approximately how many bones are in an adult human body?', '206', ARRAY['106', '306', '156'], 'en', true),
('sciences', 1, 'What is the largest marine mammal?', 'Blue whale', ARRAY['Great white shark', 'Orca', 'Dolphin'], 'en', true),
('sciences', 1, 'What is the closest star to Earth?', 'The Sun', ARRAY['Alpha Centauri', 'Sirius', 'Polaris'], 'en', true),
('sciences', 1, 'What is water primarily made of?', 'Hydrogen and oxygen', ARRAY['Carbon and oxygen', 'Nitrogen and hydrogen', 'Helium and oxygen'], 'en', true),
('sciences', 1, 'Which organ pumps blood through the body?', 'Heart', ARRAY['Lungs', 'Liver', 'Kidneys'], 'en', true),
('sciences', 1, 'How many planets are in our solar system?', '8', ARRAY['9', '7', '10'], 'en', true),
('sciences', 1, 'What is the chemical symbol for water?', 'H2O', ARRAY['CO2', 'O2', 'NaCl'], 'en', true),
('sciences', 1, 'Which sense is associated with ears?', 'Hearing', ARRAY['Sight', 'Smell', 'Taste'], 'en', true),
('sciences', 1, 'Which planet is known for its spectacular rings?', 'Saturn', ARRAY['Jupiter', 'Uranus', 'Neptune'], 'en', true),
('sciences', 1, 'What is a baby frog called?', 'Tadpole', ARRAY['Fry', 'Larva', 'Chick'], 'en', true),
('sciences', 1, 'What state is water when it freezes?', 'Solid', ARRAY['Liquid', 'Gas', 'Plasma'], 'en', true),
('sciences', 1, 'Which scientist discovered gravity thanks to an apple?', 'Isaac Newton', ARRAY['Albert Einstein', 'Galileo', 'Archimedes'], 'en', true),
('sciences', 1, 'What is the largest land animal?', 'Elephant', ARRAY['Rhinoceros', 'Hippopotamus', 'Giraffe'], 'en', true),
('sciences', 1, 'What do plants need for photosynthesis?', 'Light', ARRAY['Darkness', 'Wind', 'Cold'], 'en', true),

-- =============================================
-- ENGLISH QUESTIONS - DIFFICULTY 2 (Easy-Medium)
-- =============================================
('sciences', 2, 'What is the chemical symbol for gold?', 'Au', ARRAY['Go', 'Ag', 'Fe'], 'en', true),
('sciences', 2, 'What is the layer of gas surrounding Earth called?', 'Atmosphere', ARRAY['Stratosphere', 'Ionosphere', 'Lithosphere'], 'en', true),
('sciences', 2, 'What type of cells carry oxygen in the blood?', 'Red blood cells', ARRAY['White blood cells', 'Platelets', 'Neurons'], 'en', true),
('sciences', 2, 'What force keeps us on Earth?', 'Gravity', ARRAY['Magnetism', 'Electricity', 'Friction'], 'en', true),
('sciences', 2, 'What is the most abundant gas in Earth''s atmosphere?', 'Nitrogen', ARRAY['Oxygen', 'Carbon dioxide', 'Argon'], 'en', true),
('sciences', 2, 'How many chromosomes does a normal human cell have?', '46', ARRAY['23', '48', '36'], 'en', true),
('sciences', 2, 'What natural phenomenon is measured on the Richter scale?', 'Earthquakes', ARRAY['Tornadoes', 'Hurricanes', 'Tsunamis'], 'en', true),
('sciences', 2, 'What is the smallest bone in the human body?', 'Stapes', ARRAY['Malleus', 'Incus', 'Patella'], 'en', true),
('sciences', 2, 'Which vitamin is produced by skin exposed to sunlight?', 'Vitamin D', ARRAY['Vitamin C', 'Vitamin A', 'Vitamin B12'], 'en', true),
('sciences', 2, 'Which scientist developed the theory of relativity?', 'Albert Einstein', ARRAY['Isaac Newton', 'Stephen Hawking', 'Niels Bohr'], 'en', true),
('sciences', 2, 'What is the process called when water evaporates from leaves?', 'Transpiration', ARRAY['Respiration', 'Condensation', 'Photosynthesis'], 'en', true),
('sciences', 2, 'Which metal is liquid at room temperature?', 'Mercury', ARRAY['Lead', 'Aluminum', 'Zinc'], 'en', true),
('sciences', 2, 'Which part of the cell contains DNA?', 'Nucleus', ARRAY['Cytoplasm', 'Membrane', 'Mitochondria'], 'en', true),
('sciences', 2, 'What is the name of our galaxy?', 'Milky Way', ARRAY['Andromeda', 'Sombrero Galaxy', 'Triangulum Galaxy'], 'en', true),
('sciences', 2, 'What is the chemical symbol for iron?', 'Fe', ARRAY['Ir', 'In', 'Fr'], 'en', true),
('sciences', 2, 'How many teeth does an adult human have on average?', '32', ARRAY['28', '36', '30'], 'en', true),
('sciences', 2, 'Which organ filters blood and produces urine?', 'Kidneys', ARRAY['Liver', 'Spleen', 'Pancreas'], 'en', true),
('sciences', 2, 'What is the largest planet in our solar system?', 'Jupiter', ARRAY['Saturn', 'Neptune', 'Uranus'], 'en', true),
('sciences', 2, 'What type of energy is stored in food?', 'Chemical energy', ARRAY['Kinetic energy', 'Nuclear energy', 'Mechanical energy'], 'en', true),
('sciences', 2, 'What is the study of fossils called?', 'Paleontology', ARRAY['Archaeology', 'Geology', 'Anthropology'], 'en', true),

-- =============================================
-- ENGLISH QUESTIONS - DIFFICULTY 3 (Medium)
-- =============================================
('sciences', 3, 'What is the unit of measurement for force?', 'Newton', ARRAY['Joule', 'Watt', 'Pascal'], 'en', true),
('sciences', 3, 'Which chemical element has atomic number 6?', 'Carbon', ARRAY['Oxygen', 'Nitrogen', 'Hydrogen'], 'en', true),
('sciences', 3, 'What is the process of cell division called?', 'Mitosis', ARRAY['Meiosis', 'Fusion', 'Fission'], 'en', true),
('sciences', 3, 'What is the approximate speed of light?', '300,000 km/s', ARRAY['150,000 km/s', '500,000 km/s', '1,000,000 km/s'], 'en', true),
('sciences', 3, 'Which acid is found in the stomach?', 'Hydrochloric acid', ARRAY['Sulfuric acid', 'Citric acid', 'Acetic acid'], 'en', true),
('sciences', 3, 'Who discovered penicillin?', 'Alexander Fleming', ARRAY['Louis Pasteur', 'Marie Curie', 'Robert Koch'], 'en', true),
('sciences', 3, 'What is Darwin''s theory of evolution called?', 'Natural selection', ARRAY['Genetic mutation', 'Forced adaptation', 'Genetic drift'], 'en', true),
('sciences', 3, 'Which subatomic particle has a negative charge?', 'Electron', ARRAY['Proton', 'Neutron', 'Quark'], 'en', true),
('sciences', 3, 'What is the pH of a neutral solution?', '7', ARRAY['0', '14', '1'], 'en', true),
('sciences', 3, 'What are organisms that produce their own food called?', 'Autotrophs', ARRAY['Heterotrophs', 'Carnivores', 'Decomposers'], 'en', true),
('sciences', 3, 'Which gland regulates metabolism?', 'Thyroid', ARRAY['Pituitary', 'Pancreas', 'Adrenal'], 'en', true),
('sciences', 3, 'What is the chemical symbol for sodium?', 'Na', ARRAY['So', 'Sd', 'S'], 'en', true),
('sciences', 3, 'How long does sunlight take to reach Earth?', 'About 8 minutes', ARRAY['About 1 minute', 'About 1 hour', 'About 1 second'], 'en', true),
('sciences', 3, 'Which physicist formulated the three laws of motion?', 'Isaac Newton', ARRAY['Galileo', 'Albert Einstein', 'Johannes Kepler'], 'en', true),
('sciences', 3, 'What is the process of gas turning into liquid called?', 'Condensation', ARRAY['Evaporation', 'Sublimation', 'Melting'], 'en', true),
('sciences', 3, 'What type of chemical bond involves sharing electrons?', 'Covalent bond', ARRAY['Ionic bond', 'Metallic bond', 'Hydrogen bond'], 'en', true),
('sciences', 3, 'What is the main function of mitochondria?', 'Produce energy', ARRAY['Store DNA', 'Synthesize proteins', 'Digest waste'], 'en', true),
('sciences', 3, 'Which scientist discovered radioactivity?', 'Henri Becquerel', ARRAY['Marie Curie', 'Pierre Curie', 'Ernest Rutherford'], 'en', true),
('sciences', 3, 'What is the unit of measurement for electrical energy?', 'Kilowatt-hour', ARRAY['Ampere', 'Volt', 'Ohm'], 'en', true),
('sciences', 3, 'What is the layer of Earth we live on called?', 'Crust', ARRAY['Mantle', 'Core', 'Asthenosphere'], 'en', true),

-- =============================================
-- ENGLISH QUESTIONS - DIFFICULTY 4 (Hard)
-- =============================================
('sciences', 4, 'What is the formula for sulfuric acid?', 'H2SO4', ARRAY['H2SO3', 'HSO4', 'H3SO4'], 'en', true),
('sciences', 4, 'What is the name of the DNA replication process?', 'Semi-conservative replication', ARRAY['Conservative replication', 'Dispersive replication', 'Transcription'], 'en', true),
('sciences', 4, 'Which physical constant has a value of approximately 6.626 × 10⁻³⁴ J·s?', 'Planck constant', ARRAY['Boltzmann constant', 'Avogadro constant', 'Gravitational constant'], 'en', true),
('sciences', 4, 'What is Heisenberg''s uncertainty principle?', 'Position and momentum cannot be simultaneously known with certainty', ARRAY['Energy is always conserved', 'Nothing travels faster than light', 'Every action has an equal reaction'], 'en', true),
('sciences', 4, 'Which molecule carries genetic information from the nucleus to ribosomes?', 'Messenger RNA', ARRAY['Transfer RNA', 'Ribosomal RNA', 'DNA polymerase'], 'en', true),
('sciences', 4, 'What is the name of the cycle that describes cellular respiration reactions?', 'Krebs cycle', ARRAY['Calvin cycle', 'Nitrogen cycle', 'Cori cycle'], 'en', true),
('sciences', 4, 'Which particle was theorized by Peter Higgs?', 'Higgs boson', ARRAY['Photon', 'Gluon', 'Graviton'], 'en', true),
('sciences', 4, 'What is the atomic number of uranium?', '92', ARRAY['82', '88', '94'], 'en', true),
('sciences', 4, 'What is the phenomenon called when light changes direction passing from one medium to another?', 'Refraction', ARRAY['Reflection', 'Diffraction', 'Dispersion'], 'en', true),
('sciences', 4, 'Which equation describes the relationship between mass and energy?', 'E=mc²', ARRAY['F=ma', 'PV=nRT', 'E=hf'], 'en', true),
('sciences', 4, 'What is the name of the enzyme that unwinds DNA during replication?', 'Helicase', ARRAY['Ligase', 'Polymerase', 'Topoisomerase'], 'en', true),
('sciences', 4, 'Which theory describes the behavior of particles at the quantum scale?', 'Quantum mechanics', ARRAY['General relativity', 'String theory', 'Thermodynamics'], 'en', true),
('sciences', 4, 'What is the product of glycolysis?', 'Pyruvate', ARRAY['Glucose', 'Acetyl-CoA', 'Lactate'], 'en', true),
('sciences', 4, 'What is the charge of a proton in coulombs?', '1.6 × 10⁻¹⁹ C', ARRAY['9.1 × 10⁻³¹ C', '1.6 × 10⁻¹⁹ kg', '6.02 × 10²³ C'], 'en', true),
('sciences', 4, 'Who discovered the double helix structure of DNA?', 'Watson and Crick', ARRAY['Franklin and Wilkins', 'Darwin and Mendel', 'Pasteur and Koch'], 'en', true),
('sciences', 4, 'What is the SI unit of pressure?', 'Pascal', ARRAY['Bar', 'Atmosphere', 'Torr'], 'en', true),
('sciences', 4, 'What is the process by which cells specialize called?', 'Cell differentiation', ARRAY['Mitosis', 'Meiosis', 'Apoptosis'], 'en', true),
('sciences', 4, 'Which type of radiation has the smallest wavelength?', 'Gamma rays', ARRAY['X-rays', 'Ultraviolet', 'Microwaves'], 'en', true),
('sciences', 4, 'Which law of thermodynamics states that entropy of an isolated system can only increase?', 'Second law', ARRAY['First law', 'Third law', 'Zeroth law'], 'en', true),
('sciences', 4, 'What is the name of the force that holds quarks together?', 'Strong nuclear force', ARRAY['Weak nuclear force', 'Electromagnetic force', 'Gravitational force'], 'en', true),

-- =============================================
-- ENGLISH QUESTIONS - DIFFICULTY 5 (Expert)
-- =============================================
('sciences', 5, 'What is the approximate value of Boltzmann constant?', '1.38 × 10⁻²³ J/K', ARRAY['6.02 × 10²³ J/K', '8.31 J/mol·K', '9.81 × 10⁻¹¹ J/K'], 'en', true),
('sciences', 5, 'What principle states that two fermions cannot occupy the same quantum state?', 'Pauli exclusion principle', ARRAY['Heisenberg uncertainty principle', 'Superposition principle', 'Correspondence principle'], 'en', true),
('sciences', 5, 'What is the time-independent Schrödinger equation?', 'ĤΨ = EΨ', ARRAY['E = mc²', 'F = ma', 'PV = nRT'], 'en', true),
('sciences', 5, 'Which quantum number determines the shape of an orbital?', 'Azimuthal quantum number (l)', ARRAY['Principal quantum number (n)', 'Magnetic quantum number (ml)', 'Spin quantum number (ms)'], 'en', true),
('sciences', 5, 'What is the genetic regulation mechanism discovered by Jacob and Monod called?', 'Operon', ARRAY['Replicon', 'Codon', 'Intron'], 'en', true),
('sciences', 5, 'What is the value of the gravitational constant G?', '6.67 × 10⁻¹¹ N·m²/kg²', ARRAY['9.81 m/s²', '3 × 10⁸ m/s', '1.6 × 10⁻¹⁹ C'], 'en', true),
('sciences', 5, 'What phenomenon allows a particle to pass through a classically forbidden potential barrier?', 'Quantum tunneling', ARRAY['Photoelectric effect', 'Compton effect', 'Doppler effect'], 'en', true),
('sciences', 5, 'Which enzyme catalyzes ATP synthesis in mitochondria?', 'ATP synthase', ARRAY['ATPase', 'Cytochrome oxidase', 'NADH dehydrogenase'], 'en', true),
('sciences', 5, 'What is the theoretical minimum temperature where all molecular motion ceases?', 'Absolute zero', ARRAY['Triple point', 'Critical point', 'Boiling point'], 'en', true),
('sciences', 5, 'What is the half-life of carbon-14?', 'About 5,730 years', ARRAY['About 1,600 years', 'About 12,000 years', 'About 8,000 years'], 'en', true),
('sciences', 5, 'What is the hypothetical particle that mediates gravity called?', 'Graviton', ARRAY['Higgs boson', 'Photon', 'Gluon'], 'en', true),
('sciences', 5, 'What is the process of energy production in stars called?', 'Nuclear fusion', ARRAY['Nuclear fission', 'Combustion', 'Annihilation'], 'en', true),
('sciences', 5, 'What is the ideal gas law equation?', 'PV = nRT', ARRAY['E = mc²', 'F = ma', 'ΔG = ΔH - TΔS'], 'en', true),
('sciences', 5, 'Which scientist proposed the planetary model of the atom?', 'Niels Bohr', ARRAY['Ernest Rutherford', 'J.J. Thomson', 'John Dalton'], 'en', true),
('sciences', 5, 'What is the most widely used DNA sequencing technique called?', 'Sanger method', ARRAY['PCR', 'Electrophoresis', 'Southern blot'], 'en', true),
('sciences', 5, 'What is the relationship between Gibbs free energy, enthalpy, and entropy?', 'ΔG = ΔH - TΔS', ARRAY['ΔG = ΔH + TΔS', 'ΔG = ΔH × TΔS', 'ΔG = ΔH / TΔS'], 'en', true),
('sciences', 5, 'What principle states that the laws of physics are the same in all inertial reference frames?', 'Principle of relativity', ARRAY['Equivalence principle', 'Principle of least action', 'Mach''s principle'], 'en', true),
('sciences', 5, 'What is the electron configuration of iron (Fe)?', '[Ar] 3d⁶ 4s²', ARRAY['[Ar] 3d⁸', '[Ar] 3d⁵ 4s²', '[Ar] 3d⁷ 4s¹'], 'en', true),
('sciences', 5, 'What is the phenomenon of genetic code degeneracy called?', 'Redundancy', ARRAY['Mutation', 'Transcription', 'Translation'], 'en', true),
('sciences', 5, 'What is Avogadro''s constant?', '6.022 × 10²³ mol⁻¹', ARRAY['1.38 × 10⁻²³ mol⁻¹', '8.314 mol⁻¹', '9.109 × 10³¹ mol⁻¹'], 'en', true);
