-- Migration: Add 200 geography questions (100 French + 100 English)
-- Date: 2026-01-26

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES

-- =====================================================
-- FRENCH QUESTIONS (100 total - 20 per difficulty)
-- =====================================================

-- FRENCH - Difficulty 1 (Very Easy - Children)
('geographie', 1, 'Quelle est la capitale de la France ?', 'Paris', ARRAY['Lyon', 'Marseille', 'Bordeaux'], 'fr', true),
('geographie', 1, 'Quel est le plus grand océan du monde ?', 'L''océan Pacifique', ARRAY['L''océan Atlantique', 'L''océan Indien', 'L''océan Arctique'], 'fr', true),
('geographie', 1, 'Combien y a-t-il de continents sur Terre ?', '7', ARRAY['5', '6', '8'], 'fr', true),
('geographie', 1, 'Quel est le fleuve qui traverse Paris ?', 'La Seine', ARRAY['La Loire', 'Le Rhône', 'La Garonne'], 'fr', true),
('geographie', 1, 'Quel pays a la forme d''une botte ?', 'L''Italie', ARRAY['L''Espagne', 'La Grèce', 'Le Portugal'], 'fr', true),
('geographie', 1, 'Quelle est la capitale de l''Espagne ?', 'Madrid', ARRAY['Barcelone', 'Séville', 'Valence'], 'fr', true),
('geographie', 1, 'Sur quel continent se trouve l''Égypte ?', 'L''Afrique', ARRAY['L''Asie', 'L''Europe', 'L''Océanie'], 'fr', true),
('geographie', 1, 'Quel est le plus grand pays du monde ?', 'La Russie', ARRAY['Le Canada', 'La Chine', 'Les États-Unis'], 'fr', true),
('geographie', 1, 'Quelle mer borde le sud de la France ?', 'La mer Méditerranée', ARRAY['La mer du Nord', 'La Manche', 'L''océan Atlantique'], 'fr', true),
('geographie', 1, 'Quelle est la capitale de l''Allemagne ?', 'Berlin', ARRAY['Munich', 'Hambourg', 'Francfort'], 'fr', true),
('geographie', 1, 'Quel pays est célèbre pour ses kangourous ?', 'L''Australie', ARRAY['L''Afrique du Sud', 'Le Brésil', 'L''Inde'], 'fr', true),
('geographie', 1, 'Quelle est la capitale du Royaume-Uni ?', 'Londres', ARRAY['Manchester', 'Liverpool', 'Birmingham'], 'fr', true),
('geographie', 1, 'Quel est le plus long fleuve de France ?', 'La Loire', ARRAY['La Seine', 'Le Rhône', 'La Garonne'], 'fr', true),
('geographie', 1, 'Quel pays partage une frontière au nord de la France ?', 'La Belgique', ARRAY['L''Allemagne', 'La Suisse', 'L''Italie'], 'fr', true),
('geographie', 1, 'Quelle est la capitale de l''Italie ?', 'Rome', ARRAY['Milan', 'Naples', 'Florence'], 'fr', true),
('geographie', 1, 'Quel est l''animal emblématique du Canada ?', 'Le castor', ARRAY['L''ours', 'Le loup', 'L''aigle'], 'fr', true),
('geographie', 1, 'Quelle est la capitale du Japon ?', 'Tokyo', ARRAY['Osaka', 'Kyoto', 'Hiroshima'], 'fr', true),
('geographie', 1, 'Quel monument célèbre se trouve à Paris ?', 'La Tour Eiffel', ARRAY['Big Ben', 'La Statue de la Liberté', 'Le Colisée'], 'fr', true),
('geographie', 1, 'Quel est le continent le plus froid ?', 'L''Antarctique', ARRAY['L''Arctique', 'L''Europe', 'L''Amérique du Nord'], 'fr', true),
('geographie', 1, 'Quelle est la capitale des États-Unis ?', 'Washington D.C.', ARRAY['New York', 'Los Angeles', 'Chicago'], 'fr', true),

-- FRENCH - Difficulty 2 (Easy)
('geographie', 2, 'Quel est le plus haut sommet des Alpes ?', 'Le Mont Blanc', ARRAY['Le Mont Rose', 'Le Cervin', 'La Jungfrau'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de la Belgique ?', 'Bruxelles', ARRAY['Anvers', 'Gand', 'Liège'], 'fr', true),
('geographie', 2, 'Quel fleuve traverse l''Égypte ?', 'Le Nil', ARRAY['Le Congo', 'Le Zambèze', 'Le Niger'], 'fr', true),
('geographie', 2, 'Combien de pays composent l''Union Européenne en 2024 ?', '27', ARRAY['25', '28', '30'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de la Suisse ?', 'Berne', ARRAY['Zurich', 'Genève', 'Lausanne'], 'fr', true),
('geographie', 2, 'Quel désert est le plus grand du monde ?', 'Le Sahara', ARRAY['Le Gobi', 'L''Atacama', 'Le Kalahari'], 'fr', true),
('geographie', 2, 'Quelle est la capitale du Portugal ?', 'Lisbonne', ARRAY['Porto', 'Faro', 'Coimbra'], 'fr', true),
('geographie', 2, 'Quel océan borde la côte ouest de l''Afrique ?', 'L''océan Atlantique', ARRAY['L''océan Indien', 'L''océan Pacifique', 'La mer Rouge'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de la Grèce ?', 'Athènes', ARRAY['Thessalonique', 'Patras', 'Héraklion'], 'fr', true),
('geographie', 2, 'Quel est le plus grand lac d''Europe ?', 'Le lac Ladoga', ARRAY['Le lac Léman', 'Le lac de Constance', 'Le lac Balaton'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de l''Autriche ?', 'Vienne', ARRAY['Salzbourg', 'Innsbruck', 'Graz'], 'fr', true),
('geographie', 2, 'Quel pays est surnommé le pays du Soleil Levant ?', 'Le Japon', ARRAY['La Chine', 'La Corée du Sud', 'Le Vietnam'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de la Pologne ?', 'Varsovie', ARRAY['Cracovie', 'Gdansk', 'Poznan'], 'fr', true),
('geographie', 2, 'Quel fleuve traverse Londres ?', 'La Tamise', ARRAY['La Severn', 'La Mersey', 'La Trent'], 'fr', true),
('geographie', 2, 'Quelle est la capitale du Brésil ?', 'Brasilia', ARRAY['Rio de Janeiro', 'São Paulo', 'Salvador'], 'fr', true),
('geographie', 2, 'Quel pays a le plus d''habitants au monde ?', 'L''Inde', ARRAY['La Chine', 'Les États-Unis', 'L''Indonésie'], 'fr', true),
('geographie', 2, 'Quelle chaîne de montagnes sépare la France de l''Espagne ?', 'Les Pyrénées', ARRAY['Les Alpes', 'Le Massif Central', 'Les Vosges'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de l''Argentine ?', 'Buenos Aires', ARRAY['Córdoba', 'Rosario', 'Mendoza'], 'fr', true),
('geographie', 2, 'Quel pays est traversé par l''équateur en Amérique du Sud ?', 'L''Équateur', ARRAY['Le Pérou', 'La Bolivie', 'Le Chili'], 'fr', true),
('geographie', 2, 'Quelle est la capitale de la Norvège ?', 'Oslo', ARRAY['Bergen', 'Trondheim', 'Stavanger'], 'fr', true),

-- FRENCH - Difficulty 3 (Medium)
('geographie', 3, 'Quel détroit sépare l''Europe de l''Afrique ?', 'Le détroit de Gibraltar', ARRAY['Le détroit du Bosphore', 'Le détroit de Messine', 'Le canal de Suez'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de la Hongrie ?', 'Budapest', ARRAY['Prague', 'Vienne', 'Bratislava'], 'fr', true),
('geographie', 3, 'Quel fleuve traverse Vienne, Budapest et Belgrade ?', 'Le Danube', ARRAY['Le Rhin', 'L''Elbe', 'La Vistule'], 'fr', true),
('geographie', 3, 'Quelle est la plus grande île de la Méditerranée ?', 'La Sicile', ARRAY['La Sardaigne', 'Chypre', 'La Corse'], 'fr', true),
('geographie', 3, 'Quelle est la capitale du Maroc ?', 'Rabat', ARRAY['Casablanca', 'Marrakech', 'Fès'], 'fr', true),
('geographie', 3, 'Quel pays possède le plus de fuseaux horaires ?', 'La France', ARRAY['La Russie', 'Les États-Unis', 'Le Royaume-Uni'], 'fr', true),
('geographie', 3, 'Quelle mer est située entre l''Europe et l''Asie ?', 'La mer Noire', ARRAY['La mer Caspienne', 'La mer d''Aral', 'La mer Baltique'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de la Thaïlande ?', 'Bangkok', ARRAY['Chiang Mai', 'Phuket', 'Pattaya'], 'fr', true),
('geographie', 3, 'Quel est le plus haut sommet d''Afrique ?', 'Le Kilimandjaro', ARRAY['Le Mont Kenya', 'Le Ruwenzori', 'L''Atlas'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de l''Indonésie ?', 'Jakarta', ARRAY['Bali', 'Surabaya', 'Bandung'], 'fr', true),
('geographie', 3, 'Quel fleuve forme une partie de la frontière entre les États-Unis et le Mexique ?', 'Le Rio Grande', ARRAY['Le Colorado', 'Le Mississippi', 'Le Missouri'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de la Finlande ?', 'Helsinki', ARRAY['Turku', 'Tampere', 'Espoo'], 'fr', true),
('geographie', 3, 'Quel pays africain était autrefois appelé Abyssinie ?', 'L''Éthiopie', ARRAY['L''Érythrée', 'Le Soudan', 'La Somalie'], 'fr', true),
('geographie', 3, 'Quelle est la capitale du Vietnam ?', 'Hanoï', ARRAY['Hô Chi Minh-Ville', 'Da Nang', 'Hué'], 'fr', true),
('geographie', 3, 'Quel est le plus long fleuve d''Asie ?', 'Le Yangtsé', ARRAY['Le Mékong', 'Le Gange', 'L''Indus'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de la Roumanie ?', 'Bucarest', ARRAY['Cluj-Napoca', 'Timisoara', 'Iasi'], 'fr', true),
('geographie', 3, 'Quel pays possède la plus longue côte au monde ?', 'Le Canada', ARRAY['L''Indonésie', 'La Russie', 'L''Australie'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de l''Irlande ?', 'Dublin', ARRAY['Cork', 'Galway', 'Limerick'], 'fr', true),
('geographie', 3, 'Quel lac se trouve entre la Suisse et la France ?', 'Le lac Léman', ARRAY['Le lac de Constance', 'Le lac Majeur', 'Le lac de Neuchâtel'], 'fr', true),
('geographie', 3, 'Quelle est la capitale de la Croatie ?', 'Zagreb', ARRAY['Split', 'Dubrovnik', 'Rijeka'], 'fr', true),

-- FRENCH - Difficulty 4 (Hard)
('geographie', 4, 'Quel est le point le plus bas sur terre (terres émergées) ?', 'La mer Morte', ARRAY['La dépression de Djibouti', 'Le lac Assal', 'Death Valley'], 'fr', true),
('geographie', 4, 'Quelle est la capitale du Kazakhstan ?', 'Astana', ARRAY['Almaty', 'Shymkent', 'Karaganda'], 'fr', true),
('geographie', 4, 'Quel pays possède le plus de volcans actifs ?', 'L''Indonésie', ARRAY['Le Japon', 'Les Philippines', 'Les États-Unis'], 'fr', true),
('geographie', 4, 'Quelle est la capitale du Sri Lanka ?', 'Sri Jayawardenapura Kotte', ARRAY['Colombo', 'Kandy', 'Galle'], 'fr', true),
('geographie', 4, 'Quel détroit relie la mer Noire à la mer de Marmara ?', 'Le Bosphore', ARRAY['Les Dardanelles', 'Le détroit de Kertch', 'Le détroit de Messine'], 'fr', true),
('geographie', 4, 'Quelle est la capitale de la Mongolie ?', 'Oulan-Bator', ARRAY['Erdenet', 'Darkhan', 'Choibalsan'], 'fr', true),
('geographie', 4, 'Quel est le plus grand archipel du monde ?', 'L''Indonésie', ARRAY['Les Philippines', 'Le Japon', 'La Malaisie'], 'fr', true),
('geographie', 4, 'Quelle est la capitale du Népal ?', 'Katmandou', ARRAY['Pokhara', 'Lalitpur', 'Bhaktapur'], 'fr', true),
('geographie', 4, 'Quel fleuve traverse Bagdad ?', 'Le Tigre', ARRAY['L''Euphrate', 'Le Jourdain', 'L''Oronte'], 'fr', true),
('geographie', 4, 'Quelle est la capitale de la Birmanie (Myanmar) ?', 'Naypyidaw', ARRAY['Rangoun', 'Mandalay', 'Bago'], 'fr', true),
('geographie', 4, 'Quel pays enclavé se trouve entre la Chine et la Russie ?', 'La Mongolie', ARRAY['Le Kazakhstan', 'Le Kirghizistan', 'Le Tadjikistan'], 'fr', true),
('geographie', 4, 'Quelle est la capitale de l''Éthiopie ?', 'Addis-Abeba', ARRAY['Dire Dawa', 'Mekele', 'Gondar'], 'fr', true),
('geographie', 4, 'Quel est le plus grand désert froid du monde ?', 'L''Antarctique', ARRAY['Le Gobi', 'Le désert de Patagonie', 'Le Grand Bassin'], 'fr', true),
('geographie', 4, 'Quelle est la capitale du Pakistan ?', 'Islamabad', ARRAY['Karachi', 'Lahore', 'Faisalabad'], 'fr', true),
('geographie', 4, 'Quel pays possède la plus grande forêt tropicale ?', 'Le Brésil', ARRAY['L''Indonésie', 'La République Démocratique du Congo', 'Le Pérou'], 'fr', true),
('geographie', 4, 'Quelle est la capitale de l''Ouzbékistan ?', 'Tachkent', ARRAY['Samarcande', 'Boukhara', 'Khiva'], 'fr', true),
('geographie', 4, 'Quel est le plus profond lac du monde ?', 'Le lac Baïkal', ARRAY['Le lac Tanganyika', 'Le lac Malawi', 'La mer Caspienne'], 'fr', true),
('geographie', 4, 'Quelle est la capitale du Bangladesh ?', 'Dacca', ARRAY['Chittagong', 'Khulna', 'Rajshahi'], 'fr', true),
('geographie', 4, 'Quel pays africain a deux capitales officielles ?', 'L''Afrique du Sud', ARRAY['Le Nigeria', 'La Tanzanie', 'Le Kenya'], 'fr', true),
('geographie', 4, 'Quelle est la capitale de l''Azerbaïdjan ?', 'Bakou', ARRAY['Gandja', 'Soumgaït', 'Mingatchevir'], 'fr', true),

-- FRENCH - Difficulty 5 (Expert)
('geographie', 5, 'Quelle est la capitale du Bhoutan ?', 'Thimphou', ARRAY['Paro', 'Punakha', 'Phuentsholing'], 'fr', true),
('geographie', 5, 'Quel est le plus petit pays enclavé d''Afrique ?', 'L''Eswatini', ARRAY['Le Lesotho', 'Le Burundi', 'Le Rwanda'], 'fr', true),
('geographie', 5, 'Quelle est la capitale de la Mauritanie ?', 'Nouakchott', ARRAY['Nouadhibou', 'Kaédi', 'Zouérat'], 'fr', true),
('geographie', 5, 'Quel détroit sépare l''île de Bornéo de Sulawesi ?', 'Le détroit de Makassar', ARRAY['Le détroit de la Sonde', 'Le détroit de Malacca', 'Le détroit de Lombok'], 'fr', true),
('geographie', 5, 'Quelle est la capitale du Turkménistan ?', 'Achgabat', ARRAY['Türkmenabat', 'Daşoguz', 'Mary'], 'fr', true),
('geographie', 5, 'Quel fleuve forme la frontière entre la Zambie et le Zimbabwe aux chutes Victoria ?', 'Le Zambèze', ARRAY['Le Limpopo', 'L''Orange', 'Le Congo'], 'fr', true),
('geographie', 5, 'Quelle est la capitale de la Papouasie-Nouvelle-Guinée ?', 'Port Moresby', ARRAY['Lae', 'Mount Hagen', 'Madang'], 'fr', true),
('geographie', 5, 'Quel est le point culminant de l''Océanie ?', 'Le Puncak Jaya', ARRAY['Le Mont Wilhelm', 'Le Mont Cook', 'Le Mauna Kea'], 'fr', true),
('geographie', 5, 'Quelle est la capitale du Tadjikistan ?', 'Douchanbé', ARRAY['Khodjent', 'Kulob', 'Qurghonteppa'], 'fr', true),
('geographie', 5, 'Quel pays possède l''île de Socotra ?', 'Le Yémen', ARRAY['Oman', 'Les Émirats Arabes Unis', 'L''Arabie Saoudite'], 'fr', true),
('geographie', 5, 'Quelle est la capitale du Kirghizistan ?', 'Bichkek', ARRAY['Och', 'Jalal-Abad', 'Karakol'], 'fr', true),
('geographie', 5, 'Quel est le plus grand atoll du monde ?', 'L''atoll de Kiritimati', ARRAY['L''atoll de Rangiroa', 'L''atoll d''Aldabra', 'L''atoll de Kwajalein'], 'fr', true),
('geographie', 5, 'Quelle est la capitale du Lesotho ?', 'Maseru', ARRAY['Teyateyaneng', 'Mafeteng', 'Leribe'], 'fr', true),
('geographie', 5, 'Quel pays possède la plus haute chute d''eau ininterrompue ?', 'Le Venezuela', ARRAY['Le Brésil', 'La Zambie', 'La Norvège'], 'fr', true),
('geographie', 5, 'Quelle est la capitale de Djibouti ?', 'Djibouti', ARRAY['Ali Sabieh', 'Tadjoura', 'Obock'], 'fr', true),
('geographie', 5, 'Quel est le plus long récif corallien du monde ?', 'La Grande Barrière de Corail', ARRAY['Le récif méso-américain', 'Le récif de la mer Rouge', 'Le récif de Nouvelle-Calédonie'], 'fr', true),
('geographie', 5, 'Quelle est la capitale du Brunei ?', 'Bandar Seri Begawan', ARRAY['Kuala Belait', 'Seria', 'Tutong'], 'fr', true),
('geographie', 5, 'Quel pays possède le lac Titicaca avec le Pérou ?', 'La Bolivie', ARRAY['Le Chili', 'L''Équateur', 'La Colombie'], 'fr', true),
('geographie', 5, 'Quelle est la capitale des Maldives ?', 'Malé', ARRAY['Addu', 'Fuvahmulah', 'Kulhudhuffushi'], 'fr', true),
('geographie', 5, 'Quel pays d''Afrique possède l''île de Zanzibar ?', 'La Tanzanie', ARRAY['Le Kenya', 'Le Mozambique', 'Madagascar'], 'fr', true),

-- =====================================================
-- ENGLISH QUESTIONS (100 total - 20 per difficulty)
-- =====================================================

-- ENGLISH - Difficulty 1 (Very Easy - Children)
('geographie', 1, 'What is the capital of France?', 'Paris', ARRAY['Lyon', 'Marseille', 'Bordeaux'], 'en', true),
('geographie', 1, 'What is the largest ocean in the world?', 'Pacific Ocean', ARRAY['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'en', true),
('geographie', 1, 'How many continents are there on Earth?', '7', ARRAY['5', '6', '8'], 'en', true),
('geographie', 1, 'What country is shaped like a boot?', 'Italy', ARRAY['Spain', 'Greece', 'Portugal'], 'en', true),
('geographie', 1, 'What is the capital of Spain?', 'Madrid', ARRAY['Barcelona', 'Seville', 'Valencia'], 'en', true),
('geographie', 1, 'On which continent is Egypt located?', 'Africa', ARRAY['Asia', 'Europe', 'Oceania'], 'en', true),
('geographie', 1, 'What is the largest country in the world?', 'Russia', ARRAY['Canada', 'China', 'United States'], 'en', true),
('geographie', 1, 'What is the capital of Germany?', 'Berlin', ARRAY['Munich', 'Hamburg', 'Frankfurt'], 'en', true),
('geographie', 1, 'Which country is famous for its kangaroos?', 'Australia', ARRAY['South Africa', 'Brazil', 'India'], 'en', true),
('geographie', 1, 'What is the capital of the United Kingdom?', 'London', ARRAY['Manchester', 'Liverpool', 'Birmingham'], 'en', true),
('geographie', 1, 'What is the capital of Italy?', 'Rome', ARRAY['Milan', 'Naples', 'Florence'], 'en', true),
('geographie', 1, 'What is the capital of Japan?', 'Tokyo', ARRAY['Osaka', 'Kyoto', 'Hiroshima'], 'en', true),
('geographie', 1, 'What famous monument is in Paris?', 'Eiffel Tower', ARRAY['Big Ben', 'Statue of Liberty', 'Colosseum'], 'en', true),
('geographie', 1, 'What is the coldest continent?', 'Antarctica', ARRAY['Arctic', 'Europe', 'North America'], 'en', true),
('geographie', 1, 'What is the capital of the United States?', 'Washington D.C.', ARRAY['New York', 'Los Angeles', 'Chicago'], 'en', true),
('geographie', 1, 'What river flows through London?', 'Thames', ARRAY['Seine', 'Danube', 'Rhine'], 'en', true),
('geographie', 1, 'What is the capital of China?', 'Beijing', ARRAY['Shanghai', 'Hong Kong', 'Guangzhou'], 'en', true),
('geographie', 1, 'Which ocean borders the east coast of the United States?', 'Atlantic Ocean', ARRAY['Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'], 'en', true),
('geographie', 1, 'What is the capital of Canada?', 'Ottawa', ARRAY['Toronto', 'Vancouver', 'Montreal'], 'en', true),
('geographie', 1, 'What country is known for pyramids and pharaohs?', 'Egypt', ARRAY['Mexico', 'Peru', 'Greece'], 'en', true),

-- ENGLISH - Difficulty 2 (Easy)
('geographie', 2, 'What is the highest mountain in the Alps?', 'Mont Blanc', ARRAY['Monte Rosa', 'Matterhorn', 'Jungfrau'], 'en', true),
('geographie', 2, 'What is the capital of Belgium?', 'Brussels', ARRAY['Antwerp', 'Ghent', 'Liege'], 'en', true),
('geographie', 2, 'What river flows through Egypt?', 'Nile', ARRAY['Congo', 'Zambezi', 'Niger'], 'en', true),
('geographie', 2, 'What is the capital of Switzerland?', 'Bern', ARRAY['Zurich', 'Geneva', 'Lausanne'], 'en', true),
('geographie', 2, 'What is the largest desert in the world?', 'Sahara', ARRAY['Gobi', 'Atacama', 'Kalahari'], 'en', true),
('geographie', 2, 'What is the capital of Portugal?', 'Lisbon', ARRAY['Porto', 'Faro', 'Coimbra'], 'en', true),
('geographie', 2, 'What is the capital of Greece?', 'Athens', ARRAY['Thessaloniki', 'Patras', 'Heraklion'], 'en', true),
('geographie', 2, 'What is the capital of Austria?', 'Vienna', ARRAY['Salzburg', 'Innsbruck', 'Graz'], 'en', true),
('geographie', 2, 'Which country is called the Land of the Rising Sun?', 'Japan', ARRAY['China', 'South Korea', 'Vietnam'], 'en', true),
('geographie', 2, 'What is the capital of Poland?', 'Warsaw', ARRAY['Krakow', 'Gdansk', 'Poznan'], 'en', true),
('geographie', 2, 'What is the capital of Brazil?', 'Brasilia', ARRAY['Rio de Janeiro', 'Sao Paulo', 'Salvador'], 'en', true),
('geographie', 2, 'Which country has the most people in the world?', 'India', ARRAY['China', 'United States', 'Indonesia'], 'en', true),
('geographie', 2, 'What mountain range separates France from Spain?', 'Pyrenees', ARRAY['Alps', 'Carpathians', 'Apennines'], 'en', true),
('geographie', 2, 'What is the capital of Argentina?', 'Buenos Aires', ARRAY['Cordoba', 'Rosario', 'Mendoza'], 'en', true),
('geographie', 2, 'What is the capital of Norway?', 'Oslo', ARRAY['Bergen', 'Trondheim', 'Stavanger'], 'en', true),
('geographie', 2, 'What is the capital of Sweden?', 'Stockholm', ARRAY['Gothenburg', 'Malmo', 'Uppsala'], 'en', true),
('geographie', 2, 'What is the longest river in South America?', 'Amazon', ARRAY['Parana', 'Orinoco', 'Sao Francisco'], 'en', true),
('geographie', 2, 'What is the capital of the Netherlands?', 'Amsterdam', ARRAY['Rotterdam', 'The Hague', 'Utrecht'], 'en', true),
('geographie', 2, 'What sea lies between Europe and Africa?', 'Mediterranean Sea', ARRAY['Red Sea', 'Black Sea', 'Caspian Sea'], 'en', true),
('geographie', 2, 'What is the capital of Denmark?', 'Copenhagen', ARRAY['Aarhus', 'Odense', 'Aalborg'], 'en', true),

-- ENGLISH - Difficulty 3 (Medium)
('geographie', 3, 'What strait separates Europe from Africa?', 'Strait of Gibraltar', ARRAY['Bosphorus', 'Strait of Messina', 'Suez Canal'], 'en', true),
('geographie', 3, 'What is the capital of Hungary?', 'Budapest', ARRAY['Prague', 'Vienna', 'Bratislava'], 'en', true),
('geographie', 3, 'What river flows through Vienna, Budapest, and Belgrade?', 'Danube', ARRAY['Rhine', 'Elbe', 'Vistula'], 'en', true),
('geographie', 3, 'What is the largest island in the Mediterranean?', 'Sicily', ARRAY['Sardinia', 'Cyprus', 'Corsica'], 'en', true),
('geographie', 3, 'What is the capital of Morocco?', 'Rabat', ARRAY['Casablanca', 'Marrakech', 'Fes'], 'en', true),
('geographie', 3, 'Which country has the most time zones?', 'France', ARRAY['Russia', 'United States', 'United Kingdom'], 'en', true),
('geographie', 3, 'What sea is located between Europe and Asia?', 'Black Sea', ARRAY['Caspian Sea', 'Aral Sea', 'Baltic Sea'], 'en', true),
('geographie', 3, 'What is the capital of Thailand?', 'Bangkok', ARRAY['Chiang Mai', 'Phuket', 'Pattaya'], 'en', true),
('geographie', 3, 'What is the highest mountain in Africa?', 'Mount Kilimanjaro', ARRAY['Mount Kenya', 'Ruwenzori', 'Atlas Mountains'], 'en', true),
('geographie', 3, 'What is the capital of Indonesia?', 'Jakarta', ARRAY['Bali', 'Surabaya', 'Bandung'], 'en', true),
('geographie', 3, 'What river forms part of the US-Mexico border?', 'Rio Grande', ARRAY['Colorado', 'Mississippi', 'Missouri'], 'en', true),
('geographie', 3, 'What is the capital of Finland?', 'Helsinki', ARRAY['Turku', 'Tampere', 'Espoo'], 'en', true),
('geographie', 3, 'What African country was formerly called Abyssinia?', 'Ethiopia', ARRAY['Eritrea', 'Sudan', 'Somalia'], 'en', true),
('geographie', 3, 'What is the capital of Vietnam?', 'Hanoi', ARRAY['Ho Chi Minh City', 'Da Nang', 'Hue'], 'en', true),
('geographie', 3, 'What is the longest river in Asia?', 'Yangtze', ARRAY['Mekong', 'Ganges', 'Indus'], 'en', true),
('geographie', 3, 'What is the capital of Romania?', 'Bucharest', ARRAY['Cluj-Napoca', 'Timisoara', 'Iasi'], 'en', true),
('geographie', 3, 'Which country has the longest coastline in the world?', 'Canada', ARRAY['Indonesia', 'Russia', 'Australia'], 'en', true),
('geographie', 3, 'What is the capital of Ireland?', 'Dublin', ARRAY['Cork', 'Galway', 'Limerick'], 'en', true),
('geographie', 3, 'What lake is shared by Switzerland and France?', 'Lake Geneva', ARRAY['Lake Constance', 'Lake Maggiore', 'Lake Neuchatel'], 'en', true),
('geographie', 3, 'What is the capital of Croatia?', 'Zagreb', ARRAY['Split', 'Dubrovnik', 'Rijeka'], 'en', true),

-- ENGLISH - Difficulty 4 (Hard)
('geographie', 4, 'What is the lowest point on land on Earth?', 'Dead Sea', ARRAY['Djibouti Depression', 'Lake Assal', 'Death Valley'], 'en', true),
('geographie', 4, 'What is the capital of Kazakhstan?', 'Astana', ARRAY['Almaty', 'Shymkent', 'Karaganda'], 'en', true),
('geographie', 4, 'Which country has the most active volcanoes?', 'Indonesia', ARRAY['Japan', 'Philippines', 'United States'], 'en', true),
('geographie', 4, 'What is the official capital of Sri Lanka?', 'Sri Jayawardenepura Kotte', ARRAY['Colombo', 'Kandy', 'Galle'], 'en', true),
('geographie', 4, 'What strait connects the Black Sea to the Sea of Marmara?', 'Bosphorus', ARRAY['Dardanelles', 'Kerch Strait', 'Strait of Messina'], 'en', true),
('geographie', 4, 'What is the capital of Mongolia?', 'Ulaanbaatar', ARRAY['Erdenet', 'Darkhan', 'Choibalsan'], 'en', true),
('geographie', 4, 'What is the largest archipelago in the world?', 'Indonesia', ARRAY['Philippines', 'Japan', 'Malaysia'], 'en', true),
('geographie', 4, 'What is the capital of Nepal?', 'Kathmandu', ARRAY['Pokhara', 'Lalitpur', 'Bhaktapur'], 'en', true),
('geographie', 4, 'What river flows through Baghdad?', 'Tigris', ARRAY['Euphrates', 'Jordan', 'Orontes'], 'en', true),
('geographie', 4, 'What is the capital of Myanmar?', 'Naypyidaw', ARRAY['Yangon', 'Mandalay', 'Bago'], 'en', true),
('geographie', 4, 'What landlocked country lies between China and Russia?', 'Mongolia', ARRAY['Kazakhstan', 'Kyrgyzstan', 'Tajikistan'], 'en', true),
('geographie', 4, 'What is the capital of Ethiopia?', 'Addis Ababa', ARRAY['Dire Dawa', 'Mekele', 'Gondar'], 'en', true),
('geographie', 4, 'What is the largest cold desert in the world?', 'Antarctica', ARRAY['Gobi', 'Patagonian Desert', 'Great Basin'], 'en', true),
('geographie', 4, 'What is the capital of Pakistan?', 'Islamabad', ARRAY['Karachi', 'Lahore', 'Faisalabad'], 'en', true),
('geographie', 4, 'Which country has the largest tropical rainforest?', 'Brazil', ARRAY['Indonesia', 'Democratic Republic of Congo', 'Peru'], 'en', true),
('geographie', 4, 'What is the capital of Uzbekistan?', 'Tashkent', ARRAY['Samarkand', 'Bukhara', 'Khiva'], 'en', true),
('geographie', 4, 'What is the deepest lake in the world?', 'Lake Baikal', ARRAY['Lake Tanganyika', 'Lake Malawi', 'Caspian Sea'], 'en', true),
('geographie', 4, 'What is the capital of Bangladesh?', 'Dhaka', ARRAY['Chittagong', 'Khulna', 'Rajshahi'], 'en', true),
('geographie', 4, 'Which African country has two official capitals?', 'South Africa', ARRAY['Nigeria', 'Tanzania', 'Kenya'], 'en', true),
('geographie', 4, 'What is the capital of Azerbaijan?', 'Baku', ARRAY['Ganja', 'Sumqayit', 'Mingachevir'], 'en', true),

-- ENGLISH - Difficulty 5 (Expert)
('geographie', 5, 'What is the capital of Bhutan?', 'Thimphu', ARRAY['Paro', 'Punakha', 'Phuentsholing'], 'en', true),
('geographie', 5, 'What is the smallest landlocked country in Africa?', 'Eswatini', ARRAY['Lesotho', 'Burundi', 'Rwanda'], 'en', true),
('geographie', 5, 'What is the capital of Mauritania?', 'Nouakchott', ARRAY['Nouadhibou', 'Kaedi', 'Zouerat'], 'en', true),
('geographie', 5, 'What strait separates Borneo from Sulawesi?', 'Makassar Strait', ARRAY['Sunda Strait', 'Malacca Strait', 'Lombok Strait'], 'en', true),
('geographie', 5, 'What is the capital of Turkmenistan?', 'Ashgabat', ARRAY['Turkmenabat', 'Dashoguz', 'Mary'], 'en', true),
('geographie', 5, 'What river forms the border between Zambia and Zimbabwe at Victoria Falls?', 'Zambezi', ARRAY['Limpopo', 'Orange', 'Congo'], 'en', true),
('geographie', 5, 'What is the capital of Papua New Guinea?', 'Port Moresby', ARRAY['Lae', 'Mount Hagen', 'Madang'], 'en', true),
('geographie', 5, 'What is the highest peak in Oceania?', 'Puncak Jaya', ARRAY['Mount Wilhelm', 'Mount Cook', 'Mauna Kea'], 'en', true),
('geographie', 5, 'What is the capital of Tajikistan?', 'Dushanbe', ARRAY['Khujand', 'Kulob', 'Qurghonteppa'], 'en', true),
('geographie', 5, 'Which country owns the island of Socotra?', 'Yemen', ARRAY['Oman', 'United Arab Emirates', 'Saudi Arabia'], 'en', true),
('geographie', 5, 'What is the capital of Kyrgyzstan?', 'Bishkek', ARRAY['Osh', 'Jalal-Abad', 'Karakol'], 'en', true),
('geographie', 5, 'What is the largest atoll in the world by land area?', 'Kiritimati', ARRAY['Rangiroa', 'Aldabra', 'Kwajalein'], 'en', true),
('geographie', 5, 'What is the capital of Lesotho?', 'Maseru', ARRAY['Teyateyaneng', 'Mafeteng', 'Leribe'], 'en', true),
('geographie', 5, 'Which country has the highest uninterrupted waterfall?', 'Venezuela', ARRAY['Brazil', 'Zambia', 'Norway'], 'en', true),
('geographie', 5, 'What is the capital of Djibouti?', 'Djibouti', ARRAY['Ali Sabieh', 'Tadjoura', 'Obock'], 'en', true),
('geographie', 5, 'What is the longest coral reef system in the world?', 'Great Barrier Reef', ARRAY['Mesoamerican Reef', 'Red Sea Reef', 'New Caledonia Reef'], 'en', true),
('geographie', 5, 'What is the capital of Brunei?', 'Bandar Seri Begawan', ARRAY['Kuala Belait', 'Seria', 'Tutong'], 'en', true),
('geographie', 5, 'Which country shares Lake Titicaca with Peru?', 'Bolivia', ARRAY['Chile', 'Ecuador', 'Colombia'], 'en', true),
('geographie', 5, 'What is the capital of the Maldives?', 'Male', ARRAY['Addu', 'Fuvahmulah', 'Kulhudhuffushi'], 'en', true),
('geographie', 5, 'Which African country contains the island of Zanzibar?', 'Tanzania', ARRAY['Kenya', 'Mozambique', 'Madagascar'], 'en', true);
