-- =====================================================
-- MUSIQUE / MUSIC (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1 (Pop culture, artistes connus)
('musique', 1, 'Quel groupe britannique a chanté "Yellow Submarine" ?', 'The Beatles', ARRAY['The Rolling Stones', 'Pink Floyd', 'Queen'], 'fr', true),
('musique', 1, 'Quelle chanteuse americaine a interprete "Shake It Off" ?', 'Taylor Swift', ARRAY['Katy Perry', 'Ariana Grande', 'Beyonce'], 'fr', true),
('musique', 1, 'Quel rappeur francais a chante "Je danse le Mia" ?', 'IAM', ARRAY['NTM', 'MC Solaar', 'Booba'], 'fr', true),
('musique', 1, 'Quel instrument a des touches noires et blanches ?', 'Piano', ARRAY['Guitare', 'Violon', 'Flute'], 'fr', true),
('musique', 1, 'Quel chanteur francais a interprete "Je t''aime" avec Jane Birkin ?', 'Serge Gainsbourg', ARRAY['Johnny Hallyday', 'Michel Sardou', 'Charles Aznavour'], 'fr', true),
('musique', 1, 'Quel groupe a chante "We Will Rock You" ?', 'Queen', ARRAY['AC/DC', 'Led Zeppelin', 'Guns N'' Roses'], 'fr', true),
('musique', 1, 'Combien de cordes a une guitare classique ?', '6', ARRAY['4', '5', '8'], 'fr', true),
('musique', 1, 'Quel chanteur est surnomme "Le King" ?', 'Elvis Presley', ARRAY['Michael Jackson', 'Prince', 'Freddie Mercury'], 'fr', true),
('musique', 1, 'Quelle chanteuse a interprete "La Vie en Rose" ?', 'Edith Piaf', ARRAY['Dalida', 'Barbara', 'Mireille Mathieu'], 'fr', true),
('musique', 1, 'Quel rappeur americain a chante "Lose Yourself" ?', 'Eminem', ARRAY['Jay-Z', '50 Cent', 'Dr. Dre'], 'fr', true),
('musique', 1, 'Quel groupe a chante "Bohemian Rhapsody" ?', 'Queen', ARRAY['The Beatles', 'Pink Floyd', 'Led Zeppelin'], 'fr', true),
('musique', 1, 'Quel instrument frappe-t-on avec des baguettes ?', 'Batterie', ARRAY['Piano', 'Guitare', 'Trompette'], 'fr', true),
('musique', 1, 'Quelle chanteuse barbadienne a chante "Umbrella" ?', 'Rihanna', ARRAY['Beyonce', 'Nicki Minaj', 'Alicia Keys'], 'fr', true),
('musique', 1, 'Quel chanteur francais est connu pour "L''envie" ?', 'Johnny Hallyday', ARRAY['Michel Sardou', 'Patrick Bruel', 'Charles Aznavour'], 'fr', true),
('musique', 1, 'Quel groupe americain a chante "Hotel California" ?', 'Eagles', ARRAY['Fleetwood Mac', 'The Doors', 'Aerosmith'], 'fr', true),
('musique', 1, 'Quel est le prenom du chanteur Bowie ?', 'David', ARRAY['Michael', 'John', 'Robert'], 'fr', true),
('musique', 1, 'Quelle chanteuse a interprete "Single Ladies" ?', 'Beyonce', ARRAY['Rihanna', 'Lady Gaga', 'Jennifer Lopez'], 'fr', true),
('musique', 1, 'Quel duo francais a chante "Around the World" ?', 'Daft Punk', ARRAY['Justice', 'Air', 'Phoenix'], 'fr', true),
('musique', 1, 'Quel instrument souffle-t-on pour produire du son ?', 'Flute', ARRAY['Guitare', 'Piano', 'Violon'], 'fr', true),
('musique', 1, 'Quel chanteur a interprete "Thriller" ?', 'Michael Jackson', ARRAY['Prince', 'Whitney Houston', 'Stevie Wonder'], 'fr', true),

-- FRENCH - Niveau 2
('musique', 2, 'En quelle annee les Beatles se sont-ils separes ?', '1970', ARRAY['1968', '1972', '1975'], 'fr', true),
('musique', 2, 'Quel genre musical est ne a la Nouvelle-Orleans ?', 'Jazz', ARRAY['Blues', 'Rock', 'Country'], 'fr', true),
('musique', 2, 'Quel rappeur francais a sorti l''album "Temps Mort" ?', 'Booba', ARRAY['Rohff', 'La Fouine', 'Kaaris'], 'fr', true),
('musique', 2, 'Combien de symphonies Beethoven a-t-il composees ?', '9', ARRAY['5', '7', '12'], 'fr', true),
('musique', 2, 'Quel groupe a chante "Smells Like Teen Spirit" ?', 'Nirvana', ARRAY['Pearl Jam', 'Soundgarden', 'Alice in Chains'], 'fr', true),
('musique', 2, 'Quel chanteur francais a interprete "Les Champs-Elysees" ?', 'Joe Dassin', ARRAY['Claude Francois', 'Serge Gainsbourg', 'Michel Polnareff'], 'fr', true),
('musique', 2, 'Quel instrument a 88 touches ?', 'Piano', ARRAY['Orgue', 'Clavecin', 'Synthetiseur'], 'fr', true),
('musique', 2, 'Quelle chanteuse a interprete "Rolling in the Deep" ?', 'Adele', ARRAY['Amy Winehouse', 'Duffy', 'Florence Welch'], 'fr', true),
('musique', 2, 'Quel groupe irlandais a chante "With or Without You" ?', 'U2', ARRAY['The Cranberries', 'Thin Lizzy', 'The Corrs'], 'fr', true),
('musique', 2, 'Quel style de musique est associe a Bob Marley ?', 'Reggae', ARRAY['Ska', 'Calypso', 'Dancehall'], 'fr', true),
('musique', 2, 'Quelle note suit "do" dans la gamme ?', 'Re', ARRAY['Mi', 'Fa', 'Sol'], 'fr', true),
('musique', 2, 'Quel rappeur americain a fonde le label Death Row Records ?', 'Dr. Dre', ARRAY['Snoop Dogg', 'Tupac', 'Ice Cube'], 'fr', true),
('musique', 2, 'Quel groupe a chante "Another Brick in the Wall" ?', 'Pink Floyd', ARRAY['Led Zeppelin', 'The Who', 'Deep Purple'], 'fr', true),
('musique', 2, 'Quelle chanteuse francaise a interprete "Tout doucement" ?', 'Bibie', ARRAY['Jeanne Mas', 'Desireless', 'Caroline Loeb'], 'fr', true),
('musique', 2, 'Quel est le vrai nom de Bono de U2 ?', 'Paul Hewson', ARRAY['David Evans', 'Adam Clayton', 'Larry Mullen'], 'fr', true),
('musique', 2, 'Quel groupe a chante "Stairway to Heaven" ?', 'Led Zeppelin', ARRAY['Pink Floyd', 'Deep Purple', 'Black Sabbath'], 'fr', true),
('musique', 2, 'Quel instrument joue Stromae principalement ?', 'Synthetiseur', ARRAY['Guitare', 'Piano', 'Batterie'], 'fr', true),
('musique', 2, 'Quelle chanteuse canadienne a chante "My Heart Will Go On" ?', 'Celine Dion', ARRAY['Shania Twain', 'Alanis Morissette', 'Sarah McLachlan'], 'fr', true),
('musique', 2, 'Quel groupe a chante "Satisfaction" en 1965 ?', 'The Rolling Stones', ARRAY['The Beatles', 'The Who', 'The Kinks'], 'fr', true),
('musique', 2, 'Quel DJ francais a produit "One More Time" ?', 'Daft Punk', ARRAY['David Guetta', 'Martin Solveig', 'Bob Sinclar'], 'fr', true),

-- FRENCH - Niveau 3
('musique', 3, 'En quelle annee est mort Freddie Mercury ?', '1991', ARRAY['1989', '1993', '1995'], 'fr', true),
('musique', 3, 'Quel compositeur etait sourd a la fin de sa vie ?', 'Beethoven', ARRAY['Mozart', 'Bach', 'Chopin'], 'fr', true),
('musique', 3, 'Quel groupe a sorti l''album "Nevermind" en 1991 ?', 'Nirvana', ARRAY['Pearl Jam', 'Soundgarden', 'Red Hot Chili Peppers'], 'fr', true),
('musique', 3, 'Combien de cordes a une basse electrique standard ?', '4', ARRAY['5', '6', '3'], 'fr', true),
('musique', 3, 'Quel chanteur francais a compose "Comme d''habitude" ?', 'Claude Francois', ARRAY['Michel Sardou', 'Johnny Hallyday', 'Serge Gainsbourg'], 'fr', true),
('musique', 3, 'Quelle est la tonalite de "La lettre a Elise" ?', 'La mineur', ARRAY['Do majeur', 'Sol majeur', 'Re mineur'], 'fr', true),
('musique', 3, 'Quel groupe britannique a chante "Wonderwall" ?', 'Oasis', ARRAY['Blur', 'Radiohead', 'Pulp'], 'fr', true),
('musique', 3, 'Quel rappeur a fonde le groupe NWA ?', 'Eazy-E', ARRAY['Ice Cube', 'Dr. Dre', 'MC Ren'], 'fr', true),
('musique', 3, 'Quel est le tempo standard d''un morceau "Adagio" ?', '66-76 BPM', ARRAY['40-60 BPM', '80-100 BPM', '100-120 BPM'], 'fr', true),
('musique', 3, 'Quelle chanteuse francaise a interprete "Desenchantee" ?', 'Mylene Farmer', ARRAY['Vanessa Paradis', 'Patricia Kaas', 'Zazie'], 'fr', true),
('musique', 3, 'Quel groupe a sorti "The Dark Side of the Moon" ?', 'Pink Floyd', ARRAY['Genesis', 'Yes', 'King Crimson'], 'fr', true),
('musique', 3, 'Combien de demi-tons dans une octave ?', '12', ARRAY['8', '10', '14'], 'fr', true),
('musique', 3, 'Quel DJ neerlandais a produit "Levels" ?', 'Avicii', ARRAY['Tiesto', 'Armin van Buuren', 'Martin Garrix'], 'fr', true),
('musique', 3, 'Quel compositeur a ecrit "Les Quatre Saisons" ?', 'Vivaldi', ARRAY['Bach', 'Handel', 'Mozart'], 'fr', true),
('musique', 3, 'Quel groupe americain a chante "Sweet Child O'' Mine" ?', 'Guns N'' Roses', ARRAY['Bon Jovi', 'Motley Crue', 'Def Leppard'], 'fr', true),
('musique', 3, 'Quelle est la frequence du La de reference ?', '440 Hz', ARRAY['420 Hz', '460 Hz', '432 Hz'], 'fr', true),
('musique', 3, 'Quel chanteur belge a interprete "Papaoutai" ?', 'Stromae', ARRAY['Angele', 'Jacques Brel', 'Arno'], 'fr', true),
('musique', 3, 'Quel groupe a sorti l''album "Abbey Road" ?', 'The Beatles', ARRAY['The Rolling Stones', 'The Who', 'Pink Floyd'], 'fr', true),
('musique', 3, 'Quel instrument est aussi appele "violoncelle" en italien ?', 'Violoncello', ARRAY['Viola', 'Contrabasso', 'Violino'], 'fr', true),
('musique', 3, 'Quelle rappeuse americaine a chante "Super Bass" ?', 'Nicki Minaj', ARRAY['Cardi B', 'Megan Thee Stallion', 'Missy Elliott'], 'fr', true),

-- FRENCH - Niveau 4
('musique', 4, 'En quelle annee Mozart est-il mort ?', '1791', ARRAY['1785', '1795', '1801'], 'fr', true),
('musique', 4, 'Quel mode grec commence par Mi ?', 'Phrygien', ARRAY['Dorien', 'Lydien', 'Mixolydien'], 'fr', true),
('musique', 4, 'Combien de sonates pour piano Beethoven a-t-il ecrites ?', '32', ARRAY['24', '28', '36'], 'fr', true),
('musique', 4, 'Quel compositeur a ecrit "Le Sacre du Printemps" ?', 'Stravinsky', ARRAY['Debussy', 'Ravel', 'Prokofiev'], 'fr', true),
('musique', 4, 'Quelle est la structure d''une forme sonate ?', 'Exposition-Developpement-Reexposition', ARRAY['ABA', 'Rondo', 'Theme et variations'], 'fr', true),
('musique', 4, 'Quel groupe de rock progressif a sorti "Close to the Edge" ?', 'Yes', ARRAY['Genesis', 'King Crimson', 'Emerson Lake & Palmer'], 'fr', true),
('musique', 4, 'Combien de preludes et fugues contient "Le Clavier bien tempere" ?', '48', ARRAY['24', '36', '64'], 'fr', true),
('musique', 4, 'Quel compositeur francais a ecrit "Bolero" ?', 'Maurice Ravel', ARRAY['Claude Debussy', 'Erik Satie', 'Camille Saint-Saens'], 'fr', true),
('musique', 4, 'Quelle note est la dominante de Sol majeur ?', 'Re', ARRAY['Si', 'Mi', 'La'], 'fr', true),
('musique', 4, 'Quel chanteur de jazz a interprete "What a Wonderful World" ?', 'Louis Armstrong', ARRAY['Ella Fitzgerald', 'Frank Sinatra', 'Nat King Cole'], 'fr', true),
('musique', 4, 'Quel accord est compose de Do-Mi-Sol ?', 'Do majeur', ARRAY['Do mineur', 'Do 7eme', 'Do augmente'], 'fr', true),
('musique', 4, 'Quel compositeur a ecrit l''opera "Carmen" ?', 'Bizet', ARRAY['Verdi', 'Puccini', 'Wagner'], 'fr', true),
('musique', 4, 'Combien de mouvements a une symphonie classique ?', '4', ARRAY['3', '5', '6'], 'fr', true),
('musique', 4, 'Quel groupe a sorti "OK Computer" en 1997 ?', 'Radiohead', ARRAY['Blur', 'Oasis', 'Muse'], 'fr', true),
('musique', 4, 'Quelle est la signature rythmique d''une valse ?', '3/4', ARRAY['4/4', '2/4', '6/8'], 'fr', true),
('musique', 4, 'Quel compositeur russe a ecrit "Pierre et le Loup" ?', 'Prokofiev', ARRAY['Tchaikovsky', 'Rimsky-Korsakov', 'Shostakovich'], 'fr', true),
('musique', 4, 'Quel intervalle separe Do et Sol ?', 'Quinte juste', ARRAY['Quarte juste', 'Sixte majeure', 'Septieme mineure'], 'fr', true),
('musique', 4, 'Quel saxophoniste a joue avec Miles Davis sur "Kind of Blue" ?', 'John Coltrane', ARRAY['Charlie Parker', 'Sonny Rollins', 'Ornette Coleman'], 'fr', true),
('musique', 4, 'Combien de cordes a un violoncelle ?', '4', ARRAY['5', '6', '3'], 'fr', true),
('musique', 4, 'Quel compositeur autrichien a ecrit "La Truite" ?', 'Schubert', ARRAY['Mozart', 'Haydn', 'Brahms'], 'fr', true),

-- FRENCH - Niveau 5 (Theorie musicale, musique classique avancee)
('musique', 5, 'Quelle est la relative mineure de Mi bemol majeur ?', 'Do mineur', ARRAY['Si bemol mineur', 'La bemol mineur', 'Fa mineur'], 'fr', true),
('musique', 5, 'Combien d''operas Wagner a-t-il composes pour "L''Anneau du Nibelung" ?', '4', ARRAY['3', '5', '6'], 'fr', true),
('musique', 5, 'Quel terme designe une note abaissee d''un demi-ton ?', 'Bemol', ARRAY['Diese', 'Becarre', 'Appogiature'], 'fr', true),
('musique', 5, 'Quel compositeur a ecrit les "Variations Goldberg" ?', 'Bach', ARRAY['Handel', 'Scarlatti', 'Telemann'], 'fr', true),
('musique', 5, 'Quelle technique de chant utilise la voix de tete masculine ?', 'Falsetto', ARRAY['Belting', 'Vibrato', 'Growl'], 'fr', true),
('musique', 5, 'Combien de dieses a la tonalite de Fa diese majeur ?', '6', ARRAY['5', '7', '4'], 'fr', true),
('musique', 5, 'Quel compositeur a ecrit "Tristan und Isolde" ?', 'Wagner', ARRAY['Verdi', 'Strauss', 'Puccini'], 'fr', true),
('musique', 5, 'Quelle est la cadence qui termine sur l''accord de dominante ?', 'Demi-cadence', ARRAY['Cadence parfaite', 'Cadence plagale', 'Cadence rompue'], 'fr', true),
('musique', 5, 'Quel mode a une seconde abaissee et une sixte majeure ?', 'Phrygien dominant', ARRAY['Lydien', 'Locrien', 'Dorien'], 'fr', true),
('musique', 5, 'Combien de quatuors a cordes Beethoven a-t-il composes ?', '16', ARRAY['12', '18', '20'], 'fr', true),
('musique', 5, 'Quel compositeur a developpe la technique des 12 tons ?', 'Schoenberg', ARRAY['Webern', 'Berg', 'Stockhausen'], 'fr', true),
('musique', 5, 'Quelle est l''etendue vocale d''une soprano colorature ?', 'Do4-Fa6', ARRAY['La3-Do6', 'Mi4-Sol6', 'Sol3-Mi5'], 'fr', true),
('musique', 5, 'Quel accord est forme de tierces superposees sur 4 notes ?', 'Accord de septieme', ARRAY['Triade', 'Accord de neuvieme', 'Power chord'], 'fr', true),
('musique', 5, 'Quel compositeur francais a ecrit "Pelleas et Melisande" ?', 'Debussy', ARRAY['Ravel', 'Faure', 'Massenet'], 'fr', true),
('musique', 5, 'Combien de bemols a la tonalite de Sol bemol majeur ?', '6', ARRAY['5', '7', '4'], 'fr', true),
('musique', 5, 'Quel terme italien indique un tempo tres lent ?', 'Grave', ARRAY['Largo', 'Adagio', 'Lento'], 'fr', true),
('musique', 5, 'Quel compositeur a ecrit "Le Marteau sans Maitre" ?', 'Boulez', ARRAY['Messiaen', 'Xenakis', 'Ligeti'], 'fr', true),
('musique', 5, 'Quelle gamme a un demi-ton entre les 3e et 4e degres ?', 'Gamme mineure melodique', ARRAY['Gamme majeure', 'Gamme mineure harmonique', 'Gamme pentatonique'], 'fr', true),
('musique', 5, 'Quel compositeur a ecrit les "Etudes d''execution transcendante" ?', 'Liszt', ARRAY['Chopin', 'Schumann', 'Brahms'], 'fr', true),
('musique', 5, 'Quelle est la plus haute voix dans un choeur mixte ?', 'Soprano', ARRAY['Alto', 'Mezzo-soprano', 'Contralto'], 'fr', true),

-- ENGLISH - Level 1 (Pop culture, famous artists)
('musique', 1, 'Which British band sang "Hey Jude"?', 'The Beatles', ARRAY['The Rolling Stones', 'Pink Floyd', 'The Who'], 'en', true),
('musique', 1, 'Which pop star is known as the "Queen of Pop"?', 'Madonna', ARRAY['Britney Spears', 'Lady Gaga', 'Janet Jackson'], 'en', true),
('musique', 1, 'What instrument has black and white keys?', 'Piano', ARRAY['Guitar', 'Violin', 'Drums'], 'en', true),
('musique', 1, 'Who sang "Shape of You"?', 'Ed Sheeran', ARRAY['Justin Bieber', 'Shawn Mendes', 'Sam Smith'], 'en', true),
('musique', 1, 'Which band performed "Somebody That I Used to Know"?', 'Gotye', ARRAY['MGMT', 'Foster the People', 'Tame Impala'], 'en', true),
('musique', 1, 'How many strings does a standard guitar have?', '6', ARRAY['4', '5', '8'], 'en', true),
('musique', 1, 'Who is known as the "King of Pop"?', 'Michael Jackson', ARRAY['Prince', 'Elvis Presley', 'Stevie Wonder'], 'en', true),
('musique', 1, 'Which singer performed "Bad Guy"?', 'Billie Eilish', ARRAY['Ariana Grande', 'Dua Lipa', 'Halsey'], 'en', true),
('musique', 1, 'Which band sang "Mr. Brightside"?', 'The Killers', ARRAY['Coldplay', 'Arctic Monkeys', 'Muse'], 'en', true),
('musique', 1, 'What instrument does a drummer play?', 'Drums', ARRAY['Bass', 'Guitar', 'Keyboard'], 'en', true),
('musique', 1, 'Who sang "Hello" in 2015?', 'Adele', ARRAY['Taylor Swift', 'Beyonce', 'Rihanna'], 'en', true),
('musique', 1, 'Which rapper performed "God''s Plan"?', 'Drake', ARRAY['Kendrick Lamar', 'Travis Scott', 'Post Malone'], 'en', true),
('musique', 1, 'Which girl group sang "Wannabe"?', 'Spice Girls', ARRAY['Destiny''s Child', 'TLC', 'All Saints'], 'en', true),
('musique', 1, 'What was Elvis Presley''s nickname?', 'The King', ARRAY['The Boss', 'The Prince', 'The Duke'], 'en', true),
('musique', 1, 'Which band performed "Viva la Vida"?', 'Coldplay', ARRAY['U2', 'Radiohead', 'Muse'], 'en', true),
('musique', 1, 'Who sang "Uptown Funk" with Mark Ronson?', 'Bruno Mars', ARRAY['Pharrell Williams', 'Justin Timberlake', 'The Weeknd'], 'en', true),
('musique', 1, 'Which K-pop group sang "Dynamite"?', 'BTS', ARRAY['BLACKPINK', 'EXO', 'TWICE'], 'en', true),
('musique', 1, 'What type of instrument is a violin?', 'String', ARRAY['Wind', 'Percussion', 'Brass'], 'en', true),
('musique', 1, 'Who performed "Blinding Lights"?', 'The Weeknd', ARRAY['Post Malone', 'Dua Lipa', 'Harry Styles'], 'en', true),
('musique', 1, 'Which singer is known for "Halo"?', 'Beyonce', ARRAY['Rihanna', 'Alicia Keys', 'Jennifer Hudson'], 'en', true),

-- ENGLISH - Level 2
('musique', 2, 'In what year did the Beatles break up?', '1970', ARRAY['1968', '1972', '1975'], 'en', true),
('musique', 2, 'What genre of music originated in Jamaica?', 'Reggae', ARRAY['Ska', 'Calypso', 'Soca'], 'en', true),
('musique', 2, 'How many symphonies did Beethoven compose?', '9', ARRAY['5', '7', '12'], 'en', true),
('musique', 2, 'Which band performed "Smells Like Teen Spirit"?', 'Nirvana', ARRAY['Pearl Jam', 'Soundgarden', 'Alice in Chains'], 'en', true),
('musique', 2, 'How many keys does a standard piano have?', '88', ARRAY['76', '92', '84'], 'en', true),
('musique', 2, 'Which singer performed "Back to Black"?', 'Amy Winehouse', ARRAY['Adele', 'Duffy', 'Joss Stone'], 'en', true),
('musique', 2, 'Which Irish band sang "One"?', 'U2', ARRAY['The Cranberries', 'Thin Lizzy', 'Snow Patrol'], 'en', true),
('musique', 2, 'What note comes after "Do" in the scale?', 'Re', ARRAY['Mi', 'Fa', 'Sol'], 'en', true),
('musique', 2, 'Which rapper founded Death Row Records?', 'Dr. Dre', ARRAY['Snoop Dogg', 'Tupac', 'Suge Knight'], 'en', true),
('musique', 2, 'Which band performed "Comfortably Numb"?', 'Pink Floyd', ARRAY['Led Zeppelin', 'The Who', 'Deep Purple'], 'en', true),
('musique', 2, 'What is Bono from U2''s real name?', 'Paul Hewson', ARRAY['David Evans', 'Adam Clayton', 'Larry Mullen'], 'en', true),
('musique', 2, 'Which band sang "Enter Sandman"?', 'Metallica', ARRAY['Megadeth', 'Slayer', 'Anthrax'], 'en', true),
('musique', 2, 'Which Canadian singer sang "My Heart Will Go On"?', 'Celine Dion', ARRAY['Shania Twain', 'Alanis Morissette', 'Sarah McLachlan'], 'en', true),
('musique', 2, 'Which band performed "Satisfaction" in 1965?', 'The Rolling Stones', ARRAY['The Beatles', 'The Who', 'The Kinks'], 'en', true),
('musique', 2, 'What type of instrument is a trumpet?', 'Brass', ARRAY['Woodwind', 'Percussion', 'String'], 'en', true),
('musique', 2, 'Who is the lead singer of Maroon 5?', 'Adam Levine', ARRAY['James Valentine', 'Jesse Carmichael', 'Matt Flynn'], 'en', true),
('musique', 2, 'Which album by Adele sold over 30 million copies?', '21', ARRAY['19', '25', '30'], 'en', true),
('musique', 2, 'What genre is associated with Motown Records?', 'Soul', ARRAY['Rock', 'Jazz', 'Blues'], 'en', true),
('musique', 2, 'Which British singer performed "Rocket Man"?', 'Elton John', ARRAY['David Bowie', 'Rod Stewart', 'Phil Collins'], 'en', true),
('musique', 2, 'Which electronic duo produced "Get Lucky"?', 'Daft Punk', ARRAY['The Chemical Brothers', 'Justice', 'Kraftwerk'], 'en', true),

-- ENGLISH - Level 3
('musique', 3, 'In what year did Freddie Mercury die?', '1991', ARRAY['1989', '1993', '1995'], 'en', true),
('musique', 3, 'Which composer was deaf at the end of his life?', 'Beethoven', ARRAY['Mozart', 'Bach', 'Chopin'], 'en', true),
('musique', 3, 'Which album did Nirvana release in 1991?', 'Nevermind', ARRAY['In Utero', 'Bleach', 'MTV Unplugged'], 'en', true),
('musique', 3, 'How many strings does a standard electric bass have?', '4', ARRAY['5', '6', '3'], 'en', true),
('musique', 3, 'What is the key signature of "Fur Elise"?', 'A minor', ARRAY['C major', 'G major', 'D minor'], 'en', true),
('musique', 3, 'Which British band sang "Wonderwall"?', 'Oasis', ARRAY['Blur', 'Radiohead', 'Pulp'], 'en', true),
('musique', 3, 'Who founded the hip-hop group NWA?', 'Eazy-E', ARRAY['Ice Cube', 'Dr. Dre', 'MC Ren'], 'en', true),
('musique', 3, 'What is the standard tempo range for Adagio?', '66-76 BPM', ARRAY['40-60 BPM', '80-100 BPM', '100-120 BPM'], 'en', true),
('musique', 3, 'Which album did Pink Floyd release with "Money"?', 'The Dark Side of the Moon', ARRAY['The Wall', 'Wish You Were Here', 'Animals'], 'en', true),
('musique', 3, 'How many half steps are in an octave?', '12', ARRAY['8', '10', '14'], 'en', true),
('musique', 3, 'Which Swedish DJ produced "Levels"?', 'Avicii', ARRAY['Swedish House Mafia', 'Robyn', 'Zedd'], 'en', true),
('musique', 3, 'Which composer wrote "The Four Seasons"?', 'Vivaldi', ARRAY['Bach', 'Handel', 'Mozart'], 'en', true),
('musique', 3, 'Which American band sang "Sweet Child O'' Mine"?', 'Guns N'' Roses', ARRAY['Bon Jovi', 'Motley Crue', 'Def Leppard'], 'en', true),
('musique', 3, 'What is the frequency of concert pitch A?', '440 Hz', ARRAY['420 Hz', '460 Hz', '432 Hz'], 'en', true),
('musique', 3, 'Which Belgian singer performed "Alors on Danse"?', 'Stromae', ARRAY['Jacques Brel', 'Arno', 'Angele'], 'en', true),
('musique', 3, 'Which album did The Beatles release in 1969?', 'Abbey Road', ARRAY['Let It Be', 'The White Album', 'Revolver'], 'en', true),
('musique', 3, 'What is another name for the cello?', 'Violoncello', ARRAY['Viola', 'Double bass', 'Violin'], 'en', true),
('musique', 3, 'Which female rapper performed "Super Bass"?', 'Nicki Minaj', ARRAY['Cardi B', 'Megan Thee Stallion', 'Missy Elliott'], 'en', true),
('musique', 3, 'Which rock band released "The Joshua Tree"?', 'U2', ARRAY['R.E.M.', 'INXS', 'The Police'], 'en', true),
('musique', 3, 'What genre combines elements of rock and electronic music?', 'Electrorock', ARRAY['Synthwave', 'Industrial', 'New Wave'], 'en', true),

-- ENGLISH - Level 4
('musique', 4, 'In what year did Mozart die?', '1791', ARRAY['1785', '1795', '1801'], 'en', true),
('musique', 4, 'Which Greek mode starts on E?', 'Phrygian', ARRAY['Dorian', 'Lydian', 'Mixolydian'], 'en', true),
('musique', 4, 'How many piano sonatas did Beethoven write?', '32', ARRAY['24', '28', '36'], 'en', true),
('musique', 4, 'Which composer wrote "The Rite of Spring"?', 'Stravinsky', ARRAY['Debussy', 'Ravel', 'Prokofiev'], 'en', true),
('musique', 4, 'What is the structure of sonata form?', 'Exposition-Development-Recapitulation', ARRAY['ABA', 'Rondo', 'Theme and variations'], 'en', true),
('musique', 4, 'Which prog rock band released "Close to the Edge"?', 'Yes', ARRAY['Genesis', 'King Crimson', 'Emerson Lake & Palmer'], 'en', true),
('musique', 4, 'How many preludes and fugues are in "The Well-Tempered Clavier"?', '48', ARRAY['24', '36', '64'], 'en', true),
('musique', 4, 'Which French composer wrote "Bolero"?', 'Maurice Ravel', ARRAY['Claude Debussy', 'Erik Satie', 'Camille Saint-Saens'], 'en', true),
('musique', 4, 'What is the dominant note of G major?', 'D', ARRAY['B', 'E', 'A'], 'en', true),
('musique', 4, 'Which jazz singer performed "What a Wonderful World"?', 'Louis Armstrong', ARRAY['Ella Fitzgerald', 'Frank Sinatra', 'Nat King Cole'], 'en', true),
('musique', 4, 'What chord is made of C-E-G?', 'C major', ARRAY['C minor', 'C7', 'C augmented'], 'en', true),
('musique', 4, 'Which composer wrote the opera "Carmen"?', 'Bizet', ARRAY['Verdi', 'Puccini', 'Wagner'], 'en', true),
('musique', 4, 'How many movements does a classical symphony have?', '4', ARRAY['3', '5', '6'], 'en', true),
('musique', 4, 'Which band released "OK Computer" in 1997?', 'Radiohead', ARRAY['Blur', 'Oasis', 'Muse'], 'en', true),
('musique', 4, 'What is the time signature of a waltz?', '3/4', ARRAY['4/4', '2/4', '6/8'], 'en', true),
('musique', 4, 'Which Russian composer wrote "Peter and the Wolf"?', 'Prokofiev', ARRAY['Tchaikovsky', 'Rimsky-Korsakov', 'Shostakovich'], 'en', true),
('musique', 4, 'What interval is between C and G?', 'Perfect fifth', ARRAY['Perfect fourth', 'Major sixth', 'Minor seventh'], 'en', true),
('musique', 4, 'Which saxophonist played on Miles Davis'' "Kind of Blue"?', 'John Coltrane', ARRAY['Charlie Parker', 'Sonny Rollins', 'Ornette Coleman'], 'en', true),
('musique', 4, 'How many strings does a cello have?', '4', ARRAY['5', '6', '3'], 'en', true),
('musique', 4, 'Which Austrian composer wrote "The Trout" quintet?', 'Schubert', ARRAY['Mozart', 'Haydn', 'Brahms'], 'en', true),

-- ENGLISH - Level 5 (Music theory, advanced classical)
('musique', 5, 'What is the relative minor of E-flat major?', 'C minor', ARRAY['B-flat minor', 'A-flat minor', 'F minor'], 'en', true),
('musique', 5, 'How many operas did Wagner compose for "The Ring Cycle"?', '4', ARRAY['3', '5', '6'], 'en', true),
('musique', 5, 'What term describes a note lowered by a half step?', 'Flat', ARRAY['Sharp', 'Natural', 'Appoggiatura'], 'en', true),
('musique', 5, 'Which composer wrote the "Goldberg Variations"?', 'Bach', ARRAY['Handel', 'Scarlatti', 'Telemann'], 'en', true),
('musique', 5, 'What singing technique uses the male head voice?', 'Falsetto', ARRAY['Belting', 'Vibrato', 'Growl'], 'en', true),
('musique', 5, 'How many sharps are in F-sharp major?', '6', ARRAY['5', '7', '4'], 'en', true),
('musique', 5, 'Which composer wrote "Tristan und Isolde"?', 'Wagner', ARRAY['Verdi', 'Strauss', 'Puccini'], 'en', true),
('musique', 5, 'Which cadence ends on the dominant chord?', 'Half cadence', ARRAY['Perfect cadence', 'Plagal cadence', 'Deceptive cadence'], 'en', true),
('musique', 5, 'Which mode has a lowered second and raised sixth?', 'Phrygian dominant', ARRAY['Lydian', 'Locrian', 'Dorian'], 'en', true),
('musique', 5, 'How many string quartets did Beethoven compose?', '16', ARRAY['12', '18', '20'], 'en', true),
('musique', 5, 'Which composer developed the twelve-tone technique?', 'Schoenberg', ARRAY['Webern', 'Berg', 'Stockhausen'], 'en', true),
('musique', 5, 'What is the vocal range of a coloratura soprano?', 'C4-F6', ARRAY['A3-C6', 'E4-G6', 'G3-E5'], 'en', true),
('musique', 5, 'What chord is formed by stacking thirds with 4 notes?', 'Seventh chord', ARRAY['Triad', 'Ninth chord', 'Power chord'], 'en', true),
('musique', 5, 'Which French composer wrote "Pelleas et Melisande"?', 'Debussy', ARRAY['Ravel', 'Faure', 'Massenet'], 'en', true),
('musique', 5, 'How many flats are in G-flat major?', '6', ARRAY['5', '7', '4'], 'en', true),
('musique', 5, 'Which Italian term indicates a very slow tempo?', 'Grave', ARRAY['Largo', 'Adagio', 'Lento'], 'en', true),
('musique', 5, 'Which composer wrote "Le Marteau sans Maitre"?', 'Boulez', ARRAY['Messiaen', 'Xenakis', 'Ligeti'], 'en', true),
('musique', 5, 'Which scale has a half step between the 3rd and 4th degrees?', 'Melodic minor', ARRAY['Major scale', 'Harmonic minor', 'Pentatonic'], 'en', true),
('musique', 5, 'Which composer wrote "Transcendental Etudes"?', 'Liszt', ARRAY['Chopin', 'Schumann', 'Brahms'], 'en', true),
('musique', 5, 'What is the highest voice in a mixed choir?', 'Soprano', ARRAY['Alto', 'Mezzo-soprano', 'Contralto'], 'en', true);
