-- Migration: Add 200 technology questions (100 French + 100 English)
-- Categories cover: tech companies, inventors, internet, smartphones, computers, AI, social media, programming

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 1 (20 questions)
-- =====================================================
('technologie', 1, 'Quelle entreprise a créé l''iPhone ?', 'Apple', ARRAY['Samsung', 'Google', 'Microsoft'], 'fr', true),
('technologie', 1, 'Quel est le moteur de recherche le plus utilisé au monde ?', 'Google', ARRAY['Bing', 'Yahoo', 'DuckDuckGo'], 'fr', true),
('technologie', 1, 'Quel réseau social est représenté par un oiseau bleu ?', 'Twitter', ARRAY['Facebook', 'Instagram', 'LinkedIn'], 'fr', true),
('technologie', 1, 'Comment s''appelle l''assistant vocal d''Apple ?', 'Siri', ARRAY['Alexa', 'Cortana', 'Google Assistant'], 'fr', true),
('technologie', 1, 'Quelle entreprise fabrique les consoles PlayStation ?', 'Sony', ARRAY['Microsoft', 'Nintendo', 'Sega'], 'fr', true),
('technologie', 1, 'Quel est le système d''exploitation mobile de Google ?', 'Android', ARRAY['iOS', 'Windows Phone', 'BlackBerry OS'], 'fr', true),
('technologie', 1, 'Comment s''appelle le service de streaming vidéo de Google ?', 'YouTube', ARRAY['Netflix', 'Twitch', 'Vimeo'], 'fr', true),
('technologie', 1, 'Quelle entreprise a créé Windows ?', 'Microsoft', ARRAY['Apple', 'IBM', 'Google'], 'fr', true),
('technologie', 1, 'Quel réseau social appartient à Meta (anciennement Facebook) ?', 'Instagram', ARRAY['Twitter', 'TikTok', 'Snapchat'], 'fr', true),
('technologie', 1, 'Quel est le nom du magasin d''applications d''Apple ?', 'App Store', ARRAY['Google Play', 'Microsoft Store', 'Galaxy Store'], 'fr', true),
('technologie', 1, 'Quelle marque est connue pour ses Galaxy smartphones ?', 'Samsung', ARRAY['Apple', 'Huawei', 'Sony'], 'fr', true),
('technologie', 1, 'Comment s''appelle l''assistant vocal d''Amazon ?', 'Alexa', ARRAY['Siri', 'Cortana', 'Bixby'], 'fr', true),
('technologie', 1, 'Quel site permet de partager des photos et des stories éphémères ?', 'Snapchat', ARRAY['Facebook', 'LinkedIn', 'Reddit'], 'fr', true),
('technologie', 1, 'Quelle entreprise fabrique les consoles Xbox ?', 'Microsoft', ARRAY['Sony', 'Nintendo', 'Sega'], 'fr', true),
('technologie', 1, 'Quel est le nom du casque de réalité virtuelle de Meta ?', 'Quest', ARRAY['Vive', 'Index', 'PlayStation VR'], 'fr', true),
('technologie', 1, 'Quelle application de messagerie appartient à Meta ?', 'WhatsApp', ARRAY['Telegram', 'Signal', 'iMessage'], 'fr', true),
('technologie', 1, 'Comment s''appelle le service de musique en streaming d''Apple ?', 'Apple Music', ARRAY['Spotify', 'Deezer', 'Tidal'], 'fr', true),
('technologie', 1, 'Quelle entreprise chinoise fabrique les smartphones Huawei ?', 'Huawei', ARRAY['Xiaomi', 'Oppo', 'Vivo'], 'fr', true),
('technologie', 1, 'Quel réseau social est principalement utilisé pour les vidéos courtes ?', 'TikTok', ARRAY['YouTube', 'Vimeo', 'Dailymotion'], 'fr', true),
('technologie', 1, 'Comment s''appelle la montre connectée d''Apple ?', 'Apple Watch', ARRAY['Galaxy Watch', 'Fitbit', 'Garmin'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 2 (20 questions)
-- =====================================================
('technologie', 2, 'En quelle année Facebook a-t-il été créé ?', '2004', ARRAY['2006', '2002', '2008'], 'fr', true),
('technologie', 2, 'Qui est le fondateur de Microsoft ?', 'Bill Gates', ARRAY['Steve Jobs', 'Mark Zuckerberg', 'Jeff Bezos'], 'fr', true),
('technologie', 2, 'Quelle entreprise a inventé le premier smartphone moderne en 2007 ?', 'Apple', ARRAY['Nokia', 'BlackBerry', 'Samsung'], 'fr', true),
('technologie', 2, 'Comment s''appelle le navigateur web de Google ?', 'Chrome', ARRAY['Firefox', 'Safari', 'Edge'], 'fr', true),
('technologie', 2, 'Quelle ville américaine est le centre de l''industrie tech ?', 'San Francisco', ARRAY['New York', 'Los Angeles', 'Seattle'], 'fr', true),
('technologie', 2, 'Quel est le nom du robot conversationnel d''OpenAI ?', 'ChatGPT', ARRAY['Siri', 'Alexa', 'Bard'], 'fr', true),
('technologie', 2, 'Quelle entreprise a créé le service de streaming Netflix ?', 'Netflix', ARRAY['Amazon', 'Disney', 'Apple'], 'fr', true),
('technologie', 2, 'Comment s''appelle le service cloud d''Amazon ?', 'AWS', ARRAY['Azure', 'Google Cloud', 'IBM Cloud'], 'fr', true),
('technologie', 2, 'Qui a fondé Tesla et SpaceX ?', 'Elon Musk', ARRAY['Jeff Bezos', 'Bill Gates', 'Mark Zuckerberg'], 'fr', true),
('technologie', 2, 'Quelle entreprise a créé le langage de programmation Java ?', 'Sun Microsystems', ARRAY['Microsoft', 'IBM', 'Apple'], 'fr', true),
('technologie', 2, 'Comment s''appelle le système de paiement sans contact d''Apple ?', 'Apple Pay', ARRAY['Google Pay', 'Samsung Pay', 'PayPal'], 'fr', true),
('technologie', 2, 'Quelle entreprise française est spécialisée dans les jeux vidéo ?', 'Ubisoft', ARRAY['Electronic Arts', 'Activision', 'Rockstar'], 'fr', true),
('technologie', 2, 'Quel est le nom de la puce conçue par Apple pour ses Mac ?', 'M1', ARRAY['A15', 'Intel Core', 'Snapdragon'], 'fr', true),
('technologie', 2, 'Quelle plateforme permet aux développeurs de partager leur code ?', 'GitHub', ARRAY['LinkedIn', 'Stack Overflow', 'Reddit'], 'fr', true),
('technologie', 2, 'Comment s''appelle le service de visioconférence de Microsoft ?', 'Teams', ARRAY['Zoom', 'Meet', 'Skype'], 'fr', true),
('technologie', 2, 'Quelle entreprise a racheté LinkedIn en 2016 ?', 'Microsoft', ARRAY['Google', 'Facebook', 'Amazon'], 'fr', true),
('technologie', 2, 'Quel est le nom du premier navigateur web populaire des années 90 ?', 'Netscape', ARRAY['Internet Explorer', 'Safari', 'Chrome'], 'fr', true),
('technologie', 2, 'Quelle entreprise suédoise a créé Spotify ?', 'Spotify AB', ARRAY['Apple', 'Google', 'Amazon'], 'fr', true),
('technologie', 2, 'Comment s''appelle le format de fichier image le plus courant sur le web ?', 'JPEG', ARRAY['BMP', 'TIFF', 'RAW'], 'fr', true),
('technologie', 2, 'Quelle entreprise a créé le Kindle ?', 'Amazon', ARRAY['Apple', 'Google', 'Barnes & Noble'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 3 (20 questions)
-- =====================================================
('technologie', 3, 'En quelle année le premier iPhone a-t-il été commercialisé ?', '2007', ARRAY['2005', '2009', '2010'], 'fr', true),
('technologie', 3, 'Qui est considéré comme l''inventeur du World Wide Web ?', 'Tim Berners-Lee', ARRAY['Vint Cerf', 'Steve Jobs', 'Bill Gates'], 'fr', true),
('technologie', 3, 'Quel langage de programmation est principalement utilisé pour le développement iOS ?', 'Swift', ARRAY['Java', 'Kotlin', 'C#'], 'fr', true),
('technologie', 3, 'Quelle entreprise a créé le premier microprocesseur commercial ?', 'Intel', ARRAY['AMD', 'IBM', 'Motorola'], 'fr', true),
('technologie', 3, 'Comment s''appelle le protocole de transfert de fichiers sur Internet ?', 'FTP', ARRAY['HTTP', 'SMTP', 'SSH'], 'fr', true),
('technologie', 3, 'Quelle entreprise finlandaise dominait le marché des téléphones avant l''iPhone ?', 'Nokia', ARRAY['Ericsson', 'Motorola', 'Samsung'], 'fr', true),
('technologie', 3, 'Quel est le nom du système d''exploitation open source basé sur Unix ?', 'Linux', ARRAY['Windows', 'macOS', 'DOS'], 'fr', true),
('technologie', 3, 'En quelle année Google a-t-il été fondé ?', '1998', ARRAY['1996', '2000', '2002'], 'fr', true),
('technologie', 3, 'Quelle technologie permet de connecter des appareils sans fil à courte portée ?', 'Bluetooth', ARRAY['Wi-Fi', 'NFC', '4G'], 'fr', true),
('technologie', 3, 'Comment s''appelle l''unité de traitement graphique ?', 'GPU', ARRAY['CPU', 'RAM', 'SSD'], 'fr', true),
('technologie', 3, 'Quelle entreprise allemande fabrique le logiciel SAP ?', 'SAP SE', ARRAY['Siemens', 'Bosch', 'Deutsche Telekom'], 'fr', true),
('technologie', 3, 'Quel est le nom du langage de balisage utilisé pour créer des pages web ?', 'HTML', ARRAY['CSS', 'JavaScript', 'PHP'], 'fr', true),
('technologie', 3, 'Quelle entreprise a créé le premier ordinateur personnel grand public ?', 'Apple', ARRAY['IBM', 'Microsoft', 'HP'], 'fr', true),
('technologie', 3, 'Comment s''appelle la technologie de stockage en nuage ?', 'Cloud computing', ARRAY['Edge computing', 'Fog computing', 'Grid computing'], 'fr', true),
('technologie', 3, 'Quel réseau social professionnel a été fondé en 2003 ?', 'LinkedIn', ARRAY['Facebook', 'Twitter', 'MySpace'], 'fr', true),
('technologie', 3, 'Quelle est la signification de l''acronyme USB ?', 'Universal Serial Bus', ARRAY['United System Board', 'Ultra Speed Buffer', 'Unified Storage Base'], 'fr', true),
('technologie', 3, 'Quelle entreprise a développé le système de navigation GPS ?', 'Département de la Défense US', ARRAY['NASA', 'Google', 'Apple'], 'fr', true),
('technologie', 3, 'Comment s''appelle le format de compression audio le plus répandu ?', 'MP3', ARRAY['WAV', 'FLAC', 'AAC'], 'fr', true),
('technologie', 3, 'Quelle entreprise a créé le moteur de recherche Bing ?', 'Microsoft', ARRAY['Google', 'Yahoo', 'AOL'], 'fr', true),
('technologie', 3, 'Quel est le nom du protocole sécurisé pour les sites web ?', 'HTTPS', ARRAY['HTTP', 'FTP', 'SSH'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 4 (20 questions)
-- =====================================================
('technologie', 4, 'Quel langage de programmation a été créé par Guido van Rossum ?', 'Python', ARRAY['Ruby', 'Perl', 'PHP'], 'fr', true),
('technologie', 4, 'En quelle année le protocole TCP/IP a-t-il été standardisé ?', '1983', ARRAY['1975', '1990', '1978'], 'fr', true),
('technologie', 4, 'Quelle entreprise a développé le premier disque dur ?', 'IBM', ARRAY['Seagate', 'Western Digital', 'Toshiba'], 'fr', true),
('technologie', 4, 'Comment s''appelle l''architecture de processeur utilisée dans les smartphones ?', 'ARM', ARRAY['x86', 'MIPS', 'PowerPC'], 'fr', true),
('technologie', 4, 'Quel scientifique britannique a inventé la machine de Turing ?', 'Alan Turing', ARRAY['Charles Babbage', 'John von Neumann', 'Claude Shannon'], 'fr', true),
('technologie', 4, 'Quelle est la capacité maximale théorique d''une adresse IPv4 ?', '4,3 milliards', ARRAY['256 millions', '16 milliards', '1 milliard'], 'fr', true),
('technologie', 4, 'Quel langage de programmation a été créé chez Bell Labs en 1972 ?', 'C', ARRAY['Pascal', 'FORTRAN', 'COBOL'], 'fr', true),
('technologie', 4, 'Comment s''appelle le processus de conversion de code source en code machine ?', 'Compilation', ARRAY['Interprétation', 'Exécution', 'Debugging'], 'fr', true),
('technologie', 4, 'Quelle entreprise a créé le premier réseau social moderne, SixDegrees ?', 'MacroView', ARRAY['Yahoo', 'AOL', 'Microsoft'], 'fr', true),
('technologie', 4, 'Quel est le nom du premier virus informatique répandu ?', 'Brain', ARRAY['ILOVEYOU', 'Melissa', 'MyDoom'], 'fr', true),
('technologie', 4, 'Quelle technologie permet aux machines d''apprendre à partir de données ?', 'Machine Learning', ARRAY['Big Data', 'Data Mining', 'Business Intelligence'], 'fr', true),
('technologie', 4, 'Comment s''appelle le protocole de messagerie électronique ?', 'SMTP', ARRAY['POP3', 'IMAP', 'HTTP'], 'fr', true),
('technologie', 4, 'Quelle entreprise néerlandaise fabrique les machines de lithographie pour puces ?', 'ASML', ARRAY['Philips', 'TSMC', 'Samsung'], 'fr', true),
('technologie', 4, 'Quel est le nom de l''algorithme de cryptographie asymétrique le plus utilisé ?', 'RSA', ARRAY['AES', 'DES', 'SHA'], 'fr', true),
('technologie', 4, 'En quelle année le premier SMS a-t-il été envoyé ?', '1992', ARRAY['1990', '1995', '1988'], 'fr', true),
('technologie', 4, 'Quelle entreprise a créé le langage de programmation Go ?', 'Google', ARRAY['Microsoft', 'Apple', 'Facebook'], 'fr', true),
('technologie', 4, 'Comment s''appelle la loi qui prédit le doublement des transistors tous les 2 ans ?', 'Loi de Moore', ARRAY['Loi de Metcalfe', 'Loi d''Amdahl', 'Loi de Brooks'], 'fr', true),
('technologie', 4, 'Quel est le nom du réseau informatique ancêtre d''Internet ?', 'ARPANET', ARRAY['BITNET', 'USENET', 'NSFNET'], 'fr', true),
('technologie', 4, 'Quelle est la signification de l''acronyme API ?', 'Application Programming Interface', ARRAY['Advanced Program Integration', 'Automated Process Input', 'Application Process Interface'], 'fr', true),
('technologie', 4, 'Quelle entreprise taïwanaise est le plus grand fabricant de puces au monde ?', 'TSMC', ARRAY['Intel', 'Samsung', 'GlobalFoundries'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 5 (20 questions)
-- =====================================================
('technologie', 5, 'Quel mathématicien a créé le concept de machine universelle en 1936 ?', 'Alan Turing', ARRAY['John von Neumann', 'Claude Shannon', 'Alonzo Church'], 'fr', true),
('technologie', 5, 'Quel protocole utilise le port 443 par défaut ?', 'HTTPS', ARRAY['HTTP', 'FTP', 'SSH'], 'fr', true),
('technologie', 5, 'En quelle année Dennis Ritchie a-t-il créé le langage C ?', '1972', ARRAY['1969', '1975', '1980'], 'fr', true),
('technologie', 5, 'Quelle est la complexité temporelle moyenne du tri rapide (quicksort) ?', 'O(n log n)', ARRAY['O(n²)', 'O(n)', 'O(log n)'], 'fr', true),
('technologie', 5, 'Quel ingénieur a inventé le transistor en 1947 ?', 'William Shockley', ARRAY['Jack Kilby', 'Robert Noyce', 'Gordon Moore'], 'fr', true),
('technologie', 5, 'Comment s''appelle l''algorithme de consensus utilisé par Bitcoin ?', 'Proof of Work', ARRAY['Proof of Stake', 'Byzantine Fault Tolerance', 'Raft'], 'fr', true),
('technologie', 5, 'Quelle est la longueur d''une adresse IPv6 en bits ?', '128 bits', ARRAY['64 bits', '256 bits', '32 bits'], 'fr', true),
('technologie', 5, 'Quel langage fonctionnel a été créé au MIT en 1958 ?', 'LISP', ARRAY['FORTRAN', 'COBOL', 'ALGOL'], 'fr', true),
('technologie', 5, 'Quelle architecture de réseau neuronal est utilisée pour le traitement du langage ?', 'Transformer', ARRAY['CNN', 'RNN', 'GAN'], 'fr', true),
('technologie', 5, 'En quelle année le premier microprocesseur Intel 4004 a-t-il été commercialisé ?', '1971', ARRAY['1968', '1974', '1965'], 'fr', true),
('technologie', 5, 'Quel est le nom du théorème fondamental de la théorie de l''information ?', 'Théorème de Shannon', ARRAY['Théorème de Nyquist', 'Théorème de Bayes', 'Théorème de Turing'], 'fr', true),
('technologie', 5, 'Quelle entreprise a créé le premier compilateur en 1952 ?', 'Remington Rand', ARRAY['IBM', 'MIT', 'Bell Labs'], 'fr', true),
('technologie', 5, 'Comment s''appelle le protocole de routage utilisé sur Internet ?', 'BGP', ARRAY['OSPF', 'RIP', 'EIGRP'], 'fr', true),
('technologie', 5, 'Quel scientifique a proposé le test d''intelligence artificielle en 1950 ?', 'Alan Turing', ARRAY['John McCarthy', 'Marvin Minsky', 'Claude Shannon'], 'fr', true),
('technologie', 5, 'Quelle est la signification de l''acronyme RISC ?', 'Reduced Instruction Set Computer', ARRAY['Random Instruction Set Computer', 'Rapid Instruction Set Computer', 'Real-time Instruction Set Computer'], 'fr', true),
('technologie', 5, 'En quelle année Grace Hopper a-t-elle inventé le premier compilateur ?', '1952', ARRAY['1945', '1958', '1962'], 'fr', true),
('technologie', 5, 'Quel algorithme de hachage cryptographique produit une empreinte de 256 bits ?', 'SHA-256', ARRAY['MD5', 'SHA-1', 'SHA-512'], 'fr', true),
('technologie', 5, 'Quelle est la fréquence d''horloge du premier processeur Intel 8086 ?', '5 MHz', ARRAY['1 MHz', '10 MHz', '16 MHz'], 'fr', true),
('technologie', 5, 'Comment s''appelle le problème NP-complet classique du voyageur de commerce ?', 'TSP', ARRAY['SAT', 'CLIQUE', 'VERTEX COVER'], 'fr', true),
('technologie', 5, 'Quel scientifique a inventé le concept de réseau neuronal artificiel en 1943 ?', 'Warren McCulloch', ARRAY['Frank Rosenblatt', 'Geoffrey Hinton', 'Yann LeCun'], 'fr', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 1 (20 questions)
-- =====================================================
('technologie', 1, 'Which company created the iPhone?', 'Apple', ARRAY['Samsung', 'Google', 'Microsoft'], 'en', true),
('technologie', 1, 'What is the most used search engine in the world?', 'Google', ARRAY['Bing', 'Yahoo', 'DuckDuckGo'], 'en', true),
('technologie', 1, 'Which social network is represented by a blue bird?', 'Twitter', ARRAY['Facebook', 'Instagram', 'LinkedIn'], 'en', true),
('technologie', 1, 'What is the name of Apple''s voice assistant?', 'Siri', ARRAY['Alexa', 'Cortana', 'Google Assistant'], 'en', true),
('technologie', 1, 'Which company makes PlayStation consoles?', 'Sony', ARRAY['Microsoft', 'Nintendo', 'Sega'], 'en', true),
('technologie', 1, 'What is Google''s mobile operating system called?', 'Android', ARRAY['iOS', 'Windows Phone', 'BlackBerry OS'], 'en', true),
('technologie', 1, 'What is Google''s video streaming service called?', 'YouTube', ARRAY['Netflix', 'Twitch', 'Vimeo'], 'en', true),
('technologie', 1, 'Which company created Windows?', 'Microsoft', ARRAY['Apple', 'IBM', 'Google'], 'en', true),
('technologie', 1, 'Which social network belongs to Meta (formerly Facebook)?', 'Instagram', ARRAY['Twitter', 'TikTok', 'Snapchat'], 'en', true),
('technologie', 1, 'What is the name of Apple''s app marketplace?', 'App Store', ARRAY['Google Play', 'Microsoft Store', 'Galaxy Store'], 'en', true),
('technologie', 1, 'Which brand is known for its Galaxy smartphones?', 'Samsung', ARRAY['Apple', 'Huawei', 'Sony'], 'en', true),
('technologie', 1, 'What is Amazon''s voice assistant called?', 'Alexa', ARRAY['Siri', 'Cortana', 'Bixby'], 'en', true),
('technologie', 1, 'Which app allows sharing photos and ephemeral stories?', 'Snapchat', ARRAY['Facebook', 'LinkedIn', 'Reddit'], 'en', true),
('technologie', 1, 'Which company makes Xbox consoles?', 'Microsoft', ARRAY['Sony', 'Nintendo', 'Sega'], 'en', true),
('technologie', 1, 'What is the name of Meta''s virtual reality headset?', 'Quest', ARRAY['Vive', 'Index', 'PlayStation VR'], 'en', true),
('technologie', 1, 'Which messaging app belongs to Meta?', 'WhatsApp', ARRAY['Telegram', 'Signal', 'iMessage'], 'en', true),
('technologie', 1, 'What is Apple''s music streaming service called?', 'Apple Music', ARRAY['Spotify', 'Deezer', 'Tidal'], 'en', true),
('technologie', 1, 'Which Chinese company manufactures Huawei smartphones?', 'Huawei', ARRAY['Xiaomi', 'Oppo', 'Vivo'], 'en', true),
('technologie', 1, 'Which social network is mainly used for short videos?', 'TikTok', ARRAY['YouTube', 'Vimeo', 'Dailymotion'], 'en', true),
('technologie', 1, 'What is Apple''s smartwatch called?', 'Apple Watch', ARRAY['Galaxy Watch', 'Fitbit', 'Garmin'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 2 (20 questions)
-- =====================================================
('technologie', 2, 'In what year was Facebook created?', '2004', ARRAY['2006', '2002', '2008'], 'en', true),
('technologie', 2, 'Who is the founder of Microsoft?', 'Bill Gates', ARRAY['Steve Jobs', 'Mark Zuckerberg', 'Jeff Bezos'], 'en', true),
('technologie', 2, 'Which company invented the first modern smartphone in 2007?', 'Apple', ARRAY['Nokia', 'BlackBerry', 'Samsung'], 'en', true),
('technologie', 2, 'What is Google''s web browser called?', 'Chrome', ARRAY['Firefox', 'Safari', 'Edge'], 'en', true),
('technologie', 2, 'Which American city is the center of the tech industry?', 'San Francisco', ARRAY['New York', 'Los Angeles', 'Seattle'], 'en', true),
('technologie', 2, 'What is the name of OpenAI''s conversational robot?', 'ChatGPT', ARRAY['Siri', 'Alexa', 'Bard'], 'en', true),
('technologie', 2, 'Which company created the Netflix streaming service?', 'Netflix', ARRAY['Amazon', 'Disney', 'Apple'], 'en', true),
('technologie', 2, 'What is Amazon''s cloud service called?', 'AWS', ARRAY['Azure', 'Google Cloud', 'IBM Cloud'], 'en', true),
('technologie', 2, 'Who founded Tesla and SpaceX?', 'Elon Musk', ARRAY['Jeff Bezos', 'Bill Gates', 'Mark Zuckerberg'], 'en', true),
('technologie', 2, 'Which company created the Java programming language?', 'Sun Microsystems', ARRAY['Microsoft', 'IBM', 'Apple'], 'en', true),
('technologie', 2, 'What is Apple''s contactless payment system called?', 'Apple Pay', ARRAY['Google Pay', 'Samsung Pay', 'PayPal'], 'en', true),
('technologie', 2, 'Which French company specializes in video games?', 'Ubisoft', ARRAY['Electronic Arts', 'Activision', 'Rockstar'], 'en', true),
('technologie', 2, 'What is the name of the chip designed by Apple for its Macs?', 'M1', ARRAY['A15', 'Intel Core', 'Snapdragon'], 'en', true),
('technologie', 2, 'Which platform allows developers to share their code?', 'GitHub', ARRAY['LinkedIn', 'Stack Overflow', 'Reddit'], 'en', true),
('technologie', 2, 'What is Microsoft''s video conferencing service called?', 'Teams', ARRAY['Zoom', 'Meet', 'Skype'], 'en', true),
('technologie', 2, 'Which company acquired LinkedIn in 2016?', 'Microsoft', ARRAY['Google', 'Facebook', 'Amazon'], 'en', true),
('technologie', 2, 'What was the name of the first popular web browser in the 90s?', 'Netscape', ARRAY['Internet Explorer', 'Safari', 'Chrome'], 'en', true),
('technologie', 2, 'Which Swedish company created Spotify?', 'Spotify AB', ARRAY['Apple', 'Google', 'Amazon'], 'en', true),
('technologie', 2, 'What is the most common image file format on the web?', 'JPEG', ARRAY['BMP', 'TIFF', 'RAW'], 'en', true),
('technologie', 2, 'Which company created the Kindle?', 'Amazon', ARRAY['Apple', 'Google', 'Barnes & Noble'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 3 (20 questions)
-- =====================================================
('technologie', 3, 'In what year was the first iPhone released?', '2007', ARRAY['2005', '2009', '2010'], 'en', true),
('technologie', 3, 'Who is considered the inventor of the World Wide Web?', 'Tim Berners-Lee', ARRAY['Vint Cerf', 'Steve Jobs', 'Bill Gates'], 'en', true),
('technologie', 3, 'Which programming language is mainly used for iOS development?', 'Swift', ARRAY['Java', 'Kotlin', 'C#'], 'en', true),
('technologie', 3, 'Which company created the first commercial microprocessor?', 'Intel', ARRAY['AMD', 'IBM', 'Motorola'], 'en', true),
('technologie', 3, 'What is the protocol for transferring files on the Internet called?', 'FTP', ARRAY['HTTP', 'SMTP', 'SSH'], 'en', true),
('technologie', 3, 'Which Finnish company dominated the phone market before the iPhone?', 'Nokia', ARRAY['Ericsson', 'Motorola', 'Samsung'], 'en', true),
('technologie', 3, 'What is the name of the open source operating system based on Unix?', 'Linux', ARRAY['Windows', 'macOS', 'DOS'], 'en', true),
('technologie', 3, 'In what year was Google founded?', '1998', ARRAY['1996', '2000', '2002'], 'en', true),
('technologie', 3, 'Which technology allows short-range wireless device connections?', 'Bluetooth', ARRAY['Wi-Fi', 'NFC', '4G'], 'en', true),
('technologie', 3, 'What does GPU stand for?', 'Graphics Processing Unit', ARRAY['General Processing Unit', 'Graphical Power Unit', 'Global Processing Unit'], 'en', true),
('technologie', 3, 'Which German company makes SAP software?', 'SAP SE', ARRAY['Siemens', 'Bosch', 'Deutsche Telekom'], 'en', true),
('technologie', 3, 'What is the markup language used to create web pages?', 'HTML', ARRAY['CSS', 'JavaScript', 'PHP'], 'en', true),
('technologie', 3, 'Which company created the first consumer personal computer?', 'Apple', ARRAY['IBM', 'Microsoft', 'HP'], 'en', true),
('technologie', 3, 'What is cloud storage technology called?', 'Cloud computing', ARRAY['Edge computing', 'Fog computing', 'Grid computing'], 'en', true),
('technologie', 3, 'Which professional social network was founded in 2003?', 'LinkedIn', ARRAY['Facebook', 'Twitter', 'MySpace'], 'en', true),
('technologie', 3, 'What does USB stand for?', 'Universal Serial Bus', ARRAY['United System Board', 'Ultra Speed Buffer', 'Unified Storage Base'], 'en', true),
('technologie', 3, 'Which organization developed the GPS navigation system?', 'US Department of Defense', ARRAY['NASA', 'Google', 'Apple'], 'en', true),
('technologie', 3, 'What is the most common audio compression format?', 'MP3', ARRAY['WAV', 'FLAC', 'AAC'], 'en', true),
('technologie', 3, 'Which company created the Bing search engine?', 'Microsoft', ARRAY['Google', 'Yahoo', 'AOL'], 'en', true),
('technologie', 3, 'What is the secure protocol for websites called?', 'HTTPS', ARRAY['HTTP', 'FTP', 'SSH'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 4 (20 questions)
-- =====================================================
('technologie', 4, 'Which programming language was created by Guido van Rossum?', 'Python', ARRAY['Ruby', 'Perl', 'PHP'], 'en', true),
('technologie', 4, 'In what year was the TCP/IP protocol standardized?', '1983', ARRAY['1975', '1990', '1978'], 'en', true),
('technologie', 4, 'Which company developed the first hard drive?', 'IBM', ARRAY['Seagate', 'Western Digital', 'Toshiba'], 'en', true),
('technologie', 4, 'What is the processor architecture used in smartphones called?', 'ARM', ARRAY['x86', 'MIPS', 'PowerPC'], 'en', true),
('technologie', 4, 'Which British scientist invented the Turing machine?', 'Alan Turing', ARRAY['Charles Babbage', 'John von Neumann', 'Claude Shannon'], 'en', true),
('technologie', 4, 'What is the theoretical maximum capacity of an IPv4 address?', '4.3 billion', ARRAY['256 million', '16 billion', '1 billion'], 'en', true),
('technologie', 4, 'Which programming language was created at Bell Labs in 1972?', 'C', ARRAY['Pascal', 'FORTRAN', 'COBOL'], 'en', true),
('technologie', 4, 'What is the process of converting source code to machine code called?', 'Compilation', ARRAY['Interpretation', 'Execution', 'Debugging'], 'en', true),
('technologie', 4, 'Which company created the first modern social network, SixDegrees?', 'MacroView', ARRAY['Yahoo', 'AOL', 'Microsoft'], 'en', true),
('technologie', 4, 'What was the name of the first widespread computer virus?', 'Brain', ARRAY['ILOVEYOU', 'Melissa', 'MyDoom'], 'en', true),
('technologie', 4, 'Which technology allows machines to learn from data?', 'Machine Learning', ARRAY['Big Data', 'Data Mining', 'Business Intelligence'], 'en', true),
('technologie', 4, 'What is the email messaging protocol called?', 'SMTP', ARRAY['POP3', 'IMAP', 'HTTP'], 'en', true),
('technologie', 4, 'Which Dutch company makes lithography machines for chips?', 'ASML', ARRAY['Philips', 'TSMC', 'Samsung'], 'en', true),
('technologie', 4, 'What is the name of the most used asymmetric cryptography algorithm?', 'RSA', ARRAY['AES', 'DES', 'SHA'], 'en', true),
('technologie', 4, 'In what year was the first SMS sent?', '1992', ARRAY['1990', '1995', '1988'], 'en', true),
('technologie', 4, 'Which company created the Go programming language?', 'Google', ARRAY['Microsoft', 'Apple', 'Facebook'], 'en', true),
('technologie', 4, 'What is the law that predicts transistor doubling every 2 years called?', 'Moore''s Law', ARRAY['Metcalfe''s Law', 'Amdahl''s Law', 'Brooks'' Law'], 'en', true),
('technologie', 4, 'What was the name of the computer network that preceded the Internet?', 'ARPANET', ARRAY['BITNET', 'USENET', 'NSFNET'], 'en', true),
('technologie', 4, 'What does API stand for?', 'Application Programming Interface', ARRAY['Advanced Program Integration', 'Automated Process Input', 'Application Process Interface'], 'en', true),
('technologie', 4, 'Which Taiwanese company is the world''s largest chip manufacturer?', 'TSMC', ARRAY['Intel', 'Samsung', 'GlobalFoundries'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 5 (20 questions)
-- =====================================================
('technologie', 5, 'Which mathematician created the concept of universal machine in 1936?', 'Alan Turing', ARRAY['John von Neumann', 'Claude Shannon', 'Alonzo Church'], 'en', true),
('technologie', 5, 'Which protocol uses port 443 by default?', 'HTTPS', ARRAY['HTTP', 'FTP', 'SSH'], 'en', true),
('technologie', 5, 'In what year did Dennis Ritchie create the C language?', '1972', ARRAY['1969', '1975', '1980'], 'en', true),
('technologie', 5, 'What is the average time complexity of quicksort?', 'O(n log n)', ARRAY['O(n²)', 'O(n)', 'O(log n)'], 'en', true),
('technologie', 5, 'Which engineer invented the transistor in 1947?', 'William Shockley', ARRAY['Jack Kilby', 'Robert Noyce', 'Gordon Moore'], 'en', true),
('technologie', 5, 'What is the consensus algorithm used by Bitcoin called?', 'Proof of Work', ARRAY['Proof of Stake', 'Byzantine Fault Tolerance', 'Raft'], 'en', true),
('technologie', 5, 'What is the length of an IPv6 address in bits?', '128 bits', ARRAY['64 bits', '256 bits', '32 bits'], 'en', true),
('technologie', 5, 'Which functional language was created at MIT in 1958?', 'LISP', ARRAY['FORTRAN', 'COBOL', 'ALGOL'], 'en', true),
('technologie', 5, 'Which neural network architecture is used for language processing?', 'Transformer', ARRAY['CNN', 'RNN', 'GAN'], 'en', true),
('technologie', 5, 'In what year was the first Intel 4004 microprocessor released?', '1971', ARRAY['1968', '1974', '1965'], 'en', true),
('technologie', 5, 'What is the fundamental theorem of information theory called?', 'Shannon''s theorem', ARRAY['Nyquist theorem', 'Bayes theorem', 'Turing theorem'], 'en', true),
('technologie', 5, 'Which company created the first compiler in 1952?', 'Remington Rand', ARRAY['IBM', 'MIT', 'Bell Labs'], 'en', true),
('technologie', 5, 'What is the routing protocol used on the Internet called?', 'BGP', ARRAY['OSPF', 'RIP', 'EIGRP'], 'en', true),
('technologie', 5, 'Which scientist proposed the artificial intelligence test in 1950?', 'Alan Turing', ARRAY['John McCarthy', 'Marvin Minsky', 'Claude Shannon'], 'en', true),
('technologie', 5, 'What does RISC stand for?', 'Reduced Instruction Set Computer', ARRAY['Random Instruction Set Computer', 'Rapid Instruction Set Computer', 'Real-time Instruction Set Computer'], 'en', true),
('technologie', 5, 'In what year did Grace Hopper invent the first compiler?', '1952', ARRAY['1945', '1958', '1962'], 'en', true),
('technologie', 5, 'Which cryptographic hashing algorithm produces a 256-bit digest?', 'SHA-256', ARRAY['MD5', 'SHA-1', 'SHA-512'], 'en', true),
('technologie', 5, 'What was the clock frequency of the first Intel 8086 processor?', '5 MHz', ARRAY['1 MHz', '10 MHz', '16 MHz'], 'en', true),
('technologie', 5, 'What is the classic NP-complete traveling salesman problem called?', 'TSP', ARRAY['SAT', 'CLIQUE', 'VERTEX COVER'], 'en', true),
('technologie', 5, 'Which scientist invented the concept of artificial neural network in 1943?', 'Warren McCulloch', ARRAY['Frank Rosenblatt', 'Geoffrey Hinton', 'Yann LeCun'], 'en', true);
