-- Migration: Add 200 cinema questions (100 French + 100 English)
-- 20 questions per difficulty level (1-5) for each language

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 1 (Very Easy)
-- =====================================================
('cinema', 1, 'Quel personnage Disney chante "Libérée, Délivrée" ?', 'Elsa', ARRAY['Anna', 'Raiponce', 'Cendrillon'], 'fr', true),
('cinema', 1, 'Quel acteur joue Jack Sparrow dans Pirates des Caraïbes ?', 'Johnny Depp', ARRAY['Orlando Bloom', 'Brad Pitt', 'Tom Cruise'], 'fr', true),
('cinema', 1, 'Dans quel film trouve-t-on le personnage de Woody le cowboy ?', 'Toy Story', ARRAY['Cars', 'Monstres et Cie', 'Le Monde de Nemo'], 'fr', true),
('cinema', 1, 'Quel est le nom du lion dans Le Roi Lion ?', 'Simba', ARRAY['Mufasa', 'Scar', 'Timon'], 'fr', true),
('cinema', 1, 'Qui a réalisé Titanic ?', 'James Cameron', ARRAY['Steven Spielberg', 'Christopher Nolan', 'Martin Scorsese'], 'fr', true),
('cinema', 1, 'Quel super-héros porte un costume rouge et bleu et lance des toiles ?', 'Spider-Man', ARRAY['Superman', 'Batman', 'Iron Man'], 'fr', true),
('cinema', 1, 'Dans quel film Harry Potter va-t-il à l''école de Poudlard ?', 'Harry Potter à l''école des sorciers', ARRAY['Harry Potter et la Chambre des secrets', 'Harry Potter et le Prisonnier d''Azkaban', 'Harry Potter et la Coupe de feu'], 'fr', true),
('cinema', 1, 'Quel animal est Nemo dans Le Monde de Nemo ?', 'Un poisson-clown', ARRAY['Un requin', 'Une tortue', 'Une baleine'], 'fr', true),
('cinema', 1, 'Qui joue Iron Man dans les films Marvel ?', 'Robert Downey Jr.', ARRAY['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], 'fr', true),
('cinema', 1, 'Quel est le nom du bonhomme de neige dans La Reine des Neiges ?', 'Olaf', ARRAY['Sven', 'Kristoff', 'Hans'], 'fr', true),
('cinema', 1, 'Dans quel film voit-on une voiture de course rouge nommée Flash McQueen ?', 'Cars', ARRAY['Turbo', 'Speed Racer', 'Need for Speed'], 'fr', true),
('cinema', 1, 'Quel acteur joue Forrest Gump ?', 'Tom Hanks', ARRAY['Robin Williams', 'Jim Carrey', 'Will Smith'], 'fr', true),
('cinema', 1, 'Quel est le nom du rat chef cuisinier dans le film Pixar ?', 'Rémy', ARRAY['Emile', 'Django', 'Alfredo'], 'fr', true),
('cinema', 1, 'Dans quel film les jouets prennent vie quand les humains ne regardent pas ?', 'Toy Story', ARRAY['Small Soldiers', 'Jumanji', 'Chérie, j''ai rétréci les gosses'], 'fr', true),
('cinema', 1, 'Qui joue le rôle de Batman dans The Dark Knight ?', 'Christian Bale', ARRAY['Ben Affleck', 'Michael Keaton', 'George Clooney'], 'fr', true),
('cinema', 1, 'Quel personnage dit "Je suis ton père" dans Star Wars ?', 'Dark Vador', ARRAY['Obi-Wan Kenobi', 'Yoda', 'Palpatine'], 'fr', true),
('cinema', 1, 'Dans quel film une princesse embrasse une grenouille ?', 'La Princesse et la Grenouille', ARRAY['Cendrillon', 'La Belle au bois dormant', 'Raiponce'], 'fr', true),
('cinema', 1, 'Quel acteur joue le rôle de Thor ?', 'Chris Hemsworth', ARRAY['Chris Evans', 'Chris Pratt', 'Tom Hiddleston'], 'fr', true),
('cinema', 1, 'Quel film raconte l''histoire d''un ogre vert vivant dans un marécage ?', 'Shrek', ARRAY['Monstres et Cie', 'L''Âge de glace', 'Madagascar'], 'fr', true),
('cinema', 1, 'Qui double Buzz l''Éclair dans la version originale de Toy Story ?', 'Tim Allen', ARRAY['Tom Hanks', 'Billy Crystal', 'John Goodman'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 2 (Easy)
-- =====================================================
('cinema', 2, 'Quel film a remporté l''Oscar du meilleur film en 2020 ?', 'Parasite', ARRAY['1917', 'Joker', 'Le Mans 66'], 'fr', true),
('cinema', 2, 'Qui a réalisé la trilogie du Seigneur des Anneaux ?', 'Peter Jackson', ARRAY['Christopher Nolan', 'Ridley Scott', 'James Cameron'], 'fr', true),
('cinema', 2, 'Dans quel film Leonardo DiCaprio joue-t-il un escroc qui se fait passer pour un pilote ?', 'Arrête-moi si tu peux', ARRAY['Le Loup de Wall Street', 'Inception', 'Shutter Island'], 'fr', true),
('cinema', 2, 'Quel acteur français a joué dans Léon et Le Cinquième Élément ?', 'Jean Reno', ARRAY['Gérard Depardieu', 'Vincent Cassel', 'Jean Dujardin'], 'fr', true),
('cinema', 2, 'Quel est le vrai nom de Black Widow dans les films Marvel ?', 'Natasha Romanoff', ARRAY['Wanda Maximoff', 'Carol Danvers', 'Peggy Carter'], 'fr', true),
('cinema', 2, 'Qui joue le Joker dans le film de 2019 ?', 'Joaquin Phoenix', ARRAY['Heath Ledger', 'Jared Leto', 'Jack Nicholson'], 'fr', true),
('cinema', 2, 'Dans quel film voit-on le personnage de Gollum ?', 'Le Seigneur des Anneaux', ARRAY['Harry Potter', 'Le Hobbit', 'Narnia'], 'fr', true),
('cinema', 2, 'Quel réalisateur est connu pour ses films comme Pulp Fiction et Kill Bill ?', 'Quentin Tarantino', ARRAY['Martin Scorsese', 'David Fincher', 'Guy Ritchie'], 'fr', true),
('cinema', 2, 'Quelle actrice joue Hermione dans Harry Potter ?', 'Emma Watson', ARRAY['Emma Stone', 'Emma Roberts', 'Emily Blunt'], 'fr', true),
('cinema', 2, 'Quel film de 1997 a été le plus gros succès au box-office mondial pendant 12 ans ?', 'Titanic', ARRAY['Jurassic Park', 'Le Roi Lion', 'Independence Day'], 'fr', true),
('cinema', 2, 'Qui a réalisé Interstellar ?', 'Christopher Nolan', ARRAY['Denis Villeneuve', 'Ridley Scott', 'Alfonso Cuarón'], 'fr', true),
('cinema', 2, 'Dans quel film Tom Cruise joue-t-il un agent secret nommé Ethan Hunt ?', 'Mission: Impossible', ARRAY['Jack Reacher', 'Top Gun', 'La Firme'], 'fr', true),
('cinema', 2, 'Quel film français a gagné l''Oscar du meilleur film étranger en 2012 ?', 'The Artist', ARRAY['Intouchables', 'Amélie Poulain', 'La Haine'], 'fr', true),
('cinema', 2, 'Qui joue le rôle de Wolverine dans les films X-Men ?', 'Hugh Jackman', ARRAY['Liam Hemsworth', 'Russell Crowe', 'Gerard Butler'], 'fr', true),
('cinema', 2, 'Quel est le nom du vaisseau spatial de Han Solo ?', 'Le Faucon Millenium', ARRAY['L''Étoile de la Mort', 'Le X-Wing', 'Le TIE Fighter'], 'fr', true),
('cinema', 2, 'Quelle actrice joue Katniss dans Hunger Games ?', 'Jennifer Lawrence', ARRAY['Emma Stone', 'Shailene Woodley', 'Kristen Stewart'], 'fr', true),
('cinema', 2, 'Qui a réalisé Avatar (2009) ?', 'James Cameron', ARRAY['Steven Spielberg', 'Peter Jackson', 'George Lucas'], 'fr', true),
('cinema', 2, 'Dans quel film Keanu Reeves joue-t-il un personnage qui découvre que le monde est une simulation ?', 'Matrix', ARRAY['John Wick', 'Constantine', 'Speed'], 'fr', true),
('cinema', 2, 'Quel acteur joue le rôle principal dans Gladiator ?', 'Russell Crowe', ARRAY['Gerard Butler', 'Brad Pitt', 'Orlando Bloom'], 'fr', true),
('cinema', 2, 'Quelle saga a pour héros un archéologue avec un chapeau et un fouet ?', 'Indiana Jones', ARRAY['La Momie', 'Tomb Raider', 'National Treasure'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 3 (Medium)
-- =====================================================
('cinema', 3, 'Quel film de Stanley Kubrick se déroule pendant la guerre du Vietnam ?', 'Full Metal Jacket', ARRAY['Apocalypse Now', 'Platoon', 'Voyage au bout de l''enfer'], 'fr', true),
('cinema', 3, 'Qui a réalisé le film Amélie Poulain ?', 'Jean-Pierre Jeunet', ARRAY['Luc Besson', 'Michel Gondry', 'Jacques Audiard'], 'fr', true),
('cinema', 3, 'Dans quel film Alfred Hitchcock fait-il une apparition dans un journal ?', 'Le Bateau qui meurt', ARRAY['Psychose', 'Les Oiseaux', 'Fenêtre sur cour'], 'fr', true),
('cinema', 3, 'Quel acteur a joué dans Taxi Driver, Les Affranchis et Casino ?', 'Robert De Niro', ARRAY['Al Pacino', 'Joe Pesci', 'Harvey Keitel'], 'fr', true),
('cinema', 3, 'Quel film de 1994 raconte l''histoire de prisonniers à Shawshank ?', 'Les Évadés', ARRAY['La Ligne verte', 'Vol au-dessus d''un nid de coucou', 'Le Silence des agneaux'], 'fr', true),
('cinema', 3, 'Qui a composé la musique des films de Sergio Leone ?', 'Ennio Morricone', ARRAY['John Williams', 'Hans Zimmer', 'Bernard Herrmann'], 'fr', true),
('cinema', 3, 'Quel réalisateur japonais a créé Les Sept Samouraïs ?', 'Akira Kurosawa', ARRAY['Hayao Miyazaki', 'Takeshi Kitano', 'Yasujiro Ozu'], 'fr', true),
('cinema', 3, 'Dans quel film voit-on la phrase "Rosebud" comme élément central du mystère ?', 'Citizen Kane', ARRAY['Casablanca', 'Le Faucon maltais', 'Sunset Boulevard'], 'fr', true),
('cinema', 3, 'Quel acteur français a remporté un Oscar pour The Artist ?', 'Jean Dujardin', ARRAY['Omar Sy', 'Vincent Cassel', 'Gilles Lellouche'], 'fr', true),
('cinema', 3, 'Qui a réalisé Mulholland Drive ?', 'David Lynch', ARRAY['David Cronenberg', 'David Fincher', 'Darren Aronofsky'], 'fr', true),
('cinema', 3, 'Quel film de science-fiction de 1982 met en scène des répliquants ?', 'Blade Runner', ARRAY['Terminator', 'RoboCop', 'Total Recall'], 'fr', true),
('cinema', 3, 'Quelle actrice a joué dans La Leçon de piano et Moulin Rouge ?', 'Nicole Kidman', ARRAY['Cate Blanchett', 'Kate Winslet', 'Julianne Moore'], 'fr', true),
('cinema', 3, 'Quel réalisateur mexicain a fait Birdman et The Revenant ?', 'Alejandro González Iñárritu', ARRAY['Guillermo del Toro', 'Alfonso Cuarón', 'Robert Rodriguez'], 'fr', true),
('cinema', 3, 'Dans quel film de Wes Anderson voit-on l''Hôtel Grand Budapest ?', 'The Grand Budapest Hotel', ARRAY['Moonrise Kingdom', 'The Royal Tenenbaums', 'The French Dispatch'], 'fr', true),
('cinema', 3, 'Qui joue le rôle principal dans Léon de Luc Besson ?', 'Jean Reno', ARRAY['Vincent Cassel', 'Gérard Depardieu', 'Jean-Paul Belmondo'], 'fr', true),
('cinema', 3, 'Quel film de Denis Villeneuve raconte l''arrivée d''extraterrestres sur Terre ?', 'Premier Contact', ARRAY['Dune', 'Blade Runner 2049', 'Sicario'], 'fr', true),
('cinema', 3, 'Quelle est la première règle du Fight Club ?', 'On ne parle pas du Fight Club', ARRAY['Ne jamais abandonner', 'Toujours se battre jusqu''au bout', 'Respecter son adversaire'], 'fr', true),
('cinema', 3, 'Qui a réalisé La La Land ?', 'Damien Chazelle', ARRAY['Ryan Gosling', 'Tom Hooper', 'Barry Jenkins'], 'fr', true),
('cinema', 3, 'Dans quel film Brad Pitt joue-t-il un personnage qui vieillit à l''envers ?', 'L''Étrange Histoire de Benjamin Button', ARRAY['Seven', 'Fight Club', 'Inglourious Basterds'], 'fr', true),
('cinema', 3, 'Quel film français de 1995 se déroule dans les banlieues parisiennes ?', 'La Haine', ARRAY['Les Misérables', 'Banlieue 13', 'Divines'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 4 (Hard)
-- =====================================================
('cinema', 4, 'Quel film de Fritz Lang de 1927 est considéré comme un chef-d''œuvre du cinéma expressionniste ?', 'Metropolis', ARRAY['M le maudit', 'Le Cabinet du Dr Caligari', 'Nosferatu'], 'fr', true),
('cinema', 4, 'Qui a réalisé le film russe Le Cuirassé Potemkine ?', 'Sergueï Eisenstein', ARRAY['Andrei Tarkovski', 'Dziga Vertov', 'Alexandre Sokourov'], 'fr', true),
('cinema', 4, 'Quel terme désigne la technique de montage parallèle inventée par D.W. Griffith ?', 'Cross-cutting', ARRAY['Jump cut', 'Match cut', 'Fade out'], 'fr', true),
('cinema', 4, 'Dans quel film de Tarkovski un "stalker" guide des voyageurs vers une zone mystérieuse ?', 'Stalker', ARRAY['Solaris', 'Le Miroir', 'Andreï Roublev'], 'fr', true),
('cinema', 4, 'Quel mouvement cinématographique français des années 50-60 a lancé Godard et Truffaut ?', 'La Nouvelle Vague', ARRAY['Le Néoréalisme', 'Le Dogme 95', 'Le Cinéma vérité'], 'fr', true),
('cinema', 4, 'Qui a écrit le scénario de Chinatown ?', 'Robert Towne', ARRAY['William Goldman', 'Aaron Sorkin', 'Paddy Chayefsky'], 'fr', true),
('cinema', 4, 'Quel directeur de la photographie a travaillé avec Kubrick sur Barry Lyndon ?', 'John Alcott', ARRAY['Roger Deakins', 'Vittorio Storaro', 'Gordon Willis'], 'fr', true),
('cinema', 4, 'Quel film de Michael Powell a été si controversé qu''il a ruiné sa carrière ?', 'Le Voyeur', ARRAY['Les Chaussons rouges', 'Une question de vie ou de mort', 'Colonel Blimp'], 'fr', true),
('cinema', 4, 'Qui a composé la musique de Psychose pour Alfred Hitchcock ?', 'Bernard Herrmann', ARRAY['John Williams', 'Max Steiner', 'Miklós Rózsa'], 'fr', true),
('cinema', 4, 'Quel film de Jean-Luc Godard de 1960 a révolutionné le langage cinématographique ?', 'À bout de souffle', ARRAY['Le Mépris', 'Pierrot le fou', 'Alphaville'], 'fr', true),
('cinema', 4, 'Quelle technique utilisait Orson Welles dans Citizen Kane avec des plafonds visibles ?', 'La profondeur de champ', ARRAY['Le plan séquence', 'La contre-plongée', 'Le clair-obscur'], 'fr', true),
('cinema', 4, 'Quel réalisateur danois a fondé le mouvement Dogme 95 ?', 'Lars von Trier', ARRAY['Thomas Vinterberg', 'Susanne Bier', 'Nicolas Winding Refn'], 'fr', true),
('cinema', 4, 'Dans quel film de Terrence Malick voit-on une voix off philosophique sur la nature ?', 'La Ligne rouge', ARRAY['Les Moissons du ciel', 'The Tree of Life', 'La Balade sauvage'], 'fr', true),
('cinema', 4, 'Qui a réalisé le film iranien Une Séparation ?', 'Asghar Farhadi', ARRAY['Abbas Kiarostami', 'Jafar Panahi', 'Mohsen Makhmalbaf'], 'fr', true),
('cinema', 4, 'Quel film de Wong Kar-wai est célèbre pour sa photographie de Christopher Doyle ?', 'In the Mood for Love', ARRAY['Chungking Express', '2046', 'Happy Together'], 'fr', true),
('cinema', 4, 'Quel terme désigne un plan où la caméra suit un personnage sans coupure ?', 'Plan séquence', ARRAY['Travelling', 'Steadicam', 'Plan américain'], 'fr', true),
('cinema', 4, 'Qui a créé l''effet "bullet time" popularisé dans Matrix ?', 'John Gaeta', ARRAY['Dennis Muren', 'Phil Tippett', 'Stan Winston'], 'fr', true),
('cinema', 4, 'Quel film muet de Carl Theodor Dreyer raconte le procès de Jeanne d''Arc ?', 'La Passion de Jeanne d''Arc', ARRAY['Ordet', 'Vampyr', 'Dies Irae'], 'fr', true),
('cinema', 4, 'Quel cinéaste est associé au "cinéma de la cruauté" avec des films comme Salò ?', 'Pier Paolo Pasolini', ARRAY['Bernardo Bertolucci', 'Luchino Visconti', 'Federico Fellini'], 'fr', true),
('cinema', 4, 'Quel prix récompense la meilleure contribution technique au Festival de Cannes ?', 'Le Prix de la mise en scène', ARRAY['La Palme d''or', 'Le Grand Prix', 'Le Prix du jury'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - DIFFICULTY 5 (Expert)
-- =====================================================
('cinema', 5, 'Quel théoricien du cinéma a développé le concept de "l''effet Koulechov" ?', 'Lev Koulechov', ARRAY['Sergueï Eisenstein', 'Vsevolod Poudovkine', 'Dziga Vertov'], 'fr', true),
('cinema', 5, 'Quel film de 1929 de Luis Buñuel contient la célèbre scène de l''œil tranché ?', 'Un chien andalou', ARRAY['L''Âge d''or', 'Viridiana', 'Belle de jour'], 'fr', true),
('cinema', 5, 'Quel cinéaste a théorisé le "montage des attractions" ?', 'Sergueï Eisenstein', ARRAY['Lev Koulechov', 'Dziga Vertov', 'Alexandre Dovjenko'], 'fr', true),
('cinema', 5, 'Quel film de Robert Bresson utilise exclusivement des acteurs non professionnels appelés "modèles" ?', 'Pickpocket', ARRAY['Un condamné à mort s''est échappé', 'Au hasard Balthazar', 'L''Argent'], 'fr', true),
('cinema', 5, 'Quel critique français a écrit "La Politique des auteurs" dans les Cahiers du Cinéma ?', 'François Truffaut', ARRAY['André Bazin', 'Jacques Rivette', 'Eric Rohmer'], 'fr', true),
('cinema', 5, 'Quel film de Yasujiro Ozu est considéré comme l''un des plus grands films de tous les temps ?', 'Voyage à Tokyo', ARRAY['Printemps tardif', 'Le Goût du saké', 'Fin d''automne'], 'fr', true),
('cinema', 5, 'Quel concept André Bazin a-t-il défendu concernant le réalisme au cinéma ?', 'L''ontologie de l''image photographique', ARRAY['Le montage intellectuel', 'La distanciation brechtienne', 'Le réalisme poétique'], 'fr', true),
('cinema', 5, 'Quel film de Chris Marker de 1962 est composé presque entièrement de photographies fixes ?', 'La Jetée', ARRAY['Sans Soleil', 'Le Fond de l''air est rouge', 'Level Five'], 'fr', true),
('cinema', 5, 'Quel réalisateur a inventé le "Cinéma-œil" (Kino-Glaz) ?', 'Dziga Vertov', ARRAY['Sergueï Eisenstein', 'Lev Koulechov', 'Alexandre Medvedkine'], 'fr', true),
('cinema', 5, 'Quel film de Michelangelo Antonioni clôt sa trilogie de l''incommunicabilité ?', 'L''Éclipse', ARRAY['L''Avventura', 'La Nuit', 'Le Désert rouge'], 'fr', true),
('cinema', 5, 'Quel théoricien a développé le concept de "suture" en analyse filmique ?', 'Jean-Pierre Oudart', ARRAY['Christian Metz', 'Roland Barthes', 'Jacques Lacan'], 'fr', true),
('cinema', 5, 'Quel cinéaste japonais a réalisé L''Empire des sens en 1976 ?', 'Nagisa Oshima', ARRAY['Akira Kurosawa', 'Shohei Imamura', 'Kenji Mizoguchi'], 'fr', true),
('cinema', 5, 'Quel mouvement italien des années 1940 prônait le tournage en extérieurs réels ?', 'Le Néoréalisme', ARRAY['Le Futurisme', 'Le Giallo', 'La Commedia all''italiana'], 'fr', true),
('cinema', 5, 'Quel film d''Alain Resnais mêle documentaire et fiction sur les camps de concentration ?', 'Nuit et Brouillard', ARRAY['Hiroshima mon amour', 'L''Année dernière à Marienbad', 'Muriel'], 'fr', true),
('cinema', 5, 'Quel procédé technique permet le "deep focus" utilisé par Gregg Toland ?', 'Objectif grand angle et petite ouverture', ARRAY['Téléobjectif et grande ouverture', 'Filtre de densité neutre', 'Stabilisateur optique'], 'fr', true),
('cinema', 5, 'Quel cinéaste hongrois a réalisé Sátántangó en 7 heures 30 ?', 'Béla Tarr', ARRAY['Miklós Jancsó', 'István Szabó', 'Márta Mészáros'], 'fr', true),
('cinema', 5, 'Quel film de Jean Rouch de 1961 a inauguré le cinéma-vérité ?', 'Chronique d''un été', ARRAY['Moi, un Noir', 'Les Maîtres fous', 'Jaguar'], 'fr', true),
('cinema', 5, 'Quel concept Gilles Deleuze a-t-il développé dans ses livres sur le cinéma ?', 'L''image-temps et l''image-mouvement', ARRAY['Le hors-champ', 'La diégèse', 'Le plan subjectif'], 'fr', true),
('cinema', 5, 'Quel réalisateur philippin est connu pour ses films contemplatifs de plusieurs heures ?', 'Lav Diaz', ARRAY['Brillante Mendoza', 'Ishmael Bernal', 'Lino Brocka'], 'fr', true),
('cinema', 5, 'Quel film de F.W. Murnau de 1924 est tourné entièrement sans intertitres ?', 'Le Dernier des hommes', ARRAY['Nosferatu', 'L''Aurore', 'Faust'], 'fr', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 1 (Very Easy)
-- =====================================================
('cinema', 1, 'What Disney character sings "Let It Go"?', 'Elsa', ARRAY['Anna', 'Rapunzel', 'Cinderella'], 'en', true),
('cinema', 1, 'Which actor plays Jack Sparrow in Pirates of the Caribbean?', 'Johnny Depp', ARRAY['Orlando Bloom', 'Brad Pitt', 'Tom Cruise'], 'en', true),
('cinema', 1, 'In which movie is Woody the cowboy a main character?', 'Toy Story', ARRAY['Cars', 'Monsters, Inc.', 'Finding Nemo'], 'en', true),
('cinema', 1, 'What is the lion''s name in The Lion King?', 'Simba', ARRAY['Mufasa', 'Scar', 'Timon'], 'en', true),
('cinema', 1, 'Who directed Titanic?', 'James Cameron', ARRAY['Steven Spielberg', 'Christopher Nolan', 'Martin Scorsese'], 'en', true),
('cinema', 1, 'Which superhero wears red and blue and shoots webs?', 'Spider-Man', ARRAY['Superman', 'Batman', 'Iron Man'], 'en', true),
('cinema', 1, 'In which Harry Potter film does he first attend Hogwarts?', 'Harry Potter and the Sorcerer''s Stone', ARRAY['Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Goblet of Fire'], 'en', true),
('cinema', 1, 'What type of fish is Nemo in Finding Nemo?', 'Clownfish', ARRAY['Shark', 'Turtle', 'Whale'], 'en', true),
('cinema', 1, 'Who plays Iron Man in the Marvel movies?', 'Robert Downey Jr.', ARRAY['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], 'en', true),
('cinema', 1, 'What is the snowman''s name in Frozen?', 'Olaf', ARRAY['Sven', 'Kristoff', 'Hans'], 'en', true),
('cinema', 1, 'In which movie is Lightning McQueen a race car?', 'Cars', ARRAY['Turbo', 'Speed Racer', 'Need for Speed'], 'en', true),
('cinema', 1, 'Which actor plays Forrest Gump?', 'Tom Hanks', ARRAY['Robin Williams', 'Jim Carrey', 'Will Smith'], 'en', true),
('cinema', 1, 'What is the name of the rat who cooks in Ratatouille?', 'Remy', ARRAY['Emile', 'Django', 'Alfredo'], 'en', true),
('cinema', 1, 'In which movie do toys come to life when humans aren''t watching?', 'Toy Story', ARRAY['Small Soldiers', 'Jumanji', 'Honey, I Shrunk the Kids'], 'en', true),
('cinema', 1, 'Who plays Batman in The Dark Knight?', 'Christian Bale', ARRAY['Ben Affleck', 'Michael Keaton', 'George Clooney'], 'en', true),
('cinema', 1, 'Which character says "I am your father" in Star Wars?', 'Darth Vader', ARRAY['Obi-Wan Kenobi', 'Yoda', 'Palpatine'], 'en', true),
('cinema', 1, 'In which Disney movie does a princess kiss a frog?', 'The Princess and the Frog', ARRAY['Cinderella', 'Sleeping Beauty', 'Tangled'], 'en', true),
('cinema', 1, 'Which actor plays Thor in the Marvel movies?', 'Chris Hemsworth', ARRAY['Chris Evans', 'Chris Pratt', 'Tom Hiddleston'], 'en', true),
('cinema', 1, 'What movie is about a green ogre living in a swamp?', 'Shrek', ARRAY['Monsters, Inc.', 'Ice Age', 'Madagascar'], 'en', true),
('cinema', 1, 'Who voices Buzz Lightyear in the original Toy Story?', 'Tim Allen', ARRAY['Tom Hanks', 'Billy Crystal', 'John Goodman'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 2 (Easy)
-- =====================================================
('cinema', 2, 'Which film won the Oscar for Best Picture in 2020?', 'Parasite', ARRAY['1917', 'Joker', 'Ford v Ferrari'], 'en', true),
('cinema', 2, 'Who directed the Lord of the Rings trilogy?', 'Peter Jackson', ARRAY['Christopher Nolan', 'Ridley Scott', 'James Cameron'], 'en', true),
('cinema', 2, 'In which movie does Leonardo DiCaprio play a con artist pretending to be a pilot?', 'Catch Me If You Can', ARRAY['The Wolf of Wall Street', 'Inception', 'Shutter Island'], 'en', true),
('cinema', 2, 'Which actress plays Katniss in The Hunger Games?', 'Jennifer Lawrence', ARRAY['Emma Stone', 'Shailene Woodley', 'Kristen Stewart'], 'en', true),
('cinema', 2, 'What is Black Widow''s real name in the Marvel movies?', 'Natasha Romanoff', ARRAY['Wanda Maximoff', 'Carol Danvers', 'Peggy Carter'], 'en', true),
('cinema', 2, 'Who plays the Joker in the 2019 movie?', 'Joaquin Phoenix', ARRAY['Heath Ledger', 'Jared Leto', 'Jack Nicholson'], 'en', true),
('cinema', 2, 'In which movie does the character Gollum appear?', 'The Lord of the Rings', ARRAY['Harry Potter', 'The Hobbit', 'Narnia'], 'en', true),
('cinema', 2, 'Which director is known for Pulp Fiction and Kill Bill?', 'Quentin Tarantino', ARRAY['Martin Scorsese', 'David Fincher', 'Guy Ritchie'], 'en', true),
('cinema', 2, 'Which actress plays Hermione in Harry Potter?', 'Emma Watson', ARRAY['Emma Stone', 'Emma Roberts', 'Emily Blunt'], 'en', true),
('cinema', 2, 'Which 1997 film was the highest-grossing movie worldwide for 12 years?', 'Titanic', ARRAY['Jurassic Park', 'The Lion King', 'Independence Day'], 'en', true),
('cinema', 2, 'Who directed Interstellar?', 'Christopher Nolan', ARRAY['Denis Villeneuve', 'Ridley Scott', 'Alfonso Cuarón'], 'en', true),
('cinema', 2, 'In which movie does Tom Cruise play a secret agent named Ethan Hunt?', 'Mission: Impossible', ARRAY['Jack Reacher', 'Top Gun', 'The Firm'], 'en', true),
('cinema', 2, 'Who plays Wolverine in the X-Men films?', 'Hugh Jackman', ARRAY['Liam Hemsworth', 'Russell Crowe', 'Gerard Butler'], 'en', true),
('cinema', 2, 'What is the name of Han Solo''s spaceship?', 'Millennium Falcon', ARRAY['Death Star', 'X-Wing', 'TIE Fighter'], 'en', true),
('cinema', 2, 'Who directed Avatar (2009)?', 'James Cameron', ARRAY['Steven Spielberg', 'Peter Jackson', 'George Lucas'], 'en', true),
('cinema', 2, 'In which movie does Keanu Reeves discover the world is a simulation?', 'The Matrix', ARRAY['John Wick', 'Constantine', 'Speed'], 'en', true),
('cinema', 2, 'Which actor plays the lead role in Gladiator?', 'Russell Crowe', ARRAY['Gerard Butler', 'Brad Pitt', 'Orlando Bloom'], 'en', true),
('cinema', 2, 'Which film series features an archaeologist with a hat and whip?', 'Indiana Jones', ARRAY['The Mummy', 'Tomb Raider', 'National Treasure'], 'en', true),
('cinema', 2, 'Who plays Captain Jack Sparrow''s nemesis Davy Jones?', 'Bill Nighy', ARRAY['Geoffrey Rush', 'Ian McShane', 'Javier Bardem'], 'en', true),
('cinema', 2, 'Which movie features the line "Here''s looking at you, kid"?', 'Casablanca', ARRAY['Gone with the Wind', 'The Maltese Falcon', 'Citizen Kane'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 3 (Medium)
-- =====================================================
('cinema', 3, 'Which Stanley Kubrick film is set during the Vietnam War?', 'Full Metal Jacket', ARRAY['Apocalypse Now', 'Platoon', 'The Deer Hunter'], 'en', true),
('cinema', 3, 'Who directed the French film Amélie?', 'Jean-Pierre Jeunet', ARRAY['Luc Besson', 'Michel Gondry', 'Jacques Audiard'], 'en', true),
('cinema', 3, 'Which actor appeared in Taxi Driver, Goodfellas, and Casino?', 'Robert De Niro', ARRAY['Al Pacino', 'Joe Pesci', 'Harvey Keitel'], 'en', true),
('cinema', 3, 'Which 1994 film tells the story of prisoners at Shawshank?', 'The Shawshank Redemption', ARRAY['The Green Mile', 'One Flew Over the Cuckoo''s Nest', 'The Silence of the Lambs'], 'en', true),
('cinema', 3, 'Who composed the music for Sergio Leone''s westerns?', 'Ennio Morricone', ARRAY['John Williams', 'Hans Zimmer', 'Bernard Herrmann'], 'en', true),
('cinema', 3, 'Which Japanese director created Seven Samurai?', 'Akira Kurosawa', ARRAY['Hayao Miyazaki', 'Takeshi Kitano', 'Yasujiro Ozu'], 'en', true),
('cinema', 3, 'In which film is "Rosebud" a central mystery?', 'Citizen Kane', ARRAY['Casablanca', 'The Maltese Falcon', 'Sunset Boulevard'], 'en', true),
('cinema', 3, 'Who directed Mulholland Drive?', 'David Lynch', ARRAY['David Cronenberg', 'David Fincher', 'Darren Aronofsky'], 'en', true),
('cinema', 3, 'Which 1982 science fiction film features replicants?', 'Blade Runner', ARRAY['Terminator', 'RoboCop', 'Total Recall'], 'en', true),
('cinema', 3, 'Which actress starred in The Piano and Moulin Rouge?', 'Nicole Kidman', ARRAY['Cate Blanchett', 'Kate Winslet', 'Julianne Moore'], 'en', true),
('cinema', 3, 'Which Mexican director made Birdman and The Revenant?', 'Alejandro González Iñárritu', ARRAY['Guillermo del Toro', 'Alfonso Cuarón', 'Robert Rodriguez'], 'en', true),
('cinema', 3, 'In which Wes Anderson film do we see the Grand Budapest Hotel?', 'The Grand Budapest Hotel', ARRAY['Moonrise Kingdom', 'The Royal Tenenbaums', 'The French Dispatch'], 'en', true),
('cinema', 3, 'Which Denis Villeneuve film is about aliens arriving on Earth?', 'Arrival', ARRAY['Dune', 'Blade Runner 2049', 'Sicario'], 'en', true),
('cinema', 3, 'What is the first rule of Fight Club?', 'You do not talk about Fight Club', ARRAY['Never give up', 'Always fight to the end', 'Respect your opponent'], 'en', true),
('cinema', 3, 'Who directed La La Land?', 'Damien Chazelle', ARRAY['Ryan Gosling', 'Tom Hooper', 'Barry Jenkins'], 'en', true),
('cinema', 3, 'In which movie does Brad Pitt play a character who ages backwards?', 'The Curious Case of Benjamin Button', ARRAY['Seven', 'Fight Club', 'Inglourious Basterds'], 'en', true),
('cinema', 3, 'Which 1995 French film is set in the Paris suburbs?', 'La Haine', ARRAY['Les Misérables', 'District 13', 'Divines'], 'en', true),
('cinema', 3, 'Who won the Oscar for Best Actor for his role in The Revenant?', 'Leonardo DiCaprio', ARRAY['Tom Hardy', 'Will Poulter', 'Domhnall Gleeson'], 'en', true),
('cinema', 3, 'Which film features the quote "You can''t handle the truth!"?', 'A Few Good Men', ARRAY['The Firm', 'Jerry Maguire', 'Born on the Fourth of July'], 'en', true),
('cinema', 3, 'Who directed the South Korean thriller Oldboy (2003)?', 'Park Chan-wook', ARRAY['Bong Joon-ho', 'Kim Jee-woon', 'Lee Chang-dong'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 4 (Hard)
-- =====================================================
('cinema', 4, 'Which 1927 Fritz Lang film is a masterpiece of German expressionism?', 'Metropolis', ARRAY['M', 'The Cabinet of Dr. Caligari', 'Nosferatu'], 'en', true),
('cinema', 4, 'Who directed the Russian film Battleship Potemkin?', 'Sergei Eisenstein', ARRAY['Andrei Tarkovsky', 'Dziga Vertov', 'Alexander Sokurov'], 'en', true),
('cinema', 4, 'What technique did D.W. Griffith pioneer for parallel editing?', 'Cross-cutting', ARRAY['Jump cut', 'Match cut', 'Fade out'], 'en', true),
('cinema', 4, 'In which Tarkovsky film does a "stalker" guide travelers to a mysterious zone?', 'Stalker', ARRAY['Solaris', 'Mirror', 'Andrei Rublev'], 'en', true),
('cinema', 4, 'Which French film movement of the 1950s-60s launched Godard and Truffaut?', 'The French New Wave', ARRAY['Neorealism', 'Dogme 95', 'Cinéma vérité'], 'en', true),
('cinema', 4, 'Who wrote the screenplay for Chinatown?', 'Robert Towne', ARRAY['William Goldman', 'Aaron Sorkin', 'Paddy Chayefsky'], 'en', true),
('cinema', 4, 'Which cinematographer worked with Kubrick on Barry Lyndon?', 'John Alcott', ARRAY['Roger Deakins', 'Vittorio Storaro', 'Gordon Willis'], 'en', true),
('cinema', 4, 'Which Michael Powell film was so controversial it ruined his career?', 'Peeping Tom', ARRAY['The Red Shoes', 'A Matter of Life and Death', 'Colonel Blimp'], 'en', true),
('cinema', 4, 'Who composed the score for Psycho?', 'Bernard Herrmann', ARRAY['John Williams', 'Max Steiner', 'Miklós Rózsa'], 'en', true),
('cinema', 4, 'Which 1960 Jean-Luc Godard film revolutionized cinematic language?', 'Breathless', ARRAY['Contempt', 'Pierrot le Fou', 'Alphaville'], 'en', true),
('cinema', 4, 'What technique did Orson Welles use in Citizen Kane with visible ceilings?', 'Deep focus', ARRAY['Long take', 'Low angle', 'Chiaroscuro'], 'en', true),
('cinema', 4, 'Which Danish director founded the Dogme 95 movement?', 'Lars von Trier', ARRAY['Thomas Vinterberg', 'Susanne Bier', 'Nicolas Winding Refn'], 'en', true),
('cinema', 4, 'In which Terrence Malick film is there philosophical voice-over about nature?', 'The Thin Red Line', ARRAY['Days of Heaven', 'The Tree of Life', 'Badlands'], 'en', true),
('cinema', 4, 'Who directed the Iranian film A Separation?', 'Asghar Farhadi', ARRAY['Abbas Kiarostami', 'Jafar Panahi', 'Mohsen Makhmalbaf'], 'en', true),
('cinema', 4, 'Which Wong Kar-wai film is famous for Christopher Doyle''s cinematography?', 'In the Mood for Love', ARRAY['Chungking Express', '2046', 'Happy Together'], 'en', true),
('cinema', 4, 'What term describes a shot where the camera follows a character without cuts?', 'Long take', ARRAY['Tracking shot', 'Steadicam', 'American shot'], 'en', true),
('cinema', 4, 'Who created the "bullet time" effect popularized in The Matrix?', 'John Gaeta', ARRAY['Dennis Muren', 'Phil Tippett', 'Stan Winston'], 'en', true),
('cinema', 4, 'Which silent Carl Theodor Dreyer film depicts the trial of Joan of Arc?', 'The Passion of Joan of Arc', ARRAY['Ordet', 'Vampyr', 'Day of Wrath'], 'en', true),
('cinema', 4, 'Which filmmaker is associated with the "cinema of cruelty" including Salò?', 'Pier Paolo Pasolini', ARRAY['Bernardo Bertolucci', 'Luchino Visconti', 'Federico Fellini'], 'en', true),
('cinema', 4, 'What award at Cannes recognizes the best directorial achievement?', 'Best Director', ARRAY['Palme d''Or', 'Grand Prix', 'Jury Prize'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - DIFFICULTY 5 (Expert)
-- =====================================================
('cinema', 5, 'Which film theorist developed the "Kuleshov effect"?', 'Lev Kuleshov', ARRAY['Sergei Eisenstein', 'Vsevolod Pudovkin', 'Dziga Vertov'], 'en', true),
('cinema', 5, 'Which 1929 Luis Buñuel film contains the famous eye-slicing scene?', 'Un Chien Andalou', ARRAY['L''Age d''Or', 'Viridiana', 'Belle de Jour'], 'en', true),
('cinema', 5, 'Which filmmaker theorized the "montage of attractions"?', 'Sergei Eisenstein', ARRAY['Lev Kuleshov', 'Dziga Vertov', 'Alexander Dovzhenko'], 'en', true),
('cinema', 5, 'Which Robert Bresson film uses non-professional actors he called "models"?', 'Pickpocket', ARRAY['A Man Escaped', 'Au Hasard Balthazar', 'L''Argent'], 'en', true),
('cinema', 5, 'Which French critic wrote "La Politique des auteurs" in Cahiers du Cinéma?', 'François Truffaut', ARRAY['André Bazin', 'Jacques Rivette', 'Eric Rohmer'], 'en', true),
('cinema', 5, 'Which Yasujiro Ozu film is considered one of the greatest films ever made?', 'Tokyo Story', ARRAY['Late Spring', 'An Autumn Afternoon', 'Late Autumn'], 'en', true),
('cinema', 5, 'Which concept did André Bazin defend regarding cinematic realism?', 'The ontology of the photographic image', ARRAY['Intellectual montage', 'Brechtian distancing', 'Poetic realism'], 'en', true),
('cinema', 5, 'Which 1962 Chris Marker film is composed almost entirely of still photographs?', 'La Jetée', ARRAY['Sans Soleil', 'A Grin Without a Cat', 'Level Five'], 'en', true),
('cinema', 5, 'Which director invented "Kino-Eye" (Kino-Glaz)?', 'Dziga Vertov', ARRAY['Sergei Eisenstein', 'Lev Kuleshov', 'Alexander Medvedkin'], 'en', true),
('cinema', 5, 'Which Michelangelo Antonioni film concludes his trilogy on incommunicability?', 'L''Eclisse', ARRAY['L''Avventura', 'La Notte', 'Red Desert'], 'en', true),
('cinema', 5, 'Which theorist developed the concept of "suture" in film analysis?', 'Jean-Pierre Oudart', ARRAY['Christian Metz', 'Roland Barthes', 'Jacques Lacan'], 'en', true),
('cinema', 5, 'Which Japanese director made In the Realm of the Senses in 1976?', 'Nagisa Oshima', ARRAY['Akira Kurosawa', 'Shohei Imamura', 'Kenji Mizoguchi'], 'en', true),
('cinema', 5, 'Which Italian movement of the 1940s advocated filming on real locations?', 'Neorealism', ARRAY['Futurism', 'Giallo', 'Commedia all''italiana'], 'en', true),
('cinema', 5, 'Which Alain Resnais film blends documentary and fiction about concentration camps?', 'Night and Fog', ARRAY['Hiroshima Mon Amour', 'Last Year at Marienbad', 'Muriel'], 'en', true),
('cinema', 5, 'What technical process enables the "deep focus" used by Gregg Toland?', 'Wide-angle lens and small aperture', ARRAY['Telephoto lens and wide aperture', 'Neutral density filter', 'Optical stabilizer'], 'en', true),
('cinema', 5, 'Which Hungarian director made the 7.5-hour film Sátántangó?', 'Béla Tarr', ARRAY['Miklós Jancsó', 'István Szabó', 'Márta Mészáros'], 'en', true),
('cinema', 5, 'Which 1961 Jean Rouch film pioneered cinéma vérité?', 'Chronicle of a Summer', ARRAY['I, a Negro', 'The Mad Masters', 'Jaguar'], 'en', true),
('cinema', 5, 'Which concept did Gilles Deleuze develop in his books on cinema?', 'The time-image and movement-image', ARRAY['Off-screen space', 'Diegesis', 'Subjective shot'], 'en', true),
('cinema', 5, 'Which Filipino director is known for contemplative films lasting several hours?', 'Lav Diaz', ARRAY['Brillante Mendoza', 'Ishmael Bernal', 'Lino Brocka'], 'en', true),
('cinema', 5, 'Which 1924 F.W. Murnau film was shot entirely without intertitles?', 'The Last Laugh', ARRAY['Nosferatu', 'Sunrise', 'Faust'], 'en', true);
