-- =====================================================
-- LITTERATURE / LITERATURE (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1 (Livres pour enfants, contes)
('litterature', 1, 'Qui a ecrit Harry Potter ?', 'J.K. Rowling', ARRAY['Stephen King', 'Roald Dahl', 'J.R.R. Tolkien'], 'fr', true),
('litterature', 1, 'Comment s''appelle le meilleur ami de Harry Potter ?', 'Ron Weasley', ARRAY['Draco Malfoy', 'Neville Longbottom', 'Cedric Diggory'], 'fr', true),
('litterature', 1, 'Dans quel conte trouve-t-on un loup qui mange une grand-mere ?', 'Le Petit Chaperon rouge', ARRAY['Les Trois Petits Cochons', 'Cendrillon', 'Blanche-Neige'], 'fr', true),
('litterature', 1, 'Combien y a-t-il de nains dans Blanche-Neige ?', '7', ARRAY['5', '6', '8'], 'fr', true),
('litterature', 1, 'Qui a ecrit Le Petit Prince ?', 'Antoine de Saint-Exupery', ARRAY['Victor Hugo', 'Jules Verne', 'Marcel Pagnol'], 'fr', true),
('litterature', 1, 'Quel animal est Baloo dans Le Livre de la Jungle ?', 'Un ours', ARRAY['Un tigre', 'Un singe', 'Un loup'], 'fr', true),
('litterature', 1, 'Comment s''appelle la fee dans Peter Pan ?', 'Clochette', ARRAY['Aurore', 'Flora', 'Viviane'], 'fr', true),
('litterature', 1, 'Quel personnage a un nez qui s''allonge quand il ment ?', 'Pinocchio', ARRAY['Geppetto', 'Jiminy Cricket', 'Le Petit Prince'], 'fr', true),
('litterature', 1, 'Dans quelle maison Harry Potter est-il reparti ?', 'Gryffondor', ARRAY['Serpentard', 'Serdaigle', 'Poufsouffle'], 'fr', true),
('litterature', 1, 'Qui a ecrit Les Fables ?', 'Jean de La Fontaine', ARRAY['Charles Perrault', 'Moliere', 'Victor Hugo'], 'fr', true),
('litterature', 1, 'Quel animal court apres le Petit Chaperon rouge ?', 'Le loup', ARRAY['L''ours', 'Le renard', 'Le lion'], 'fr', true),
('litterature', 1, 'Comment s''appelle le chat dans Alice au Pays des Merveilles ?', 'Le Chat du Cheshire', ARRAY['Le Chat Botte', 'Garfield', 'Felix'], 'fr', true),
('litterature', 1, 'Qui a ecrit les contes de Cendrillon et La Belle au bois dormant ?', 'Charles Perrault', ARRAY['Hans Christian Andersen', 'Les freres Grimm', 'Jean de La Fontaine'], 'fr', true),
('litterature', 1, 'Quel personnage vit dans un chateau avec une Bete ?', 'Belle', ARRAY['Cendrillon', 'Blanche-Neige', 'Raiponce'], 'fr', true),
('litterature', 1, 'Comment s''appelle l''elfe de maison ami de Harry Potter ?', 'Dobby', ARRAY['Kreacher', 'Winky', 'Hokey'], 'fr', true),
('litterature', 1, 'Qui a ecrit Le Chat Botte ?', 'Charles Perrault', ARRAY['Jean de La Fontaine', 'Les freres Grimm', 'Hans Christian Andersen'], 'fr', true),
('litterature', 1, 'Dans quel livre trouve-t-on le personnage de Mowgli ?', 'Le Livre de la Jungle', ARRAY['Tarzan', 'Le Roi Lion', 'Madagascar'], 'fr', true),
('litterature', 1, 'Quelle couleur est le chaperon de la petite fille du conte ?', 'Rouge', ARRAY['Bleu', 'Vert', 'Jaune'], 'fr', true),
('litterature', 1, 'Qui a ecrit La Petite Sirene ?', 'Hans Christian Andersen', ARRAY['Charles Perrault', 'Les freres Grimm', 'Victor Hugo'], 'fr', true),
('litterature', 1, 'Comment s''appelle le directeur de Poudlard ?', 'Albus Dumbledore', ARRAY['Severus Rogue', 'Minerva McGonagall', 'Rubeus Hagrid'], 'fr', true),

-- FRENCH - Niveau 2 (Litterature jeunesse, classiques accessibles)
('litterature', 2, 'Qui a ecrit Les Miserables ?', 'Victor Hugo', ARRAY['Emile Zola', 'Honore de Balzac', 'Gustave Flaubert'], 'fr', true),
('litterature', 2, 'Quel est le prenom du capitaine Nemo ?', 'Prince Dakkar', ARRAY['Jules', 'Phileas', 'Michel'], 'fr', true),
('litterature', 2, 'Qui a ecrit Vingt Mille Lieues sous les mers ?', 'Jules Verne', ARRAY['Alexandre Dumas', 'Victor Hugo', 'Honore de Balzac'], 'fr', true),
('litterature', 2, 'Dans quel roman trouve-t-on le personnage de Jean Valjean ?', 'Les Miserables', ARRAY['Le Comte de Monte-Cristo', 'Notre-Dame de Paris', 'Germinal'], 'fr', true),
('litterature', 2, 'Qui a ecrit Le Comte de Monte-Cristo ?', 'Alexandre Dumas', ARRAY['Victor Hugo', 'Jules Verne', 'Honore de Balzac'], 'fr', true),
('litterature', 2, 'Comment s''appelle le bossu dans le roman de Victor Hugo ?', 'Quasimodo', ARRAY['Frollo', 'Phoebus', 'Esmeralda'], 'fr', true),
('litterature', 2, 'Qui a ecrit Les Trois Mousquetaires ?', 'Alexandre Dumas', ARRAY['Victor Hugo', 'Honore de Balzac', 'Emile Zola'], 'fr', true),
('litterature', 2, 'Comment s''appellent les trois mousquetaires ?', 'Athos, Porthos, Aramis', ARRAY['Pierre, Paul, Jacques', 'Louis, Henri, Charles', 'Jean, Marc, Luc'], 'fr', true),
('litterature', 2, 'Quel auteur a cree Sherlock Holmes ?', 'Arthur Conan Doyle', ARRAY['Agatha Christie', 'Edgar Allan Poe', 'Charles Dickens'], 'fr', true),
('litterature', 2, 'Qui a ecrit Le Tour du monde en quatre-vingts jours ?', 'Jules Verne', ARRAY['Alexandre Dumas', 'H.G. Wells', 'Robert Louis Stevenson'], 'fr', true),
('litterature', 2, 'Comment s''appelle le compagnon de Sherlock Holmes ?', 'Docteur Watson', ARRAY['Inspecteur Lestrade', 'Mycroft Holmes', 'Professeur Moriarty'], 'fr', true),
('litterature', 2, 'Qui a ecrit L''Ile au tresor ?', 'Robert Louis Stevenson', ARRAY['Jules Verne', 'Daniel Defoe', 'Herman Melville'], 'fr', true),
('litterature', 2, 'Dans quel roman Phileas Fogg fait-il le tour du monde ?', 'Le Tour du monde en quatre-vingts jours', ARRAY['Vingt Mille Lieues sous les mers', 'Voyage au centre de la Terre', 'De la Terre a la Lune'], 'fr', true),
('litterature', 2, 'Qui a ecrit Robinson Crusoe ?', 'Daniel Defoe', ARRAY['Jonathan Swift', 'Robert Louis Stevenson', 'Herman Melville'], 'fr', true),
('litterature', 2, 'Quel auteur francais a ecrit Le Petit Nicolas ?', 'Rene Goscinny', ARRAY['Marcel Pagnol', 'Antoine de Saint-Exupery', 'Herge'], 'fr', true),
('litterature', 2, 'Comment s''appelle le chien des Baskerville ?', 'Le chien des Baskerville', ARRAY['Rex', 'Fang', 'Cerberus'], 'fr', true),
('litterature', 2, 'Qui a ecrit Les Voyages de Gulliver ?', 'Jonathan Swift', ARRAY['Daniel Defoe', 'Jules Verne', 'Robert Louis Stevenson'], 'fr', true),
('litterature', 2, 'Dans quel roman trouve-t-on le personnage d''Edmond Dantes ?', 'Le Comte de Monte-Cristo', ARRAY['Les Trois Mousquetaires', 'Les Miserables', 'Le Rouge et le Noir'], 'fr', true),
('litterature', 2, 'Qui a ecrit Charlie et la Chocolaterie ?', 'Roald Dahl', ARRAY['J.K. Rowling', 'Lewis Carroll', 'C.S. Lewis'], 'fr', true),
('litterature', 2, 'Comment s''appelle le proprietaire de la chocolaterie dans le roman de Roald Dahl ?', 'Willy Wonka', ARRAY['Charlie Bucket', 'Augustus Gloop', 'Mike Teavee'], 'fr', true),

-- FRENCH - Niveau 3 (Classiques francais, auteurs celebres)
('litterature', 3, 'Qui a ecrit Madame Bovary ?', 'Gustave Flaubert', ARRAY['Emile Zola', 'Honore de Balzac', 'Stendhal'], 'fr', true),
('litterature', 3, 'Quel mouvement litteraire Victor Hugo representait-il ?', 'Le romantisme', ARRAY['Le realisme', 'Le naturalisme', 'Le classicisme'], 'fr', true),
('litterature', 3, 'Qui a ecrit Germinal ?', 'Emile Zola', ARRAY['Victor Hugo', 'Gustave Flaubert', 'Guy de Maupassant'], 'fr', true),
('litterature', 3, 'Comment s''appelle le personnage principal de Madame Bovary ?', 'Emma Bovary', ARRAY['Anna Karenine', 'Eugenie Grandet', 'Nana'], 'fr', true),
('litterature', 3, 'Qui a ecrit Le Pere Goriot ?', 'Honore de Balzac', ARRAY['Emile Zola', 'Victor Hugo', 'Gustave Flaubert'], 'fr', true),
('litterature', 3, 'Quel est le titre du roman de Stendhal sur Julien Sorel ?', 'Le Rouge et le Noir', ARRAY['La Chartreuse de Parme', 'Lucien Leuwen', 'Armance'], 'fr', true),
('litterature', 3, 'Qui a ecrit L''Assommoir ?', 'Emile Zola', ARRAY['Guy de Maupassant', 'Honore de Balzac', 'Alphonse Daudet'], 'fr', true),
('litterature', 3, 'Quel auteur a cree la serie Les Rougon-Macquart ?', 'Emile Zola', ARRAY['Honore de Balzac', 'Victor Hugo', 'Gustave Flaubert'], 'fr', true),
('litterature', 3, 'Qui a ecrit Bel-Ami ?', 'Guy de Maupassant', ARRAY['Emile Zola', 'Gustave Flaubert', 'Honore de Balzac'], 'fr', true),
('litterature', 3, 'Comment s''appelle l''ensemble des romans d''Honore de Balzac ?', 'La Comedie humaine', ARRAY['Les Rougon-Macquart', 'A la recherche du temps perdu', 'Les Thibault'], 'fr', true),
('litterature', 3, 'Qui a ecrit Les Fleurs du mal ?', 'Charles Baudelaire', ARRAY['Paul Verlaine', 'Arthur Rimbaud', 'Stephane Mallarme'], 'fr', true),
('litterature', 3, 'Quel poete francais a ecrit Le Bateau ivre ?', 'Arthur Rimbaud', ARRAY['Charles Baudelaire', 'Paul Verlaine', 'Victor Hugo'], 'fr', true),
('litterature', 3, 'Qui a ecrit Cyrano de Bergerac ?', 'Edmond Rostand', ARRAY['Moliere', 'Jean Racine', 'Pierre Corneille'], 'fr', true),
('litterature', 3, 'Quel auteur francais a recu le prix Nobel en 1957 ?', 'Albert Camus', ARRAY['Jean-Paul Sartre', 'Andre Gide', 'Francois Mauriac'], 'fr', true),
('litterature', 3, 'Qui a ecrit L''Etranger ?', 'Albert Camus', ARRAY['Jean-Paul Sartre', 'Simone de Beauvoir', 'Andre Malraux'], 'fr', true),
('litterature', 3, 'Quel philosophe francais a refuse le prix Nobel de litterature ?', 'Jean-Paul Sartre', ARRAY['Albert Camus', 'Simone de Beauvoir', 'Michel Foucault'], 'fr', true),
('litterature', 3, 'Qui a ecrit La Nausee ?', 'Jean-Paul Sartre', ARRAY['Albert Camus', 'Simone de Beauvoir', 'Andre Gide'], 'fr', true),
('litterature', 3, 'Quel mouvement litteraire Emile Zola representait-il ?', 'Le naturalisme', ARRAY['Le romantisme', 'Le realisme', 'Le symbolisme'], 'fr', true),
('litterature', 3, 'Qui a ecrit Le Deuxieme Sexe ?', 'Simone de Beauvoir', ARRAY['Virginia Woolf', 'Marguerite Duras', 'Colette'], 'fr', true),
('litterature', 3, 'Quel auteur a ecrit A la recherche du temps perdu ?', 'Marcel Proust', ARRAY['Andre Gide', 'Paul Claudel', 'Romain Rolland'], 'fr', true),

-- FRENCH - Niveau 4 (Litterature classique, theatre, poesie)
('litterature', 4, 'Qui a ecrit Le Cid ?', 'Pierre Corneille', ARRAY['Jean Racine', 'Moliere', 'Edmond Rostand'], 'fr', true),
('litterature', 4, 'Quelle piece de Moliere met en scene un hypocrite religieux ?', 'Tartuffe', ARRAY['Le Misanthrope', 'L''Avare', 'Dom Juan'], 'fr', true),
('litterature', 4, 'Qui a ecrit Phedre ?', 'Jean Racine', ARRAY['Pierre Corneille', 'Moliere', 'Victor Hugo'], 'fr', true),
('litterature', 4, 'Quel auteur du XVIIe siecle a ecrit Les Essais ?', 'Michel de Montaigne', ARRAY['Blaise Pascal', 'Rene Descartes', 'Jean de La Bruyere'], 'fr', true),
('litterature', 4, 'Qui a ecrit Les Pensees ?', 'Blaise Pascal', ARRAY['Rene Descartes', 'Michel de Montaigne', 'Nicolas Malebranche'], 'fr', true),
('litterature', 4, 'Quel poete francais du XVIe siecle a fonde la Pleiade ?', 'Pierre de Ronsard', ARRAY['Joachim du Bellay', 'Francois Rabelais', 'Clement Marot'], 'fr', true),
('litterature', 4, 'Qui a ecrit Gargantua et Pantagruel ?', 'Francois Rabelais', ARRAY['Michel de Montaigne', 'Pierre de Ronsard', 'Joachim du Bellay'], 'fr', true),
('litterature', 4, 'Quel philosophe des Lumieres a ecrit Candide ?', 'Voltaire', ARRAY['Jean-Jacques Rousseau', 'Denis Diderot', 'Montesquieu'], 'fr', true),
('litterature', 4, 'Qui a ecrit Les Liaisons dangereuses ?', 'Choderlos de Laclos', ARRAY['Marquis de Sade', 'Marivaux', 'Beaumarchais'], 'fr', true),
('litterature', 4, 'Quel auteur a ecrit Le Mariage de Figaro ?', 'Beaumarchais', ARRAY['Moliere', 'Marivaux', 'Alfred de Musset'], 'fr', true),
('litterature', 4, 'Qui a ecrit Les Confessions ?', 'Jean-Jacques Rousseau', ARRAY['Voltaire', 'Denis Diderot', 'Montesquieu'], 'fr', true),
('litterature', 4, 'Quel auteur a dirige l''Encyclopedie ?', 'Denis Diderot', ARRAY['Voltaire', 'Jean-Jacques Rousseau', 'D''Alembert'], 'fr', true),
('litterature', 4, 'Qui a ecrit De l''esprit des lois ?', 'Montesquieu', ARRAY['Voltaire', 'Jean-Jacques Rousseau', 'Denis Diderot'], 'fr', true),
('litterature', 4, 'Quel poete symboliste a ecrit Un coup de des jamais n''abolira le hasard ?', 'Stephane Mallarme', ARRAY['Paul Verlaine', 'Arthur Rimbaud', 'Charles Baudelaire'], 'fr', true),
('litterature', 4, 'Qui a ecrit Alcools ?', 'Guillaume Apollinaire', ARRAY['Paul Eluard', 'Louis Aragon', 'Andre Breton'], 'fr', true),
('litterature', 4, 'Quel mouvement litteraire Andre Breton a-t-il fonde ?', 'Le surrealisme', ARRAY['Le dadaisme', 'L''expressionnisme', 'Le cubisme'], 'fr', true),
('litterature', 4, 'Qui a ecrit Nadja ?', 'Andre Breton', ARRAY['Louis Aragon', 'Paul Eluard', 'Robert Desnos'], 'fr', true),
('litterature', 4, 'Quel auteur francais a ecrit La Condition humaine ?', 'Andre Malraux', ARRAY['Albert Camus', 'Jean-Paul Sartre', 'Louis-Ferdinand Celine'], 'fr', true),
('litterature', 4, 'Qui a ecrit Voyage au bout de la nuit ?', 'Louis-Ferdinand Celine', ARRAY['Marcel Proust', 'Andre Gide', 'Andre Malraux'], 'fr', true),
('litterature', 4, 'Quel auteur a ecrit La Peste ?', 'Albert Camus', ARRAY['Jean-Paul Sartre', 'Andre Malraux', 'Simone de Beauvoir'], 'fr', true),

-- FRENCH - Niveau 5 (Theorie litteraire, litterature mondiale, Nobel)
('litterature', 5, 'Quel concept Aristote a-t-il developpe dans sa Poetique ?', 'La catharsis', ARRAY['L''ironie dramatique', 'Le monologue interieur', 'Le stream of consciousness'], 'fr', true),
('litterature', 5, 'Qui a ecrit Ulysse, roman moderniste majeur ?', 'James Joyce', ARRAY['Virginia Woolf', 'Marcel Proust', 'Franz Kafka'], 'fr', true),
('litterature', 5, 'Quel auteur russe a ecrit Guerre et Paix ?', 'Leon Tolstoi', ARRAY['Fiodor Dostoievski', 'Anton Tchekhov', 'Ivan Tourgueniev'], 'fr', true),
('litterature', 5, 'Qui a ecrit Les Freres Karamazov ?', 'Fiodor Dostoievski', ARRAY['Leon Tolstoi', 'Nikolai Gogol', 'Anton Tchekhov'], 'fr', true),
('litterature', 5, 'Quel auteur allemand a ecrit Faust ?', 'Johann Wolfgang von Goethe', ARRAY['Friedrich Schiller', 'Heinrich Heine', 'Thomas Mann'], 'fr', true),
('litterature', 5, 'Qui a ecrit La Metamorphose ?', 'Franz Kafka', ARRAY['Thomas Mann', 'Hermann Hesse', 'Robert Musil'], 'fr', true),
('litterature', 5, 'Quel auteur colombien a recu le prix Nobel en 1982 ?', 'Gabriel Garcia Marquez', ARRAY['Pablo Neruda', 'Octavio Paz', 'Mario Vargas Llosa'], 'fr', true),
('litterature', 5, 'Qui a ecrit Cent ans de solitude ?', 'Gabriel Garcia Marquez', ARRAY['Jorge Luis Borges', 'Julio Cortazar', 'Carlos Fuentes'], 'fr', true),
('litterature', 5, 'Quel mouvement litteraire est associe a Gabriel Garcia Marquez ?', 'Le realisme magique', ARRAY['Le surrealisme', 'Le naturalisme', 'L''existentialisme'], 'fr', true),
('litterature', 5, 'Qui a ecrit Mrs Dalloway ?', 'Virginia Woolf', ARRAY['James Joyce', 'D.H. Lawrence', 'E.M. Forster'], 'fr', true),
('litterature', 5, 'Quel auteur japonais a recu le prix Nobel en 1968 ?', 'Yasunari Kawabata', ARRAY['Yukio Mishima', 'Kenzaburo Oe', 'Haruki Murakami'], 'fr', true),
('litterature', 5, 'Qui a ecrit Le Bruit et la Fureur ?', 'William Faulkner', ARRAY['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck'], 'fr', true),
('litterature', 5, 'Quel auteur tcheque a ecrit L''Insoutenable Legerete de l''etre ?', 'Milan Kundera', ARRAY['Franz Kafka', 'Vaclav Havel', 'Bohumil Hrabal'], 'fr', true),
('litterature', 5, 'Qui a ecrit Le Nom de la rose ?', 'Umberto Eco', ARRAY['Italo Calvino', 'Alberto Moravia', 'Primo Levi'], 'fr', true),
('litterature', 5, 'Quel concept Roland Barthes a-t-il theorise dans son essai de 1967 ?', 'La mort de l''auteur', ARRAY['L''effet de reel', 'Le degre zero', 'Le plaisir du texte'], 'fr', true),
('litterature', 5, 'Qui a ecrit Le Proces ?', 'Franz Kafka', ARRAY['Albert Camus', 'Jean-Paul Sartre', 'Thomas Mann'], 'fr', true),
('litterature', 5, 'Quel auteur portugais a recu le prix Nobel en 1998 ?', 'Jose Saramago', ARRAY['Fernando Pessoa', 'Antonio Lobo Antunes', 'Miguel Torga'], 'fr', true),
('litterature', 5, 'Qui a ecrit Don Quichotte ?', 'Miguel de Cervantes', ARRAY['Lope de Vega', 'Calderon de la Barca', 'Francisco de Quevedo'], 'fr', true),
('litterature', 5, 'Quel auteur americain a ecrit Moby Dick ?', 'Herman Melville', ARRAY['Nathaniel Hawthorne', 'Edgar Allan Poe', 'Mark Twain'], 'fr', true),
('litterature', 5, 'Qui a ecrit La Divine Comedie ?', 'Dante Alighieri', ARRAY['Petrarque', 'Boccace', 'Machiavel'], 'fr', true),

-- ENGLISH - Level 1 (Children''s books, fairy tales)
('litterature', 1, 'Who wrote Harry Potter?', 'J.K. Rowling', ARRAY['Stephen King', 'Roald Dahl', 'J.R.R. Tolkien'], 'en', true),
('litterature', 1, 'What is the name of Harry Potter''s best friend?', 'Ron Weasley', ARRAY['Draco Malfoy', 'Neville Longbottom', 'Cedric Diggory'], 'en', true),
('litterature', 1, 'In which fairy tale does a wolf eat a grandmother?', 'Little Red Riding Hood', ARRAY['The Three Little Pigs', 'Cinderella', 'Snow White'], 'en', true),
('litterature', 1, 'How many dwarfs are there in Snow White?', '7', ARRAY['5', '6', '8'], 'en', true),
('litterature', 1, 'Who wrote The Little Prince?', 'Antoine de Saint-Exupery', ARRAY['Victor Hugo', 'Jules Verne', 'Marcel Pagnol'], 'en', true),
('litterature', 1, 'What animal is Baloo in The Jungle Book?', 'A bear', ARRAY['A tiger', 'A monkey', 'A wolf'], 'en', true),
('litterature', 1, 'What is the name of the fairy in Peter Pan?', 'Tinker Bell', ARRAY['Aurora', 'Flora', 'Viviane'], 'en', true),
('litterature', 1, 'Which character has a nose that grows when he lies?', 'Pinocchio', ARRAY['Geppetto', 'Jiminy Cricket', 'The Little Prince'], 'en', true),
('litterature', 1, 'Which house is Harry Potter sorted into?', 'Gryffindor', ARRAY['Slytherin', 'Ravenclaw', 'Hufflepuff'], 'en', true),
('litterature', 1, 'Who wrote The Chronicles of Narnia?', 'C.S. Lewis', ARRAY['J.R.R. Tolkien', 'Roald Dahl', 'Lewis Carroll'], 'en', true),
('litterature', 1, 'What animal chases Little Red Riding Hood?', 'The wolf', ARRAY['The bear', 'The fox', 'The lion'], 'en', true),
('litterature', 1, 'What is the name of the cat in Alice in Wonderland?', 'The Cheshire Cat', ARRAY['Puss in Boots', 'Garfield', 'Felix'], 'en', true),
('litterature', 1, 'Who wrote Cinderella and Sleeping Beauty?', 'Charles Perrault', ARRAY['Hans Christian Andersen', 'The Brothers Grimm', 'Jean de La Fontaine'], 'en', true),
('litterature', 1, 'Which character lives in a castle with a Beast?', 'Belle', ARRAY['Cinderella', 'Snow White', 'Rapunzel'], 'en', true),
('litterature', 1, 'What is the name of the house-elf who is Harry Potter''s friend?', 'Dobby', ARRAY['Kreacher', 'Winky', 'Hokey'], 'en', true),
('litterature', 1, 'Who wrote Charlie and the Chocolate Factory?', 'Roald Dahl', ARRAY['J.K. Rowling', 'Lewis Carroll', 'C.S. Lewis'], 'en', true),
('litterature', 1, 'In which book do we find the character Mowgli?', 'The Jungle Book', ARRAY['Tarzan', 'The Lion King', 'Madagascar'], 'en', true),
('litterature', 1, 'What color is the little girl''s hood in the fairy tale?', 'Red', ARRAY['Blue', 'Green', 'Yellow'], 'en', true),
('litterature', 1, 'Who wrote The Little Mermaid?', 'Hans Christian Andersen', ARRAY['Charles Perrault', 'The Brothers Grimm', 'Victor Hugo'], 'en', true),
('litterature', 1, 'What is the name of the headmaster of Hogwarts?', 'Albus Dumbledore', ARRAY['Severus Snape', 'Minerva McGonagall', 'Rubeus Hagrid'], 'en', true),

-- ENGLISH - Level 2 (Young adult literature, accessible classics)
('litterature', 2, 'Who wrote Oliver Twist?', 'Charles Dickens', ARRAY['Mark Twain', 'Jane Austen', 'Thomas Hardy'], 'en', true),
('litterature', 2, 'What is the name of Captain Nemo''s submarine?', 'Nautilus', ARRAY['Poseidon', 'Neptune', 'Triton'], 'en', true),
('litterature', 2, 'Who wrote Twenty Thousand Leagues Under the Sea?', 'Jules Verne', ARRAY['H.G. Wells', 'Robert Louis Stevenson', 'Herman Melville'], 'en', true),
('litterature', 2, 'In which novel do we find the character Oliver Twist?', 'Oliver Twist', ARRAY['David Copperfield', 'Great Expectations', 'A Tale of Two Cities'], 'en', true),
('litterature', 2, 'Who wrote The Adventures of Tom Sawyer?', 'Mark Twain', ARRAY['Charles Dickens', 'Robert Louis Stevenson', 'Jack London'], 'en', true),
('litterature', 2, 'What is the name of Tom Sawyer''s best friend?', 'Huckleberry Finn', ARRAY['Jim', 'Injun Joe', 'Sid'], 'en', true),
('litterature', 2, 'Who wrote Treasure Island?', 'Robert Louis Stevenson', ARRAY['Jules Verne', 'Daniel Defoe', 'Herman Melville'], 'en', true),
('litterature', 2, 'What is the name of the one-legged pirate in Treasure Island?', 'Long John Silver', ARRAY['Captain Flint', 'Billy Bones', 'Blind Pew'], 'en', true),
('litterature', 2, 'Who created Sherlock Holmes?', 'Arthur Conan Doyle', ARRAY['Agatha Christie', 'Edgar Allan Poe', 'Charles Dickens'], 'en', true),
('litterature', 2, 'Who wrote Around the World in Eighty Days?', 'Jules Verne', ARRAY['H.G. Wells', 'Robert Louis Stevenson', 'Daniel Defoe'], 'en', true),
('litterature', 2, 'What is the name of Sherlock Holmes''s companion?', 'Doctor Watson', ARRAY['Inspector Lestrade', 'Mycroft Holmes', 'Professor Moriarty'], 'en', true),
('litterature', 2, 'Who wrote Robinson Crusoe?', 'Daniel Defoe', ARRAY['Jonathan Swift', 'Robert Louis Stevenson', 'Herman Melville'], 'en', true),
('litterature', 2, 'In which novel does Phileas Fogg travel around the world?', 'Around the World in Eighty Days', ARRAY['Twenty Thousand Leagues Under the Sea', 'Journey to the Center of the Earth', 'From the Earth to the Moon'], 'en', true),
('litterature', 2, 'Who wrote Gulliver''s Travels?', 'Jonathan Swift', ARRAY['Daniel Defoe', 'Jules Verne', 'Robert Louis Stevenson'], 'en', true),
('litterature', 2, 'Who wrote The Wizard of Oz?', 'L. Frank Baum', ARRAY['Lewis Carroll', 'C.S. Lewis', 'J.M. Barrie'], 'en', true),
('litterature', 2, 'What is the name of the famous hound in Conan Doyle''s novel?', 'The Hound of the Baskervilles', ARRAY['Rex', 'Fang', 'Cerberus'], 'en', true),
('litterature', 2, 'Who wrote Alice''s Adventures in Wonderland?', 'Lewis Carroll', ARRAY['C.S. Lewis', 'J.M. Barrie', 'Roald Dahl'], 'en', true),
('litterature', 2, 'In which novel do we find the character of Sydney Carton?', 'A Tale of Two Cities', ARRAY['Great Expectations', 'Oliver Twist', 'David Copperfield'], 'en', true),
('litterature', 2, 'Who wrote The Secret Garden?', 'Frances Hodgson Burnett', ARRAY['Louisa May Alcott', 'Lucy Maud Montgomery', 'E. Nesbit'], 'en', true),
('litterature', 2, 'What is the name of the chocolate factory owner in Roald Dahl''s novel?', 'Willy Wonka', ARRAY['Charlie Bucket', 'Augustus Gloop', 'Mike Teavee'], 'en', true),

-- ENGLISH - Level 3 (Classic literature, famous authors)
('litterature', 3, 'Who wrote Pride and Prejudice?', 'Jane Austen', ARRAY['Charlotte Bronte', 'Emily Bronte', 'George Eliot'], 'en', true),
('litterature', 3, 'Which literary movement did William Wordsworth represent?', 'Romanticism', ARRAY['Realism', 'Naturalism', 'Classicism'], 'en', true),
('litterature', 3, 'Who wrote Jane Eyre?', 'Charlotte Bronte', ARRAY['Emily Bronte', 'Jane Austen', 'George Eliot'], 'en', true),
('litterature', 3, 'What is the name of the protagonist in Pride and Prejudice?', 'Elizabeth Bennet', ARRAY['Emma Woodhouse', 'Jane Eyre', 'Catherine Earnshaw'], 'en', true),
('litterature', 3, 'Who wrote Wuthering Heights?', 'Emily Bronte', ARRAY['Charlotte Bronte', 'Jane Austen', 'George Eliot'], 'en', true),
('litterature', 3, 'What is the title of Oscar Wilde''s famous novel?', 'The Picture of Dorian Gray', ARRAY['The Importance of Being Earnest', 'Lady Windermere''s Fan', 'An Ideal Husband'], 'en', true),
('litterature', 3, 'Who wrote Great Expectations?', 'Charles Dickens', ARRAY['Thomas Hardy', 'George Eliot', 'William Thackeray'], 'en', true),
('litterature', 3, 'Which author wrote the Sherlock Holmes stories?', 'Arthur Conan Doyle', ARRAY['Agatha Christie', 'Wilkie Collins', 'G.K. Chesterton'], 'en', true),
('litterature', 3, 'Who wrote Frankenstein?', 'Mary Shelley', ARRAY['Bram Stoker', 'Edgar Allan Poe', 'H.G. Wells'], 'en', true),
('litterature', 3, 'What is the name of the monster in Mary Shelley''s novel?', 'Frankenstein''s monster', ARRAY['Frankenstein', 'Victor', 'Adam'], 'en', true),
('litterature', 3, 'Who wrote Dracula?', 'Bram Stoker', ARRAY['Mary Shelley', 'Edgar Allan Poe', 'H.P. Lovecraft'], 'en', true),
('litterature', 3, 'Which American poet wrote The Raven?', 'Edgar Allan Poe', ARRAY['Walt Whitman', 'Emily Dickinson', 'Robert Frost'], 'en', true),
('litterature', 3, 'Who wrote The Great Gatsby?', 'F. Scott Fitzgerald', ARRAY['Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], 'en', true),
('litterature', 3, 'Which American author won the Nobel Prize in 1954?', 'Ernest Hemingway', ARRAY['William Faulkner', 'John Steinbeck', 'F. Scott Fitzgerald'], 'en', true),
('litterature', 3, 'Who wrote The Old Man and the Sea?', 'Ernest Hemingway', ARRAY['John Steinbeck', 'William Faulkner', 'F. Scott Fitzgerald'], 'en', true),
('litterature', 3, 'Which author wrote 1984?', 'George Orwell', ARRAY['Aldous Huxley', 'Ray Bradbury', 'H.G. Wells'], 'en', true),
('litterature', 3, 'Who wrote Brave New World?', 'Aldous Huxley', ARRAY['George Orwell', 'Ray Bradbury', 'H.G. Wells'], 'en', true),
('litterature', 3, 'Which literary movement did George Orwell represent?', 'Dystopian fiction', ARRAY['Romanticism', 'Realism', 'Modernism'], 'en', true),
('litterature', 3, 'Who wrote Animal Farm?', 'George Orwell', ARRAY['Aldous Huxley', 'Ray Bradbury', 'Arthur Koestler'], 'en', true),
('litterature', 3, 'Which author wrote To Kill a Mockingbird?', 'Harper Lee', ARRAY['John Steinbeck', 'William Faulkner', 'Truman Capote'], 'en', true),

-- ENGLISH - Level 4 (Classic literature, theater, poetry)
('litterature', 4, 'Who wrote Hamlet?', 'William Shakespeare', ARRAY['Christopher Marlowe', 'Ben Jonson', 'John Webster'], 'en', true),
('litterature', 4, 'Which Shakespeare play features the character Iago?', 'Othello', ARRAY['Hamlet', 'Macbeth', 'King Lear'], 'en', true),
('litterature', 4, 'Who wrote Paradise Lost?', 'John Milton', ARRAY['John Donne', 'Edmund Spenser', 'Geoffrey Chaucer'], 'en', true),
('litterature', 4, 'Which English author wrote The Canterbury Tales?', 'Geoffrey Chaucer', ARRAY['William Langland', 'John Gower', 'Thomas Malory'], 'en', true),
('litterature', 4, 'Who wrote Don Juan?', 'Lord Byron', ARRAY['Percy Bysshe Shelley', 'John Keats', 'William Wordsworth'], 'en', true),
('litterature', 4, 'Which Romantic poet wrote Ode to a Nightingale?', 'John Keats', ARRAY['Percy Bysshe Shelley', 'Lord Byron', 'William Wordsworth'], 'en', true),
('litterature', 4, 'Who wrote Middlemarch?', 'George Eliot', ARRAY['Thomas Hardy', 'Charles Dickens', 'Anthony Trollope'], 'en', true),
('litterature', 4, 'Which American author wrote Leaves of Grass?', 'Walt Whitman', ARRAY['Emily Dickinson', 'Robert Frost', 'Edgar Allan Poe'], 'en', true),
('litterature', 4, 'Who wrote Heart of Darkness?', 'Joseph Conrad', ARRAY['Rudyard Kipling', 'E.M. Forster', 'Graham Greene'], 'en', true),
('litterature', 4, 'Which author wrote A Passage to India?', 'E.M. Forster', ARRAY['Rudyard Kipling', 'Joseph Conrad', 'Graham Greene'], 'en', true),
('litterature', 4, 'Who wrote The Waste Land?', 'T.S. Eliot', ARRAY['Ezra Pound', 'W.B. Yeats', 'W.H. Auden'], 'en', true),
('litterature', 4, 'Which Irish poet won the Nobel Prize in 1923?', 'W.B. Yeats', ARRAY['James Joyce', 'Samuel Beckett', 'Oscar Wilde'], 'en', true),
('litterature', 4, 'Who wrote Mrs Dalloway?', 'Virginia Woolf', ARRAY['James Joyce', 'D.H. Lawrence', 'E.M. Forster'], 'en', true),
('litterature', 4, 'Which modernist technique did Virginia Woolf pioneer?', 'Stream of consciousness', ARRAY['Unreliable narrator', 'Magical realism', 'Epistolary novel'], 'en', true),
('litterature', 4, 'Who wrote Sons and Lovers?', 'D.H. Lawrence', ARRAY['Virginia Woolf', 'E.M. Forster', 'Joseph Conrad'], 'en', true),
('litterature', 4, 'Which American author wrote The Sound and the Fury?', 'William Faulkner', ARRAY['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck'], 'en', true),
('litterature', 4, 'Who wrote Waiting for Godot?', 'Samuel Beckett', ARRAY['Harold Pinter', 'Eugene Ionesco', 'Jean Genet'], 'en', true),
('litterature', 4, 'Which literary movement is Samuel Beckett associated with?', 'Theatre of the Absurd', ARRAY['Expressionism', 'Surrealism', 'Naturalism'], 'en', true),
('litterature', 4, 'Who wrote The Grapes of Wrath?', 'John Steinbeck', ARRAY['William Faulkner', 'Ernest Hemingway', 'F. Scott Fitzgerald'], 'en', true),
('litterature', 4, 'Which author wrote Lord of the Flies?', 'William Golding', ARRAY['George Orwell', 'Aldous Huxley', 'Anthony Burgess'], 'en', true),

-- ENGLISH - Level 5 (Literary theory, world literature, Nobel Prize)
('litterature', 5, 'Which concept did Aristotle develop in his Poetics?', 'Catharsis', ARRAY['Dramatic irony', 'Interior monologue', 'Stream of consciousness'], 'en', true),
('litterature', 5, 'Who wrote Ulysses, a major modernist novel?', 'James Joyce', ARRAY['Virginia Woolf', 'Marcel Proust', 'Franz Kafka'], 'en', true),
('litterature', 5, 'Which Russian author wrote War and Peace?', 'Leo Tolstoy', ARRAY['Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev'], 'en', true),
('litterature', 5, 'Who wrote The Brothers Karamazov?', 'Fyodor Dostoevsky', ARRAY['Leo Tolstoy', 'Nikolai Gogol', 'Anton Chekhov'], 'en', true),
('litterature', 5, 'Which German author wrote Faust?', 'Johann Wolfgang von Goethe', ARRAY['Friedrich Schiller', 'Heinrich Heine', 'Thomas Mann'], 'en', true),
('litterature', 5, 'Who wrote The Metamorphosis?', 'Franz Kafka', ARRAY['Thomas Mann', 'Hermann Hesse', 'Robert Musil'], 'en', true),
('litterature', 5, 'Which Colombian author won the Nobel Prize in 1982?', 'Gabriel Garcia Marquez', ARRAY['Pablo Neruda', 'Octavio Paz', 'Mario Vargas Llosa'], 'en', true),
('litterature', 5, 'Who wrote One Hundred Years of Solitude?', 'Gabriel Garcia Marquez', ARRAY['Jorge Luis Borges', 'Julio Cortazar', 'Carlos Fuentes'], 'en', true),
('litterature', 5, 'Which literary movement is associated with Gabriel Garcia Marquez?', 'Magical realism', ARRAY['Surrealism', 'Naturalism', 'Existentialism'], 'en', true),
('litterature', 5, 'Who wrote In Search of Lost Time?', 'Marcel Proust', ARRAY['Andre Gide', 'Paul Claudel', 'Romain Rolland'], 'en', true),
('litterature', 5, 'Which Japanese author won the Nobel Prize in 1968?', 'Yasunari Kawabata', ARRAY['Yukio Mishima', 'Kenzaburo Oe', 'Haruki Murakami'], 'en', true),
('litterature', 5, 'Who wrote The Trial?', 'Franz Kafka', ARRAY['Albert Camus', 'Jean-Paul Sartre', 'Thomas Mann'], 'en', true),
('litterature', 5, 'Which Czech author wrote The Unbearable Lightness of Being?', 'Milan Kundera', ARRAY['Franz Kafka', 'Vaclav Havel', 'Bohumil Hrabal'], 'en', true),
('litterature', 5, 'Who wrote The Name of the Rose?', 'Umberto Eco', ARRAY['Italo Calvino', 'Alberto Moravia', 'Primo Levi'], 'en', true),
('litterature', 5, 'Which concept did Roland Barthes theorize in his 1967 essay?', 'The death of the author', ARRAY['The reality effect', 'Writing degree zero', 'The pleasure of the text'], 'en', true),
('litterature', 5, 'Who wrote Crime and Punishment?', 'Fyodor Dostoevsky', ARRAY['Leo Tolstoy', 'Anton Chekhov', 'Ivan Turgenev'], 'en', true),
('litterature', 5, 'Which Portuguese author won the Nobel Prize in 1998?', 'Jose Saramago', ARRAY['Fernando Pessoa', 'Antonio Lobo Antunes', 'Miguel Torga'], 'en', true),
('litterature', 5, 'Who wrote Don Quixote?', 'Miguel de Cervantes', ARRAY['Lope de Vega', 'Calderon de la Barca', 'Francisco de Quevedo'], 'en', true),
('litterature', 5, 'Which American author wrote Moby Dick?', 'Herman Melville', ARRAY['Nathaniel Hawthorne', 'Edgar Allan Poe', 'Mark Twain'], 'en', true),
('litterature', 5, 'Who wrote The Divine Comedy?', 'Dante Alighieri', ARRAY['Petrarch', 'Boccaccio', 'Machiavelli'], 'en', true);
