-- =====================================================
-- BIGHEAD - 2200 New Questions (100 per category x 11 categories x 2 languages)
-- Distribution: ~20 questions per difficulty level (1-5)
-- =====================================================

-- =====================================================
-- CULTURE GÉNÉRALE / GENERAL KNOWLEDGE (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1
('culture_generale', 1, 'Quelle est la couleur du sang ?', 'Rouge', ARRAY['Bleu', 'Vert', 'Jaune'], 'fr', true),
('culture_generale', 1, 'Combien de lettres y a-t-il dans l''alphabet français ?', '26', ARRAY['24', '25', '27'], 'fr', true),
('culture_generale', 1, 'Quel animal produit du lait que nous buvons ?', 'Vache', ARRAY['Cochon', 'Poule', 'Mouton'], 'fr', true),
('culture_generale', 1, 'Quelle est la forme de la Terre ?', 'Ronde', ARRAY['Carrée', 'Plate', 'Triangulaire'], 'fr', true),
('culture_generale', 1, 'Combien de roues a une voiture ?', '4', ARRAY['2', '3', '6'], 'fr', true),
('culture_generale', 1, 'Quel fruit est jaune et courbé ?', 'Banane', ARRAY['Pomme', 'Orange', 'Fraise'], 'fr', true),
('culture_generale', 1, 'Quel est le jour après samedi ?', 'Dimanche', ARRAY['Lundi', 'Vendredi', 'Mardi'], 'fr', true),
('culture_generale', 1, 'Quelle est la couleur de l''herbe ?', 'Vert', ARRAY['Bleu', 'Rouge', 'Jaune'], 'fr', true),
('culture_generale', 1, 'Quel animal a une trompe ?', 'Éléphant', ARRAY['Lion', 'Girafe', 'Tigre'], 'fr', true),
('culture_generale', 1, 'Combien de saisons y a-t-il dans une année ?', '4', ARRAY['2', '3', '5'], 'fr', true),
('culture_generale', 1, 'Quel insecte produit du miel ?', 'Abeille', ARRAY['Mouche', 'Papillon', 'Fourmi'], 'fr', true),
('culture_generale', 1, 'Quelle est la couleur du soleil ?', 'Jaune', ARRAY['Bleu', 'Vert', 'Rouge'], 'fr', true),
('culture_generale', 1, 'Combien de minutes dans une heure ?', '60', ARRAY['30', '45', '100'], 'fr', true),
('culture_generale', 1, 'Quel animal a des rayures noires et blanches ?', 'Zèbre', ARRAY['Lion', 'Éléphant', 'Girafe'], 'fr', true),
('culture_generale', 1, 'Quel est le contraire de grand ?', 'Petit', ARRAY['Gros', 'Large', 'Haut'], 'fr', true),
('culture_generale', 1, 'Combien de côtés a un triangle ?', '3', ARRAY['4', '5', '6'], 'fr', true),
('culture_generale', 1, 'Quel animal vit dans l''eau et a des nageoires ?', 'Poisson', ARRAY['Oiseau', 'Chat', 'Chien'], 'fr', true),
('culture_generale', 1, 'Quelle boisson chaude est faite avec des feuilles ?', 'Thé', ARRAY['Café', 'Chocolat', 'Lait'], 'fr', true),
('culture_generale', 1, 'Combien font 5 + 5 ?', '10', ARRAY['8', '9', '11'], 'fr', true),
('culture_generale', 1, 'Quel oiseau ne peut pas voler et vit en Antarctique ?', 'Pingouin', ARRAY['Aigle', 'Moineau', 'Perroquet'], 'fr', true),

-- FRENCH - Niveau 2
('culture_generale', 2, 'Quel est le plus grand pays du monde ?', 'Russie', ARRAY['Canada', 'Chine', 'États-Unis'], 'fr', true),
('culture_generale', 2, 'Combien de planètes compte notre système solaire ?', '8', ARRAY['7', '9', '10'], 'fr', true),
('culture_generale', 2, 'Quelle est la capitale de l''Espagne ?', 'Madrid', ARRAY['Barcelone', 'Séville', 'Valence'], 'fr', true),
('culture_generale', 2, 'Quel métal est liquide à température ambiante ?', 'Mercure', ARRAY['Or', 'Argent', 'Fer'], 'fr', true),
('culture_generale', 2, 'Combien de jours a le mois de février en année bissextile ?', '29', ARRAY['28', '30', '31'], 'fr', true),
('culture_generale', 2, 'Quel pays a inventé la pizza ?', 'Italie', ARRAY['France', 'Espagne', 'Grèce'], 'fr', true),
('culture_generale', 2, 'Quelle est la plus grande île du monde ?', 'Groenland', ARRAY['Madagascar', 'Bornéo', 'Nouvelle-Guinée'], 'fr', true),
('culture_generale', 2, 'Combien d''étoiles y a-t-il sur le drapeau européen ?', '12', ARRAY['10', '15', '27'], 'fr', true),
('culture_generale', 2, 'Quel est l''animal le plus grand du monde ?', 'Baleine bleue', ARRAY['Éléphant', 'Girafe', 'Requin'], 'fr', true),
('culture_generale', 2, 'Quelle est la monnaie utilisée aux États-Unis ?', 'Dollar', ARRAY['Euro', 'Livre', 'Peso'], 'fr', true),
('culture_generale', 2, 'Quel est le plus haut bâtiment du monde ?', 'Burj Khalifa', ARRAY['Tour Eiffel', 'Empire State', 'Big Ben'], 'fr', true),
('culture_generale', 2, 'Combien de cordes a une guitare classique ?', '6', ARRAY['4', '5', '8'], 'fr', true),
('culture_generale', 2, 'Quel est le sport national du Japon ?', 'Sumo', ARRAY['Judo', 'Karaté', 'Kendo'], 'fr', true),
('culture_generale', 2, 'Quelle ville est surnommée la "Ville Lumière" ?', 'Paris', ARRAY['Rome', 'Londres', 'New York'], 'fr', true),
('culture_generale', 2, 'Quel pays a la plus grande population ?', 'Inde', ARRAY['Chine', 'États-Unis', 'Brésil'], 'fr', true),
('culture_generale', 2, 'Combien de touches a un piano standard ?', '88', ARRAY['76', '92', '100'], 'fr', true),
('culture_generale', 2, 'Quelle est la capitale du Canada ?', 'Ottawa', ARRAY['Toronto', 'Montréal', 'Vancouver'], 'fr', true),
('culture_generale', 2, 'Quel est le plus petit continent ?', 'Océanie', ARRAY['Europe', 'Antarctique', 'Amérique du Sud'], 'fr', true),
('culture_generale', 2, 'Quelle planète est connue comme la planète rouge ?', 'Mars', ARRAY['Jupiter', 'Vénus', 'Saturne'], 'fr', true),
('culture_generale', 2, 'Combien de joueurs dans une équipe de football ?', '11', ARRAY['9', '10', '12'], 'fr', true),

-- FRENCH - Niveau 3
('culture_generale', 3, 'Quel est le nom du plus grand désert chaud du monde ?', 'Sahara', ARRAY['Gobi', 'Kalahari', 'Atacama'], 'fr', true),
('culture_generale', 3, 'Combien de pays composent le Royaume-Uni ?', '4', ARRAY['2', '3', '5'], 'fr', true),
('culture_generale', 3, 'Quelle est la capitale de la Turquie ?', 'Ankara', ARRAY['Istanbul', 'Izmir', 'Antalya'], 'fr', true),
('culture_generale', 3, 'Quel gaz respirons-nous principalement ?', 'Azote', ARRAY['Oxygène', 'CO2', 'Hydrogène'], 'fr', true),
('culture_generale', 3, 'En quelle année a été créé Internet ?', '1969', ARRAY['1975', '1983', '1991'], 'fr', true),
('culture_generale', 3, 'Quelle est la plus longue rivière d''Europe ?', 'Volga', ARRAY['Danube', 'Rhin', 'Loire'], 'fr', true),
('culture_generale', 3, 'Combien de vertèbres a la colonne vertébrale humaine ?', '33', ARRAY['26', '29', '36'], 'fr', true),
('culture_generale', 3, 'Quel pays a trois capitales ?', 'Afrique du Sud', ARRAY['Suisse', 'Pays-Bas', 'Belgique'], 'fr', true),
('culture_generale', 3, 'Quelle est la distance d''un marathon en km ?', '42,195', ARRAY['40', '41,5', '45'], 'fr', true),
('culture_generale', 3, 'Quel organe produit l''insuline ?', 'Pancréas', ARRAY['Foie', 'Rein', 'Estomac'], 'fr', true),
('culture_generale', 3, 'Combien de pays sont membres permanents du Conseil de sécurité de l''ONU ?', '5', ARRAY['6', '7', '10'], 'fr', true),
('culture_generale', 3, 'Quelle est la température d''ébullition de l''eau en Celsius ?', '100', ARRAY['90', '110', '120'], 'fr', true),
('culture_generale', 3, 'Quel pays a le plus de Prix Nobel ?', 'États-Unis', ARRAY['Royaume-Uni', 'Allemagne', 'France'], 'fr', true),
('culture_generale', 3, 'Combien d''os a le corps humain adulte ?', '206', ARRAY['196', '216', '226'], 'fr', true),
('culture_generale', 3, 'Quelle est la plus ancienne civilisation connue ?', 'Sumérienne', ARRAY['Égyptienne', 'Chinoise', 'Grecque'], 'fr', true),
('culture_generale', 3, 'Quel est le pH de l''eau pure ?', '7', ARRAY['0', '5', '14'], 'fr', true),
('culture_generale', 3, 'Combien de pays partagent une frontière avec la France métropolitaine ?', '8', ARRAY['5', '6', '7'], 'fr', true),
('culture_generale', 3, 'Quelle hormone régule le sommeil ?', 'Mélatonine', ARRAY['Adrénaline', 'Dopamine', 'Cortisol'], 'fr', true),
('culture_generale', 3, 'Quel est le plus grand lac d''Afrique ?', 'Victoria', ARRAY['Tanganyika', 'Malawi', 'Tchad'], 'fr', true),
('culture_generale', 3, 'Combien de paires de côtes a l''être humain ?', '12', ARRAY['10', '11', '14'], 'fr', true),

-- FRENCH - Niveau 4
('culture_generale', 4, 'Quelle est la vitesse de la lumière en km/s ?', '300 000', ARRAY['150 000', '200 000', '400 000'], 'fr', true),
('culture_generale', 4, 'Combien de satellites naturels a Jupiter ?', '95', ARRAY['67', '79', '82'], 'fr', true),
('culture_generale', 4, 'Quel est le nom de la plus grande lune de Saturne ?', 'Titan', ARRAY['Europe', 'Ganymède', 'Callisto'], 'fr', true),
('culture_generale', 4, 'En quelle année a été fondée l''OTAN ?', '1949', ARRAY['1945', '1951', '1955'], 'fr', true),
('culture_generale', 4, 'Quelle est la densité de l''eau en kg/m³ ?', '1000', ARRAY['500', '750', '1250'], 'fr', true),
('culture_generale', 4, 'Combien de chromosomes a une cellule humaine ?', '46', ARRAY['42', '44', '48'], 'fr', true),
('culture_generale', 4, 'Quel est le plus ancien empire continu de l''histoire ?', 'Empire du Japon', ARRAY['Empire romain', 'Empire chinois', 'Empire ottoman'], 'fr', true),
('culture_generale', 4, 'Quelle est la formule chimique du glucose ?', 'C6H12O6', ARRAY['C12H22O11', 'C2H5OH', 'CH4'], 'fr', true),
('culture_generale', 4, 'Combien de langues officielles a l''Inde ?', '22', ARRAY['15', '18', '25'], 'fr', true),
('culture_generale', 4, 'Quel est le point le plus bas sur Terre ?', 'Mer Morte', ARRAY['Vallée de la Mort', 'Lac Assal', 'Dépression de Qattara'], 'fr', true),
('culture_generale', 4, 'Quelle est la durée d''une année sur Mars en jours terrestres ?', '687', ARRAY['365', '500', '780'], 'fr', true),
('culture_generale', 4, 'Combien de muscles utilisons-nous pour sourire ?', '17', ARRAY['12', '23', '36'], 'fr', true),
('culture_generale', 4, 'Quel élément chimique a pour symbole W ?', 'Tungstène', ARRAY['Wolfram', 'Uranium', 'Zinc'], 'fr', true),
('culture_generale', 4, 'Quelle est la capitale du Kazakhstan ?', 'Astana', ARRAY['Almaty', 'Tachkent', 'Bichkek'], 'fr', true),
('culture_generale', 4, 'Combien de temps met le sang pour faire un tour complet du corps ?', '1 minute', ARRAY['30 secondes', '2 minutes', '5 minutes'], 'fr', true),
('culture_generale', 4, 'Quel est le plus grand organe du corps humain ?', 'Peau', ARRAY['Foie', 'Intestin', 'Poumons'], 'fr', true),
('culture_generale', 4, 'Quelle montagne est la plus haute d''Europe ?', 'Elbrouz', ARRAY['Mont Blanc', 'Cervin', 'Mont Rose'], 'fr', true),
('culture_generale', 4, 'Combien de pays n''ont pas de côte ?', '44', ARRAY['35', '40', '50'], 'fr', true),
('culture_generale', 4, 'Quel est le seul pays traversé par l''équateur et le tropique du Capricorne ?', 'Brésil', ARRAY['Indonésie', 'Kenya', 'Colombie'], 'fr', true),
('culture_generale', 4, 'Quelle est la profondeur maximale de la fosse des Mariannes ?', '11 034 m', ARRAY['8 000 m', '9 500 m', '12 500 m'], 'fr', true),

-- FRENCH - Niveau 5
('culture_generale', 5, 'Quel est le nombre d''Avogadro ?', '6,022 × 10²³', ARRAY['3,14 × 10²³', '9,8 × 10²³', '1,6 × 10²³'], 'fr', true),
('culture_generale', 5, 'En quelle année a été signé le traité de Westphalie ?', '1648', ARRAY['1618', '1688', '1713'], 'fr', true),
('culture_generale', 5, 'Quel est le plus grand producteur mondial de café ?', 'Brésil', ARRAY['Colombie', 'Vietnam', 'Éthiopie'], 'fr', true),
('culture_generale', 5, 'Combien de bits dans un octet ?', '8', ARRAY['4', '16', '32'], 'fr', true),
('culture_generale', 5, 'Quelle est la constante de Planck ?', '6,63 × 10⁻³⁴ J·s', ARRAY['3,14 × 10⁻³⁴ J·s', '9,8 × 10⁻³⁴ J·s', '1,6 × 10⁻³⁴ J·s'], 'fr', true),
('culture_generale', 5, 'Quel pays a le plus haut PIB par habitant ?', 'Luxembourg', ARRAY['Suisse', 'Norvège', 'Qatar'], 'fr', true),
('culture_generale', 5, 'Combien de millisecondes dans une seconde ?', '1000', ARRAY['100', '500', '10000'], 'fr', true),
('culture_generale', 5, 'Quel est le nom de la théorie unissant mécanique quantique et relativité ?', 'Théorie des cordes', ARRAY['Théorie du tout', 'Mécanique quantique', 'Relativité générale'], 'fr', true),
('culture_generale', 5, 'Quelle est la capitale du Bhoutan ?', 'Thimphou', ARRAY['Katmandou', 'Dacca', 'Colombo'], 'fr', true),
('culture_generale', 5, 'Combien d''isotopes stables a l''hydrogène ?', '2', ARRAY['1', '3', '4'], 'fr', true),
('culture_generale', 5, 'Quel est le plus grand biome terrestre ?', 'Taïga', ARRAY['Forêt tropicale', 'Désert', 'Savane'], 'fr', true),
('culture_generale', 5, 'Quelle est la fréquence du courant électrique en Europe ?', '50 Hz', ARRAY['60 Hz', '40 Hz', '100 Hz'], 'fr', true),
('culture_generale', 5, 'Combien de faces a un icosaèdre ?', '20', ARRAY['12', '16', '24'], 'fr', true),
('culture_generale', 5, 'Quel est le nom du premier antibiotique découvert ?', 'Pénicilline', ARRAY['Streptomycine', 'Tétracycline', 'Amoxicilline'], 'fr', true),
('culture_generale', 5, 'Quelle est la température du zéro absolu en Celsius ?', '-273,15', ARRAY['-300', '-250', '-200'], 'fr', true),
('culture_generale', 5, 'Combien de pays ont l''anglais comme langue officielle ?', '67', ARRAY['45', '54', '75'], 'fr', true),
('culture_generale', 5, 'Quel est le plus petit pays d''Afrique ?', 'Seychelles', ARRAY['Gambie', 'Cap-Vert', 'Sao Tomé'], 'fr', true),
('culture_generale', 5, 'Quelle est la masse du Soleil par rapport à la Terre ?', '333 000 fois', ARRAY['100 000 fois', '500 000 fois', '1 million de fois'], 'fr', true),
('culture_generale', 5, 'Combien de pays ont le français comme langue officielle ?', '29', ARRAY['21', '25', '35'], 'fr', true),
('culture_generale', 5, 'Quel est le nom de la plus grande structure connue de l''univers ?', 'Grande Muraille d''Hercule', ARRAY['Superamas Laniakea', 'Filament de Perseus', 'Vide du Bouvier'], 'fr', true),

-- ENGLISH - Level 1
('culture_generale', 1, 'What color is blood?', 'Red', ARRAY['Blue', 'Green', 'Yellow'], 'en', true),
('culture_generale', 1, 'How many letters are in the English alphabet?', '26', ARRAY['24', '25', '27'], 'en', true),
('culture_generale', 1, 'What animal produces milk that we drink?', 'Cow', ARRAY['Pig', 'Chicken', 'Sheep'], 'en', true),
('culture_generale', 1, 'What is the shape of Earth?', 'Round', ARRAY['Square', 'Flat', 'Triangular'], 'en', true),
('culture_generale', 1, 'How many wheels does a car have?', '4', ARRAY['2', '3', '6'], 'en', true),
('culture_generale', 1, 'What fruit is yellow and curved?', 'Banana', ARRAY['Apple', 'Orange', 'Strawberry'], 'en', true),
('culture_generale', 1, 'What day comes after Saturday?', 'Sunday', ARRAY['Monday', 'Friday', 'Tuesday'], 'en', true),
('culture_generale', 1, 'What color is grass?', 'Green', ARRAY['Blue', 'Red', 'Yellow'], 'en', true),
('culture_generale', 1, 'What animal has a trunk?', 'Elephant', ARRAY['Lion', 'Giraffe', 'Tiger'], 'en', true),
('culture_generale', 1, 'How many seasons are in a year?', '4', ARRAY['2', '3', '5'], 'en', true),
('culture_generale', 1, 'What insect produces honey?', 'Bee', ARRAY['Fly', 'Butterfly', 'Ant'], 'en', true),
('culture_generale', 1, 'What color is the sun?', 'Yellow', ARRAY['Blue', 'Green', 'Red'], 'en', true),
('culture_generale', 1, 'How many minutes in an hour?', '60', ARRAY['30', '45', '100'], 'en', true),
('culture_generale', 1, 'What animal has black and white stripes?', 'Zebra', ARRAY['Lion', 'Elephant', 'Giraffe'], 'en', true),
('culture_generale', 1, 'What is the opposite of big?', 'Small', ARRAY['Fat', 'Wide', 'Tall'], 'en', true),
('culture_generale', 1, 'How many sides does a triangle have?', '3', ARRAY['4', '5', '6'], 'en', true),
('culture_generale', 1, 'What animal lives in water and has fins?', 'Fish', ARRAY['Bird', 'Cat', 'Dog'], 'en', true),
('culture_generale', 1, 'What hot drink is made from leaves?', 'Tea', ARRAY['Coffee', 'Chocolate', 'Milk'], 'en', true),
('culture_generale', 1, 'What is 5 + 5?', '10', ARRAY['8', '9', '11'], 'en', true),
('culture_generale', 1, 'What bird cannot fly and lives in Antarctica?', 'Penguin', ARRAY['Eagle', 'Sparrow', 'Parrot'], 'en', true),

-- ENGLISH - Level 2
('culture_generale', 2, 'What is the largest country in the world?', 'Russia', ARRAY['Canada', 'China', 'United States'], 'en', true),
('culture_generale', 2, 'How many planets are in our solar system?', '8', ARRAY['7', '9', '10'], 'en', true),
('culture_generale', 2, 'What is the capital of Spain?', 'Madrid', ARRAY['Barcelona', 'Seville', 'Valencia'], 'en', true),
('culture_generale', 2, 'What metal is liquid at room temperature?', 'Mercury', ARRAY['Gold', 'Silver', 'Iron'], 'en', true),
('culture_generale', 2, 'How many days does February have in a leap year?', '29', ARRAY['28', '30', '31'], 'en', true),
('culture_generale', 2, 'Which country invented pizza?', 'Italy', ARRAY['France', 'Spain', 'Greece'], 'en', true),
('culture_generale', 2, 'What is the largest island in the world?', 'Greenland', ARRAY['Madagascar', 'Borneo', 'New Guinea'], 'en', true),
('culture_generale', 2, 'How many stars are on the European flag?', '12', ARRAY['10', '15', '27'], 'en', true),
('culture_generale', 2, 'What is the largest animal in the world?', 'Blue whale', ARRAY['Elephant', 'Giraffe', 'Shark'], 'en', true),
('culture_generale', 2, 'What currency is used in the United States?', 'Dollar', ARRAY['Euro', 'Pound', 'Peso'], 'en', true),
('culture_generale', 2, 'What is the tallest building in the world?', 'Burj Khalifa', ARRAY['Eiffel Tower', 'Empire State', 'Big Ben'], 'en', true),
('culture_generale', 2, 'How many strings does a classical guitar have?', '6', ARRAY['4', '5', '8'], 'en', true),
('culture_generale', 2, 'What is the national sport of Japan?', 'Sumo', ARRAY['Judo', 'Karate', 'Kendo'], 'en', true),
('culture_generale', 2, 'Which city is called the "City of Light"?', 'Paris', ARRAY['Rome', 'London', 'New York'], 'en', true),
('culture_generale', 2, 'Which country has the largest population?', 'India', ARRAY['China', 'United States', 'Brazil'], 'en', true),
('culture_generale', 2, 'How many keys does a standard piano have?', '88', ARRAY['76', '92', '100'], 'en', true),
('culture_generale', 2, 'What is the capital of Canada?', 'Ottawa', ARRAY['Toronto', 'Montreal', 'Vancouver'], 'en', true),
('culture_generale', 2, 'What is the smallest continent?', 'Australia/Oceania', ARRAY['Europe', 'Antarctica', 'South America'], 'en', true),
('culture_generale', 2, 'Which planet is known as the red planet?', 'Mars', ARRAY['Jupiter', 'Venus', 'Saturn'], 'en', true),
('culture_generale', 2, 'How many players are on a soccer team?', '11', ARRAY['9', '10', '12'], 'en', true),

-- ENGLISH - Level 3
('culture_generale', 3, 'What is the name of the largest hot desert in the world?', 'Sahara', ARRAY['Gobi', 'Kalahari', 'Atacama'], 'en', true),
('culture_generale', 3, 'How many countries make up the United Kingdom?', '4', ARRAY['2', '3', '5'], 'en', true),
('culture_generale', 3, 'What is the capital of Turkey?', 'Ankara', ARRAY['Istanbul', 'Izmir', 'Antalya'], 'en', true),
('culture_generale', 3, 'What gas do we primarily breathe?', 'Nitrogen', ARRAY['Oxygen', 'CO2', 'Hydrogen'], 'en', true),
('culture_generale', 3, 'In what year was the Internet created?', '1969', ARRAY['1975', '1983', '1991'], 'en', true),
('culture_generale', 3, 'What is the longest river in Europe?', 'Volga', ARRAY['Danube', 'Rhine', 'Loire'], 'en', true),
('culture_generale', 3, 'How many vertebrae does the human spine have?', '33', ARRAY['26', '29', '36'], 'en', true),
('culture_generale', 3, 'Which country has three capitals?', 'South Africa', ARRAY['Switzerland', 'Netherlands', 'Belgium'], 'en', true),
('culture_generale', 3, 'What is the distance of a marathon in km?', '42.195', ARRAY['40', '41.5', '45'], 'en', true),
('culture_generale', 3, 'Which organ produces insulin?', 'Pancreas', ARRAY['Liver', 'Kidney', 'Stomach'], 'en', true),
('culture_generale', 3, 'How many countries are permanent members of the UN Security Council?', '5', ARRAY['6', '7', '10'], 'en', true),
('culture_generale', 3, 'What is the boiling point of water in Celsius?', '100', ARRAY['90', '110', '120'], 'en', true),
('culture_generale', 3, 'Which country has the most Nobel Prizes?', 'United States', ARRAY['United Kingdom', 'Germany', 'France'], 'en', true),
('culture_generale', 3, 'How many bones does the adult human body have?', '206', ARRAY['196', '216', '226'], 'en', true),
('culture_generale', 3, 'What is the oldest known civilization?', 'Sumerian', ARRAY['Egyptian', 'Chinese', 'Greek'], 'en', true),
('culture_generale', 3, 'What is the pH of pure water?', '7', ARRAY['0', '5', '14'], 'en', true),
('culture_generale', 3, 'How many countries share a border with metropolitan France?', '8', ARRAY['5', '6', '7'], 'en', true),
('culture_generale', 3, 'Which hormone regulates sleep?', 'Melatonin', ARRAY['Adrenaline', 'Dopamine', 'Cortisol'], 'en', true),
('culture_generale', 3, 'What is the largest lake in Africa?', 'Victoria', ARRAY['Tanganyika', 'Malawi', 'Chad'], 'en', true),
('culture_generale', 3, 'How many pairs of ribs does a human have?', '12', ARRAY['10', '11', '14'], 'en', true),

-- ENGLISH - Level 4
('culture_generale', 4, 'What is the speed of light in km/s?', '300,000', ARRAY['150,000', '200,000', '400,000'], 'en', true),
('culture_generale', 4, 'How many natural satellites does Jupiter have?', '95', ARRAY['67', '79', '82'], 'en', true),
('culture_generale', 4, 'What is the name of Saturn''s largest moon?', 'Titan', ARRAY['Europa', 'Ganymede', 'Callisto'], 'en', true),
('culture_generale', 4, 'In what year was NATO founded?', '1949', ARRAY['1945', '1951', '1955'], 'en', true),
('culture_generale', 4, 'What is the density of water in kg/m³?', '1000', ARRAY['500', '750', '1250'], 'en', true),
('culture_generale', 4, 'How many chromosomes does a human cell have?', '46', ARRAY['42', '44', '48'], 'en', true),
('culture_generale', 4, 'What is the oldest continuous empire in history?', 'Empire of Japan', ARRAY['Roman Empire', 'Chinese Empire', 'Ottoman Empire'], 'en', true),
('culture_generale', 4, 'What is the chemical formula for glucose?', 'C6H12O6', ARRAY['C12H22O11', 'C2H5OH', 'CH4'], 'en', true),
('culture_generale', 4, 'How many official languages does India have?', '22', ARRAY['15', '18', '25'], 'en', true),
('culture_generale', 4, 'What is the lowest point on Earth?', 'Dead Sea', ARRAY['Death Valley', 'Lake Assal', 'Qattara Depression'], 'en', true),
('culture_generale', 4, 'How long is a year on Mars in Earth days?', '687', ARRAY['365', '500', '780'], 'en', true),
('culture_generale', 4, 'How many muscles do we use to smile?', '17', ARRAY['12', '23', '36'], 'en', true),
('culture_generale', 4, 'What chemical element has the symbol W?', 'Tungsten', ARRAY['Wolfram', 'Uranium', 'Zinc'], 'en', true),
('culture_generale', 4, 'What is the capital of Kazakhstan?', 'Astana', ARRAY['Almaty', 'Tashkent', 'Bishkek'], 'en', true),
('culture_generale', 4, 'How long does it take for blood to make one complete circuit?', '1 minute', ARRAY['30 seconds', '2 minutes', '5 minutes'], 'en', true),
('culture_generale', 4, 'What is the largest organ in the human body?', 'Skin', ARRAY['Liver', 'Intestine', 'Lungs'], 'en', true),
('culture_generale', 4, 'What is the highest mountain in Europe?', 'Mount Elbrus', ARRAY['Mont Blanc', 'Matterhorn', 'Monte Rosa'], 'en', true),
('culture_generale', 4, 'How many countries have no coastline?', '44', ARRAY['35', '40', '50'], 'en', true),
('culture_generale', 4, 'What is the only country crossed by both the equator and Tropic of Capricorn?', 'Brazil', ARRAY['Indonesia', 'Kenya', 'Colombia'], 'en', true),
('culture_generale', 4, 'What is the maximum depth of the Mariana Trench?', '11,034 m', ARRAY['8,000 m', '9,500 m', '12,500 m'], 'en', true),

-- ENGLISH - Level 5
('culture_generale', 5, 'What is Avogadro''s number?', '6.022 × 10²³', ARRAY['3.14 × 10²³', '9.8 × 10²³', '1.6 × 10²³'], 'en', true),
('culture_generale', 5, 'In what year was the Treaty of Westphalia signed?', '1648', ARRAY['1618', '1688', '1713'], 'en', true),
('culture_generale', 5, 'What is the world''s largest producer of coffee?', 'Brazil', ARRAY['Colombia', 'Vietnam', 'Ethiopia'], 'en', true),
('culture_generale', 5, 'How many bits in a byte?', '8', ARRAY['4', '16', '32'], 'en', true),
('culture_generale', 5, 'What is Planck''s constant?', '6.63 × 10⁻³⁴ J·s', ARRAY['3.14 × 10⁻³⁴ J·s', '9.8 × 10⁻³⁴ J·s', '1.6 × 10⁻³⁴ J·s'], 'en', true),
('culture_generale', 5, 'Which country has the highest GDP per capita?', 'Luxembourg', ARRAY['Switzerland', 'Norway', 'Qatar'], 'en', true),
('culture_generale', 5, 'How many milliseconds in a second?', '1000', ARRAY['100', '500', '10000'], 'en', true),
('culture_generale', 5, 'What theory attempts to unite quantum mechanics and relativity?', 'String theory', ARRAY['Theory of everything', 'Quantum mechanics', 'General relativity'], 'en', true),
('culture_generale', 5, 'What is the capital of Bhutan?', 'Thimphu', ARRAY['Kathmandu', 'Dhaka', 'Colombo'], 'en', true),
('culture_generale', 5, 'How many stable isotopes does hydrogen have?', '2', ARRAY['1', '3', '4'], 'en', true),
('culture_generale', 5, 'What is the largest terrestrial biome?', 'Taiga', ARRAY['Tropical rainforest', 'Desert', 'Savanna'], 'en', true),
('culture_generale', 5, 'What is the frequency of electrical current in Europe?', '50 Hz', ARRAY['60 Hz', '40 Hz', '100 Hz'], 'en', true),
('culture_generale', 5, 'How many faces does an icosahedron have?', '20', ARRAY['12', '16', '24'], 'en', true),
('culture_generale', 5, 'What was the first antibiotic discovered?', 'Penicillin', ARRAY['Streptomycin', 'Tetracycline', 'Amoxicillin'], 'en', true),
('culture_generale', 5, 'What is absolute zero in Celsius?', '-273.15', ARRAY['-300', '-250', '-200'], 'en', true),
('culture_generale', 5, 'How many countries have English as an official language?', '67', ARRAY['45', '54', '75'], 'en', true),
('culture_generale', 5, 'What is the smallest country in Africa?', 'Seychelles', ARRAY['Gambia', 'Cape Verde', 'São Tomé'], 'en', true),
('culture_generale', 5, 'What is the mass of the Sun compared to Earth?', '333,000 times', ARRAY['100,000 times', '500,000 times', '1 million times'], 'en', true),
('culture_generale', 5, 'How many countries have French as an official language?', '29', ARRAY['21', '25', '35'], 'en', true),
('culture_generale', 5, 'What is the largest known structure in the universe?', 'Hercules-Corona Borealis Great Wall', ARRAY['Laniakea Supercluster', 'Perseus Filament', 'Boötes Void'], 'en', true);

-- =====================================================
-- HISTOIRE / HISTORY (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1
('histoire', 1, 'Quel pharaon a fait construire la grande pyramide de Gizeh ?', 'Khéops', ARRAY['Toutânkhamon', 'Ramsès II', 'Cléopâtre'], 'fr', true),
('histoire', 1, 'Quel peuple vivait dans des igloos ?', 'Inuits', ARRAY['Vikings', 'Aztèques', 'Mayas'], 'fr', true),
('histoire', 1, 'Comment s''appelait le navire de pirates le plus célèbre ?', 'Le Black Pearl', ARRAY['Le Titanic', 'Le Mayflower', 'La Santa Maria'], 'fr', true),
('histoire', 1, 'Qui a inventé l''ampoule électrique ?', 'Thomas Edison', ARRAY['Benjamin Franklin', 'Nikola Tesla', 'Albert Einstein'], 'fr', true),
('histoire', 1, 'Quel monument se trouve à Athènes ?', 'Parthénon', ARRAY['Colisée', 'Tour Eiffel', 'Big Ben'], 'fr', true),
('histoire', 1, 'Comment s''appelle le château où vivait Louis XIV ?', 'Versailles', ARRAY['Louvre', 'Chambord', 'Fontainebleau'], 'fr', true),
('histoire', 1, 'Quelle civilisation a inventé les chiffres que nous utilisons ?', 'Arabes', ARRAY['Romains', 'Grecs', 'Chinois'], 'fr', true),
('histoire', 1, 'Qui était le premier homme sur la Lune ?', 'Neil Armstrong', ARRAY['Buzz Aldrin', 'Youri Gagarine', 'John Glenn'], 'fr', true),
('histoire', 1, 'Quel héros grec a combattu le Minotaure ?', 'Thésée', ARRAY['Hercule', 'Achille', 'Ulysse'], 'fr', true),
('histoire', 1, 'Comment s''appelait le roi d''Angleterre qui a eu 6 femmes ?', 'Henri VIII', ARRAY['Henri IV', 'Richard Ier', 'Édouard III'], 'fr', true),
('histoire', 1, 'Quel animal Marco Polo a-t-il ramené de Chine ?', 'Des pâtes', ARRAY['Le thé', 'La soie', 'Le riz'], 'fr', true),
('histoire', 1, 'Quelle reine d''Angleterre a donné son nom à une époque ?', 'Victoria', ARRAY['Élisabeth', 'Marie', 'Anne'], 'fr', true),
('histoire', 1, 'Comment s''appelait le dieu du tonnerre chez les Vikings ?', 'Thor', ARRAY['Odin', 'Loki', 'Freya'], 'fr', true),
('histoire', 1, 'Quel pays a offert la Statue de la Liberté aux États-Unis ?', 'France', ARRAY['Angleterre', 'Allemagne', 'Italie'], 'fr', true),
('histoire', 1, 'Quelle merveille du monde se trouvait à Babylone ?', 'Jardins suspendus', ARRAY['Pyramides', 'Colosse', 'Phare'], 'fr', true),
('histoire', 1, 'Quel explorateur a découvert le Canada ?', 'Jacques Cartier', ARRAY['Christophe Colomb', 'Vasco de Gama', 'Magellan'], 'fr', true),
('histoire', 1, 'Comment s''appelle l''écriture des Égyptiens ?', 'Hiéroglyphes', ARRAY['Cunéiforme', 'Alphabet', 'Idéogrammes'], 'fr', true),
('histoire', 1, 'Quel roi de France était appelé le Bien-Aimé ?', 'Louis XV', ARRAY['Louis XIV', 'Louis XVI', 'Louis XIII'], 'fr', true),
('histoire', 1, 'Quelle ville a été détruite par un cheval de bois ?', 'Troie', ARRAY['Athènes', 'Sparte', 'Rome'], 'fr', true),
('histoire', 1, 'Qui a fondé Rome selon la légende ?', 'Romulus', ARRAY['Rémus', 'César', 'Auguste'], 'fr', true),

-- FRENCH - Niveau 2
('histoire', 2, 'En quelle année a eu lieu la Révolution française ?', '1789', ARRAY['1769', '1799', '1809'], 'fr', true),
('histoire', 2, 'Qui a écrit la Déclaration d''indépendance américaine ?', 'Thomas Jefferson', ARRAY['George Washington', 'Benjamin Franklin', 'John Adams'], 'fr', true),
('histoire', 2, 'Quelle guerre a duré de 1914 à 1918 ?', 'Première Guerre mondiale', ARRAY['Guerre de Crimée', 'Guerre franco-prussienne', 'Guerre des Boers'], 'fr', true),
('histoire', 2, 'Quel empire a dominé le Mexique avant les Espagnols ?', 'Aztèque', ARRAY['Maya', 'Inca', 'Olmèque'], 'fr', true),
('histoire', 2, 'Qui était le premier empereur de Chine ?', 'Qin Shi Huang', ARRAY['Liu Bang', 'Wu Zetian', 'Kangxi'], 'fr', true),
('histoire', 2, 'En quelle année Christophe Colomb a-t-il atteint l''Amérique ?', '1492', ARRAY['1482', '1502', '1512'], 'fr', true),
('histoire', 2, 'Quel traité a mis fin à la Première Guerre mondiale ?', 'Traité de Versailles', ARRAY['Traité de Paris', 'Traité de Vienne', 'Traité de Berlin'], 'fr', true),
('histoire', 2, 'Qui était Jeanne d''Arc ?', 'Héroïne française', ARRAY['Reine de France', 'Impératrice', 'Princesse'], 'fr', true),
('histoire', 2, 'Quel roi anglais a signé la Magna Carta ?', 'Jean sans Terre', ARRAY['Richard Cœur de Lion', 'Henri II', 'Édouard Ier'], 'fr', true),
('histoire', 2, 'En quelle année l''homme a-t-il marché sur la Lune ?', '1969', ARRAY['1965', '1971', '1973'], 'fr', true),
('histoire', 2, 'Quelle civilisation a construit Angkor Vat ?', 'Khmère', ARRAY['Thaïe', 'Vietnamienne', 'Birmane'], 'fr', true),
('histoire', 2, 'Qui a assassiné Abraham Lincoln ?', 'John Wilkes Booth', ARRAY['Lee Harvey Oswald', 'Charles Guiteau', 'Leon Czolgosz'], 'fr', true),
('histoire', 2, 'Quelle bataille a marqué la fin de Napoléon ?', 'Waterloo', ARRAY['Austerlitz', 'Trafalgar', 'Leipzig'], 'fr', true),
('histoire', 2, 'En quelle année a commencé la Seconde Guerre mondiale ?', '1939', ARRAY['1937', '1938', '1940'], 'fr', true),
('histoire', 2, 'Quel pays a colonisé l''Inde ?', 'Royaume-Uni', ARRAY['France', 'Portugal', 'Pays-Bas'], 'fr', true),
('histoire', 2, 'Qui a construit le Taj Mahal ?', 'Shah Jahan', ARRAY['Akbar', 'Aurangzeb', 'Babur'], 'fr', true),
('histoire', 2, 'Quelle révolution a eu lieu en 1917 en Russie ?', 'Révolution d''Octobre', ARRAY['Révolution de Février', 'Révolution blanche', 'Révolution rouge'], 'fr', true),
('histoire', 2, 'Qui était le dernier roi de France ?', 'Louis-Philippe Ier', ARRAY['Charles X', 'Louis XVIII', 'Napoléon III'], 'fr', true),
('histoire', 2, 'En quelle année l''esclavage a-t-il été aboli en France ?', '1848', ARRAY['1789', '1815', '1870'], 'fr', true),
('histoire', 2, 'Quel philosophe grec a été condamné à boire la ciguë ?', 'Socrate', ARRAY['Platon', 'Aristote', 'Épicure'], 'fr', true),

-- FRENCH - Niveau 3
('histoire', 3, 'En quelle année a été fondé l''Empire romain ?', '27 av. J.-C.', ARRAY['753 av. J.-C.', '44 av. J.-C.', '14 ap. J.-C.'], 'fr', true),
('histoire', 3, 'Quel empereur romain a légalisé le christianisme ?', 'Constantin', ARRAY['Néron', 'Auguste', 'Trajan'], 'fr', true),
('histoire', 3, 'Quelle dynastie a régné sur la France de 987 à 1328 ?', 'Capétiens', ARRAY['Mérovingiens', 'Carolingiens', 'Valois'], 'fr', true),
('histoire', 3, 'En quelle année Gutenberg a-t-il inventé l''imprimerie ?', '1450', ARRAY['1400', '1500', '1550'], 'fr', true),
('histoire', 3, 'Quelle guerre a opposé les Roses blanches et rouges en Angleterre ?', 'Guerre des Deux-Roses', ARRAY['Guerre civile', 'Guerre des Barons', 'Guerre de Cent Ans'], 'fr', true),
('histoire', 3, 'Qui a été le premier président de la Ve République française ?', 'Charles de Gaulle', ARRAY['René Coty', 'Vincent Auriol', 'Georges Pompidou'], 'fr', true),
('histoire', 3, 'En quelle année a eu lieu la chute de Constantinople ?', '1453', ARRAY['1421', '1492', '1517'], 'fr', true),
('histoire', 3, 'Quel explorateur a fait le premier tour du monde ?', 'Magellan', ARRAY['Christophe Colomb', 'Vasco de Gama', 'James Cook'], 'fr', true),
('histoire', 3, 'Quelle bataille a marqué la fin de la guerre de Cent Ans ?', 'Castillon', ARRAY['Crécy', 'Azincourt', 'Poitiers'], 'fr', true),
('histoire', 3, 'En quelle année a eu lieu la bataille d''Hastings ?', '1066', ARRAY['1016', '1086', '1106'], 'fr', true),
('histoire', 3, 'Qui était le chef des Huns ?', 'Attila', ARRAY['Gengis Khan', 'Tamerlan', 'Alaric'], 'fr', true),
('histoire', 3, 'Quelle civilisation a inventé la roue ?', 'Sumériens', ARRAY['Égyptiens', 'Grecs', 'Romains'], 'fr', true),
('histoire', 3, 'En quelle année Louis XVI a-t-il été guillotiné ?', '1793', ARRAY['1789', '1791', '1795'], 'fr', true),
('histoire', 3, 'Quel pays a lancé la première bombe atomique ?', 'États-Unis', ARRAY['URSS', 'Allemagne', 'Japon'], 'fr', true),
('histoire', 3, 'Quelle était la capitale de l''Empire byzantin ?', 'Constantinople', ARRAY['Rome', 'Athènes', 'Alexandrie'], 'fr', true),
('histoire', 3, 'En quelle année a été signé le traité de Rome ?', '1957', ARRAY['1945', '1951', '1963'], 'fr', true),
('histoire', 3, 'Qui a dirigé la Longue Marche en Chine ?', 'Mao Zedong', ARRAY['Sun Yat-sen', 'Chiang Kai-shek', 'Deng Xiaoping'], 'fr', true),
('histoire', 3, 'Quelle guerre a eu lieu de 1950 à 1953 ?', 'Guerre de Corée', ARRAY['Guerre du Vietnam', 'Guerre d''Indochine', 'Guerre du Golfe'], 'fr', true),
('histoire', 3, 'En quelle année Napoléon est-il mort ?', '1821', ARRAY['1815', '1818', '1825'], 'fr', true),
('histoire', 3, 'Quel empereur a divisé l''Empire romain en deux ?', 'Dioclétien', ARRAY['Constantin', 'Théodose', 'Justinien'], 'fr', true),

-- FRENCH - Niveau 4
('histoire', 4, 'En quelle année a eu lieu la bataille de Marathon ?', '490 av. J.-C.', ARRAY['480 av. J.-C.', '500 av. J.-C.', '470 av. J.-C.'], 'fr', true),
('histoire', 4, 'Quel roi de France a été surnommé le Roi Fainéant ?', 'Louis V', ARRAY['Louis IV', 'Louis VI', 'Louis VII'], 'fr', true),
('histoire', 4, 'Quelle conférence a divisé l''Afrique entre les puissances européennes ?', 'Conférence de Berlin', ARRAY['Conférence de Vienne', 'Conférence de Paris', 'Conférence de Londres'], 'fr', true),
('histoire', 4, 'En quelle année a été fondée la Compagnie des Indes orientales néerlandaise ?', '1602', ARRAY['1580', '1620', '1650'], 'fr', true),
('histoire', 4, 'Qui était le premier califat de l''Islam ?', 'Califat rachidun', ARRAY['Califat omeyyade', 'Califat abbasside', 'Califat fatimide'], 'fr', true),
('histoire', 4, 'Quelle révolte a eu lieu à Paris en 1358 ?', 'Jacquerie', ARRAY['Fronde', 'Commune', 'Révolte des Maillotins'], 'fr', true),
('histoire', 4, 'En quelle année a été signé le traité de Tordesillas ?', '1494', ARRAY['1480', '1500', '1510'], 'fr', true),
('histoire', 4, 'Quel empereur byzantin a fait construire Sainte-Sophie ?', 'Justinien', ARRAY['Constantin', 'Théodose', 'Héraclius'], 'fr', true),
('histoire', 4, 'Quelle bataille a marqué la fin de l''Empire aztèque ?', 'Tenochtitlan', ARRAY['Tlaxcala', 'Cholula', 'Texcoco'], 'fr', true),
('histoire', 4, 'En quelle année a eu lieu le schisme d''Orient ?', '1054', ARRAY['1024', '1084', '1124'], 'fr', true),
('histoire', 4, 'Qui a fondé l''Empire mongol ?', 'Gengis Khan', ARRAY['Kubilai Khan', 'Tamerlan', 'Attila'], 'fr', true),
('histoire', 4, 'Quelle guerre a opposé Athènes et Sparte ?', 'Guerre du Péloponnèse', ARRAY['Guerres médiques', 'Guerre de Troie', 'Guerre sacrée'], 'fr', true),
('histoire', 4, 'En quelle année a été proclamée la République de Weimar ?', '1919', ARRAY['1918', '1920', '1923'], 'fr', true),
('histoire', 4, 'Quel pharaon a tenté d''imposer le monothéisme ?', 'Akhenaton', ARRAY['Ramsès II', 'Toutânkhamon', 'Khéops'], 'fr', true),
('histoire', 4, 'Quelle dynastie a succédé aux Mérovingiens ?', 'Carolingiens', ARRAY['Capétiens', 'Valois', 'Bourbons'], 'fr', true),
('histoire', 4, 'En quelle année Marco Polo est-il arrivé en Chine ?', '1275', ARRAY['1250', '1290', '1300'], 'fr', true),
('histoire', 4, 'Quel traité a mis fin à la guerre de Trente Ans ?', 'Traité de Westphalie', ARRAY['Traité de Münster', 'Traité d''Utrecht', 'Traité de Nimègue'], 'fr', true),
('histoire', 4, 'Quelle bataille a marqué la fin de l''Empire perse ?', 'Gaugamèles', ARRAY['Issos', 'Granique', 'Arbèles'], 'fr', true),
('histoire', 4, 'En quelle année a été fondée l''ONU ?', '1945', ARRAY['1919', '1939', '1950'], 'fr', true),
('histoire', 4, 'Qui était le dernier empereur romain d''Occident ?', 'Romulus Augustule', ARRAY['Honorius', 'Valentinien III', 'Julius Nepos'], 'fr', true),

-- FRENCH - Niveau 5
('histoire', 5, 'En quelle année a eu lieu la bataille de Qadesh ?', '1274 av. J.-C.', ARRAY['1200 av. J.-C.', '1300 av. J.-C.', '1250 av. J.-C.'], 'fr', true),
('histoire', 5, 'Quel roi d''Assyrie a détruit Babylone en 689 av. J.-C. ?', 'Sennachérib', ARRAY['Assurbanipal', 'Sargon II', 'Tiglath-Pileser III'], 'fr', true),
('histoire', 5, 'Quelle dynastie a régné sur l''Éthiopie jusqu''en 1974 ?', 'Salomonide', ARRAY['Zagwé', 'Aksumite', 'Gondarienne'], 'fr', true),
('histoire', 5, 'En quelle année a eu lieu le congrès de Vienne ?', '1815', ARRAY['1810', '1820', '1825'], 'fr', true),
('histoire', 5, 'Quel empire a été fondé par Cyrus le Grand ?', 'Empire perse achéménide', ARRAY['Empire mède', 'Empire parthe', 'Empire sassanide'], 'fr', true),
('histoire', 5, 'Quelle bataille a marqué la fin de la Reconquista ?', 'Grenade', ARRAY['Séville', 'Cordoue', 'Tolède'], 'fr', true),
('histoire', 5, 'En quelle année a été signé le traité de Nerchinsk ?', '1689', ARRAY['1670', '1700', '1720'], 'fr', true),
('histoire', 5, 'Quel souverain a unifié le Japon en 1590 ?', 'Toyotomi Hideyoshi', ARRAY['Oda Nobunaga', 'Tokugawa Ieyasu', 'Date Masamune'], 'fr', true),
('histoire', 5, 'Quelle révolte a eu lieu en Inde en 1857 ?', 'Révolte des Cipayes', ARRAY['Révolte des Marathes', 'Révolte des Sikhs', 'Révolte des Moghols'], 'fr', true),
('histoire', 5, 'En quelle année a été fondée la dynastie Ming ?', '1368', ARRAY['1350', '1380', '1400'], 'fr', true),
('histoire', 5, 'Quel empire a été renversé par la révolution Xinhai ?', 'Empire Qing', ARRAY['Empire Ming', 'Empire Yuan', 'Empire Tang'], 'fr', true),
('histoire', 5, 'Quelle bataille a marqué la fin de la domination seldjoukide ?', 'Köse Dağ', ARRAY['Manzikert', 'Dandanakan', 'Myriokephalon'], 'fr', true),
('histoire', 5, 'En quelle année a été proclamé l''Empire allemand ?', '1871', ARRAY['1866', '1870', '1875'], 'fr', true),
('histoire', 5, 'Quel roi de Prusse a lancé la guerre de Sept Ans ?', 'Frédéric II', ARRAY['Frédéric Ier', 'Frédéric-Guillaume Ier', 'Frédéric-Guillaume II'], 'fr', true),
('histoire', 5, 'Quelle civilisation a construit Great Zimbabwe ?', 'Shona', ARRAY['Zoulou', 'Bantu', 'Swahili'], 'fr', true),
('histoire', 5, 'En quelle année a eu lieu la bataille de Lépante ?', '1571', ARRAY['1550', '1580', '1600'], 'fr', true),
('histoire', 5, 'Quel traité a mis fin à la guerre russo-japonaise ?', 'Traité de Portsmouth', ARRAY['Traité de Shimonoseki', 'Traité de Tokyo', 'Traité de Pékin'], 'fr', true),
('histoire', 5, 'Quelle dynastie a précédé les Romanov en Russie ?', 'Riourikides', ARRAY['Godounov', 'Chouïski', 'Romanov'], 'fr', true),
('histoire', 5, 'En quelle année a été fondée la Ligue hanséatique ?', '1358', ARRAY['1200', '1300', '1400'], 'fr', true),
('histoire', 5, 'Quel sultan ottoman a conquis Constantinople ?', 'Mehmed II', ARRAY['Soliman Ier', 'Bayezid Ier', 'Murad II'], 'fr', true),

-- ENGLISH - Level 1
('histoire', 1, 'Which pharaoh built the Great Pyramid of Giza?', 'Khufu', ARRAY['Tutankhamun', 'Ramses II', 'Cleopatra'], 'en', true),
('histoire', 1, 'Which people lived in igloos?', 'Inuit', ARRAY['Vikings', 'Aztecs', 'Mayans'], 'en', true),
('histoire', 1, 'Who invented the light bulb?', 'Thomas Edison', ARRAY['Benjamin Franklin', 'Nikola Tesla', 'Albert Einstein'], 'en', true),
('histoire', 1, 'Which monument is located in Athens?', 'Parthenon', ARRAY['Colosseum', 'Eiffel Tower', 'Big Ben'], 'en', true),
('histoire', 1, 'What is the name of the castle where Louis XIV lived?', 'Versailles', ARRAY['Louvre', 'Chambord', 'Fontainebleau'], 'en', true),
('histoire', 1, 'Who was the first man on the Moon?', 'Neil Armstrong', ARRAY['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], 'en', true),
('histoire', 1, 'Which Greek hero fought the Minotaur?', 'Theseus', ARRAY['Hercules', 'Achilles', 'Odysseus'], 'en', true),
('histoire', 1, 'What was the name of the English king who had 6 wives?', 'Henry VIII', ARRAY['Henry IV', 'Richard I', 'Edward III'], 'en', true),
('histoire', 1, 'Which English queen gave her name to an era?', 'Victoria', ARRAY['Elizabeth', 'Mary', 'Anne'], 'en', true),
('histoire', 1, 'What was the name of the Viking god of thunder?', 'Thor', ARRAY['Odin', 'Loki', 'Freya'], 'en', true),
('histoire', 1, 'Which country gave the Statue of Liberty to the United States?', 'France', ARRAY['England', 'Germany', 'Italy'], 'en', true),
('histoire', 1, 'Which wonder of the world was in Babylon?', 'Hanging Gardens', ARRAY['Pyramids', 'Colossus', 'Lighthouse'], 'en', true),
('histoire', 1, 'What is the name of Egyptian writing?', 'Hieroglyphics', ARRAY['Cuneiform', 'Alphabet', 'Ideograms'], 'en', true),
('histoire', 1, 'Which city was destroyed by a wooden horse?', 'Troy', ARRAY['Athens', 'Sparta', 'Rome'], 'en', true),
('histoire', 1, 'Who founded Rome according to legend?', 'Romulus', ARRAY['Remus', 'Caesar', 'Augustus'], 'en', true),
('histoire', 1, 'What type of ships did Vikings use?', 'Longships', ARRAY['Galleys', 'Caravels', 'Triremes'], 'en', true),
('histoire', 1, 'Who was Julius Caesar?', 'Roman Emperor', ARRAY['King of France', 'Pharaoh', 'King of Greece'], 'en', true),
('histoire', 1, 'What animal did Hannibal use to cross the Alps?', 'Elephants', ARRAY['Horses', 'Camels', 'Oxen'], 'en', true),
('histoire', 1, 'Who invented the printing press?', 'Gutenberg', ARRAY['Leonardo da Vinci', 'Galileo', 'Newton'], 'en', true),
('histoire', 1, 'In which city is the Colosseum located?', 'Rome', ARRAY['Athens', 'Paris', 'London'], 'en', true),

-- ENGLISH - Level 2
('histoire', 2, 'In what year did the French Revolution occur?', '1789', ARRAY['1769', '1799', '1809'], 'en', true),
('histoire', 2, 'Who wrote the American Declaration of Independence?', 'Thomas Jefferson', ARRAY['George Washington', 'Benjamin Franklin', 'John Adams'], 'en', true),
('histoire', 2, 'Which war lasted from 1914 to 1918?', 'World War I', ARRAY['Crimean War', 'Franco-Prussian War', 'Boer War'], 'en', true),
('histoire', 2, 'Which empire dominated Mexico before the Spanish?', 'Aztec', ARRAY['Mayan', 'Inca', 'Olmec'], 'en', true),
('histoire', 2, 'Who was the first emperor of China?', 'Qin Shi Huang', ARRAY['Liu Bang', 'Wu Zetian', 'Kangxi'], 'en', true),
('histoire', 2, 'In what year did Columbus reach America?', '1492', ARRAY['1482', '1502', '1512'], 'en', true),
('histoire', 2, 'Which treaty ended World War I?', 'Treaty of Versailles', ARRAY['Treaty of Paris', 'Treaty of Vienna', 'Treaty of Berlin'], 'en', true),
('histoire', 2, 'Who was Joan of Arc?', 'French heroine', ARRAY['Queen of France', 'Empress', 'Princess'], 'en', true),
('histoire', 2, 'Which English king signed the Magna Carta?', 'King John', ARRAY['Richard the Lionheart', 'Henry II', 'Edward I'], 'en', true),
('histoire', 2, 'In what year did man walk on the Moon?', '1969', ARRAY['1965', '1971', '1973'], 'en', true),
('histoire', 2, 'Which civilization built Angkor Wat?', 'Khmer', ARRAY['Thai', 'Vietnamese', 'Burmese'], 'en', true),
('histoire', 2, 'Who assassinated Abraham Lincoln?', 'John Wilkes Booth', ARRAY['Lee Harvey Oswald', 'Charles Guiteau', 'Leon Czolgosz'], 'en', true),
('histoire', 2, 'Which battle marked the end of Napoleon?', 'Waterloo', ARRAY['Austerlitz', 'Trafalgar', 'Leipzig'], 'en', true),
('histoire', 2, 'In what year did World War II begin?', '1939', ARRAY['1937', '1938', '1940'], 'en', true),
('histoire', 2, 'Which country colonized India?', 'United Kingdom', ARRAY['France', 'Portugal', 'Netherlands'], 'en', true),
('histoire', 2, 'Who built the Taj Mahal?', 'Shah Jahan', ARRAY['Akbar', 'Aurangzeb', 'Babur'], 'en', true),
('histoire', 2, 'Which revolution took place in Russia in 1917?', 'October Revolution', ARRAY['February Revolution', 'White Revolution', 'Red Revolution'], 'en', true),
('histoire', 2, 'Who was the last king of France?', 'Louis-Philippe I', ARRAY['Charles X', 'Louis XVIII', 'Napoleon III'], 'en', true),
('histoire', 2, 'In what year was slavery abolished in France?', '1848', ARRAY['1789', '1815', '1870'], 'en', true),
('histoire', 2, 'Which Greek philosopher was sentenced to drink hemlock?', 'Socrates', ARRAY['Plato', 'Aristotle', 'Epicurus'], 'en', true),

-- ENGLISH - Level 3
('histoire', 3, 'In what year was the Roman Empire founded?', '27 BC', ARRAY['753 BC', '44 BC', '14 AD'], 'en', true),
('histoire', 3, 'Which Roman emperor legalized Christianity?', 'Constantine', ARRAY['Nero', 'Augustus', 'Trajan'], 'en', true),
('histoire', 3, 'Which dynasty ruled France from 987 to 1328?', 'Capetians', ARRAY['Merovingians', 'Carolingians', 'Valois'], 'en', true),
('histoire', 3, 'In what year did Gutenberg invent the printing press?', '1450', ARRAY['1400', '1500', '1550'], 'en', true),
('histoire', 3, 'Who was the first president of the Fifth French Republic?', 'Charles de Gaulle', ARRAY['René Coty', 'Vincent Auriol', 'Georges Pompidou'], 'en', true),
('histoire', 3, 'In what year did Constantinople fall?', '1453', ARRAY['1421', '1492', '1517'], 'en', true),
('histoire', 3, 'Which explorer was first to circumnavigate the world?', 'Magellan', ARRAY['Columbus', 'Vasco da Gama', 'James Cook'], 'en', true),
('histoire', 3, 'In what year was the Battle of Hastings?', '1066', ARRAY['1016', '1086', '1106'], 'en', true),
('histoire', 3, 'Who was the leader of the Huns?', 'Attila', ARRAY['Genghis Khan', 'Tamerlane', 'Alaric'], 'en', true),
('histoire', 3, 'Which civilization invented the wheel?', 'Sumerians', ARRAY['Egyptians', 'Greeks', 'Romans'], 'en', true),
('histoire', 3, 'In what year was Louis XVI guillotined?', '1793', ARRAY['1789', '1791', '1795'], 'en', true),
('histoire', 3, 'Which country dropped the first atomic bomb?', 'United States', ARRAY['USSR', 'Germany', 'Japan'], 'en', true),
('histoire', 3, 'What was the capital of the Byzantine Empire?', 'Constantinople', ARRAY['Rome', 'Athens', 'Alexandria'], 'en', true),
('histoire', 3, 'In what year was the Treaty of Rome signed?', '1957', ARRAY['1945', '1951', '1963'], 'en', true),
('histoire', 3, 'Who led the Long March in China?', 'Mao Zedong', ARRAY['Sun Yat-sen', 'Chiang Kai-shek', 'Deng Xiaoping'], 'en', true),
('histoire', 3, 'Which war took place from 1950 to 1953?', 'Korean War', ARRAY['Vietnam War', 'Indochina War', 'Gulf War'], 'en', true),
('histoire', 3, 'In what year did Napoleon die?', '1821', ARRAY['1815', '1818', '1825'], 'en', true),
('histoire', 3, 'Which emperor divided the Roman Empire in two?', 'Diocletian', ARRAY['Constantine', 'Theodosius', 'Justinian'], 'en', true),
('histoire', 3, 'Which war pitted the White and Red Roses in England?', 'War of the Roses', ARRAY['Civil War', 'Barons'' War', 'Hundred Years'' War'], 'en', true),
('histoire', 3, 'Which battle marked the end of the Hundred Years'' War?', 'Castillon', ARRAY['Crécy', 'Agincourt', 'Poitiers'], 'en', true),

-- ENGLISH - Level 4
('histoire', 4, 'In what year was the Battle of Marathon?', '490 BC', ARRAY['480 BC', '500 BC', '470 BC'], 'en', true),
('histoire', 4, 'Which conference divided Africa among European powers?', 'Berlin Conference', ARRAY['Vienna Conference', 'Paris Conference', 'London Conference'], 'en', true),
('histoire', 4, 'In what year was the Dutch East India Company founded?', '1602', ARRAY['1580', '1620', '1650'], 'en', true),
('histoire', 4, 'In what year was the Treaty of Tordesillas signed?', '1494', ARRAY['1480', '1500', '1510'], 'en', true),
('histoire', 4, 'Which Byzantine emperor built Hagia Sophia?', 'Justinian', ARRAY['Constantine', 'Theodosius', 'Heraclius'], 'en', true),
('histoire', 4, 'In what year was the Great Schism?', '1054', ARRAY['1024', '1084', '1124'], 'en', true),
('histoire', 4, 'Who founded the Mongol Empire?', 'Genghis Khan', ARRAY['Kublai Khan', 'Tamerlane', 'Attila'], 'en', true),
('histoire', 4, 'Which war pitted Athens against Sparta?', 'Peloponnesian War', ARRAY['Persian Wars', 'Trojan War', 'Sacred War'], 'en', true),
('histoire', 4, 'In what year was the Weimar Republic proclaimed?', '1919', ARRAY['1918', '1920', '1923'], 'en', true),
('histoire', 4, 'Which pharaoh tried to impose monotheism?', 'Akhenaten', ARRAY['Ramses II', 'Tutankhamun', 'Khufu'], 'en', true),
('histoire', 4, 'Which dynasty succeeded the Merovingians?', 'Carolingians', ARRAY['Capetians', 'Valois', 'Bourbons'], 'en', true),
('histoire', 4, 'In what year did Marco Polo arrive in China?', '1275', ARRAY['1250', '1290', '1300'], 'en', true),
('histoire', 4, 'Which treaty ended the Thirty Years'' War?', 'Treaty of Westphalia', ARRAY['Treaty of Münster', 'Treaty of Utrecht', 'Treaty of Nijmegen'], 'en', true),
('histoire', 4, 'Which battle marked the end of the Persian Empire?', 'Gaugamela', ARRAY['Issus', 'Granicus', 'Arbela'], 'en', true),
('histoire', 4, 'In what year was the UN founded?', '1945', ARRAY['1919', '1939', '1950'], 'en', true),
('histoire', 4, 'Who was the last Western Roman Emperor?', 'Romulus Augustulus', ARRAY['Honorius', 'Valentinian III', 'Julius Nepos'], 'en', true),
('histoire', 4, 'Which battle marked the end of the Aztec Empire?', 'Tenochtitlan', ARRAY['Tlaxcala', 'Cholula', 'Texcoco'], 'en', true),
('histoire', 4, 'Which revolt took place in Paris in 1358?', 'Jacquerie', ARRAY['Fronde', 'Commune', 'Maillotins Revolt'], 'en', true),
('histoire', 4, 'What was the first caliphate of Islam?', 'Rashidun Caliphate', ARRAY['Umayyad Caliphate', 'Abbasid Caliphate', 'Fatimid Caliphate'], 'en', true),
('histoire', 4, 'Which French king was called the Do-Nothing King?', 'Louis V', ARRAY['Louis IV', 'Louis VI', 'Louis VII'], 'en', true),

-- ENGLISH - Level 5
('histoire', 5, 'In what year was the Battle of Kadesh?', '1274 BC', ARRAY['1200 BC', '1300 BC', '1250 BC'], 'en', true),
('histoire', 5, 'Which Assyrian king destroyed Babylon in 689 BC?', 'Sennacherib', ARRAY['Ashurbanipal', 'Sargon II', 'Tiglath-Pileser III'], 'en', true),
('histoire', 5, 'Which dynasty ruled Ethiopia until 1974?', 'Solomonic', ARRAY['Zagwe', 'Aksumite', 'Gondarian'], 'en', true),
('histoire', 5, 'In what year was the Congress of Vienna?', '1815', ARRAY['1810', '1820', '1825'], 'en', true),
('histoire', 5, 'Which empire was founded by Cyrus the Great?', 'Achaemenid Persian Empire', ARRAY['Median Empire', 'Parthian Empire', 'Sassanid Empire'], 'en', true),
('histoire', 5, 'Which battle marked the end of the Reconquista?', 'Granada', ARRAY['Seville', 'Cordoba', 'Toledo'], 'en', true),
('histoire', 5, 'In what year was the Treaty of Nerchinsk signed?', '1689', ARRAY['1670', '1700', '1720'], 'en', true),
('histoire', 5, 'Which ruler unified Japan in 1590?', 'Toyotomi Hideyoshi', ARRAY['Oda Nobunaga', 'Tokugawa Ieyasu', 'Date Masamune'], 'en', true),
('histoire', 5, 'Which revolt took place in India in 1857?', 'Sepoy Mutiny', ARRAY['Maratha Revolt', 'Sikh Revolt', 'Mughal Revolt'], 'en', true),
('histoire', 5, 'In what year was the Ming dynasty founded?', '1368', ARRAY['1350', '1380', '1400'], 'en', true),
('histoire', 5, 'Which empire was overthrown by the Xinhai Revolution?', 'Qing Empire', ARRAY['Ming Empire', 'Yuan Empire', 'Tang Empire'], 'en', true),
('histoire', 5, 'In what year was the German Empire proclaimed?', '1871', ARRAY['1866', '1870', '1875'], 'en', true),
('histoire', 5, 'Which Prussian king started the Seven Years'' War?', 'Frederick II', ARRAY['Frederick I', 'Frederick William I', 'Frederick William II'], 'en', true),
('histoire', 5, 'Which civilization built Great Zimbabwe?', 'Shona', ARRAY['Zulu', 'Bantu', 'Swahili'], 'en', true),
('histoire', 5, 'In what year was the Battle of Lepanto?', '1571', ARRAY['1550', '1580', '1600'], 'en', true),
('histoire', 5, 'Which treaty ended the Russo-Japanese War?', 'Treaty of Portsmouth', ARRAY['Treaty of Shimonoseki', 'Treaty of Tokyo', 'Treaty of Beijing'], 'en', true),
('histoire', 5, 'Which dynasty preceded the Romanovs in Russia?', 'Rurikids', ARRAY['Godunov', 'Shuisky', 'Romanov'], 'en', true),
('histoire', 5, 'In what year was the Hanseatic League founded?', '1358', ARRAY['1200', '1300', '1400'], 'en', true),
('histoire', 5, 'Which Ottoman sultan conquered Constantinople?', 'Mehmed II', ARRAY['Suleiman I', 'Bayezid I', 'Murad II'], 'en', true),
('histoire', 5, 'Which battle marked the end of Seljuk domination?', 'Köse Dağ', ARRAY['Manzikert', 'Dandanakan', 'Myriokephalon'], 'en', true);
