-- Cleanup duplicate function/index that accumulated over earlier migrations.
--
-- 1) Two `create_duel` overloads exist:
--      create_duel(uuid, text, int)
--      create_duel(uuid, text, int, text)         <- the canonical one with p_language
--    The 3-arg version is dead code (mobile always passes p_language). Drop it.
--
-- 2) `users.username` has two identical UNIQUE indexes/constraints:
--      users_username_key       <- the original (auto-generated by UNIQUE NOT NULL)
--      users_username_unique    <- redundant duplicate
--    Drop the duplicate; keep `users_username_key`.

BEGIN;

-- 1) Drop the legacy 3-arg overload of create_duel.
DROP FUNCTION IF EXISTS public.create_duel(uuid, text, integer);

-- 2) Drop the duplicate unique constraint on users.username.
--    Dropping the constraint also drops its backing index of the same name.
ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_username_unique;

COMMIT;
