-- =====================================================
-- JEUX VIDEO / VIDEO GAMES (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1 (Facile - Jeux populaires grand public)
('jeux_video', 1, 'Quel est le personnage principal de la série Mario ?', 'Mario', ARRAY['Luigi', 'Bowser', 'Toad'], 'fr', true),
('jeux_video', 1, 'Dans Minecraft, quel bloc est le plus commun ?', 'Pierre', ARRAY['Diamant', 'Or', 'Fer'], 'fr', true),
('jeux_video', 1, 'Quel est le nom du battle royale de Epic Games sorti en 2017 ?', 'Fortnite', ARRAY['Apex Legends', 'PUBG', 'Warzone'], 'fr', true),
('jeux_video', 1, 'Quelle console Nintendo est portable et hybride ?', 'Nintendo Switch', ARRAY['Wii U', 'Nintendo DS', 'Game Boy'], 'fr', true),
('jeux_video', 1, 'Quel est le nom du plombier vert, frere de Mario ?', 'Luigi', ARRAY['Wario', 'Waluigi', 'Toad'], 'fr', true),
('jeux_video', 1, 'Dans Pokemon, quel est le starter de type feu de la premiere generation ?', 'Salameche', ARRAY['Bulbizarre', 'Carapuce', 'Pikachu'], 'fr', true),
('jeux_video', 1, 'Quelle marque fabrique la PlayStation ?', 'Sony', ARRAY['Microsoft', 'Nintendo', 'Sega'], 'fr', true),
('jeux_video', 1, 'Quel jeu de course met en scene Mario et ses amis ?', 'Mario Kart', ARRAY['Gran Turismo', 'Need for Speed', 'Forza'], 'fr', true),
('jeux_video', 1, 'Comment s''appelle le heros de Zelda ?', 'Link', ARRAY['Zelda', 'Ganondorf', 'Sheik'], 'fr', true),
('jeux_video', 1, 'Quel jeu permet de construire avec des blocs en pixel ?', 'Minecraft', ARRAY['Roblox', 'Terraria', 'Lego Worlds'], 'fr', true),
('jeux_video', 1, 'Quelle creature jaune est la mascotte de Pokemon ?', 'Pikachu', ARRAY['Rondoudou', 'Evoli', 'Mewtwo'], 'fr', true),
('jeux_video', 1, 'Quel est l''ennemi principal de Mario ?', 'Bowser', ARRAY['Donkey Kong', 'Wario', 'Koopa'], 'fr', true),
('jeux_video', 1, 'Dans quel jeu joue-t-on au football avec des voitures ?', 'Rocket League', ARRAY['FIFA', 'GTA', 'Need for Speed'], 'fr', true),
('jeux_video', 1, 'Quel jeu de bataille en ligne oppose des heros ?', 'League of Legends', ARRAY['Counter-Strike', 'Valorant', 'Overwatch'], 'fr', true),
('jeux_video', 1, 'Quelle console Microsoft concurrence la PlayStation ?', 'Xbox', ARRAY['Nintendo', 'Sega', 'Atari'], 'fr', true),
('jeux_video', 1, 'Dans Fortnite, comment s''appelle la danse celebre ?', 'Floss', ARRAY['Dab', 'Moonwalk', 'Robot'], 'fr', true),
('jeux_video', 1, 'Quel personnage rose de Nintendo peut voler ?', 'Kirby', ARRAY['Jigglypuff', 'Peach', 'Toad'], 'fr', true),
('jeux_video', 1, 'Quel jeu de simulation de vie met en scene des villageois animaux ?', 'Animal Crossing', ARRAY['Stardew Valley', 'Harvest Moon', 'The Sims'], 'fr', true),
('jeux_video', 1, 'Quelle princesse Mario doit-il souvent sauver ?', 'Peach', ARRAY['Zelda', 'Daisy', 'Rosalina'], 'fr', true),
('jeux_video', 1, 'Quel jeu mobile consiste a attraper des Pokemon dans le monde reel ?', 'Pokemon GO', ARRAY['Pokemon Unite', 'Pokemon Masters', 'Pokemon Sleep'], 'fr', true),

-- FRENCH - Niveau 2 (Moyen - Culture gaming generale)
('jeux_video', 2, 'Quel studio a cree The Last of Us ?', 'Naughty Dog', ARRAY['Rockstar', 'Ubisoft', 'Bethesda'], 'fr', true),
('jeux_video', 2, 'Dans GTA V, combien y a-t-il de personnages jouables principaux ?', '3', ARRAY['1', '2', '4'], 'fr', true),
('jeux_video', 2, 'Quel jeu de survie se deroule sur une ile avec des dinosaures ?', 'ARK: Survival Evolved', ARRAY['Rust', 'DayZ', 'The Forest'], 'fr', true),
('jeux_video', 2, 'Quelle serie de jeux met en scene un assassin a travers l''histoire ?', 'Assassin''s Creed', ARRAY['Hitman', 'Splinter Cell', 'Metal Gear'], 'fr', true),
('jeux_video', 2, 'Quel est le nom du mode zombie de Call of Duty ?', 'Zombies', ARRAY['Outbreak', 'Survival', 'Horde'], 'fr', true),
('jeux_video', 2, 'Dans quel jeu explore-t-on l''espace avec un vaisseau spatial ?', 'No Man''s Sky', ARRAY['Star Citizen', 'Elite Dangerous', 'Eve Online'], 'fr', true),
('jeux_video', 2, 'Quel jeu de combat met en scene des personnages de Nintendo ?', 'Super Smash Bros.', ARRAY['Tekken', 'Street Fighter', 'Mortal Kombat'], 'fr', true),
('jeux_video', 2, 'Quelle entreprise a cree Overwatch ?', 'Blizzard', ARRAY['Valve', 'Riot Games', 'Epic Games'], 'fr', true),
('jeux_video', 2, 'Dans Minecraft, quel boss final trouve-t-on dans l''End ?', 'Ender Dragon', ARRAY['Wither', 'Herobrine', 'Elder Guardian'], 'fr', true),
('jeux_video', 2, 'Quel jeu de sport electronique est le plus populaire en Coree ?', 'League of Legends', ARRAY['Dota 2', 'CS:GO', 'Overwatch'], 'fr', true),
('jeux_video', 2, 'Quelle serie de jeux Bethesda se deroule dans un monde post-apocalyptique ?', 'Fallout', ARRAY['Elder Scrolls', 'Doom', 'Wolfenstein'], 'fr', true),
('jeux_video', 2, 'Dans Zelda, quel instrument magique Link utilise-t-il souvent ?', 'Ocarina', ARRAY['Flute', 'Harpe', 'Tambour'], 'fr', true),
('jeux_video', 2, 'Quel jeu de CD Projekt Red met en scene Geralt de Riv ?', 'The Witcher', ARRAY['Cyberpunk 2077', 'Gwent', 'Thronebreaker'], 'fr', true),
('jeux_video', 2, 'Quelle console portable Sony a precede la PS Vita ?', 'PSP', ARRAY['PS One', 'PS Mini', 'PS Go'], 'fr', true),
('jeux_video', 2, 'Dans quel jeu incarne-t-on un chasseur de monstres geants ?', 'Monster Hunter', ARRAY['Dark Souls', 'God of War', 'Devil May Cry'], 'fr', true),
('jeux_video', 2, 'Quel jeu de simulation de vie a ete cree par Will Wright ?', 'Les Sims', ARRAY['Animal Crossing', 'Stardew Valley', 'Second Life'], 'fr', true),
('jeux_video', 2, 'Quelle plateforme de distribution de jeux PC appartient a Valve ?', 'Steam', ARRAY['Epic Games Store', 'GOG', 'Origin'], 'fr', true),
('jeux_video', 2, 'Dans Red Dead Redemption 2, comment s''appelle le protagoniste ?', 'Arthur Morgan', ARRAY['John Marston', 'Dutch', 'Micah'], 'fr', true),
('jeux_video', 2, 'Quel jeu de From Software est connu pour sa difficulte extreme ?', 'Dark Souls', ARRAY['Sekiro', 'Bloodborne', 'Elden Ring'], 'fr', true),
('jeux_video', 2, 'Quelle serie de jeux de course arcade met en scene des voitures exotiques ?', 'Need for Speed', ARRAY['Gran Turismo', 'Forza', 'Burnout'], 'fr', true),

-- FRENCH - Niveau 3 (Difficile - Connaissances approfondies)
('jeux_video', 3, 'En quelle annee la premiere PlayStation est-elle sortie au Japon ?', '1994', ARRAY['1992', '1995', '1996'], 'fr', true),
('jeux_video', 3, 'Quel est le vrai nom de Master Chief dans Halo ?', 'John-117', ARRAY['James-117', 'Jack-117', 'Joseph-117'], 'fr', true),
('jeux_video', 3, 'Quel studio a developpe le premier The Elder Scrolls ?', 'Bethesda', ARRAY['Bioware', 'Obsidian', 'CD Projekt'], 'fr', true),
('jeux_video', 3, 'Dans World of Warcraft, combien de classes etaient disponibles au lancement ?', '9', ARRAY['8', '10', '12'], 'fr', true),
('jeux_video', 3, 'Quel jeu a popularise le genre battle royale avant Fortnite ?', 'PUBG', ARRAY['H1Z1', 'DayZ', 'Arma'], 'fr', true),
('jeux_video', 3, 'Quelle societe japonaise a cree Pac-Man ?', 'Namco', ARRAY['Sega', 'Konami', 'Capcom'], 'fr', true),
('jeux_video', 3, 'Dans Metal Gear Solid, quel est le nom de code du heros ?', 'Solid Snake', ARRAY['Big Boss', 'Liquid Snake', 'Raiden'], 'fr', true),
('jeux_video', 3, 'Quel jeu de Rockstar se deroule dans une ville inspiree de Los Angeles ?', 'GTA V', ARRAY['GTA IV', 'GTA San Andreas', 'LA Noire'], 'fr', true),
('jeux_video', 3, 'Combien de generations de consoles principales Nintendo y a-t-il eu ?', '9', ARRAY['7', '8', '10'], 'fr', true),
('jeux_video', 3, 'Quel personnage de Street Fighter est surnomme "The World Warrior" ?', 'Ryu', ARRAY['Ken', 'Guile', 'Chun-Li'], 'fr', true),
('jeux_video', 3, 'Dans quelle ville se deroule principalement Bioshock ?', 'Rapture', ARRAY['Columbia', 'Arcadia', 'Neptune'], 'fr', true),
('jeux_video', 3, 'Quel jeu a introduit le concept de "permadeath" au grand public ?', 'Rogue', ARRAY['NetHack', 'Angband', 'ADOM'], 'fr', true),
('jeux_video', 3, 'Quelle console a ete la premiere a utiliser des CD comme support ?', 'PC Engine CD', ARRAY['PlayStation', 'Sega CD', 'Neo Geo CD'], 'fr', true),
('jeux_video', 3, 'Quel est le nom du createur de Metal Gear ?', 'Hideo Kojima', ARRAY['Shigeru Miyamoto', 'Shinji Mikami', 'Hidetaka Miyazaki'], 'fr', true),
('jeux_video', 3, 'Dans Resident Evil, quel virus cause l''epidemie zombie ?', 'Virus T', ARRAY['Virus G', 'Virus C', 'Virus Las Plagas'], 'fr', true),
('jeux_video', 3, 'Quel jeu de Valve n''a jamais eu de troisieme opus ?', 'Half-Life', ARRAY['Portal', 'Left 4 Dead', 'Team Fortress'], 'fr', true),
('jeux_video', 3, 'Quelle equipe d''esport a remporte le premier Worlds de League of Legends ?', 'Fnatic', ARRAY['SK Gaming', 'TSM', 'CLG'], 'fr', true),
('jeux_video', 3, 'Dans Final Fantasy VII, comment s''appelle l''entreprise antagoniste ?', 'Shinra', ARRAY['Midgar', 'Avalanche', 'Soldier'], 'fr', true),
('jeux_video', 3, 'Quel jeu de simulation a permis de creer des villes depuis 1989 ?', 'SimCity', ARRAY['Cities Skylines', 'Civilization', 'Anno'], 'fr', true),
('jeux_video', 3, 'Quelle console Sega a ete lancee pour concurrencer la Super Nintendo ?', 'Mega Drive', ARRAY['Saturn', 'Dreamcast', 'Master System'], 'fr', true),

-- FRENCH - Niveau 4 (Tres difficile - Culture retro et technique)
('jeux_video', 4, 'En quelle annee le premier Doom est-il sorti ?', '1993', ARRAY['1991', '1992', '1994'], 'fr', true),
('jeux_video', 4, 'Quel etait le nom de code de la Nintendo 64 pendant son developpement ?', 'Project Reality', ARRAY['Ultra 64', 'Nintendo Ultra', 'Project N64'], 'fr', true),
('jeux_video', 4, 'Combien de bits avait le processeur de la Sega Genesis/Mega Drive ?', '16', ARRAY['8', '32', '64'], 'fr', true),
('jeux_video', 4, 'Quel jeu Atari a cause le crash de l''industrie en 1983 ?', 'E.T.', ARRAY['Pac-Man', 'Asteroids', 'Centipede'], 'fr', true),
('jeux_video', 4, 'Quelle est la resolution native de la Game Boy originale ?', '160x144', ARRAY['160x160', '128x128', '240x160'], 'fr', true),
('jeux_video', 4, 'Quel studio a cree le premier Castlevania ?', 'Konami', ARRAY['Capcom', 'Namco', 'Sega'], 'fr', true),
('jeux_video', 4, 'Dans quel jeu apparait pour la premiere fois Samus Aran ?', 'Metroid', ARRAY['Super Metroid', 'Metroid Prime', 'Metroid Fusion'], 'fr', true),
('jeux_video', 4, 'Quel est le premier jeu a avoir utilise la technique du cel-shading ?', 'Jet Set Radio', ARRAY['Wind Waker', 'XIII', 'Borderlands'], 'fr', true),
('jeux_video', 4, 'Combien d''exemplaires la Wii s''est-elle vendue dans le monde ?', '101 millions', ARRAY['85 millions', '95 millions', '115 millions'], 'fr', true),
('jeux_video', 4, 'Quel jeu de tir a la premiere personne a invente le headshot ?', 'GoldenEye 007', ARRAY['Doom', 'Quake', 'Half-Life'], 'fr', true),
('jeux_video', 4, 'Quelle console Nintendo a ete un echec commercial majeur ?', 'Virtual Boy', ARRAY['Game Boy', 'SNES', 'N64'], 'fr', true),
('jeux_video', 4, 'Quel moteur de jeu a ete cree pour le premier Unreal ?', 'Unreal Engine', ARRAY['id Tech', 'Source', 'CryEngine'], 'fr', true),
('jeux_video', 4, 'En quelle annee Sony a-t-elle lance le PlayStation Network ?', '2006', ARRAY['2004', '2005', '2007'], 'fr', true),
('jeux_video', 4, 'Quel personnage de jeu video a ete le premier a avoir une etoile a Hollywood ?', 'Sonic', ARRAY['Mario', 'Pac-Man', 'Donkey Kong'], 'fr', true),
('jeux_video', 4, 'Quel est le jeu le plus vendu de tous les temps sur une seule plateforme ?', 'Wii Sports', ARRAY['Tetris', 'GTA V', 'Minecraft'], 'fr', true),
('jeux_video', 4, 'Quelle fut la premiere console a avoir un disque dur integre ?', 'Xbox', ARRAY['PS2', 'Dreamcast', 'GameCube'], 'fr', true),
('jeux_video', 4, 'Quel est le vrai nom de la mascotte Sonic ?', 'Sonic the Hedgehog', ARRAY['Mr. Needlemouse', 'Blue Blur', 'Speed'], 'fr', true),
('jeux_video', 4, 'Combien de pixels compose un sprite Mario dans Super Mario Bros ?', '16x16', ARRAY['8x8', '32x32', '24x24'], 'fr', true),
('jeux_video', 4, 'Quel jeu PC de 1998 a revolutionne les FPS narratifs ?', 'Half-Life', ARRAY['Quake II', 'Unreal', 'System Shock 2'], 'fr', true),
('jeux_video', 4, 'Quelle console a ete la premiere a supporter le jeu en ligne massivement ?', 'Dreamcast', ARRAY['PS2', 'Xbox', 'GameCube'], 'fr', true),

-- FRENCH - Niveau 5 (Expert - Faits obscurs et histoire profonde)
('jeux_video', 5, 'Quel est le premier jeu video de l''histoire reconnu ?', 'Tennis for Two', ARRAY['Pong', 'Spacewar!', 'Computer Space'], 'fr', true),
('jeux_video', 5, 'En quelle annee Shigeru Miyamoto a-t-il rejoint Nintendo ?', '1977', ARRAY['1975', '1980', '1983'], 'fr', true),
('jeux_video', 5, 'Quel etait le nom original de Pac-Man au Japon ?', 'Puck-Man', ARRAY['Pac-Man', 'Paku-Paku', 'Eat-Man'], 'fr', true),
('jeux_video', 5, 'Combien de copies le jeu E.T. d''Atari a-t-il ete enterre au Nouveau-Mexique ?', '728000', ARRAY['500000', '1 million', '250000'], 'fr', true),
('jeux_video', 5, 'Quel processeur equipait la premiere Xbox ?', 'Intel Pentium III', ARRAY['AMD Athlon', 'Intel Celeron', 'PowerPC'], 'fr', true),
('jeux_video', 5, 'Quelle societe a fabrique la premiere console de jeu video commerciale ?', 'Magnavox', ARRAY['Atari', 'Coleco', 'Mattel'], 'fr', true),
('jeux_video', 5, 'Quel est le code Konami complet ?', 'Haut Haut Bas Bas Gauche Droite Gauche Droite B A', ARRAY['Haut Bas Gauche Droite A B', 'A B Haut Bas Gauche Droite', 'Gauche Droite Haut Bas A B'], 'fr', true),
('jeux_video', 5, 'Quel jeu detient le record du plus gros budget de developpement ?', 'Star Citizen', ARRAY['GTA V', 'Cyberpunk 2077', 'Red Dead Redemption 2'], 'fr', true),
('jeux_video', 5, 'En quelle annee la Game Boy est-elle sortie au Japon ?', '1989', ARRAY['1987', '1990', '1991'], 'fr', true),
('jeux_video', 5, 'Quel est le premier jeu a avoir genere 1 milliard de dollars ?', 'GTA V', ARRAY['Call of Duty MW3', 'World of Warcraft', 'Minecraft'], 'fr', true),
('jeux_video', 5, 'Quelle frequence d''horloge avait le processeur de la NES ?', '1.79 MHz', ARRAY['2.5 MHz', '3.58 MHz', '1.0 MHz'], 'fr', true),
('jeux_video', 5, 'Quel jeu arcade a rapporte le plus d''argent dans les annees 80 ?', 'Pac-Man', ARRAY['Space Invaders', 'Donkey Kong', 'Asteroids'], 'fr', true),
('jeux_video', 5, 'Combien de temps a dure le developpement de Duke Nukem Forever ?', '15 ans', ARRAY['10 ans', '12 ans', '18 ans'], 'fr', true),
('jeux_video', 5, 'Quel est le premier jeu a avoir utilise la capture de mouvement ?', 'Prince of Persia', ARRAY['Mortal Kombat', 'Another World', 'Virtua Fighter'], 'fr', true),
('jeux_video', 5, 'Quelle console a ete la premiere a atteindre 100 millions de ventes ?', 'PlayStation', ARRAY['PS2', 'NES', 'Game Boy'], 'fr', true),
('jeux_video', 5, 'Quel developpeur a cree le premier roguelike graphique Rogue ?', 'Michael Toy et Glenn Wichman', ARRAY['Richard Garriott', 'Will Crowther', 'Don Woods'], 'fr', true),
('jeux_video', 5, 'Combien de RAM avait la Super Nintendo ?', '128 Ko', ARRAY['64 Ko', '256 Ko', '512 Ko'], 'fr', true),
('jeux_video', 5, 'Quel jeu a ete le premier a utiliser le mode 7 de la SNES ?', 'F-Zero', ARRAY['Super Mario Kart', 'Pilotwings', 'Super Mario World'], 'fr', true),
('jeux_video', 5, 'En quelle annee id Software a-t-il ete fonde ?', '1991', ARRAY['1989', '1990', '1993'], 'fr', true),
('jeux_video', 5, 'Quel est le premier MMORPG graphique ?', 'Neverwinter Nights (AOL)', ARRAY['Ultima Online', 'EverQuest', 'Meridian 59'], 'fr', true),

-- ENGLISH - Level 1 (Easy - Popular mainstream games)
('jeux_video', 1, 'What is the name of the main character in the Mario series?', 'Mario', ARRAY['Luigi', 'Bowser', 'Toad'], 'en', true),
('jeux_video', 1, 'In Minecraft, what is the most common block?', 'Stone', ARRAY['Diamond', 'Gold', 'Iron'], 'en', true),
('jeux_video', 1, 'What is the name of Epic Games'' battle royale released in 2017?', 'Fortnite', ARRAY['Apex Legends', 'PUBG', 'Warzone'], 'en', true),
('jeux_video', 1, 'Which Nintendo console is portable and hybrid?', 'Nintendo Switch', ARRAY['Wii U', 'Nintendo DS', 'Game Boy'], 'en', true),
('jeux_video', 1, 'What is the name of Mario''s green brother?', 'Luigi', ARRAY['Wario', 'Waluigi', 'Toad'], 'en', true),
('jeux_video', 1, 'In Pokemon, what is the fire-type starter from the first generation?', 'Charmander', ARRAY['Bulbasaur', 'Squirtle', 'Pikachu'], 'en', true),
('jeux_video', 1, 'Which brand manufactures the PlayStation?', 'Sony', ARRAY['Microsoft', 'Nintendo', 'Sega'], 'en', true),
('jeux_video', 1, 'What racing game features Mario and his friends?', 'Mario Kart', ARRAY['Gran Turismo', 'Need for Speed', 'Forza'], 'en', true),
('jeux_video', 1, 'What is the name of the hero in The Legend of Zelda?', 'Link', ARRAY['Zelda', 'Ganondorf', 'Sheik'], 'en', true),
('jeux_video', 1, 'Which game lets you build with pixel blocks?', 'Minecraft', ARRAY['Roblox', 'Terraria', 'Lego Worlds'], 'en', true),
('jeux_video', 1, 'Which yellow creature is the mascot of Pokemon?', 'Pikachu', ARRAY['Jigglypuff', 'Eevee', 'Mewtwo'], 'en', true),
('jeux_video', 1, 'Who is Mario''s main enemy?', 'Bowser', ARRAY['Donkey Kong', 'Wario', 'Koopa'], 'en', true),
('jeux_video', 1, 'In which game do you play soccer with cars?', 'Rocket League', ARRAY['FIFA', 'GTA', 'Need for Speed'], 'en', true),
('jeux_video', 1, 'Which online battle game features heroes and champions?', 'League of Legends', ARRAY['Counter-Strike', 'Valorant', 'Overwatch'], 'en', true),
('jeux_video', 1, 'Which Microsoft console competes with PlayStation?', 'Xbox', ARRAY['Nintendo', 'Sega', 'Atari'], 'en', true),
('jeux_video', 1, 'In Fortnite, what is the famous dance called?', 'Floss', ARRAY['Dab', 'Moonwalk', 'Robot'], 'en', true),
('jeux_video', 1, 'Which pink Nintendo character can fly?', 'Kirby', ARRAY['Jigglypuff', 'Peach', 'Toad'], 'en', true),
('jeux_video', 1, 'Which life simulation game features animal villagers?', 'Animal Crossing', ARRAY['Stardew Valley', 'Harvest Moon', 'The Sims'], 'en', true),
('jeux_video', 1, 'Which princess does Mario often have to rescue?', 'Peach', ARRAY['Zelda', 'Daisy', 'Rosalina'], 'en', true),
('jeux_video', 1, 'Which mobile game lets you catch Pokemon in the real world?', 'Pokemon GO', ARRAY['Pokemon Unite', 'Pokemon Masters', 'Pokemon Sleep'], 'en', true),

-- ENGLISH - Level 2 (Medium - General gaming culture)
('jeux_video', 2, 'Which studio created The Last of Us?', 'Naughty Dog', ARRAY['Rockstar', 'Ubisoft', 'Bethesda'], 'en', true),
('jeux_video', 2, 'In GTA V, how many main playable characters are there?', '3', ARRAY['1', '2', '4'], 'en', true),
('jeux_video', 2, 'Which survival game takes place on an island with dinosaurs?', 'ARK: Survival Evolved', ARRAY['Rust', 'DayZ', 'The Forest'], 'en', true),
('jeux_video', 2, 'Which game series features an assassin throughout history?', 'Assassin''s Creed', ARRAY['Hitman', 'Splinter Cell', 'Metal Gear'], 'en', true),
('jeux_video', 2, 'What is the name of Call of Duty''s zombie mode?', 'Zombies', ARRAY['Outbreak', 'Survival', 'Horde'], 'en', true),
('jeux_video', 2, 'In which game do you explore space with a spacecraft?', 'No Man''s Sky', ARRAY['Star Citizen', 'Elite Dangerous', 'Eve Online'], 'en', true),
('jeux_video', 2, 'Which fighting game features Nintendo characters?', 'Super Smash Bros.', ARRAY['Tekken', 'Street Fighter', 'Mortal Kombat'], 'en', true),
('jeux_video', 2, 'Which company created Overwatch?', 'Blizzard', ARRAY['Valve', 'Riot Games', 'Epic Games'], 'en', true),
('jeux_video', 2, 'In Minecraft, what final boss is found in the End?', 'Ender Dragon', ARRAY['Wither', 'Herobrine', 'Elder Guardian'], 'en', true),
('jeux_video', 2, 'Which esport is most popular in South Korea?', 'League of Legends', ARRAY['Dota 2', 'CS:GO', 'Overwatch'], 'en', true),
('jeux_video', 2, 'Which Bethesda game series takes place in a post-apocalyptic world?', 'Fallout', ARRAY['Elder Scrolls', 'Doom', 'Wolfenstein'], 'en', true),
('jeux_video', 2, 'In Zelda, what magical instrument does Link often use?', 'Ocarina', ARRAY['Flute', 'Harp', 'Drums'], 'en', true),
('jeux_video', 2, 'Which CD Projekt Red game features Geralt of Rivia?', 'The Witcher', ARRAY['Cyberpunk 2077', 'Gwent', 'Thronebreaker'], 'en', true),
('jeux_video', 2, 'Which Sony handheld preceded the PS Vita?', 'PSP', ARRAY['PS One', 'PS Mini', 'PS Go'], 'en', true),
('jeux_video', 2, 'In which game do you play as a hunter of giant monsters?', 'Monster Hunter', ARRAY['Dark Souls', 'God of War', 'Devil May Cry'], 'en', true),
('jeux_video', 2, 'Which life simulation game was created by Will Wright?', 'The Sims', ARRAY['Animal Crossing', 'Stardew Valley', 'Second Life'], 'en', true),
('jeux_video', 2, 'Which PC game distribution platform belongs to Valve?', 'Steam', ARRAY['Epic Games Store', 'GOG', 'Origin'], 'en', true),
('jeux_video', 2, 'In Red Dead Redemption 2, what is the protagonist''s name?', 'Arthur Morgan', ARRAY['John Marston', 'Dutch', 'Micah'], 'en', true),
('jeux_video', 2, 'Which From Software game is known for extreme difficulty?', 'Dark Souls', ARRAY['Sekiro', 'Bloodborne', 'Elden Ring'], 'en', true),
('jeux_video', 2, 'Which arcade racing series features exotic cars?', 'Need for Speed', ARRAY['Gran Turismo', 'Forza', 'Burnout'], 'en', true),

-- ENGLISH - Level 3 (Hard - In-depth knowledge)
('jeux_video', 3, 'In what year was the first PlayStation released in Japan?', '1994', ARRAY['1992', '1995', '1996'], 'en', true),
('jeux_video', 3, 'What is Master Chief''s real name in Halo?', 'John-117', ARRAY['James-117', 'Jack-117', 'Joseph-117'], 'en', true),
('jeux_video', 3, 'Which studio developed the first The Elder Scrolls?', 'Bethesda', ARRAY['Bioware', 'Obsidian', 'CD Projekt'], 'en', true),
('jeux_video', 3, 'In World of Warcraft, how many classes were available at launch?', '9', ARRAY['8', '10', '12'], 'en', true),
('jeux_video', 3, 'Which game popularized the battle royale genre before Fortnite?', 'PUBG', ARRAY['H1Z1', 'DayZ', 'Arma'], 'en', true),
('jeux_video', 3, 'Which Japanese company created Pac-Man?', 'Namco', ARRAY['Sega', 'Konami', 'Capcom'], 'en', true),
('jeux_video', 3, 'In Metal Gear Solid, what is the hero''s code name?', 'Solid Snake', ARRAY['Big Boss', 'Liquid Snake', 'Raiden'], 'en', true),
('jeux_video', 3, 'Which Rockstar game takes place in a city inspired by Los Angeles?', 'GTA V', ARRAY['GTA IV', 'GTA San Andreas', 'LA Noire'], 'en', true),
('jeux_video', 3, 'How many main Nintendo console generations have there been?', '9', ARRAY['7', '8', '10'], 'en', true),
('jeux_video', 3, 'Which Street Fighter character is nicknamed "The World Warrior"?', 'Ryu', ARRAY['Ken', 'Guile', 'Chun-Li'], 'en', true),
('jeux_video', 3, 'In which city does Bioshock mainly take place?', 'Rapture', ARRAY['Columbia', 'Arcadia', 'Neptune'], 'en', true),
('jeux_video', 3, 'Which game introduced the concept of permadeath to mainstream gaming?', 'Rogue', ARRAY['NetHack', 'Angband', 'ADOM'], 'en', true),
('jeux_video', 3, 'Which console was the first to use CDs as its media format?', 'PC Engine CD', ARRAY['PlayStation', 'Sega CD', 'Neo Geo CD'], 'en', true),
('jeux_video', 3, 'What is the name of Metal Gear''s creator?', 'Hideo Kojima', ARRAY['Shigeru Miyamoto', 'Shinji Mikami', 'Hidetaka Miyazaki'], 'en', true),
('jeux_video', 3, 'In Resident Evil, which virus causes the zombie outbreak?', 'T-Virus', ARRAY['G-Virus', 'C-Virus', 'Las Plagas'], 'en', true),
('jeux_video', 3, 'Which Valve game never had a third installment?', 'Half-Life', ARRAY['Portal', 'Left 4 Dead', 'Team Fortress'], 'en', true),
('jeux_video', 3, 'Which esports team won the first League of Legends World Championship?', 'Fnatic', ARRAY['SK Gaming', 'TSM', 'CLG'], 'en', true),
('jeux_video', 3, 'In Final Fantasy VII, what is the name of the antagonist corporation?', 'Shinra', ARRAY['Midgar', 'Avalanche', 'Soldier'], 'en', true),
('jeux_video', 3, 'Which simulation game has let players build cities since 1989?', 'SimCity', ARRAY['Cities Skylines', 'Civilization', 'Anno'], 'en', true),
('jeux_video', 3, 'Which Sega console was launched to compete with the Super Nintendo?', 'Genesis', ARRAY['Saturn', 'Dreamcast', 'Master System'], 'en', true),

-- ENGLISH - Level 4 (Very Hard - Retro and technical culture)
('jeux_video', 4, 'In what year was the first Doom released?', '1993', ARRAY['1991', '1992', '1994'], 'en', true),
('jeux_video', 4, 'What was the code name of the Nintendo 64 during development?', 'Project Reality', ARRAY['Ultra 64', 'Nintendo Ultra', 'Project N64'], 'en', true),
('jeux_video', 4, 'How many bits did the Sega Genesis processor have?', '16', ARRAY['8', '32', '64'], 'en', true),
('jeux_video', 4, 'Which Atari game caused the industry crash of 1983?', 'E.T.', ARRAY['Pac-Man', 'Asteroids', 'Centipede'], 'en', true),
('jeux_video', 4, 'What is the native resolution of the original Game Boy?', '160x144', ARRAY['160x160', '128x128', '240x160'], 'en', true),
('jeux_video', 4, 'Which studio created the first Castlevania?', 'Konami', ARRAY['Capcom', 'Namco', 'Sega'], 'en', true),
('jeux_video', 4, 'In which game does Samus Aran first appear?', 'Metroid', ARRAY['Super Metroid', 'Metroid Prime', 'Metroid Fusion'], 'en', true),
('jeux_video', 4, 'What was the first game to use cel-shading technique?', 'Jet Set Radio', ARRAY['Wind Waker', 'XIII', 'Borderlands'], 'en', true),
('jeux_video', 4, 'How many units did the Wii sell worldwide?', '101 million', ARRAY['85 million', '95 million', '115 million'], 'en', true),
('jeux_video', 4, 'Which first-person shooter invented the headshot?', 'GoldenEye 007', ARRAY['Doom', 'Quake', 'Half-Life'], 'en', true),
('jeux_video', 4, 'Which Nintendo console was a major commercial failure?', 'Virtual Boy', ARRAY['Game Boy', 'SNES', 'N64'], 'en', true),
('jeux_video', 4, 'Which game engine was created for the first Unreal?', 'Unreal Engine', ARRAY['id Tech', 'Source', 'CryEngine'], 'en', true),
('jeux_video', 4, 'In what year did Sony launch the PlayStation Network?', '2006', ARRAY['2004', '2005', '2007'], 'en', true),
('jeux_video', 4, 'Which video game character was the first to have a star on Hollywood?', 'Sonic', ARRAY['Mario', 'Pac-Man', 'Donkey Kong'], 'en', true),
('jeux_video', 4, 'What is the best-selling game of all time on a single platform?', 'Wii Sports', ARRAY['Tetris', 'GTA V', 'Minecraft'], 'en', true),
('jeux_video', 4, 'Which was the first console to have a built-in hard drive?', 'Xbox', ARRAY['PS2', 'Dreamcast', 'GameCube'], 'en', true),
('jeux_video', 4, 'What is Sonic''s full official name?', 'Sonic the Hedgehog', ARRAY['Mr. Needlemouse', 'Blue Blur', 'Speed'], 'en', true),
('jeux_video', 4, 'How many pixels make up a Mario sprite in Super Mario Bros?', '16x16', ARRAY['8x8', '32x32', '24x24'], 'en', true),
('jeux_video', 4, 'Which 1998 PC game revolutionized narrative FPS games?', 'Half-Life', ARRAY['Quake II', 'Unreal', 'System Shock 2'], 'en', true),
('jeux_video', 4, 'Which console was the first to support massively online gaming?', 'Dreamcast', ARRAY['PS2', 'Xbox', 'GameCube'], 'en', true),

-- ENGLISH - Level 5 (Expert - Obscure facts and deep history)
('jeux_video', 5, 'What is recognized as the first video game in history?', 'Tennis for Two', ARRAY['Pong', 'Spacewar!', 'Computer Space'], 'en', true),
('jeux_video', 5, 'In what year did Shigeru Miyamoto join Nintendo?', '1977', ARRAY['1975', '1980', '1983'], 'en', true),
('jeux_video', 5, 'What was Pac-Man''s original name in Japan?', 'Puck-Man', ARRAY['Pac-Man', 'Paku-Paku', 'Eat-Man'], 'en', true),
('jeux_video', 5, 'How many copies of Atari''s E.T. game were buried in New Mexico?', '728000', ARRAY['500000', '1 million', '250000'], 'en', true),
('jeux_video', 5, 'What processor powered the original Xbox?', 'Intel Pentium III', ARRAY['AMD Athlon', 'Intel Celeron', 'PowerPC'], 'en', true),
('jeux_video', 5, 'Which company manufactured the first commercial video game console?', 'Magnavox', ARRAY['Atari', 'Coleco', 'Mattel'], 'en', true),
('jeux_video', 5, 'What is the complete Konami Code?', 'Up Up Down Down Left Right Left Right B A', ARRAY['Up Down Left Right A B', 'A B Up Down Left Right', 'Left Right Up Down A B'], 'en', true),
('jeux_video', 5, 'Which game holds the record for the largest development budget?', 'Star Citizen', ARRAY['GTA V', 'Cyberpunk 2077', 'Red Dead Redemption 2'], 'en', true),
('jeux_video', 5, 'In what year was the Game Boy released in Japan?', '1989', ARRAY['1987', '1990', '1991'], 'en', true),
('jeux_video', 5, 'What was the first game to generate 1 billion dollars?', 'GTA V', ARRAY['Call of Duty MW3', 'World of Warcraft', 'Minecraft'], 'en', true),
('jeux_video', 5, 'What was the clock frequency of the NES processor?', '1.79 MHz', ARRAY['2.5 MHz', '3.58 MHz', '1.0 MHz'], 'en', true),
('jeux_video', 5, 'Which arcade game generated the most revenue in the 1980s?', 'Pac-Man', ARRAY['Space Invaders', 'Donkey Kong', 'Asteroids'], 'en', true),
('jeux_video', 5, 'How long was Duke Nukem Forever in development?', '15 years', ARRAY['10 years', '12 years', '18 years'], 'en', true),
('jeux_video', 5, 'What was the first game to use motion capture?', 'Prince of Persia', ARRAY['Mortal Kombat', 'Another World', 'Virtua Fighter'], 'en', true),
('jeux_video', 5, 'Which console was the first to reach 100 million sales?', 'PlayStation', ARRAY['PS2', 'NES', 'Game Boy'], 'en', true),
('jeux_video', 5, 'Who developed the first graphical roguelike Rogue?', 'Michael Toy and Glenn Wichman', ARRAY['Richard Garriott', 'Will Crowther', 'Don Woods'], 'en', true),
('jeux_video', 5, 'How much RAM did the Super Nintendo have?', '128 KB', ARRAY['64 KB', '256 KB', '512 KB'], 'en', true),
('jeux_video', 5, 'What was the first game to use the SNES Mode 7?', 'F-Zero', ARRAY['Super Mario Kart', 'Pilotwings', 'Super Mario World'], 'en', true),
('jeux_video', 5, 'In what year was id Software founded?', '1991', ARRAY['1989', '1990', '1993'], 'en', true),
('jeux_video', 5, 'What was the first graphical MMORPG?', 'Neverwinter Nights (AOL)', ARRAY['Ultima Online', 'EverQuest', 'Meridian 59'], 'en', true);
