-- Add 100+ more English questions across various categories

INSERT INTO questions (question_text, correct_answer, wrong_answers, category, is_active, difficulty, language) VALUES

-- HISTORY (20 questions)
('Who was the first President of the United States?', 'George Washington', ARRAY['Thomas Jefferson', 'Abraham Lincoln', 'John Adams'], 'history', true, 1, 'en'),
('In which year did World War II end?', '1945', ARRAY['1944', '1946', '1943'], 'history', true, 1, 'en'),
('Which ancient civilization built the pyramids of Giza?', 'Egyptians', ARRAY['Romans', 'Greeks', 'Persians'], 'history', true, 1, 'en'),
('Who discovered America in 1492?', 'Christopher Columbus', ARRAY['Vasco da Gama', 'Ferdinand Magellan', 'Marco Polo'], 'history', true, 1, 'en'),
('Which empire was ruled by Julius Caesar?', 'Roman Empire', ARRAY['Greek Empire', 'Persian Empire', 'Ottoman Empire'], 'history', true, 1, 'en'),
('What year did the Berlin Wall fall?', '1989', ARRAY['1987', '1991', '1985'], 'history', true, 2, 'en'),
('Who was the first man to walk on the Moon?', 'Neil Armstrong', ARRAY['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], 'history', true, 1, 'en'),
('Which war was fought between the North and South in the USA?', 'Civil War', ARRAY['Revolutionary War', 'War of 1812', 'Mexican-American War'], 'history', true, 1, 'en'),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', ARRAY['Michelangelo', 'Raphael', 'Rembrandt'], 'history', true, 1, 'en'),
('In which city was the Titanic built?', 'Belfast', ARRAY['London', 'Liverpool', 'Southampton'], 'history', true, 2, 'en'),
('Who was the leader of Nazi Germany?', 'Adolf Hitler', ARRAY['Joseph Stalin', 'Benito Mussolini', 'Francisco Franco'], 'history', true, 1, 'en'),
('Which country was the first to grant women the right to vote?', 'New Zealand', ARRAY['United States', 'United Kingdom', 'France'], 'history', true, 2, 'en'),
('What ancient wonder was located in Alexandria?', 'Lighthouse', ARRAY['Colossus', 'Hanging Gardens', 'Mausoleum'], 'history', true, 2, 'en'),
('Who wrote the Declaration of Independence?', 'Thomas Jefferson', ARRAY['George Washington', 'Benjamin Franklin', 'John Adams'], 'history', true, 1, 'en'),
('Which queen ruled England for 63 years until 1901?', 'Queen Victoria', ARRAY['Queen Elizabeth I', 'Queen Mary', 'Queen Anne'], 'history', true, 2, 'en'),
('What was the name of the ship that brought Pilgrims to America?', 'Mayflower', ARRAY['Santa Maria', 'Endeavour', 'Beagle'], 'history', true, 1, 'en'),
('Who was assassinated in Sarajevo in 1914, starting WWI?', 'Archduke Franz Ferdinand', ARRAY['Kaiser Wilhelm II', 'Tsar Nicholas II', 'King George V'], 'history', true, 2, 'en'),
('Which civilization invented paper?', 'Chinese', ARRAY['Egyptian', 'Roman', 'Greek'], 'history', true, 1, 'en'),
('What year did the French Revolution begin?', '1789', ARRAY['1776', '1799', '1815'], 'history', true, 1, 'en'),
('Who was the first female Prime Minister of the UK?', 'Margaret Thatcher', ARRAY['Theresa May', 'Queen Victoria', 'Elizabeth II'], 'history', true, 1, 'en'),

-- GEOGRAPHY (20 questions)
('What is the largest country in the world by area?', 'Russia', ARRAY['Canada', 'China', 'United States'], 'geography', true, 1, 'en'),
('Which river is the longest in the world?', 'Nile', ARRAY['Amazon', 'Yangtze', 'Mississippi'], 'geography', true, 1, 'en'),
('What is the capital of Japan?', 'Tokyo', ARRAY['Kyoto', 'Osaka', 'Hiroshima'], 'geography', true, 1, 'en'),
('Which mountain is the tallest in the world?', 'Mount Everest', ARRAY['K2', 'Kangchenjunga', 'Mont Blanc'], 'geography', true, 1, 'en'),
('What is the smallest country in the world?', 'Vatican City', ARRAY['Monaco', 'San Marino', 'Liechtenstein'], 'geography', true, 1, 'en'),
('Which ocean is the largest?', 'Pacific Ocean', ARRAY['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'geography', true, 1, 'en'),
('What is the capital of Canada?', 'Ottawa', ARRAY['Toronto', 'Vancouver', 'Montreal'], 'geography', true, 1, 'en'),
('Which desert is the largest in the world?', 'Sahara', ARRAY['Arabian', 'Gobi', 'Kalahari'], 'geography', true, 1, 'en'),
('What is the capital of Brazil?', 'Brasilia', ARRAY['Rio de Janeiro', 'Sao Paulo', 'Salvador'], 'geography', true, 2, 'en'),
('Which country has the most islands?', 'Sweden', ARRAY['Indonesia', 'Finland', 'Philippines'], 'geography', true, 2, 'en'),
('What is the deepest lake in the world?', 'Lake Baikal', ARRAY['Lake Superior', 'Lake Tanganyika', 'Caspian Sea'], 'geography', true, 2, 'en'),
('Which continent has the most countries?', 'Africa', ARRAY['Europe', 'Asia', 'South America'], 'geography', true, 1, 'en'),
('What is the capital of South Korea?', 'Seoul', ARRAY['Busan', 'Incheon', 'Daegu'], 'geography', true, 1, 'en'),
('Which country is known as the Land of the Rising Sun?', 'Japan', ARRAY['China', 'Thailand', 'Vietnam'], 'geography', true, 1, 'en'),
('What is the longest wall in the world?', 'Great Wall of China', ARRAY['Hadrian''s Wall', 'Berlin Wall', 'Western Wall'], 'geography', true, 1, 'en'),
('Which waterfall is the highest in the world?', 'Angel Falls', ARRAY['Niagara Falls', 'Victoria Falls', 'Iguazu Falls'], 'geography', true, 2, 'en'),
('What is the capital of Egypt?', 'Cairo', ARRAY['Alexandria', 'Luxor', 'Giza'], 'geography', true, 1, 'en'),
('Which strait separates Europe from Africa?', 'Strait of Gibraltar', ARRAY['Bosphorus', 'English Channel', 'Suez Canal'], 'geography', true, 2, 'en'),
('What is the largest island in the world?', 'Greenland', ARRAY['Madagascar', 'Borneo', 'New Guinea'], 'geography', true, 1, 'en'),
('Which country has the longest coastline?', 'Canada', ARRAY['Australia', 'Russia', 'Indonesia'], 'geography', true, 2, 'en'),

-- SCIENCE (20 questions)
('What is the chemical symbol for gold?', 'Au', ARRAY['Ag', 'Fe', 'Cu'], 'science', true, 1, 'en'),
('How many planets are in our solar system?', '8', ARRAY['9', '7', '10'], 'science', true, 1, 'en'),
('What is the largest organ in the human body?', 'Skin', ARRAY['Liver', 'Heart', 'Brain'], 'science', true, 1, 'en'),
('What gas do plants absorb from the atmosphere?', 'Carbon dioxide', ARRAY['Oxygen', 'Nitrogen', 'Hydrogen'], 'science', true, 1, 'en'),
('What is the speed of light approximately?', '300,000 km/s', ARRAY['150,000 km/s', '500,000 km/s', '1,000,000 km/s'], 'science', true, 2, 'en'),
('Which planet is known as the Red Planet?', 'Mars', ARRAY['Jupiter', 'Venus', 'Saturn'], 'science', true, 1, 'en'),
('What is the hardest natural substance on Earth?', 'Diamond', ARRAY['Gold', 'Iron', 'Quartz'], 'science', true, 1, 'en'),
('How many bones are in the adult human body?', '206', ARRAY['186', '226', '256'], 'science', true, 2, 'en'),
('What is the most abundant gas in Earth''s atmosphere?', 'Nitrogen', ARRAY['Oxygen', 'Carbon dioxide', 'Argon'], 'science', true, 1, 'en'),
('Which blood type is the universal donor?', 'O negative', ARRAY['A positive', 'AB positive', 'B negative'], 'science', true, 2, 'en'),
('What is the smallest unit of matter?', 'Atom', ARRAY['Molecule', 'Cell', 'Electron'], 'science', true, 1, 'en'),
('Which planet has the most moons?', 'Saturn', ARRAY['Jupiter', 'Uranus', 'Neptune'], 'science', true, 2, 'en'),
('What is the boiling point of water in Celsius?', '100°C', ARRAY['90°C', '110°C', '120°C'], 'science', true, 1, 'en'),
('What type of animal is a dolphin?', 'Mammal', ARRAY['Fish', 'Reptile', 'Amphibian'], 'science', true, 1, 'en'),
('Who developed the theory of relativity?', 'Albert Einstein', ARRAY['Isaac Newton', 'Stephen Hawking', 'Nikola Tesla'], 'science', true, 1, 'en'),
('What is the center of an atom called?', 'Nucleus', ARRAY['Electron', 'Proton', 'Neutron'], 'science', true, 1, 'en'),
('Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin D', ARRAY['Vitamin C', 'Vitamin A', 'Vitamin B'], 'science', true, 2, 'en'),
('What is the largest planet in our solar system?', 'Jupiter', ARRAY['Saturn', 'Neptune', 'Uranus'], 'science', true, 1, 'en'),
('How many chromosomes do humans have?', '46', ARRAY['23', '48', '44'], 'science', true, 2, 'en'),
('What force keeps planets in orbit around the Sun?', 'Gravity', ARRAY['Magnetism', 'Friction', 'Inertia'], 'science', true, 1, 'en'),

-- SPORTS (20 questions)
('How many players are on a soccer team on the field?', '11', ARRAY['10', '12', '9'], 'sports', true, 1, 'en'),
('Which country has won the most FIFA World Cups?', 'Brazil', ARRAY['Germany', 'Italy', 'Argentina'], 'sports', true, 1, 'en'),
('In which sport would you perform a slam dunk?', 'Basketball', ARRAY['Volleyball', 'Tennis', 'Baseball'], 'sports', true, 1, 'en'),
('How many rings are on the Olympic flag?', '5', ARRAY['4', '6', '7'], 'sports', true, 1, 'en'),
('Which tennis tournament is played on grass?', 'Wimbledon', ARRAY['US Open', 'French Open', 'Australian Open'], 'sports', true, 1, 'en'),
('What sport is played at Augusta National?', 'Golf', ARRAY['Tennis', 'Polo', 'Cricket'], 'sports', true, 1, 'en'),
('How many points is a touchdown worth in American football?', '6', ARRAY['7', '3', '5'], 'sports', true, 1, 'en'),
('Which country invented cricket?', 'England', ARRAY['Australia', 'India', 'South Africa'], 'sports', true, 1, 'en'),
('What is the national sport of Japan?', 'Sumo wrestling', ARRAY['Judo', 'Karate', 'Baseball'], 'sports', true, 2, 'en'),
('How long is an Olympic swimming pool?', '50 meters', ARRAY['25 meters', '100 meters', '75 meters'], 'sports', true, 1, 'en'),
('Which boxer was known as "The Greatest"?', 'Muhammad Ali', ARRAY['Mike Tyson', 'Floyd Mayweather', 'Joe Louis'], 'sports', true, 1, 'en'),
('In which city were the first modern Olympics held?', 'Athens', ARRAY['Paris', 'London', 'Rome'], 'sports', true, 1, 'en'),
('How many holes are played in a standard round of golf?', '18', ARRAY['9', '12', '21'], 'sports', true, 1, 'en'),
('Which sport uses a shuttlecock?', 'Badminton', ARRAY['Tennis', 'Squash', 'Table Tennis'], 'sports', true, 1, 'en'),
('What is the maximum score in a single frame of bowling?', '30', ARRAY['10', '20', '300'], 'sports', true, 2, 'en'),
('Which country hosted the 2016 Summer Olympics?', 'Brazil', ARRAY['China', 'UK', 'Russia'], 'sports', true, 1, 'en'),
('In baseball, how many strikes make an out?', '3', ARRAY['2', '4', '5'], 'sports', true, 1, 'en'),
('Which sport is known as "the beautiful game"?', 'Soccer/Football', ARRAY['Basketball', 'Tennis', 'Cricket'], 'sports', true, 1, 'en'),
('How many periods are in an NHL hockey game?', '3', ARRAY['2', '4', '5'], 'sports', true, 1, 'en'),
('What color jersey does the Tour de France leader wear?', 'Yellow', ARRAY['Green', 'Red', 'Blue'], 'sports', true, 1, 'en'),

-- ENTERTAINMENT (20 questions)
('Who played Jack in the movie Titanic?', 'Leonardo DiCaprio', ARRAY['Brad Pitt', 'Tom Cruise', 'Johnny Depp'], 'entertainment', true, 1, 'en'),
('Which band sang "Bohemian Rhapsody"?', 'Queen', ARRAY['The Beatles', 'Led Zeppelin', 'Pink Floyd'], 'entertainment', true, 1, 'en'),
('What is the highest-grossing film of all time?', 'Avatar', ARRAY['Avengers: Endgame', 'Titanic', 'Star Wars'], 'entertainment', true, 2, 'en'),
('Who is the author of Harry Potter?', 'J.K. Rowling', ARRAY['Stephen King', 'J.R.R. Tolkien', 'George R.R. Martin'], 'entertainment', true, 1, 'en'),
('Which TV show features dragons and the Iron Throne?', 'Game of Thrones', ARRAY['The Witcher', 'Lord of the Rings', 'Vikings'], 'entertainment', true, 1, 'en'),
('Who sang "Thriller"?', 'Michael Jackson', ARRAY['Prince', 'Madonna', 'Whitney Houston'], 'entertainment', true, 1, 'en'),
('What is the name of Batman''s butler?', 'Alfred', ARRAY['James', 'Thomas', 'Richard'], 'entertainment', true, 1, 'en'),
('Which Disney movie features a character named Simba?', 'The Lion King', ARRAY['Aladdin', 'Tarzan', 'Jungle Book'], 'entertainment', true, 1, 'en'),
('Who directed Jurassic Park?', 'Steven Spielberg', ARRAY['James Cameron', 'George Lucas', 'Christopher Nolan'], 'entertainment', true, 1, 'en'),
('What instrument did Jimi Hendrix play?', 'Guitar', ARRAY['Drums', 'Piano', 'Bass'], 'entertainment', true, 1, 'en'),
('Which movie features the quote "I''ll be back"?', 'The Terminator', ARRAY['Predator', 'Total Recall', 'Commando'], 'entertainment', true, 1, 'en'),
('Who painted "Starry Night"?', 'Vincent van Gogh', ARRAY['Pablo Picasso', 'Claude Monet', 'Salvador Dali'], 'entertainment', true, 1, 'en'),
('What is the name of the coffee shop in Friends?', 'Central Perk', ARRAY['The Coffee House', 'Java Joe''s', 'Morning Brew'], 'entertainment', true, 1, 'en'),
('Which superhero is known as the "Man of Steel"?', 'Superman', ARRAY['Iron Man', 'Batman', 'Captain America'], 'entertainment', true, 1, 'en'),
('Who wrote "Romeo and Juliet"?', 'William Shakespeare', ARRAY['Charles Dickens', 'Jane Austen', 'Oscar Wilde'], 'entertainment', true, 1, 'en'),
('What year was the first iPhone released?', '2007', ARRAY['2005', '2008', '2010'], 'entertainment', true, 2, 'en'),
('Which band performed at the first Live Aid concert?', 'Status Quo', ARRAY['Queen', 'U2', 'The Who'], 'entertainment', true, 2, 'en'),
('What is the name of Sherlock Holmes'' assistant?', 'Dr. Watson', ARRAY['Dr. Jekyll', 'Dr. Moriarty', 'Dr. Lestrade'], 'entertainment', true, 1, 'en'),
('Which movie won the first Academy Award for Best Picture?', 'Wings', ARRAY['Sunrise', 'The Jazz Singer', 'Metropolis'], 'entertainment', true, 3, 'en'),
('Who is the lead singer of U2?', 'Bono', ARRAY['The Edge', 'Adam Clayton', 'Larry Mullen Jr.'], 'entertainment', true, 1, 'en'),

-- TECHNOLOGY (10 questions)
('Who founded Microsoft?', 'Bill Gates', ARRAY['Steve Jobs', 'Mark Zuckerberg', 'Jeff Bezos'], 'technology', true, 1, 'en'),
('What does "HTTP" stand for?', 'HyperText Transfer Protocol', ARRAY['High Tech Transfer Protocol', 'Hyper Terminal Transfer Protocol', 'Home Text Transfer Protocol'], 'technology', true, 2, 'en'),
('Which company created the iPhone?', 'Apple', ARRAY['Samsung', 'Google', 'Microsoft'], 'technology', true, 1, 'en'),
('What year was Facebook founded?', '2004', ARRAY['2006', '2002', '2008'], 'technology', true, 2, 'en'),
('What does "AI" stand for?', 'Artificial Intelligence', ARRAY['Automated Integration', 'Advanced Internet', 'Auto Information'], 'technology', true, 1, 'en'),
('Who is the CEO of Tesla?', 'Elon Musk', ARRAY['Jeff Bezos', 'Tim Cook', 'Sundar Pichai'], 'technology', true, 1, 'en'),
('What programming language has a coffee cup logo?', 'Java', ARRAY['Python', 'C++', 'JavaScript'], 'technology', true, 2, 'en'),
('Which company owns Instagram?', 'Meta (Facebook)', ARRAY['Google', 'Twitter', 'Snapchat'], 'technology', true, 1, 'en'),
('What does "USB" stand for?', 'Universal Serial Bus', ARRAY['United System Bus', 'Universal System Backup', 'Ultra Speed Bus'], 'technology', true, 2, 'en'),
('Which company created Android?', 'Google', ARRAY['Apple', 'Microsoft', 'Samsung'], 'technology', true, 1, 'en'),

-- FOOD & DRINK (10 questions)
('What is the main ingredient in guacamole?', 'Avocado', ARRAY['Tomato', 'Onion', 'Lime'], 'food', true, 1, 'en'),
('Which country is famous for sushi?', 'Japan', ARRAY['China', 'Korea', 'Thailand'], 'food', true, 1, 'en'),
('What type of pasta is shaped like small rice grains?', 'Orzo', ARRAY['Penne', 'Fusilli', 'Rigatoni'], 'food', true, 2, 'en'),
('Which fruit is known as the "king of fruits"?', 'Durian', ARRAY['Mango', 'Pineapple', 'Jackfruit'], 'food', true, 2, 'en'),
('What is the main ingredient in hummus?', 'Chickpeas', ARRAY['Lentils', 'Black beans', 'Peanuts'], 'food', true, 1, 'en'),
('Which country produces the most coffee?', 'Brazil', ARRAY['Colombia', 'Vietnam', 'Ethiopia'], 'food', true, 1, 'en'),
('What gives bread its holes?', 'Yeast', ARRAY['Baking soda', 'Salt', 'Sugar'], 'food', true, 1, 'en'),
('Which cheese is traditionally used on pizza?', 'Mozzarella', ARRAY['Cheddar', 'Parmesan', 'Gouda'], 'food', true, 1, 'en'),
('What is the most consumed beverage in the world after water?', 'Tea', ARRAY['Coffee', 'Soda', 'Beer'], 'food', true, 1, 'en'),
('Which nut is used to make marzipan?', 'Almond', ARRAY['Walnut', 'Hazelnut', 'Pistachio'], 'food', true, 2, 'en')

ON CONFLICT DO NOTHING;
