-- Migration: Add 200 art questions (100 French + 100 English)
-- Categories cover: famous painters, sculptures, art movements, museums, art history
-- Difficulty levels 1-5, 20 questions per difficulty per language

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES

-- =====================================================
-- FRENCH QUESTIONS - Difficulty 1 (20 questions)
-- =====================================================
('art', 1, 'Qui a peint "La Joconde" (Mona Lisa) ?', 'Léonard de Vinci', ARRAY['Michel-Ange', 'Raphaël', 'Botticelli'], 'fr', true),
('art', 1, 'Dans quel musée parisien peut-on voir "La Joconde" ?', 'Le Louvre', ARRAY['Le Musée d''Orsay', 'Le Centre Pompidou', 'Le Petit Palais'], 'fr', true),
('art', 1, 'Qui a peint "La Nuit étoilée" ?', 'Vincent van Gogh', ARRAY['Claude Monet', 'Paul Cézanne', 'Paul Gauguin'], 'fr', true),
('art', 1, 'Quel artiste est célèbre pour ses tournesols ?', 'Vincent van Gogh', ARRAY['Claude Monet', 'Pierre-Auguste Renoir', 'Édouard Manet'], 'fr', true),
('art', 1, 'Qui a sculpté "David", la célèbre statue de Florence ?', 'Michel-Ange', ARRAY['Donatello', 'Bernin', 'Cellini'], 'fr', true),
('art', 1, 'Quel mouvement artistique Claude Monet représente-t-il ?', 'L''Impressionnisme', ARRAY['Le Cubisme', 'Le Surréalisme', 'Le Romantisme'], 'fr', true),
('art', 1, 'Qui a peint le plafond de la Chapelle Sixtine ?', 'Michel-Ange', ARRAY['Raphaël', 'Léonard de Vinci', 'Titien'], 'fr', true),
('art', 1, 'Quel artiste espagnol a cofondé le cubisme ?', 'Pablo Picasso', ARRAY['Salvador Dalí', 'Joan Miró', 'Francisco Goya'], 'fr', true),
('art', 1, 'Qui a peint "Le Cri" ?', 'Edvard Munch', ARRAY['Vincent van Gogh', 'Egon Schiele', 'Gustav Klimt'], 'fr', true),
('art', 1, 'Dans quel pays se trouve le musée du Prado ?', 'Espagne', ARRAY['Italie', 'France', 'Portugal'], 'fr', true),
('art', 1, 'Quelle est la technique de Léonard de Vinci qui crée un effet vaporeux ?', 'Le sfumato', ARRAY['Le clair-obscur', 'La perspective', 'L''aquarelle'], 'fr', true),
('art', 1, 'Qui a peint "Les Nymphéas" ?', 'Claude Monet', ARRAY['Pierre-Auguste Renoir', 'Edgar Degas', 'Camille Pissarro'], 'fr', true),
('art', 1, 'Quel artiste surréaliste est connu pour ses montres molles ?', 'Salvador Dalí', ARRAY['René Magritte', 'Max Ernst', 'Joan Miró'], 'fr', true),
('art', 1, 'De quelle nationalité était Rembrandt ?', 'Néerlandaise', ARRAY['Allemande', 'Belge', 'Française'], 'fr', true),
('art', 1, 'Qui a peint "La Jeune Fille à la perle" ?', 'Johannes Vermeer', ARRAY['Rembrandt', 'Frans Hals', 'Jan Steen'], 'fr', true),
('art', 1, 'Quel est le vrai nom de Le Greco ?', 'Domínikos Theotokópoulos', ARRAY['Diego Velázquez', 'Francisco de Zurbarán', 'Bartolomé Murillo'], 'fr', true),
('art', 1, 'Qui a créé "Le Penseur" ?', 'Auguste Rodin', ARRAY['Camille Claudel', 'Antoine Bourdelle', 'Aristide Maillol'], 'fr', true),
('art', 1, 'Quel artiste a coupé une partie de son oreille ?', 'Vincent van Gogh', ARRAY['Paul Gauguin', 'Henri de Toulouse-Lautrec', 'Paul Cézanne'], 'fr', true),
('art', 1, 'Qui a peint "La Liberté guidant le peuple" ?', 'Eugène Delacroix', ARRAY['Théodore Géricault', 'Jacques-Louis David', 'Jean-Auguste-Dominique Ingres'], 'fr', true),
('art', 1, 'Quel musée new-yorkais abrite "Les Demoiselles d''Avignon" ?', 'Le MoMA', ARRAY['Le Metropolitan Museum', 'Le Guggenheim', 'Le Whitney Museum'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - Difficulty 2 (20 questions)
-- =====================================================
('art', 2, 'Quel mouvement artistique est né à Paris au début du 20e siècle avec Picasso et Braque ?', 'Le Cubisme', ARRAY['Le Fauvisme', 'Le Dadaïsme', 'L''Expressionnisme'], 'fr', true),
('art', 2, 'Qui a peint "Le Déjeuner sur l''herbe" ?', 'Édouard Manet', ARRAY['Claude Monet', 'Pierre-Auguste Renoir', 'Gustave Courbet'], 'fr', true),
('art', 2, 'Quel artiste est associé aux danseuses de ballet ?', 'Edgar Degas', ARRAY['Henri de Toulouse-Lautrec', 'Pierre-Auguste Renoir', 'Berthe Morisot'], 'fr', true),
('art', 2, 'Dans quelle ville se trouve la Galerie des Offices ?', 'Florence', ARRAY['Rome', 'Venise', 'Milan'], 'fr', true),
('art', 2, 'Qui a peint "Les Ménines" ?', 'Diego Velázquez', ARRAY['Francisco Goya', 'El Greco', 'Bartolomé Murillo'], 'fr', true),
('art', 2, 'Quel mouvement Andy Warhol représente-t-il ?', 'Le Pop Art', ARRAY['L''Expressionnisme abstrait', 'Le Minimalisme', 'Le Néo-expressionnisme'], 'fr', true),
('art', 2, 'Qui a fondé l''école du Bauhaus ?', 'Walter Gropius', ARRAY['Ludwig Mies van der Rohe', 'Le Corbusier', 'Frank Lloyd Wright'], 'fr', true),
('art', 2, 'Quel peintre français est le maître du néoclassicisme ?', 'Jacques-Louis David', ARRAY['Jean-Auguste-Dominique Ingres', 'Eugène Delacroix', 'Théodore Géricault'], 'fr', true),
('art', 2, 'Qui a peint "Le Radeau de la Méduse" ?', 'Théodore Géricault', ARRAY['Eugène Delacroix', 'Jacques-Louis David', 'Anne-Louis Girodet'], 'fr', true),
('art', 2, 'Quel artiste a créé les "Mobiles" ?', 'Alexander Calder', ARRAY['Jean Tinguely', 'Naum Gabo', 'Constantin Brâncuși'], 'fr', true),
('art', 2, 'Qui a peint "Le Baiser" avec des motifs dorés ?', 'Gustav Klimt', ARRAY['Egon Schiele', 'Oskar Kokoschka', 'Koloman Moser'], 'fr', true),
('art', 2, 'Quel est le nom du mouvement artistique de Kandinsky ?', 'L''Art abstrait', ARRAY['L''Expressionnisme', 'Le Constructivisme', 'Le Suprématisme'], 'fr', true),
('art', 2, 'Qui a peint "American Gothic" ?', 'Grant Wood', ARRAY['Edward Hopper', 'Norman Rockwell', 'Andrew Wyeth'], 'fr', true),
('art', 2, 'Quel sculpteur a créé "L''Oiseau dans l''espace" ?', 'Constantin Brâncuși', ARRAY['Alberto Giacometti', 'Henry Moore', 'Jean Arp'], 'fr', true),
('art', 2, 'Qui a peint "Guernica" ?', 'Pablo Picasso', ARRAY['Joan Miró', 'Salvador Dalí', 'Juan Gris'], 'fr', true),
('art', 2, 'Quel mouvement artistique est caractérisé par des couleurs vives et non naturelles ?', 'Le Fauvisme', ARRAY['L''Impressionnisme', 'Le Pointillisme', 'Le Symbolisme'], 'fr', true),
('art', 2, 'Qui était le chef de file du fauvisme ?', 'Henri Matisse', ARRAY['André Derain', 'Maurice de Vlaminck', 'Raoul Dufy'], 'fr', true),
('art', 2, 'Quel artiste est connu pour ses peintures de boîtes de soupe Campbell ?', 'Andy Warhol', ARRAY['Roy Lichtenstein', 'Jasper Johns', 'Robert Rauschenberg'], 'fr', true),
('art', 2, 'Qui a peint "La Persistance de la mémoire" ?', 'Salvador Dalí', ARRAY['René Magritte', 'Max Ernst', 'Yves Tanguy'], 'fr', true),
('art', 2, 'Dans quel pays se trouve le musée de l''Ermitage ?', 'Russie', ARRAY['Allemagne', 'Autriche', 'Pologne'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - Difficulty 3 (20 questions)
-- =====================================================
('art', 3, 'Quel artiste a développé la technique du "dripping" ?', 'Jackson Pollock', ARRAY['Willem de Kooning', 'Mark Rothko', 'Franz Kline'], 'fr', true),
('art', 3, 'Qui a peint "La Grande Odalisque" ?', 'Jean-Auguste-Dominique Ingres', ARRAY['Jacques-Louis David', 'Eugène Delacroix', 'Théodore Chassériau'], 'fr', true),
('art', 3, 'Quel mouvement artistique Piet Mondrian représente-t-il ?', 'Le Néoplasticisme (De Stijl)', ARRAY['Le Suprématisme', 'Le Constructivisme', 'Le Bauhaus'], 'fr', true),
('art', 3, 'Qui a créé la sculpture "Fontaine" (un urinoir signé) ?', 'Marcel Duchamp', ARRAY['Man Ray', 'Francis Picabia', 'Jean Arp'], 'fr', true),
('art', 3, 'Quel artiste italien du baroque est connu pour son utilisation dramatique du clair-obscur ?', 'Le Caravage', ARRAY['Artemisia Gentileschi', 'Guido Reni', 'Annibale Carracci'], 'fr', true),
('art', 3, 'Qui a peint "Un bar aux Folies Bergère" ?', 'Édouard Manet', ARRAY['Henri de Toulouse-Lautrec', 'Edgar Degas', 'Pierre-Auguste Renoir'], 'fr', true),
('art', 3, 'Quel sculpteur italien a créé "L''Extase de Sainte Thérèse" ?', 'Gian Lorenzo Bernini (Le Bernin)', ARRAY['Michel-Ange', 'Donatello', 'Antonio Canova'], 'fr', true),
('art', 3, 'Qui a peint "La Ronde de nuit" ?', 'Rembrandt', ARRAY['Frans Hals', 'Johannes Vermeer', 'Jan Steen'], 'fr', true),
('art', 3, 'Quel mouvement artistique est né à Zurich en 1916 ?', 'Le Dadaïsme', ARRAY['Le Surréalisme', 'Le Futurisme', 'Le Constructivisme'], 'fr', true),
('art', 3, 'Qui a écrit le "Manifeste du Surréalisme" en 1924 ?', 'André Breton', ARRAY['Salvador Dalí', 'Max Ernst', 'René Magritte'], 'fr', true),
('art', 3, 'Quel peintre vénitien est connu pour ses œuvres religieuses monumentales ?', 'Tintoret', ARRAY['Titien', 'Véronèse', 'Giovanni Bellini'], 'fr', true),
('art', 3, 'Qui a peint "Le Jardin des délices" ?', 'Jérôme Bosch', ARRAY['Pieter Bruegel l''Ancien', 'Albrecht Dürer', 'Lucas Cranach'], 'fr', true),
('art', 3, 'Quel artiste américain est associé au mouvement "Color Field" ?', 'Mark Rothko', ARRAY['Jackson Pollock', 'Willem de Kooning', 'Robert Motherwell'], 'fr', true),
('art', 3, 'Qui a fondé le mouvement De Stijl ?', 'Theo van Doesburg', ARRAY['Piet Mondrian', 'Gerrit Rietveld', 'Bart van der Leck'], 'fr', true),
('art', 3, 'Quel sculpteur suisse est célèbre pour ses figures allongées ?', 'Alberto Giacometti', ARRAY['Jean Tinguely', 'Max Bill', 'Sophie Taeuber-Arp'], 'fr', true),
('art', 3, 'Qui a peint "Olympia" qui a fait scandale au Salon de 1865 ?', 'Édouard Manet', ARRAY['Gustave Courbet', 'Jean-Auguste-Dominique Ingres', 'Alexandre Cabanel'], 'fr', true),
('art', 3, 'Quel artiste a créé les "Compressions" d''automobiles ?', 'César', ARRAY['Arman', 'Jean Tinguely', 'Niki de Saint Phalle'], 'fr', true),
('art', 3, 'Qui a peint "Les Époux Arnolfini" ?', 'Jan van Eyck', ARRAY['Rogier van der Weyden', 'Hans Memling', 'Robert Campin'], 'fr', true),
('art', 3, 'Quel mouvement artistique italien célébrait la vitesse et la modernité ?', 'Le Futurisme', ARRAY['Le Divisionnisme', 'Le Métaphysique', 'L''Arte Povera'], 'fr', true),
('art', 3, 'Qui a peint "La Naissance de Vénus" ?', 'Sandro Botticelli', ARRAY['Raphaël', 'Titien', 'Léonard de Vinci'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - Difficulty 4 (20 questions)
-- =====================================================
('art', 4, 'Quel artiste a inventé le concept de "ready-made" ?', 'Marcel Duchamp', ARRAY['Kurt Schwitters', 'Man Ray', 'Francis Picabia'], 'fr', true),
('art', 4, 'Qui a peint "Le Triomphe de Galatée" à la Villa Farnesina ?', 'Raphaël', ARRAY['Michel-Ange', 'Sebastiano del Piombo', 'Giulio Romano'], 'fr', true),
('art', 4, 'Quel peintre flamand a créé "La Descente de Croix" à Anvers ?', 'Pierre Paul Rubens', ARRAY['Antoine van Dyck', 'Jacob Jordaens', 'Frans Snyders'], 'fr', true),
('art', 4, 'Qui a fondé le mouvement artistique "Fluxus" ?', 'George Maciunas', ARRAY['Nam June Paik', 'Yoko Ono', 'Joseph Beuys'], 'fr', true),
('art', 4, 'Quel artiste américain est connu pour ses "Flags" et "Targets" ?', 'Jasper Johns', ARRAY['Robert Rauschenberg', 'Roy Lichtenstein', 'Claes Oldenburg'], 'fr', true),
('art', 4, 'Qui a peint le retable d''Issenheim ?', 'Matthias Grünewald', ARRAY['Albrecht Dürer', 'Hans Holbein', 'Lucas Cranach'], 'fr', true),
('art', 4, 'Quel sculpteur britannique est connu pour ses formes organiques percées ?', 'Henry Moore', ARRAY['Barbara Hepworth', 'Anthony Caro', 'Eduardo Paolozzi'], 'fr', true),
('art', 4, 'Qui a créé le mouvement artistique "Arte Povera" ?', 'Germano Celant', ARRAY['Michelangelo Pistoletto', 'Mario Merz', 'Jannis Kounellis'], 'fr', true),
('art', 4, 'Quel peintre rococo français est connu pour "Les Hasards heureux de l''escarpolette" ?', 'Jean-Honoré Fragonard', ARRAY['François Boucher', 'Antoine Watteau', 'Jean-Baptiste Greuze'], 'fr', true),
('art', 4, 'Qui a peint "Les Ambassadeurs" avec son anamorphose célèbre ?', 'Hans Holbein le Jeune', ARRAY['Albrecht Dürer', 'Lucas Cranach', 'Hans Baldung'], 'fr', true),
('art', 4, 'Quel mouvement est caractérisé par le "supremus" de Malevitch ?', 'Le Suprématisme', ARRAY['Le Constructivisme', 'Le Rayonnisme', 'Le Néoplasticisme'], 'fr', true),
('art', 4, 'Qui a peint "L''Atelier du peintre", une allégorie réelle ?', 'Gustave Courbet', ARRAY['Honoré Daumier', 'Jean-François Millet', 'Théodore Rousseau'], 'fr', true),
('art', 4, 'Quel artiste conceptuel est connu pour ses œuvres utilisant du texte néon ?', 'Joseph Kosuth', ARRAY['Lawrence Weiner', 'Sol LeWitt', 'Robert Barry'], 'fr', true),
('art', 4, 'Qui a créé les "Accumulations" d''objets ?', 'Arman', ARRAY['César', 'Jean Tinguely', 'Daniel Spoerri'], 'fr', true),
('art', 4, 'Quel peintre symboliste belge a créé "L''Entrée du Christ à Bruxelles" ?', 'James Ensor', ARRAY['Fernand Khnopff', 'Félicien Rops', 'Léon Spilliaert'], 'fr', true),
('art', 4, 'Qui a fondé le groupe "Die Brücke" ?', 'Ernst Ludwig Kirchner', ARRAY['Emil Nolde', 'Erich Heckel', 'Karl Schmidt-Rottluff'], 'fr', true),
('art', 4, 'Quel artiste a créé "Spiral Jetty" ?', 'Robert Smithson', ARRAY['Michael Heizer', 'Walter De Maria', 'James Turrell'], 'fr', true),
('art', 4, 'Qui a peint "Le Verrou" ?', 'Jean-Honoré Fragonard', ARRAY['François Boucher', 'Antoine Watteau', 'Jean-Baptiste Greuze'], 'fr', true),
('art', 4, 'Quel mouvement artistique a été théorisé par Clement Greenberg ?', 'L''Expressionnisme abstrait', ARRAY['Le Minimalisme', 'Le Pop Art', 'Le Color Field'], 'fr', true),
('art', 4, 'Qui a peint la série "Les Quatre Saisons" en trompe-l''œil avec des fruits ?', 'Giuseppe Arcimboldo', ARRAY['Caravage', 'Annibale Carracci', 'Giovanni Bologna'], 'fr', true),

-- =====================================================
-- FRENCH QUESTIONS - Difficulty 5 (20 questions)
-- =====================================================
('art', 5, 'Quel critique d''art a inventé le terme "Impressionnisme" de manière péjorative ?', 'Louis Leroy', ARRAY['Charles Baudelaire', 'Émile Zola', 'Théophile Gautier'], 'fr', true),
('art', 5, 'Qui a théorisé le "Carré blanc sur fond blanc" ?', 'Kasimir Malevitch', ARRAY['El Lissitzky', 'Alexandre Rodtchenko', 'Vladimir Tatline'], 'fr', true),
('art', 5, 'Quel artiste a créé "Merzbau", une installation architecturale évolutive ?', 'Kurt Schwitters', ARRAY['Hans Arp', 'Max Ernst', 'Raoul Hausmann'], 'fr', true),
('art', 5, 'Qui a écrit "Du spirituel dans l''art" ?', 'Vassily Kandinsky', ARRAY['Paul Klee', 'Franz Marc', 'August Macke'], 'fr', true),
('art', 5, 'Quel peintre maniériste a créé "La Madone au long cou" ?', 'Parmigianino', ARRAY['Pontormo', 'Bronzino', 'Rosso Fiorentino'], 'fr', true),
('art', 5, 'Qui a fondé le mouvement "Supports/Surfaces" ?', 'Claude Viallat', ARRAY['Daniel Dezeuze', 'Louis Cane', 'Patrick Saytour'], 'fr', true),
('art', 5, 'Quel artiste a créé les "Anthropométries" avec des modèles vivants ?', 'Yves Klein', ARRAY['Piero Manzoni', 'Lucio Fontana', 'Alberto Burri'], 'fr', true),
('art', 5, 'Qui a théorisé le "Mono-ha" japonais ?', 'Lee Ufan', ARRAY['Nobuo Sekine', 'Kishio Suga', 'Susumu Koshimizu'], 'fr', true),
('art', 5, 'Quel peintre hollandais du 17e a peint "La Leçon d''anatomie du docteur Tulp" ?', 'Rembrandt', ARRAY['Frans Hals', 'Gerard ter Borch', 'Pieter de Hooch'], 'fr', true),
('art', 5, 'Qui a créé le mouvement "Spatialisme" en Italie ?', 'Lucio Fontana', ARRAY['Alberto Burri', 'Piero Manzoni', 'Enrico Castellani'], 'fr', true),
('art', 5, 'Quel artiste a réalisé "I Like America and America Likes Me" ?', 'Joseph Beuys', ARRAY['Nam June Paik', 'Wolf Vostell', 'Vito Acconci'], 'fr', true),
('art', 5, 'Qui a peint le cycle de "La Vie de Marie de Médicis" ?', 'Pierre Paul Rubens', ARRAY['Antoine van Dyck', 'Jacob Jordaens', 'Nicolas Poussin'], 'fr', true),
('art', 5, 'Quel mouvement artistique est associé à Lygia Clark et Hélio Oiticica ?', 'Le Néoconcrétisme', ARRAY['Le Tropicalisme', 'L''Arte Povera', 'Le Minimalisme'], 'fr', true),
('art', 5, 'Qui a théorisé la "Peinture analytique" ?', 'Giulio Paolini', ARRAY['Emilio Prini', 'Alighiero Boetti', 'Giovanni Anselmo'], 'fr', true),
('art', 5, 'Quel peintre baroque espagnol a créé les "Peintures noires" ?', 'Francisco Goya', ARRAY['Diego Velázquez', 'El Greco', 'José de Ribera'], 'fr', true),
('art', 5, 'Qui a fondé le groupe "Zero" en Allemagne ?', 'Heinz Mack', ARRAY['Otto Piene', 'Günther Uecker', 'Yves Klein'], 'fr', true),
('art', 5, 'Quel artiste est connu pour ses "Combines" mêlant peinture et objets ?', 'Robert Rauschenberg', ARRAY['Jasper Johns', 'Jim Dine', 'Larry Rivers'], 'fr', true),
('art', 5, 'Qui a peint "Les Époux Lavoisier" ?', 'Jacques-Louis David', ARRAY['Jean-Auguste-Dominique Ingres', 'Anne-Louis Girodet', 'François Gérard'], 'fr', true),
('art', 5, 'Quel mouvement artistique est lié aux "Nouveaux Réalistes" ?', 'Le Nouveau Réalisme', ARRAY['Le Pop Art', 'Le Néo-Dadaïsme', 'L''Assemblage'], 'fr', true),
('art', 5, 'Qui a créé "La Mariée mise à nu par ses célibataires, même" (Le Grand Verre) ?', 'Marcel Duchamp', ARRAY['Francis Picabia', 'Man Ray', 'Kurt Schwitters'], 'fr', true),

-- =====================================================
-- ENGLISH QUESTIONS - Difficulty 1 (20 questions)
-- =====================================================
('art', 1, 'Who painted the "Mona Lisa"?', 'Leonardo da Vinci', ARRAY['Michelangelo', 'Raphael', 'Botticelli'], 'en', true),
('art', 1, 'In which museum can you see the "Mona Lisa"?', 'The Louvre', ARRAY['The Uffizi', 'The Prado', 'The Metropolitan Museum'], 'en', true),
('art', 1, 'Who painted "The Starry Night"?', 'Vincent van Gogh', ARRAY['Claude Monet', 'Paul Cézanne', 'Paul Gauguin'], 'en', true),
('art', 1, 'Which artist is famous for painting sunflowers?', 'Vincent van Gogh', ARRAY['Claude Monet', 'Pierre-Auguste Renoir', 'Édouard Manet'], 'en', true),
('art', 1, 'Who sculpted the famous "David" statue in Florence?', 'Michelangelo', ARRAY['Donatello', 'Bernini', 'Cellini'], 'en', true),
('art', 1, 'Which art movement does Claude Monet represent?', 'Impressionism', ARRAY['Cubism', 'Surrealism', 'Romanticism'], 'en', true),
('art', 1, 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', ARRAY['Raphael', 'Leonardo da Vinci', 'Titian'], 'en', true),
('art', 1, 'Which Spanish artist co-founded Cubism?', 'Pablo Picasso', ARRAY['Salvador Dalí', 'Joan Miró', 'Francisco Goya'], 'en', true),
('art', 1, 'Who painted "The Scream"?', 'Edvard Munch', ARRAY['Vincent van Gogh', 'Egon Schiele', 'Gustav Klimt'], 'en', true),
('art', 1, 'In which country is the Prado Museum located?', 'Spain', ARRAY['Italy', 'France', 'Portugal'], 'en', true),
('art', 1, 'What is Leonardo da Vinci''s technique that creates a hazy effect called?', 'Sfumato', ARRAY['Chiaroscuro', 'Perspective', 'Watercolor'], 'en', true),
('art', 1, 'Who painted the "Water Lilies" series?', 'Claude Monet', ARRAY['Pierre-Auguste Renoir', 'Edgar Degas', 'Camille Pissarro'], 'en', true),
('art', 1, 'Which surrealist artist is known for melting clocks?', 'Salvador Dalí', ARRAY['René Magritte', 'Max Ernst', 'Joan Miró'], 'en', true),
('art', 1, 'What nationality was Rembrandt?', 'Dutch', ARRAY['German', 'Belgian', 'French'], 'en', true),
('art', 1, 'Who painted "Girl with a Pearl Earring"?', 'Johannes Vermeer', ARRAY['Rembrandt', 'Frans Hals', 'Jan Steen'], 'en', true),
('art', 1, 'What was El Greco''s real name?', 'Domínikos Theotokópoulos', ARRAY['Diego Velázquez', 'Francisco de Zurbarán', 'Bartolomé Murillo'], 'en', true),
('art', 1, 'Who created "The Thinker" sculpture?', 'Auguste Rodin', ARRAY['Camille Claudel', 'Antoine Bourdelle', 'Aristide Maillol'], 'en', true),
('art', 1, 'Which artist famously cut off part of his ear?', 'Vincent van Gogh', ARRAY['Paul Gauguin', 'Henri de Toulouse-Lautrec', 'Paul Cézanne'], 'en', true),
('art', 1, 'Who painted "Liberty Leading the People"?', 'Eugène Delacroix', ARRAY['Théodore Géricault', 'Jacques-Louis David', 'Jean-Auguste-Dominique Ingres'], 'en', true),
('art', 1, 'Which New York museum houses "Les Demoiselles d''Avignon"?', 'MoMA', ARRAY['The Metropolitan Museum', 'The Guggenheim', 'The Whitney Museum'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - Difficulty 2 (20 questions)
-- =====================================================
('art', 2, 'Which art movement was born in Paris in the early 20th century with Picasso and Braque?', 'Cubism', ARRAY['Fauvism', 'Dadaism', 'Expressionism'], 'en', true),
('art', 2, 'Who painted "Luncheon on the Grass" (Le Déjeuner sur l''herbe)?', 'Édouard Manet', ARRAY['Claude Monet', 'Pierre-Auguste Renoir', 'Gustave Courbet'], 'en', true),
('art', 2, 'Which artist is associated with ballet dancers?', 'Edgar Degas', ARRAY['Henri de Toulouse-Lautrec', 'Pierre-Auguste Renoir', 'Berthe Morisot'], 'en', true),
('art', 2, 'In which city is the Uffizi Gallery located?', 'Florence', ARRAY['Rome', 'Venice', 'Milan'], 'en', true),
('art', 2, 'Who painted "Las Meninas"?', 'Diego Velázquez', ARRAY['Francisco Goya', 'El Greco', 'Bartolomé Murillo'], 'en', true),
('art', 2, 'Which movement does Andy Warhol represent?', 'Pop Art', ARRAY['Abstract Expressionism', 'Minimalism', 'Neo-Expressionism'], 'en', true),
('art', 2, 'Who founded the Bauhaus school?', 'Walter Gropius', ARRAY['Ludwig Mies van der Rohe', 'Le Corbusier', 'Frank Lloyd Wright'], 'en', true),
('art', 2, 'Which French painter was the master of Neoclassicism?', 'Jacques-Louis David', ARRAY['Jean-Auguste-Dominique Ingres', 'Eugène Delacroix', 'Théodore Géricault'], 'en', true),
('art', 2, 'Who painted "The Raft of the Medusa"?', 'Théodore Géricault', ARRAY['Eugène Delacroix', 'Jacques-Louis David', 'Anne-Louis Girodet'], 'en', true),
('art', 2, 'Which artist created "Mobiles"?', 'Alexander Calder', ARRAY['Jean Tinguely', 'Naum Gabo', 'Constantin Brâncuși'], 'en', true),
('art', 2, 'Who painted "The Kiss" with golden patterns?', 'Gustav Klimt', ARRAY['Egon Schiele', 'Oskar Kokoschka', 'Koloman Moser'], 'en', true),
('art', 2, 'What is the name of the art movement associated with Kandinsky?', 'Abstract Art', ARRAY['Expressionism', 'Constructivism', 'Suprematism'], 'en', true),
('art', 2, 'Who painted "American Gothic"?', 'Grant Wood', ARRAY['Edward Hopper', 'Norman Rockwell', 'Andrew Wyeth'], 'en', true),
('art', 2, 'Which sculptor created "Bird in Space"?', 'Constantin Brâncuși', ARRAY['Alberto Giacometti', 'Henry Moore', 'Jean Arp'], 'en', true),
('art', 2, 'Who painted "Guernica"?', 'Pablo Picasso', ARRAY['Joan Miró', 'Salvador Dalí', 'Juan Gris'], 'en', true),
('art', 2, 'Which art movement is characterized by vivid, non-natural colors?', 'Fauvism', ARRAY['Impressionism', 'Pointillism', 'Symbolism'], 'en', true),
('art', 2, 'Who was the leader of Fauvism?', 'Henri Matisse', ARRAY['André Derain', 'Maurice de Vlaminck', 'Raoul Dufy'], 'en', true),
('art', 2, 'Which artist is known for paintings of Campbell''s soup cans?', 'Andy Warhol', ARRAY['Roy Lichtenstein', 'Jasper Johns', 'Robert Rauschenberg'], 'en', true),
('art', 2, 'Who painted "The Persistence of Memory"?', 'Salvador Dalí', ARRAY['René Magritte', 'Max Ernst', 'Yves Tanguy'], 'en', true),
('art', 2, 'In which country is the Hermitage Museum located?', 'Russia', ARRAY['Germany', 'Austria', 'Poland'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - Difficulty 3 (20 questions)
-- =====================================================
('art', 3, 'Which artist developed the "dripping" technique?', 'Jackson Pollock', ARRAY['Willem de Kooning', 'Mark Rothko', 'Franz Kline'], 'en', true),
('art', 3, 'Who painted "La Grande Odalisque"?', 'Jean-Auguste-Dominique Ingres', ARRAY['Jacques-Louis David', 'Eugène Delacroix', 'Théodore Chassériau'], 'en', true),
('art', 3, 'Which art movement does Piet Mondrian represent?', 'Neoplasticism (De Stijl)', ARRAY['Suprematism', 'Constructivism', 'Bauhaus'], 'en', true),
('art', 3, 'Who created the sculpture "Fountain" (a signed urinal)?', 'Marcel Duchamp', ARRAY['Man Ray', 'Francis Picabia', 'Jean Arp'], 'en', true),
('art', 3, 'Which Italian Baroque artist is known for dramatic use of chiaroscuro?', 'Caravaggio', ARRAY['Artemisia Gentileschi', 'Guido Reni', 'Annibale Carracci'], 'en', true),
('art', 3, 'Who painted "A Bar at the Folies-Bergère"?', 'Édouard Manet', ARRAY['Henri de Toulouse-Lautrec', 'Edgar Degas', 'Pierre-Auguste Renoir'], 'en', true),
('art', 3, 'Which Italian sculptor created "The Ecstasy of Saint Teresa"?', 'Gian Lorenzo Bernini', ARRAY['Michelangelo', 'Donatello', 'Antonio Canova'], 'en', true),
('art', 3, 'Who painted "The Night Watch"?', 'Rembrandt', ARRAY['Frans Hals', 'Johannes Vermeer', 'Jan Steen'], 'en', true),
('art', 3, 'Which art movement was born in Zurich in 1916?', 'Dadaism', ARRAY['Surrealism', 'Futurism', 'Constructivism'], 'en', true),
('art', 3, 'Who wrote the "Surrealist Manifesto" in 1924?', 'André Breton', ARRAY['Salvador Dalí', 'Max Ernst', 'René Magritte'], 'en', true),
('art', 3, 'Which Venetian painter is known for monumental religious works?', 'Tintoretto', ARRAY['Titian', 'Veronese', 'Giovanni Bellini'], 'en', true),
('art', 3, 'Who painted "The Garden of Earthly Delights"?', 'Hieronymus Bosch', ARRAY['Pieter Bruegel the Elder', 'Albrecht Dürer', 'Lucas Cranach'], 'en', true),
('art', 3, 'Which American artist is associated with the "Color Field" movement?', 'Mark Rothko', ARRAY['Jackson Pollock', 'Willem de Kooning', 'Robert Motherwell'], 'en', true),
('art', 3, 'Who founded the De Stijl movement?', 'Theo van Doesburg', ARRAY['Piet Mondrian', 'Gerrit Rietveld', 'Bart van der Leck'], 'en', true),
('art', 3, 'Which Swiss sculptor is famous for elongated figures?', 'Alberto Giacometti', ARRAY['Jean Tinguely', 'Max Bill', 'Sophie Taeuber-Arp'], 'en', true),
('art', 3, 'Who painted "Olympia" that caused scandal at the 1865 Salon?', 'Édouard Manet', ARRAY['Gustave Courbet', 'Jean-Auguste-Dominique Ingres', 'Alexandre Cabanel'], 'en', true),
('art', 3, 'Which artist created the "Compressions" of automobiles?', 'César', ARRAY['Arman', 'Jean Tinguely', 'Niki de Saint Phalle'], 'en', true),
('art', 3, 'Who painted "The Arnolfini Portrait"?', 'Jan van Eyck', ARRAY['Rogier van der Weyden', 'Hans Memling', 'Robert Campin'], 'en', true),
('art', 3, 'Which Italian art movement celebrated speed and modernity?', 'Futurism', ARRAY['Divisionism', 'Metaphysical Art', 'Arte Povera'], 'en', true),
('art', 3, 'Who painted "The Birth of Venus"?', 'Sandro Botticelli', ARRAY['Raphael', 'Titian', 'Leonardo da Vinci'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - Difficulty 4 (20 questions)
-- =====================================================
('art', 4, 'Which artist invented the concept of "ready-made"?', 'Marcel Duchamp', ARRAY['Kurt Schwitters', 'Man Ray', 'Francis Picabia'], 'en', true),
('art', 4, 'Who painted "The Triumph of Galatea" at the Villa Farnesina?', 'Raphael', ARRAY['Michelangelo', 'Sebastiano del Piombo', 'Giulio Romano'], 'en', true),
('art', 4, 'Which Flemish painter created "The Descent from the Cross" in Antwerp?', 'Peter Paul Rubens', ARRAY['Anthony van Dyck', 'Jacob Jordaens', 'Frans Snyders'], 'en', true),
('art', 4, 'Who founded the "Fluxus" art movement?', 'George Maciunas', ARRAY['Nam June Paik', 'Yoko Ono', 'Joseph Beuys'], 'en', true),
('art', 4, 'Which American artist is known for "Flags" and "Targets"?', 'Jasper Johns', ARRAY['Robert Rauschenberg', 'Roy Lichtenstein', 'Claes Oldenburg'], 'en', true),
('art', 4, 'Who painted the Isenheim Altarpiece?', 'Matthias Grünewald', ARRAY['Albrecht Dürer', 'Hans Holbein', 'Lucas Cranach'], 'en', true),
('art', 4, 'Which British sculptor is known for organic pierced forms?', 'Henry Moore', ARRAY['Barbara Hepworth', 'Anthony Caro', 'Eduardo Paolozzi'], 'en', true),
('art', 4, 'Who created the "Arte Povera" art movement?', 'Germano Celant', ARRAY['Michelangelo Pistoletto', 'Mario Merz', 'Jannis Kounellis'], 'en', true),
('art', 4, 'Which French Rococo painter is known for "The Swing"?', 'Jean-Honoré Fragonard', ARRAY['François Boucher', 'Antoine Watteau', 'Jean-Baptiste Greuze'], 'en', true),
('art', 4, 'Who painted "The Ambassadors" with its famous anamorphosis?', 'Hans Holbein the Younger', ARRAY['Albrecht Dürer', 'Lucas Cranach', 'Hans Baldung'], 'en', true),
('art', 4, 'Which movement is characterized by Malevich''s "supremus"?', 'Suprematism', ARRAY['Constructivism', 'Rayonism', 'Neoplasticism'], 'en', true),
('art', 4, 'Who painted "The Painter''s Studio", a real allegory?', 'Gustave Courbet', ARRAY['Honoré Daumier', 'Jean-François Millet', 'Théodore Rousseau'], 'en', true),
('art', 4, 'Which conceptual artist is known for works using neon text?', 'Joseph Kosuth', ARRAY['Lawrence Weiner', 'Sol LeWitt', 'Robert Barry'], 'en', true),
('art', 4, 'Who created the "Accumulations" of objects?', 'Arman', ARRAY['César', 'Jean Tinguely', 'Daniel Spoerri'], 'en', true),
('art', 4, 'Which Belgian symbolist painter created "Christ''s Entry into Brussels"?', 'James Ensor', ARRAY['Fernand Khnopff', 'Félicien Rops', 'Léon Spilliaert'], 'en', true),
('art', 4, 'Who founded the "Die Brücke" group?', 'Ernst Ludwig Kirchner', ARRAY['Emil Nolde', 'Erich Heckel', 'Karl Schmidt-Rottluff'], 'en', true),
('art', 4, 'Which artist created "Spiral Jetty"?', 'Robert Smithson', ARRAY['Michael Heizer', 'Walter De Maria', 'James Turrell'], 'en', true),
('art', 4, 'Who painted "The Bolt"?', 'Jean-Honoré Fragonard', ARRAY['François Boucher', 'Antoine Watteau', 'Jean-Baptiste Greuze'], 'en', true),
('art', 4, 'Which art movement was theorized by Clement Greenberg?', 'Abstract Expressionism', ARRAY['Minimalism', 'Pop Art', 'Color Field'], 'en', true),
('art', 4, 'Who painted the "Four Seasons" series with trompe-l''oeil fruit portraits?', 'Giuseppe Arcimboldo', ARRAY['Caravaggio', 'Annibale Carracci', 'Giovanni Bologna'], 'en', true),

-- =====================================================
-- ENGLISH QUESTIONS - Difficulty 5 (20 questions)
-- =====================================================
('art', 5, 'Which art critic coined the term "Impressionism" pejoratively?', 'Louis Leroy', ARRAY['Charles Baudelaire', 'Émile Zola', 'Théophile Gautier'], 'en', true),
('art', 5, 'Who theorized "White on White"?', 'Kazimir Malevich', ARRAY['El Lissitzky', 'Alexander Rodchenko', 'Vladimir Tatlin'], 'en', true),
('art', 5, 'Which artist created "Merzbau", an evolving architectural installation?', 'Kurt Schwitters', ARRAY['Hans Arp', 'Max Ernst', 'Raoul Hausmann'], 'en', true),
('art', 5, 'Who wrote "Concerning the Spiritual in Art"?', 'Wassily Kandinsky', ARRAY['Paul Klee', 'Franz Marc', 'August Macke'], 'en', true),
('art', 5, 'Which Mannerist painter created "Madonna with the Long Neck"?', 'Parmigianino', ARRAY['Pontormo', 'Bronzino', 'Rosso Fiorentino'], 'en', true),
('art', 5, 'Who founded the "Supports/Surfaces" movement?', 'Claude Viallat', ARRAY['Daniel Dezeuze', 'Louis Cane', 'Patrick Saytour'], 'en', true),
('art', 5, 'Which artist created "Anthropométries" with live models?', 'Yves Klein', ARRAY['Piero Manzoni', 'Lucio Fontana', 'Alberto Burri'], 'en', true),
('art', 5, 'Who theorized the Japanese "Mono-ha" movement?', 'Lee Ufan', ARRAY['Nobuo Sekine', 'Kishio Suga', 'Susumu Koshimizu'], 'en', true),
('art', 5, 'Which 17th-century Dutch painter created "The Anatomy Lesson of Dr. Nicolaes Tulp"?', 'Rembrandt', ARRAY['Frans Hals', 'Gerard ter Borch', 'Pieter de Hooch'], 'en', true),
('art', 5, 'Who created the "Spatialism" movement in Italy?', 'Lucio Fontana', ARRAY['Alberto Burri', 'Piero Manzoni', 'Enrico Castellani'], 'en', true),
('art', 5, 'Which artist performed "I Like America and America Likes Me"?', 'Joseph Beuys', ARRAY['Nam June Paik', 'Wolf Vostell', 'Vito Acconci'], 'en', true),
('art', 5, 'Who painted the "Life of Marie de'' Medici" cycle?', 'Peter Paul Rubens', ARRAY['Anthony van Dyck', 'Jacob Jordaens', 'Nicolas Poussin'], 'en', true),
('art', 5, 'Which art movement is associated with Lygia Clark and Hélio Oiticica?', 'Neoconcretism', ARRAY['Tropicália', 'Arte Povera', 'Minimalism'], 'en', true),
('art', 5, 'Who theorized "Analytical Painting"?', 'Giulio Paolini', ARRAY['Emilio Prini', 'Alighiero Boetti', 'Giovanni Anselmo'], 'en', true),
('art', 5, 'Which Spanish Baroque painter created the "Black Paintings"?', 'Francisco Goya', ARRAY['Diego Velázquez', 'El Greco', 'José de Ribera'], 'en', true),
('art', 5, 'Who founded the "Zero" group in Germany?', 'Heinz Mack', ARRAY['Otto Piene', 'Günther Uecker', 'Yves Klein'], 'en', true),
('art', 5, 'Which artist is known for "Combines" mixing painting and objects?', 'Robert Rauschenberg', ARRAY['Jasper Johns', 'Jim Dine', 'Larry Rivers'], 'en', true),
('art', 5, 'Who painted "Portrait of Antoine-Laurent Lavoisier and His Wife"?', 'Jacques-Louis David', ARRAY['Jean-Auguste-Dominique Ingres', 'Anne-Louis Girodet', 'François Gérard'], 'en', true),
('art', 5, 'Which art movement is linked to the "Nouveaux Réalistes"?', 'Nouveau Réalisme', ARRAY['Pop Art', 'Neo-Dada', 'Assemblage'], 'en', true),
('art', 5, 'Who created "The Bride Stripped Bare by Her Bachelors, Even" (The Large Glass)?', 'Marcel Duchamp', ARRAY['Francis Picabia', 'Man Ray', 'Kurt Schwitters'], 'en', true);
