-- =====================================================
-- SPORT / SPORTS (100 FR + 100 EN)
-- =====================================================

INSERT INTO questions (category, difficulty, question_text, correct_answer, wrong_answers, language, is_active) VALUES
-- FRENCH - Niveau 1
('sport', 1, 'Combien de joueurs compose une équipe de football ?', '11', ARRAY['9', '10', '12'], 'fr', true),
('sport', 1, 'Quel sport se joue avec une raquette et un volant ?', 'Badminton', ARRAY['Tennis', 'Squash', 'Ping-pong'], 'fr', true),
('sport', 1, 'Dans quel sport utilise-t-on un ballon orange ?', 'Basketball', ARRAY['Football', 'Volleyball', 'Handball'], 'fr', true),
('sport', 1, 'Combien de sets faut-il gagner au tennis pour remporter un match ?', '3', ARRAY['2', '4', '5'], 'fr', true),
('sport', 1, 'Quel sport pratique Usain Bolt ?', 'Athlétisme', ARRAY['Natation', 'Cyclisme', 'Football'], 'fr', true),
('sport', 1, 'Dans quel sport marque-t-on des touchdowns ?', 'Football américain', ARRAY['Rugby', 'Football', 'Hockey'], 'fr', true),
('sport', 1, 'Quelle couleur est la ceinture des débutants en judo ?', 'Blanche', ARRAY['Jaune', 'Orange', 'Verte'], 'fr', true),
('sport', 1, 'Combien de temps dure un match de football ?', '90 minutes', ARRAY['60 minutes', '80 minutes', '120 minutes'], 'fr', true),
('sport', 1, 'Quel sport se pratique sur de la glace avec un palet ?', 'Hockey sur glace', ARRAY['Curling', 'Patinage', 'Bobsleigh'], 'fr', true),
('sport', 1, 'Quelle est la distance d''un marathon ?', '42 km', ARRAY['21 km', '35 km', '50 km'], 'fr', true),
('sport', 1, 'Dans quel sport lance-t-on un ballon dans un panier ?', 'Basketball', ARRAY['Handball', 'Volleyball', 'Football'], 'fr', true),
('sport', 1, 'Combien de points vaut un essai au rugby ?', '5', ARRAY['3', '4', '6'], 'fr', true),
('sport', 1, 'Quel nageur a gagné 23 médailles d''or olympiques ?', 'Michael Phelps', ARRAY['Ian Thorpe', 'Ryan Lochte', 'Mark Spitz'], 'fr', true),
('sport', 1, 'Quel sport pratique Rafael Nadal ?', 'Tennis', ARRAY['Golf', 'Football', 'Cyclisme'], 'fr', true),
('sport', 1, 'Combien de joueurs dans une équipe de basketball ?', '5', ARRAY['4', '6', '7'], 'fr', true),
('sport', 1, 'Dans quel sport utilise-t-on des gants de boxe ?', 'Boxe', ARRAY['Judo', 'Karaté', 'Lutte'], 'fr', true),
('sport', 1, 'Quelle est la couleur du maillot jaune du Tour de France ?', 'Jaune', ARRAY['Rouge', 'Vert', 'Blanc'], 'fr', true),
('sport', 1, 'Quel sport se joue avec une crosse et une balle ?', 'Golf', ARRAY['Hockey', 'Baseball', 'Cricket'], 'fr', true),
('sport', 1, 'Combien d''anneaux olympiques y a-t-il ?', '5', ARRAY['4', '6', '7'], 'fr', true),
('sport', 1, 'Dans quel sport utilise-t-on des skis ?', 'Ski', ARRAY['Snowboard', 'Patinage', 'Luge'], 'fr', true),

-- FRENCH - Niveau 2
('sport', 2, 'Quel pays a remporté la Coupe du Monde 2018 ?', 'France', ARRAY['Croatie', 'Brésil', 'Allemagne'], 'fr', true),
('sport', 2, 'Combien de Grand Chelem y a-t-il en tennis ?', '4', ARRAY['3', '5', '6'], 'fr', true),
('sport', 2, 'Quel footballeur a remporté le plus de Ballons d''Or ?', 'Lionel Messi', ARRAY['Cristiano Ronaldo', 'Johan Cruyff', 'Michel Platini'], 'fr', true),
('sport', 2, 'Dans quel pays se sont déroulés les JO de 2020 ?', 'Japon', ARRAY['Chine', 'Corée du Sud', 'États-Unis'], 'fr', true),
('sport', 2, 'Quelle équipe NBA a le plus de titres ?', 'Boston Celtics', ARRAY['Los Angeles Lakers', 'Chicago Bulls', 'Golden State Warriors'], 'fr', true),
('sport', 2, 'Combien de temps dure un quart-temps en NBA ?', '12 minutes', ARRAY['10 minutes', '15 minutes', '20 minutes'], 'fr', true),
('sport', 2, 'Quel cycliste a remporté 5 Tours de France consécutifs ?', 'Miguel Indurain', ARRAY['Bernard Hinault', 'Eddy Merckx', 'Lance Armstrong'], 'fr', true),
('sport', 2, 'Dans quel sport Roger Federer excelle-t-il ?', 'Tennis', ARRAY['Golf', 'Squash', 'Badminton'], 'fr', true),
('sport', 2, 'Quelle est la distance d''un semi-marathon ?', '21,1 km', ARRAY['15 km', '25 km', '30 km'], 'fr', true),
('sport', 2, 'Quel club de football a remporté le plus de Ligues des Champions ?', 'Real Madrid', ARRAY['AC Milan', 'Bayern Munich', 'Liverpool'], 'fr', true),
('sport', 2, 'Combien de joueurs dans une équipe de volleyball ?', '6', ARRAY['5', '7', '8'], 'fr', true),
('sport', 2, 'Quel pays organise le tournoi de Wimbledon ?', 'Royaume-Uni', ARRAY['France', 'États-Unis', 'Australie'], 'fr', true),
('sport', 2, 'Quelle est la hauteur d''un panier de basketball ?', '3,05 m', ARRAY['2,75 m', '3,25 m', '3,50 m'], 'fr', true),
('sport', 2, 'Quel sportif a le plus de médailles olympiques ?', 'Michael Phelps', ARRAY['Usain Bolt', 'Carl Lewis', 'Mark Spitz'], 'fr', true),
('sport', 2, 'Dans quel sport utilise-t-on un fleuret ?', 'Escrime', ARRAY['Boxe', 'Judo', 'Lutte'], 'fr', true),
('sport', 2, 'Quelle équipe a remporté le Super Bowl le plus souvent ?', 'New England Patriots', ARRAY['Pittsburgh Steelers', 'Dallas Cowboys', 'San Francisco 49ers'], 'fr', true),
('sport', 2, 'Combien de rounds dans un combat de boxe professionnel ?', '12', ARRAY['10', '15', '8'], 'fr', true),
('sport', 2, 'Quel pays a inventé le judo ?', 'Japon', ARRAY['Chine', 'Corée', 'Thaïlande'], 'fr', true),
('sport', 2, 'Quelle est la longueur d''une piscine olympique ?', '50 mètres', ARRAY['25 mètres', '75 mètres', '100 mètres'], 'fr', true),
('sport', 2, 'Quel sport se pratique à Roland-Garros ?', 'Tennis', ARRAY['Golf', 'Équitation', 'Athlétisme'], 'fr', true),

-- FRENCH - Niveau 3
('sport', 3, 'En quelle année la France a-t-elle remporté sa première Coupe du Monde ?', '1998', ARRAY['1994', '2002', '2006'], 'fr', true),
('sport', 3, 'Quel boxeur était surnommé "The Greatest" ?', 'Muhammad Ali', ARRAY['Mike Tyson', 'Sugar Ray Leonard', 'Floyd Mayweather'], 'fr', true),
('sport', 3, 'Combien de titres de Grand Chelem a Rafael Nadal ?', '22', ARRAY['20', '21', '23'], 'fr', true),
('sport', 3, 'Quel pilote F1 détient le record de titres mondiaux ?', 'Michael Schumacher', ARRAY['Lewis Hamilton', 'Ayrton Senna', 'Sebastian Vettel'], 'fr', true),
('sport', 3, 'Dans quel sport trouve-t-on le terme "bogey" ?', 'Golf', ARRAY['Tennis', 'Bowling', 'Cricket'], 'fr', true),
('sport', 3, 'Quelle ville a accueilli les JO d''été de 2024 ?', 'Paris', ARRAY['Los Angeles', 'Tokyo', 'Londres'], 'fr', true),
('sport', 3, 'Combien de kilomètres fait un Ironman ?', '226 km', ARRAY['180 km', '200 km', '250 km'], 'fr', true),
('sport', 3, 'Quel joueur de tennis a le plus de victoires à Wimbledon ?', 'Roger Federer', ARRAY['Pete Sampras', 'Novak Djokovic', 'Björn Borg'], 'fr', true),
('sport', 3, 'Dans quel sport Kylian Mbappé excelle-t-il ?', 'Football', ARRAY['Basketball', 'Handball', 'Rugby'], 'fr', true),
('sport', 3, 'Quelle est la distance du 110 mètres haies ?', '110 mètres', ARRAY['100 mètres', '120 mètres', '115 mètres'], 'fr', true),
('sport', 3, 'Quel pays a remporté la Coupe du Monde de rugby 2019 ?', 'Afrique du Sud', ARRAY['Nouvelle-Zélande', 'Angleterre', 'Australie'], 'fr', true),
('sport', 3, 'Combien de trous compte un parcours de golf standard ?', '18', ARRAY['9', '12', '21'], 'fr', true),
('sport', 3, 'Quel club a remporté la Premier League le plus souvent ?', 'Manchester United', ARRAY['Liverpool', 'Arsenal', 'Chelsea'], 'fr', true),
('sport', 3, 'Dans quel sport utilise-t-on un sabre ?', 'Escrime', ARRAY['Kendo', 'Arts martiaux', 'Combat médiéval'], 'fr', true),
('sport', 3, 'Quelle est la vitesse maximale d''un service au tennis ?', '263 km/h', ARRAY['220 km/h', '240 km/h', '280 km/h'], 'fr', true),
('sport', 3, 'Quel cycliste détient le record de victoires au Tour de France ?', 'Jacques Anquetil', ARRAY['Eddy Merckx', 'Bernard Hinault', 'Miguel Indurain'], 'fr', true),
('sport', 3, 'Combien de sets minimum pour gagner un match de tennis féminin en Grand Chelem ?', '2', ARRAY['3', '4', '5'], 'fr', true),
('sport', 3, 'Quel sport se joue avec un shuttlecock ?', 'Badminton', ARRAY['Tennis', 'Squash', 'Volleyball'], 'fr', true),
('sport', 3, 'Dans quel pays se déroule le Masters de golf ?', 'États-Unis', ARRAY['Écosse', 'Angleterre', 'Irlande'], 'fr', true),
('sport', 3, 'Quelle équipe de NBA a Michael Jordan rendue célèbre ?', 'Chicago Bulls', ARRAY['Los Angeles Lakers', 'Boston Celtics', 'Miami Heat'], 'fr', true),

-- FRENCH - Niveau 4
('sport', 4, 'En quelle année ont eu lieu les premiers Jeux Olympiques modernes ?', '1896', ARRAY['1892', '1900', '1904'], 'fr', true),
('sport', 4, 'Quel est le record du monde du 100 mètres masculin ?', '9,58 s', ARRAY['9,69 s', '9,72 s', '9,63 s'], 'fr', true),
('sport', 4, 'Combien de joueurs composent une équipe de water-polo ?', '7', ARRAY['5', '6', '8'], 'fr', true),
('sport', 4, 'Quel pays a remporté le plus de Coupes du Monde de football ?', 'Brésil', ARRAY['Allemagne', 'Italie', 'Argentine'], 'fr', true),
('sport', 4, 'Dans quel sport trouve-t-on le terme "ippon" ?', 'Judo', ARRAY['Karaté', 'Taekwondo', 'Kung-fu'], 'fr', true),
('sport', 4, 'Quelle est la longueur d''un terrain de football ?', '100-110 m', ARRAY['90-100 m', '80-90 m', '110-120 m'], 'fr', true),
('sport', 4, 'Quel pilote de F1 a le plus de pole positions ?', 'Lewis Hamilton', ARRAY['Michael Schumacher', 'Ayrton Senna', 'Sebastian Vettel'], 'fr', true),
('sport', 4, 'Combien pèse un ballon de football officiel ?', '410-450 g', ARRAY['350-400 g', '450-500 g', '500-550 g'], 'fr', true),
('sport', 4, 'Quel pays organise le tournoi de Roland-Garros ?', 'France', ARRAY['Espagne', 'Italie', 'Suisse'], 'fr', true),
('sport', 4, 'Dans quel sport utilise-t-on un épée ?', 'Escrime', ARRAY['Kendo', 'Fencing', 'Duel'], 'fr', true),
('sport', 4, 'Quelle est la durée d''un match de rugby ?', '80 minutes', ARRAY['60 minutes', '70 minutes', '90 minutes'], 'fr', true),
('sport', 4, 'Quel est le score parfait au bowling ?', '300', ARRAY['200', '250', '350'], 'fr', true),
('sport', 4, 'Combien de coureurs participent au Tour de France ?', '176', ARRAY['150', '200', '220'], 'fr', true),
('sport', 4, 'Quel athlète a remporté 9 médailles d''or olympiques en athlétisme ?', 'Carl Lewis', ARRAY['Usain Bolt', 'Jesse Owens', 'Michael Johnson'], 'fr', true),
('sport', 4, 'Dans quel sport trouve-t-on le terme "ace" ?', 'Tennis', ARRAY['Golf', 'Volleyball', 'Badminton'], 'fr', true),
('sport', 4, 'Quelle est la hauteur d''un filet de tennis au centre ?', '0,914 m', ARRAY['0,85 m', '1 m', '1,07 m'], 'fr', true),
('sport', 4, 'Quel pays a remporté l''Euro 2020 ?', 'Italie', ARRAY['Angleterre', 'France', 'Espagne'], 'fr', true),
('sport', 4, 'Combien de médailles d''or Usain Bolt a-t-il remportées aux JO ?', '8', ARRAY['6', '9', '10'], 'fr', true),
('sport', 4, 'Quel est le nom du trophée de la NHL ?', 'Coupe Stanley', ARRAY['Coupe du Monde', 'Trophée O''Brien', 'Coupe Prince de Galles'], 'fr', true),
('sport', 4, 'Dans quel sport trouve-t-on le terme "birdie" ?', 'Golf', ARRAY['Tennis', 'Badminton', 'Cricket'], 'fr', true),

-- FRENCH - Niveau 5
('sport', 5, 'En quelle année Zinedine Zidane a-t-il pris sa retraite ?', '2006', ARRAY['2004', '2008', '2010'], 'fr', true),
('sport', 5, 'Quel est le record du monde du saut en hauteur masculin ?', '2,45 m', ARRAY['2,40 m', '2,50 m', '2,43 m'], 'fr', true),
('sport', 5, 'Combien de Grand Chelem a Serena Williams remportés ?', '23', ARRAY['21', '22', '24'], 'fr', true),
('sport', 5, 'Quelle équipe a remporté la Coupe d''Europe des clubs champions 1993 ?', 'Marseille', ARRAY['AC Milan', 'Barcelone', 'Ajax'], 'fr', true),
('sport', 5, 'Dans quel sport trouve-t-on le terme "waza-ari" ?', 'Judo', ARRAY['Karaté', 'Sumo', 'Aikido'], 'fr', true),
('sport', 5, 'Quel est le record du monde du 200 mètres masculin ?', '19,19 s', ARRAY['19,32 s', '19,26 s', '19,50 s'], 'fr', true),
('sport', 5, 'Combien de fois Eddy Merckx a-t-il remporté le Tour de France ?', '5', ARRAY['4', '6', '7'], 'fr', true),
('sport', 5, 'Quel pays a remporté la Coupe Davis le plus souvent ?', 'États-Unis', ARRAY['Australie', 'France', 'Espagne'], 'fr', true),
('sport', 5, 'Dans quel sport trouve-t-on le terme "double fault" ?', 'Tennis', ARRAY['Volleyball', 'Badminton', 'Squash'], 'fr', true),
('sport', 5, 'Quel est le nom du stade du FC Barcelone ?', 'Camp Nou', ARRAY['Santiago Bernabéu', 'San Siro', 'Allianz Arena'], 'fr', true),
('sport', 5, 'Combien de points vaut une transformation au rugby ?', '2', ARRAY['1', '3', '5'], 'fr', true),
('sport', 5, 'Quel pilote a remporté le plus de Grand Prix de F1 ?', 'Lewis Hamilton', ARRAY['Michael Schumacher', 'Sebastian Vettel', 'Alain Prost'], 'fr', true),
('sport', 5, 'Dans quel sport utilise-t-on un "wedge" ?', 'Golf', ARRAY['Cricket', 'Hockey', 'Baseball'], 'fr', true),
('sport', 5, 'Quelle est la distance du lancer du poids masculin (record mondial) ?', '23,37 m', ARRAY['22,50 m', '24,00 m', '21,80 m'], 'fr', true),
('sport', 5, 'Quel joueur de tennis a remporté le plus de titres ATP ?', 'Jimmy Connors', ARRAY['Roger Federer', 'Rafael Nadal', 'Ivan Lendl'], 'fr', true),
('sport', 5, 'Combien de joueurs dans une équipe de baseball ?', '9', ARRAY['8', '10', '11'], 'fr', true),
('sport', 5, 'Quel est le record du monde du marathon masculin ?', '2h00min35s', ARRAY['2h01min39s', '2h02min57s', '2h03min23s'], 'fr', true),
('sport', 5, 'Dans quel sport trouve-t-on le terme "hat-trick" ?', 'Football', ARRAY['Cricket', 'Hockey', 'Tous les trois'], 'fr', true),
('sport', 5, 'Quel pays a le plus de médailles olympiques ?', 'États-Unis', ARRAY['Russie', 'Chine', 'Allemagne'], 'fr', true),
('sport', 5, 'Combien de minutes dure un combat de MMA en UFC ?', '15 minutes', ARRAY['12 minutes', '20 minutes', '25 minutes'], 'fr', true),

-- ENGLISH - Level 1
('sport', 1, 'How many players are on a soccer team?', '11', ARRAY['9', '10', '12'], 'en', true),
('sport', 1, 'Which sport uses a racket and shuttlecock?', 'Badminton', ARRAY['Tennis', 'Squash', 'Ping-pong'], 'en', true),
('sport', 1, 'In which sport do you use an orange ball?', 'Basketball', ARRAY['Soccer', 'Volleyball', 'Handball'], 'en', true),
('sport', 1, 'How many sets do you need to win a tennis match?', '3', ARRAY['2', '4', '5'], 'en', true),
('sport', 1, 'Which sport does Usain Bolt practice?', 'Athletics', ARRAY['Swimming', 'Cycling', 'Soccer'], 'en', true),
('sport', 1, 'In which sport do you score touchdowns?', 'American Football', ARRAY['Rugby', 'Soccer', 'Hockey'], 'en', true),
('sport', 1, 'What color is a beginner''s belt in judo?', 'White', ARRAY['Yellow', 'Orange', 'Green'], 'en', true),
('sport', 1, 'How long is a soccer match?', '90 minutes', ARRAY['60 minutes', '80 minutes', '120 minutes'], 'en', true),
('sport', 1, 'Which sport is played on ice with a puck?', 'Ice Hockey', ARRAY['Curling', 'Figure Skating', 'Bobsled'], 'en', true),
('sport', 1, 'What is the distance of a marathon?', '42 km', ARRAY['21 km', '35 km', '50 km'], 'en', true),
('sport', 1, 'In which sport do you throw a ball into a basket?', 'Basketball', ARRAY['Handball', 'Volleyball', 'Soccer'], 'en', true),
('sport', 1, 'How many points is a try worth in rugby?', '5', ARRAY['3', '4', '6'], 'en', true),
('sport', 1, 'Which swimmer won 23 Olympic gold medals?', 'Michael Phelps', ARRAY['Ian Thorpe', 'Ryan Lochte', 'Mark Spitz'], 'en', true),
('sport', 1, 'Which sport does Rafael Nadal play?', 'Tennis', ARRAY['Golf', 'Soccer', 'Cycling'], 'en', true),
('sport', 1, 'How many players are on a basketball team?', '5', ARRAY['4', '6', '7'], 'en', true),
('sport', 1, 'In which sport do you use boxing gloves?', 'Boxing', ARRAY['Judo', 'Karate', 'Wrestling'], 'en', true),
('sport', 1, 'What color is the Tour de France leader''s jersey?', 'Yellow', ARRAY['Red', 'Green', 'White'], 'en', true),
('sport', 1, 'Which sport uses clubs and a ball?', 'Golf', ARRAY['Hockey', 'Baseball', 'Cricket'], 'en', true),
('sport', 1, 'How many Olympic rings are there?', '5', ARRAY['4', '6', '7'], 'en', true),
('sport', 1, 'In which sport do you use skis?', 'Skiing', ARRAY['Snowboarding', 'Ice Skating', 'Bobsled'], 'en', true),

-- ENGLISH - Level 2
('sport', 2, 'Which country won the 2018 World Cup?', 'France', ARRAY['Croatia', 'Brazil', 'Germany'], 'en', true),
('sport', 2, 'How many Grand Slams are there in tennis?', '4', ARRAY['3', '5', '6'], 'en', true),
('sport', 2, 'Which footballer has won the most Ballon d''Ors?', 'Lionel Messi', ARRAY['Cristiano Ronaldo', 'Johan Cruyff', 'Michel Platini'], 'en', true),
('sport', 2, 'In which country were the 2020 Olympics held?', 'Japan', ARRAY['China', 'South Korea', 'United States'], 'en', true),
('sport', 2, 'Which NBA team has the most titles?', 'Boston Celtics', ARRAY['Los Angeles Lakers', 'Chicago Bulls', 'Golden State Warriors'], 'en', true),
('sport', 2, 'How long is an NBA quarter?', '12 minutes', ARRAY['10 minutes', '15 minutes', '20 minutes'], 'en', true),
('sport', 2, 'Which cyclist won 5 consecutive Tour de France?', 'Miguel Indurain', ARRAY['Bernard Hinault', 'Eddy Merckx', 'Lance Armstrong'], 'en', true),
('sport', 2, 'In which sport does Roger Federer excel?', 'Tennis', ARRAY['Golf', 'Squash', 'Badminton'], 'en', true),
('sport', 2, 'What is the distance of a half marathon?', '21.1 km', ARRAY['15 km', '25 km', '30 km'], 'en', true),
('sport', 2, 'Which football club has won the most Champions League titles?', 'Real Madrid', ARRAY['AC Milan', 'Bayern Munich', 'Liverpool'], 'en', true),
('sport', 2, 'How many players are on a volleyball team?', '6', ARRAY['5', '7', '8'], 'en', true),
('sport', 2, 'Which country hosts Wimbledon?', 'United Kingdom', ARRAY['France', 'United States', 'Australia'], 'en', true),
('sport', 2, 'What is the height of a basketball hoop?', '3.05 m', ARRAY['2.75 m', '3.25 m', '3.50 m'], 'en', true),
('sport', 2, 'Which athlete has the most Olympic medals?', 'Michael Phelps', ARRAY['Usain Bolt', 'Carl Lewis', 'Mark Spitz'], 'en', true),
('sport', 2, 'In which sport do you use a foil?', 'Fencing', ARRAY['Boxing', 'Judo', 'Wrestling'], 'en', true),
('sport', 2, 'Which team has won the most Super Bowls?', 'New England Patriots', ARRAY['Pittsburgh Steelers', 'Dallas Cowboys', 'San Francisco 49ers'], 'en', true),
('sport', 2, 'How many rounds in a professional boxing match?', '12', ARRAY['10', '15', '8'], 'en', true),
('sport', 2, 'Which country invented judo?', 'Japan', ARRAY['China', 'Korea', 'Thailand'], 'en', true),
('sport', 2, 'What is the length of an Olympic swimming pool?', '50 meters', ARRAY['25 meters', '75 meters', '100 meters'], 'en', true),
('sport', 2, 'Which sport is played at Roland-Garros?', 'Tennis', ARRAY['Golf', 'Horse Racing', 'Athletics'], 'en', true),

-- ENGLISH - Level 3
('sport', 3, 'In what year did France win their first World Cup?', '1998', ARRAY['1994', '2002', '2006'], 'en', true),
('sport', 3, 'Which boxer was nicknamed "The Greatest"?', 'Muhammad Ali', ARRAY['Mike Tyson', 'Sugar Ray Leonard', 'Floyd Mayweather'], 'en', true),
('sport', 3, 'How many Grand Slam titles has Rafael Nadal won?', '22', ARRAY['20', '21', '23'], 'en', true),
('sport', 3, 'Which F1 driver holds the record for world titles?', 'Michael Schumacher', ARRAY['Lewis Hamilton', 'Ayrton Senna', 'Sebastian Vettel'], 'en', true),
('sport', 3, 'In which sport do you find the term "bogey"?', 'Golf', ARRAY['Tennis', 'Bowling', 'Cricket'], 'en', true),
('sport', 3, 'Which city hosted the 2024 Summer Olympics?', 'Paris', ARRAY['Los Angeles', 'Tokyo', 'London'], 'en', true),
('sport', 3, 'How many kilometers is an Ironman?', '226 km', ARRAY['180 km', '200 km', '250 km'], 'en', true),
('sport', 3, 'Which tennis player has the most Wimbledon wins?', 'Roger Federer', ARRAY['Pete Sampras', 'Novak Djokovic', 'Björn Borg'], 'en', true),
('sport', 3, 'In which sport does Kylian Mbappé excel?', 'Soccer', ARRAY['Basketball', 'Handball', 'Rugby'], 'en', true),
('sport', 3, 'What is the distance of the 110-meter hurdles?', '110 meters', ARRAY['100 meters', '120 meters', '115 meters'], 'en', true),
('sport', 3, 'Which country won the 2019 Rugby World Cup?', 'South Africa', ARRAY['New Zealand', 'England', 'Australia'], 'en', true),
('sport', 3, 'How many holes are on a standard golf course?', '18', ARRAY['9', '12', '21'], 'en', true),
('sport', 3, 'Which club has won the Premier League the most?', 'Manchester United', ARRAY['Liverpool', 'Arsenal', 'Chelsea'], 'en', true),
('sport', 3, 'In which sport do you use a saber?', 'Fencing', ARRAY['Kendo', 'Martial Arts', 'Medieval Combat'], 'en', true),
('sport', 3, 'What is the maximum speed of a tennis serve?', '263 km/h', ARRAY['220 km/h', '240 km/h', '280 km/h'], 'en', true),
('sport', 3, 'Which cyclist holds the record for Tour de France wins?', 'Jacques Anquetil', ARRAY['Eddy Merckx', 'Bernard Hinault', 'Miguel Indurain'], 'en', true),
('sport', 3, 'How many sets minimum to win a women''s Grand Slam tennis match?', '2', ARRAY['3', '4', '5'], 'en', true),
('sport', 3, 'Which sport is played with a shuttlecock?', 'Badminton', ARRAY['Tennis', 'Squash', 'Volleyball'], 'en', true),
('sport', 3, 'In which country is the Masters golf tournament held?', 'United States', ARRAY['Scotland', 'England', 'Ireland'], 'en', true),
('sport', 3, 'Which NBA team did Michael Jordan make famous?', 'Chicago Bulls', ARRAY['Los Angeles Lakers', 'Boston Celtics', 'Miami Heat'], 'en', true),

-- ENGLISH - Level 4
('sport', 4, 'In what year were the first modern Olympic Games held?', '1896', ARRAY['1892', '1900', '1904'], 'en', true),
('sport', 4, 'What is the men''s 100m world record?', '9.58 s', ARRAY['9.69 s', '9.72 s', '9.63 s'], 'en', true),
('sport', 4, 'How many players are on a water polo team?', '7', ARRAY['5', '6', '8'], 'en', true),
('sport', 4, 'Which country has won the most FIFA World Cups?', 'Brazil', ARRAY['Germany', 'Italy', 'Argentina'], 'en', true),
('sport', 4, 'In which sport do you find the term "ippon"?', 'Judo', ARRAY['Karate', 'Taekwondo', 'Kung-fu'], 'en', true),
('sport', 4, 'What is the length of a soccer field?', '100-110 m', ARRAY['90-100 m', '80-90 m', '110-120 m'], 'en', true),
('sport', 4, 'Which F1 driver has the most pole positions?', 'Lewis Hamilton', ARRAY['Michael Schumacher', 'Ayrton Senna', 'Sebastian Vettel'], 'en', true),
('sport', 4, 'How much does an official soccer ball weigh?', '410-450 g', ARRAY['350-400 g', '450-500 g', '500-550 g'], 'en', true),
('sport', 4, 'Which country hosts Roland-Garros?', 'France', ARRAY['Spain', 'Italy', 'Switzerland'], 'en', true),
('sport', 4, 'In which sport do you use an épée?', 'Fencing', ARRAY['Kendo', 'Combat', 'Duel'], 'en', true),
('sport', 4, 'How long is a rugby match?', '80 minutes', ARRAY['60 minutes', '70 minutes', '90 minutes'], 'en', true),
('sport', 4, 'What is a perfect score in bowling?', '300', ARRAY['200', '250', '350'], 'en', true),
('sport', 4, 'How many riders participate in the Tour de France?', '176', ARRAY['150', '200', '220'], 'en', true),
('sport', 4, 'Which athlete won 9 Olympic gold medals in athletics?', 'Carl Lewis', ARRAY['Usain Bolt', 'Jesse Owens', 'Michael Johnson'], 'en', true),
('sport', 4, 'In which sport do you find the term "ace"?', 'Tennis', ARRAY['Golf', 'Volleyball', 'Badminton'], 'en', true),
('sport', 4, 'What is the height of a tennis net at the center?', '0.914 m', ARRAY['0.85 m', '1 m', '1.07 m'], 'en', true),
('sport', 4, 'Which country won Euro 2020?', 'Italy', ARRAY['England', 'France', 'Spain'], 'en', true),
('sport', 4, 'How many Olympic gold medals did Usain Bolt win?', '8', ARRAY['6', '9', '10'], 'en', true),
('sport', 4, 'What is the name of the NHL trophy?', 'Stanley Cup', ARRAY['World Cup', 'O''Brien Trophy', 'Prince of Wales Cup'], 'en', true),
('sport', 4, 'In which sport do you find the term "birdie"?', 'Golf', ARRAY['Tennis', 'Badminton', 'Cricket'], 'en', true),

-- ENGLISH - Level 5
('sport', 5, 'In what year did Zinedine Zidane retire?', '2006', ARRAY['2004', '2008', '2010'], 'en', true),
('sport', 5, 'What is the men''s high jump world record?', '2.45 m', ARRAY['2.40 m', '2.50 m', '2.43 m'], 'en', true),
('sport', 5, 'How many Grand Slams has Serena Williams won?', '23', ARRAY['21', '22', '24'], 'en', true),
('sport', 5, 'Which team won the 1993 European Champions Cup?', 'Marseille', ARRAY['AC Milan', 'Barcelona', 'Ajax'], 'en', true),
('sport', 5, 'In which sport do you find the term "waza-ari"?', 'Judo', ARRAY['Karate', 'Sumo', 'Aikido'], 'en', true),
('sport', 5, 'What is the men''s 200m world record?', '19.19 s', ARRAY['19.32 s', '19.26 s', '19.50 s'], 'en', true),
('sport', 5, 'How many times did Eddy Merckx win the Tour de France?', '5', ARRAY['4', '6', '7'], 'en', true),
('sport', 5, 'Which country has won the most Davis Cups?', 'United States', ARRAY['Australia', 'France', 'Spain'], 'en', true),
('sport', 5, 'In which sport do you find the term "double fault"?', 'Tennis', ARRAY['Volleyball', 'Badminton', 'Squash'], 'en', true),
('sport', 5, 'What is the name of FC Barcelona''s stadium?', 'Camp Nou', ARRAY['Santiago Bernabéu', 'San Siro', 'Allianz Arena'], 'en', true),
('sport', 5, 'How many points is a conversion worth in rugby?', '2', ARRAY['1', '3', '5'], 'en', true),
('sport', 5, 'Which driver has won the most F1 Grand Prix?', 'Lewis Hamilton', ARRAY['Michael Schumacher', 'Sebastian Vettel', 'Alain Prost'], 'en', true),
('sport', 5, 'In which sport do you use a "wedge"?', 'Golf', ARRAY['Cricket', 'Hockey', 'Baseball'], 'en', true),
('sport', 5, 'What is the men''s shot put world record distance?', '23.37 m', ARRAY['22.50 m', '24.00 m', '21.80 m'], 'en', true),
('sport', 5, 'Which tennis player has won the most ATP titles?', 'Jimmy Connors', ARRAY['Roger Federer', 'Rafael Nadal', 'Ivan Lendl'], 'en', true),
('sport', 5, 'How many players are on a baseball team?', '9', ARRAY['8', '10', '11'], 'en', true),
('sport', 5, 'What is the men''s marathon world record?', '2h00min35s', ARRAY['2h01min39s', '2h02min57s', '2h03min23s'], 'en', true),
('sport', 5, 'In which sport do you find the term "hat-trick"?', 'Soccer', ARRAY['Cricket', 'Hockey', 'All three'], 'en', true),
('sport', 5, 'Which country has the most Olympic medals?', 'United States', ARRAY['Russia', 'China', 'Germany'], 'en', true),
('sport', 5, 'How many minutes does a UFC MMA fight last?', '15 minutes', ARRAY['12 minutes', '20 minutes', '25 minutes'], 'en', true);
